objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>The date of birth of the patient</description>
        <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Activity.object
<CustomObject>
    <fields>
        <fullName>PC_SupportPlanActivity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Support Plan Activity from which this activity was generated from</description>
        <label>Support Plan Activity</label>
        <referenceTo>PC_SupportPlanActivity__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Care_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated support coordinator</description>
        <label>Care Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Enrollment_Date__c</fullName>
        <description>The date on which the patient was enrolled to the program</description>
        <label>Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Status_Indicator_4__c</fullName>
        <description>The adherence status of the patient</description>
        <label>ADHERENCE</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Case_Status_Indicators</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Treatment_Start_Date__c</fullName>
        <description>The date on which the patient started the treatment</description>
        <label>Treatment Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Program_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Program Code provides a unique mnemonic or code value that can be used to reference engagement programs. It is expected that a program code would not change during the life of a program, whereas, the name may be modified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Provide a short unique code that will not need to be changed.</inlineHelpText>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_EngagementProgram_SupportPlan__c.object
<CustomObject>
    <description>Custom junction object between Engagement Program and Support Plan objects to associate many Support Plans to many Engagement Programs.</description>
    <fields>
        <fullName>PC_SupportPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support Plan to associate with Engagement Program</description>
        <label>Support Plan</label>
        <referenceTo>PC_SupportPlan__c</referenceTo>
        <relationshipLabel>Engagement Program Support Plans</relationshipLabel>
        <relationshipName>Engagement_Program_Support_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Engagement Program Support Plan</label>
    <nameField>
        <displayFormat>ESP-{00000}</displayFormat>
        <label>Engagement Program Support Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Program Support Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_SupportPlan__c.object
<CustomObject>
    <description>Custom object in Patient Connect that helps to create a predefined template of activities (tasks and events) according to the type of case and the brands that are supported.</description>
    <fields>
        <fullName>PC_ConditionBehavior__c</fullName>
        <description>Indicates how the Start Condition should be treated: 
 -Wait Until True: The Support Plan will stay on the current activity unless a Start Condition is met.
 -No Condition: There is no condition on the Support Plan activity and hence can be created/executed.</description>
        <label>Condition Behavior</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Condition</fullName>
                    <default>true</default>
                    <label>No Condition</label>
                </value>
                <value>
                    <fullName>Wait until True</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Support Plan is active.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_TriggerEventConditionalBehavior__c</fullName>
        <description>Indicates how the Trigger Event Condition should be treated:
-Wait Until True: The Support plan will stay on the current activity till Trigger Event Condition is met.
-No Condition: There is no condition and hence Support plan can be created/executed.</description>
        <label>Conditional Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Condition</fullName>
                </value>
                <value>
                    <fullName>Wait until True</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_TriggerEventObject__c</fullName>
        <description>API Name of Object on which  Support plan is Run</description>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_TriggerEventType__c</fullName>
        <description>Event Type of Trigger Object on which  Support plan should start processing</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Insert/Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Support Plan</label>
    <nameField>
        <label>Support Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_SupportPlanActivity__c.object
<CustomObject>
    <description>Custom object in Patient Connect to store template activities for a Support Plan.</description>
    <fields>
        <fullName>PC_ConditionBehavior__c</fullName>
        <description>Indicates how the Start Condition should be treated: 
 -Wait Until True: The Support Plan will stay on the current activity unless a Start Condition is met.
 -No Condition: There is no condition on the Support Plan activity and hence can be created/executed.</description>
        <label>Condition Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Condition</fullName>
                    <default>true</default>
                    <label>No Condition</label>
                </value>
                <value>
                    <fullName>Wait until True</fullName>
                </value>
                <value>
                    <fullName>Skip if False</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_SupportPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Support Plan to which an activity or an activity sequence belongs.</description>
        <label>Support Plan</label>
        <referenceTo>PC_SupportPlan__c</referenceTo>
        <relationshipLabel>Support Plan Activities</relationshipLabel>
        <relationshipName>Support_Plan_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support Plan Activity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Plan Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_SupportPlanActivityLog__c.object
<CustomObject>
    <description>Custom object to store Support Plan Activity Logs</description>
    <fields>
        <fullName>PC_ActionRecordId__c</fullName>
        <description>Id of record on which action is performed as part of Support plan Activity</description>
        <label>Action Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_SupportPlanActivity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support Plan Activity using which the new Record is created</description>
        <label>Support Plan Activity</label>
        <referenceTo>PC_SupportPlanActivity__c</referenceTo>
        <relationshipLabel>Support Plan Activity Logs</relationshipLabel>
        <relationshipName>PC_SupportPlanActivityLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_SupportPlanRuntime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support Plan Runtime which was used to execute Support Plan Activity</description>
        <label>Support Plan Runtime</label>
        <referenceTo>PC_SupportPlanRuntime__c</referenceTo>
        <relationshipLabel>Support Plan Activity Logs</relationshipLabel>
        <relationshipName>PC_SupportPlanActivityLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_TriggerRecordId__c</fullName>
        <description>Id of Record which triggered Support Plan</description>
        <label>Trigger Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Support Plan Activity Log</label>
    <nameField>
        <displayFormat>SPAL-{000000}</displayFormat>
        <label>Support Plan Activity Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Plan Activity Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_SupportPlanRuntime__c.object
<CustomObject>
    <description>Patient Connect custom object to capture run time instance of a Support Plan</description>
    <fields>
        <fullName>PC_Completed_Activity__c</fullName>
        <description>The id of the previously completed Activity</description>
        <label>Completed Activity</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_CurrentActivityStatus__c</fullName>
        <description>Status of the current activity. Determines if the activity is in progress or a pending state.</description>
        <label>Current Activity Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Condition</fullName>
                    <default>true</default>
                    <label>Pending Condition</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_CurrentActivity__c</fullName>
        <description>Name of the current activity being evaluated for the Support Plan.</description>
        <label>Current Activity</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_StartTime__c</fullName>
        <description>Start date or time when the Support Plan was initiated.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PC_SupportPlanCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case for which the Support Plan has been executed.</description>
        <label>Support Plan Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Support Plan Runtime</relationshipLabel>
        <relationshipName>Support_Plan_Runtime</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_SupportPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support Plan to which the run time instance belongs.</description>
        <label>Support Plan</label>
        <referenceTo>PC_SupportPlan__c</referenceTo>
        <relationshipLabel>Support Plan Runtime</relationshipLabel>
        <relationshipName>Support_Plan_Runtime</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support Plan Runtime</label>
    <nameField>
        <label>Support Plan Runtime Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Plan Runtime</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/PC_Case_Status_Indicators.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Action Required</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Not applicable</fullName>
    </customValue>
    <masterLabel>Case Status Indicators</masterLabel>
</GlobalValueSet>

classes/PC_Test_UpdateSupportPlanRuntimes.cls
/**
 * Created by vkashikar on 4/23/2020.
 */

@isTest
private class PC_Test_UpdateSupportPlanRuntimes {
    // VIJAY - This test class is implemented to get the coverage up.
    private static User adminUser;
    private static User careCoordinator;
    private static Case programCase;
    private static Case programCase2;
    private static Case casetestDueDate;
    private static Account patient;
    private static Account  manufacturer;
    private static PC_SupportPlan__c supportPlan1, supportPlan2;
    private static PC_SupportPlanActivity__c supPlanActy1,supPlanActy2, supPlanActyOrphaned;
    private static PC_SupportPlanRuntime__c supportPlanRuntime, supportPlanRuntime2;
    private static PC_Engagement_Program__c enmtProgram;
    private static PC_EngagementProgram_SupportPlan__c enmtPgmSupPlan;
    private static Task outcomeTask;
    private static List<Task> tasks, migratedTasks, tasksOrphaned;
    private static PC_SupportPlanActivityLog__c supportPlanActivityLog;
    
    @testSetup
    static void setup() {
        adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@email.com', 'pctest');
        PC_Database.ins(adminUser, false);

        //Create Care Coordinator
        careCoordinator = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@t2.com', 'test2');
        careCoordinator = (User) PC_Database.ins(careCoordinator);

        patient = PC_Test_Setup.createSampleAccount('', PC_Constants.PATIENT_RECORD_TYPE);
        patient.PC_Date_of_Birth__c = date.today().addDays(-100);
        patient = (Account)PC_Database.ins(patient, false);
        // check if patient is created
        system.assertNotEquals(patient.Id, null);

        //Create Manufacturer
        List<Account>  manufacturers = PC_Test_Setup.createAccounts('testmanufacturer', 1, PC_Constants.MANUFACTURER_RECORD_TYPE);
        manufacturer = (Account)PC_Database.ins(manufacturers[0], false);

        //Create Engagement Program
        enmtProgram= PC_Test_Setup.createEngagementProgram('TestPgm',manufacturer.Id );
        enmtProgram.PC_Program_Code__c = 'TestPgm';
        enmtProgram = (PC_Engagement_Program__c) PC_Database.ins(enmtProgram, false);

        programCase = PC_Test_Setup.createCase(adminUser, patient);
        programCase.PC_Engagement_Program__c = enmtProgram.Id;
        programCase.PC_Status_Indicator_4__c = 'In Progress';
        programCase.PC_Care_Coordinator__c      =   careCoordinator.Id;
        programCase.PC_Enrollment_Date__c = date.today().addDays(-10);
        programCase.PC_Treatment_Start_Date__c = date.today().addDays(+10);
        programCase = (Case)PC_Database.ins(programCase, false);
        // check if program Case is created
        system.assertNotEquals(programCase.Id, null);

        //Create Support Plan
        supportPlan1= PC_Test_Setup.createSupportPlan();
        supportPlan1.Name = 'support plan 1';
        supportPlan1.PC_IsActive__c=true;
        supportPlan1.PC_TriggerEventObject__c='Case';
        supportPlan1.PC_TriggerEventType__c='Insert/Update';
        supportPlan1.PC_TriggerEventConditionalBehavior__c = PC_Constants.SUPPORTPLAN_CONDBEHAVIOR_STATUS_NONE;
        supportPlan1.PC_ConditionBehavior__c = PC_Constants.SUPPORTPLAN_CONDBEHAVIOR_STATUS_NONE;
        supportPlan1 = (PC_SupportPlan__c) PC_Database.ins(supportPlan1, false);        

        //Create Support Plan Activity1 Linked to the Support Plan
        supPlanActy1= PC_Test_Setup.createSupportPlanActivity('Activity 1: Task - Log a Call');
        supPlanActy1.PC_SupportPlan__c = supportPlan1.Id;
        supPlanActy1 = (PC_SupportPlanActivity__c) PC_Database.ins(supPlanActy1, false);        

        tasks = PC_Test_Setup.createTasks(programCase, 1);
        tasks = (List<Task>) PC_Database.ins(tasks);

        tasks[0].PC_SupportPlanActivity__c = supPlanActy1.Id;
        tasks = (List<Task>) PC_Database.upd(tasks);

        supportPlanRuntime = new PC_SupportPlanRuntime__c();
        supportPlanRuntime.PC_SupportPlan__c = supportPlan1.Id;
        //supportPlanRuntime.PC_Completed_Activity__c = supPlanActy1.Id;
        supportPlanRuntime.PC_CurrentActivity__c = supPlanActy1.Id;
        supportPlanRuntime.PC_StartTime__c = Datetime.now();
        supportPlanRuntime.PC_CurrentActivityStatus__c = 'In Progress';
        supportPlanRuntime.PC_SupportPlanCase__c = programCase.Id;
        supportPlanRuntime = (PC_SupportPlanRuntime__c) PC_Database.ins(supportPlanRuntime);
        
        createDataForMigratedTask();
        //createOrphanedTask();
        
    }

    @isTest static void test() {
        try {
            User adminUser;
            // running as system admin
            adminUser = PC_Test_Setup.createUser('System Administrator', 'user@test100.com', 'test');
            PC_Database.ins(adminUser);
            System.runAs(adminUser) {
                Test.startTest();
                PC_UpdateSupportPlanRuntimes batchJob = new PC_UpdateSupportPlanRuntimes();
                Id batchId = Database.executeBatch(batchJob);
                Test.stopTest();
            }
        }
        catch(Exception ex) {
            system.debug('*****************');
            system.debug(ex.getMessage());
            system.assert(false);
        }

    }    
    
    
    static void createDataForMigratedTask() {
        
        programCase2 = PC_Test_Setup.createCase(adminUser, patient);
        programCase2.PC_Engagement_Program__c = enmtProgram.Id;
        programCase2.PC_Status_Indicator_4__c = 'In Progress';
        programCase2.PC_Care_Coordinator__c      =   careCoordinator.Id;
        programCase2.PC_Enrollment_Date__c = date.today().addDays(-10);
        programCase2.PC_Treatment_Start_Date__c = date.today().addDays(+10);
        programCase2 = (Case)PC_Database.ins(programCase2, false);
        
        //Create Support Plan
        supportPlan2= PC_Test_Setup.createSupportPlan();
        supportPlan2.PC_IsActive__c=true;
        supportPlan2.Name = 'support plan 2';
        supportPlan2.PC_TriggerEventObject__c='Case';
        supportPlan2.PC_TriggerEventType__c='Insert/Update';
        supportPlan2.PC_TriggerEventConditionalBehavior__c = PC_Constants.SUPPORTPLAN_CONDBEHAVIOR_STATUS_NONE;
        supportPlan2.PC_ConditionBehavior__c = PC_Constants.SUPPORTPLAN_CONDBEHAVIOR_STATUS_NONE;
        supportPlan2 = (PC_SupportPlan__c) PC_Database.ins(supportPlan2, false);
        
        //Create Support Plan Activity21 Linked to the Support Plan
        supPlanActy2= PC_Test_Setup.createSupportPlanActivity('Activity 21: Task - Log a Call');
        supPlanActy2.PC_SupportPlan__c = supportPlan2.Id;
        supPlanActy2 = (PC_SupportPlanActivity__c) PC_Database.ins(supPlanActy2, false);
        
        migratedTasks = PC_Test_Setup.createTasks(programCase2, 1);
        migratedTasks = (List<Task>) PC_Database.ins(migratedTasks);

        migratedTasks[0].PC_SupportPlanActivity__c = supPlanActy2.Id;
        migratedTasks = (List<Task>) PC_Database.upd(migratedTasks);
        
        supportPlanRuntime2 = new PC_SupportPlanRuntime__c();
        supportPlanRuntime2.PC_SupportPlan__c = supportPlan2.Id;
        //supportPlanRuntime.PC_Completed_Activity__c = supPlanActy1.Id;
        supportPlanRuntime2.PC_CurrentActivity__c = supPlanActy2.Id;
        supportPlanRuntime2.PC_StartTime__c = Datetime.now();
        supportPlanRuntime2.PC_CurrentActivityStatus__c = 'In Progress';
        supportPlanRuntime2.PC_SupportPlanCase__c = programCase2.Id;
        supportPlanRuntime2 = (PC_SupportPlanRuntime__c) PC_Database.ins(supportPlanRuntime2);

        supportPlanActivityLog = new PC_SupportPlanActivityLog__c();
        supportPlanActivityLog.PC_ActionRecordId__c = migratedTasks[0].Id;
        supportPlanActivityLog.PC_TriggerRecordId__c = programCase2.Id;
        supportPlanActivityLog.PC_SupportPlanActivity__c = migratedTasks[0].PC_SupportPlanActivity__c;
        supportPlanActivityLog = (PC_SupportPlanActivityLog__c) PC_Database.ins(supportPlanActivityLog);
    }
    /*static void createOrphanedTask() {
        
        supPlanActyOrphaned= PC_Test_Setup.createSupportPlanActivity('Activity supPlanActyOrphaned: Task - Log a Call');
        // supPlanActy2.PC_SupportPlan__c = supportPlan2.Id; // We don't want this to be linked to any support plan
        supPlanActyOrphaned = (PC_SupportPlanActivity__c) PC_Database.ins(supPlanActyOrphaned, false);
        
        tasksOrphaned = PC_Test_Setup.createTasks(programCase2, 1); 
        tasksOrphaned = (List<Task>) PC_Database.ins(tasksOrphaned);
        
        tasksOrphaned[0].PC_SupportPlanActivity__c = supPlanActyOrphaned.Id;
        tasksOrphaned = (List<Task>) PC_Database.upd(tasksOrphaned);
    }*/
    @isTest static void testMethodToCoverCatchBlocks() {
        try {
            Test.startTest();
            PC_UpdateSupportPlanRuntimes batchJob = new PC_UpdateSupportPlanRuntimes();
            batchJob.start(null);
            batchJob.execute(null, [SELECT Id, WhatId, Status, PC_SupportPlanActivity__c
                        FROM Task WHERE (Status != 'Completed' AND Status != 'Closed')
                        AND PC_SupportPlanActivity__c != NULL LIMIT 1]);
            batchJob.finish(null);
            Id batchId = Database.executeBatch(batchJob);
            Test.stopTest();
        }
        catch(Exception ex) {
            system.assert(true); // expected.
        }
    }
}