objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Email__c</fullName>
        <description>The email address of the account.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PC_Specialist_Type__c</fullName>
        <description>The type of the physician specialist. It is dependent on the Account.Type choice &quot;Specialist&quot;.</description>
        <label>Specialist Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cardiologist</fullName>
                </value>
                <value>
                    <fullName>Endocrinologist</fullName>
                </value>
                <value>
                    <fullName>Gastroenterologist</fullName>
                </value>
                <value>
                    <fullName>Hepatologist</fullName>
                </value>
                <value>
                    <fullName>Neurologist</fullName>
                </value>
                <value>
                    <fullName>Oncologist</fullName>
                </value>
                <value>
                    <fullName>Orthopod</fullName>
                </value>
                <value>
                    <fullName>Primary Care</fullName>
                </value>
                <value>
                    <fullName>Rheumatologist</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>The status allows records to be classified as inactive and filters out of lookups and reports. The status is used to support validation rules for related records.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Sub_Type__c</fullName>
        <description>Used to further categorize accounts when the account type is “Business”.</description>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Infusion Clinic</fullName>
                </value>
                <value>
                    <fullName>Diabetes Center</fullName>
                </value>
                <value>
                    <fullName>MS Clinic</fullName>
                </value>
                <value>
                    <fullName>Hospital Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Retail Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Specialty Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Group Plan</fullName>
                </value>
                <value>
                    <fullName>Federal Plan</fullName>
                </value>
                <value>
                    <fullName>State Plan</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>Eye Clinic</fullName>
                </value>
                <value>
                    <fullName>MRI Service</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Care_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated support coordinator</description>
        <label>Care Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Email__c</fullName>
        <description>The email of the patient account</description>
        <formula>Account.PC_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated physician account</description>
        <label>Physician</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PC_Physician</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Physician</relationshipLabel>
        <relationshipName>Physician</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_eLetter__c.object
<CustomObject>
    <fields>
        <fullName>PC_Send_to_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this flag is checked, all other flags (Send Fax,Send email) are automatically unchecked and the eLetter is sent to the current User (for editing before sending to the Patients/Recipients)</description>
        <inlineHelpText>If Selected, the eLetter will be sent to current logged in User.</inlineHelpText>
        <label>Send to User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Target_Recipients__c</fullName>
        <description>Selects the target recipients for the eLetter.</description>
        <label>Target Recipients</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Association_Role</valueSetName>
        </valueSet>
    </fields>
    <label>eLetter</label>
    <nameField>
        <label>eLetter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eLetters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Program_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Program Code provides a unique mnemonic or code value that can be used to reference engagement programs. It is expected that a program code would not change during the life of a program, whereas, the name may be modified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Provide a short unique code that will not need to be changed.</inlineHelpText>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program_Eletter__c.object
<CustomObject>
    <description>Junction table to associate an eLetter template to multiple programs.</description>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <description>Lookup to the engagement program associated with the eLetter.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Engagement Program eLetter</relationshipLabel>
        <relationshipName>Engagement_Program_eLetter</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_eLetter__c</fullName>
        <description>Lookup to the eLetter template associated with the engagement program.</description>
        <label>eLetter</label>
        <referenceTo>PC_eLetter__c</referenceTo>
        <relationshipLabel>Engagement Program eLetter</relationshipLabel>
        <relationshipName>Engagement_Program_eLetter</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Engagement Program eLetter</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Engagement Program Eletter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Program eLetter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Interaction__c.object
<CustomObject>
    <description>Patient Connect custom object used to manage information and activities for interactions with / for patients such as infusion appointments, training sessions or another types of patient appointments typically delivered by 3rd parties.</description>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>The status of the Interaction such as Requested or Confirmed.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_ReminderLog__c.object
<CustomObject>
    <description>Logs are stored in this object when a reminder is sent.</description>
    <fields>
        <fullName>PC_ReminderQueue__c</fullName>
        <description>Queue Record ID for which the log got created.</description>
        <inlineHelpText>Queue Record ID for which the log got created.</inlineHelpText>
        <label>Reminder Queue</label>
        <referenceTo>PC_ReminderQueue__c</referenceTo>
        <relationshipLabel>Reminder Logs</relationshipLabel>
        <relationshipName>Reminder_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reminder Log</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Reminder Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reminder Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_ReminderQueue__c.object
<CustomObject>
    <description>Reminder queue stores the details of the reminders for configured objects.</description>
    <fields>
        <fullName>PC_DueDate__c</fullName>
        <description>Appointment due date which will be taken as reference for reminder offset calculation.</description>
        <inlineHelpText>Appointment Date.</inlineHelpText>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PC_LastSuccessfulReminderSent__c</fullName>
        <description>Stores the date/time of Last Successful Reminder Sent as part of the Reminder Queue</description>
        <inlineHelpText>Stores the date/time of Last Successful Reminder Sent as part of the Reminder Queue</inlineHelpText>
        <label>Last Successful Reminder Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PC_Recipient__c</fullName>
        <description>Recipient to whom the reminder will be sent.</description>
        <inlineHelpText>Recipient to whom the reminder will be sent.</inlineHelpText>
        <label>Recipient</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PC_RecordID__c</fullName>
        <description>Record ID that is referred for which queue record is created.</description>
        <externalId>true</externalId>
        <inlineHelpText>Record ID for which reminder is sent.</inlineHelpText>
        <label>Record ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_ReminderChannel__c</fullName>
        <description>Stores the value of channel through which the reminder will be sent.</description>
        <inlineHelpText>Reminder service channel to send reminders.</inlineHelpText>
        <label>Reminder Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_ReminderSetting__c</fullName>
        <description>Custom metadata setting name that is used while sending reminders.</description>
        <inlineHelpText>Custom metadata setting name which has all properties defined.</inlineHelpText>
        <label>Reminder Setting Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Reminder Queue</label>
    <nameField>
        <displayFormat>RQ-{0000}</displayFormat>
        <label>Reminder Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reminder Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/PC_Association_Role.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HCO</fullName>
    </customValue>
    <customValue>
        <fullName>Treating Physician</fullName>
    </customValue>
    <customValue>
        <fullName>Reimbursement Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Care Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Field Reimbursement Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Case Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Caregiver</fullName>
    </customValue>
    <masterLabel>Association Role</masterLabel>
</GlobalValueSet>

classes/PC_Test_ProcessQueuesInBatchScheduler.cls
/*********************************************************************************************************
Class Name      : PC_Test_ProcessQueuesInBatchScheduler
Description     : Test class for PC_ProcessQueuesInBatchScheduler class.
Created By      : Deloitte
Created Date    : June 21, 2021
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer          Log#         Date                   Description
--------------------------------------------------------------------------------------------------------------
Kanteti Kishore               June 21, 2021          Initial Version
Kanteti Kishore               Oct  15, 2021          [PC-8183] Modified code to support SMS reminder functionality using eLetters
***********************************************************************************************************/

@IsTest
public class PC_Test_ProcessQueuesInBatchScheduler{
    private static final String EMAIL_SETTING_NAME = 'PC_AppointmentEmailReminder';
    private static final String SMS_SETTING_NAME = 'PC_SMSReminder';

    @testSetup static void setup(){
        //Create Treating Physician
        Id physicianRecordTypeId = PC_System.recordTypeId(PC_Constants.PC_ACCOUNT, PC_Constants.PHYSICIAN_RECORD_TYPE);
        Account physician = new Account();
        physician.Name = 'Physician Name';
        physician.RecordTypeId = physicianRecordTypeId;
        physician.PC_Specialist_Type__c = 'Cardiologist';
        physician.Type = 'Specialist';
        physician.PC_Sub_Type__c = 'Other';
        physician.PC_Email__c = 'testphy@test.com';
        physician.Phone='34567863456';
        PC_Database.ins(physician, false);

        //Create Manufacturer
        Account manufacturerAcc = PC_Test_Setup.createTestAccount(PC_Constants.MANUFACTURER_RECORD_TYPE);
        PC_Database.ins(manufacturerAcc, false);

        //Create engagement Program
        PC_Engagement_Program__c engagementProgram = PC_Test_Setup.createEngagementProgram('ProgramA', manufacturerAcc.Id);
        PC_Database.ins(engagementProgram, false);

        //Create Patient Account
        Id patientRecordTypeId = PC_System.recordTypeId(PC_Constants.PC_ACCOUNT, PC_Constants.PATIENT_RECORD_TYPE);
        Account patient = new Account(Name = 'Patient1', RecordTypeId = patientRecordTypeId);
        PC_Database.ins(patient, false);

        //Create Program Case
        Case programCase = PC_Test_Setup.createProgram(patient);

        //Create Manufacturer
        List<Account>  manufacturers = PC_Test_Setup.createAccounts('testmanufacturer', 1, PC_Constants.MANUFACTURER_RECORD_TYPE);
        Account manufacturer = new Account();
        manufacturer = (Account)PC_Database.ins(manufacturers[0], false);

        //Create Engagement Program
        PC_Engagement_Program__c enmtProgram= PC_Test_Setup.createEngagementProgram('TestPgm',manufacturer.Id );
        enmtProgram.PC_Program_Code__c = 'TestPgm';
        enmtProgram = (PC_Engagement_Program__c) PC_Database.ins(enmtProgram, false);

        //Create Care Coordinator
        User careCoordinator = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@t2.com', 'test2');
        careCoordinator.Phone = '93457543223';
        careCoordinator = (User) PC_Database.ins(careCoordinator);

        //Create Case
        Case caseOne = PC_Test_Setup.createCase(careCoordinator,patient);
        caseOne.PC_Engagement_Program__c= enmtProgram.Id;
        caseOne.PC_Care_Coordinator__c      =   careCoordinator.Id;
        caseOne.PC_Physician__c             =   physician.Id;
        caseOne = (Case) PC_Database.ins(caseOne, false);

        //Create eLetter
        PC_eLetter__c eletter = PC_Test_Setup.createEletter();
        eLetter.Name = 'Sample eLetter';
        eLetter.PC_Target_Recipients__c = 'Care Coordinator; Treating Physician';
        eLetter.PC_Send_to_User__c= false;
        eletter = (PC_eLetter__c) PC_Database.ins(eletter);

        User objUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@t1234.com', 'test1');
        PC_Database.ins(objUser);

        //Create Email Template
        system.runAs(objUser) {
            EmailTemplate emailTemplate = new EmailTemplate (
                    developerName = 'Email_Template_Name',
                    FolderId = UserInfo.getUserId(),
                    TemplateType = 'Text',
                    Name = 'Email Template Name',
                    Body = 'This is an Email Body',
                    IsActive = TRUE
            );
            PC_Database.ins(emailTemplate);
        }

        // Create Engagement Program Eletter for Case
        PC_Engagement_Program_Eletter__c caseEngagementProgramEletter = new PC_Engagement_Program_Eletter__c();
        caseEngagementProgramEletter.PC_eLetter__c = eLetter.Id;
        caseEngagementProgramEletter.PC_Engagement_Program__c = enmtProgram.Id;
        PC_Database.ins(caseEngagementProgramEletter,false);

        //Create Interaction
        PC_Interaction__c interaction = PC_Test_Setup.newInteraction(programCase.Id);
        interaction = (PC_Interaction__c) PC_Database.ins(interaction,false);

        //Create Email Related Reminder Queues
        List<PC_ReminderQueue__c> reminderQueues = PC_Test_Setup.createReminderQueues(interaction.Id,EMAIL_SETTING_NAME,10);
        //Expired Reminder Queue
        reminderQueues[4].PC_DueDate__c = System.today().addDays(-4);
        //Minimum Interval Not Met
        reminderQueues[5].PC_LastSuccessfulReminderSent__c = System.now();
        //No handler for the channel
        reminderQueues[6].PC_ReminderChannel__c = 'Fax';

        //Create SMS Related Reminder Queues
        List<PC_ReminderQueue__c> smsReminderQueues = PC_Test_Setup.createReminderQueues(caseOne.Id,SMS_SETTING_NAME,2);
        for(PC_ReminderQueue__c queue :  smsReminderQueues){
            queue.PC_ReminderChannel__c = 'SMS';
        }
        //Creating Care Coordinator Recipient
        PC_ReminderQueue.RecipientDetail careCoordinatorRecipient = new PC_ReminderQueue.RecipientDetail();
        careCoordinatorRecipient.id = careCoordinator.Id;
        careCoordinatorRecipient.name = careCoordinator.Name;
        careCoordinatorRecipient.address = careCoordinator.Phone;
        careCoordinatorRecipient.type = 'User';
        smsReminderQueues[0].PC_Recipient__c = JSON.serialize(careCoordinatorRecipient);

        //Creating Physician Recipient
        PC_ReminderQueue.RecipientDetail physicianRecipient = new PC_ReminderQueue.RecipientDetail();
        physicianRecipient.id = physician.Id;
        physicianRecipient.name = physician.Name;
        physicianRecipient.address = physician.Phone;
        physicianRecipient.type = 'Account';
        smsReminderQueues[1].PC_Recipient__c = JSON.serialize(physicianRecipient);

        reminderQueues.addAll(smsReminderQueues);
        reminderQueues = (List<PC_ReminderQueue__c>) PC_Database.ins(reminderQueues, false);
    }
    @isTest static void testProcessQueuesBatch() {
        //Create admin User
        User adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@test100.com', 'test100');
        adminUser = (User) PC_Database.ins(adminUser);

        System.runAs(adminUser) {
            Test.StartTest();
            SchedulableContext sc = null;
            PC_ProcessQueuesInBatchScheduler queuesInBatchScheduler = new PC_ProcessQueuesInBatchScheduler();
            queuesInBatchScheduler.execute(sc);
            Test.StopTest();
        }
    }
    @isTest static void testProcessQueuesBatchFailedScenario() {
        //Create admin User
        User adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@test100.com', 'test100');
        adminUser = (User) PC_Database.ins(adminUser);
        List<PC_ReminderQueue__c> createdQueues = [SELECT Id, PC_Recipient__c, PC_ReminderSetting__c FROM PC_ReminderQueue__c];
        createdQueues[7].PC_RecordID__c = '12345';
        PC_Database.upd(createdQueues,false);
        System.runAs(adminUser) {
            Test.StartTest();
            SchedulableContext sc = null;
            PC_ProcessQueuesInBatchScheduler queuesInBatchScheduler = new PC_ProcessQueuesInBatchScheduler();
            queuesInBatchScheduler.execute(sc);
            Test.StopTest();
        }
    }
    @isTest static void testReminderLogTrigger() {
        //Create admin User
        User adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@test100.com', 'test100');
        adminUser = (User) PC_Database.ins(adminUser);
        PC_ReminderQueue__c reminderQueue = [SELECT Id FROM PC_ReminderQueue__c LIMIT 1];
        System.runAs(adminUser) {
            Test.StartTest();
            PC_ReminderLog__c reminderLog = new PC_ReminderLog__c();
            reminderLog.PC_ReminderQueue__c = reminderQueue.Id;
            reminderLog.PC_Status__c = PC_Constants.SUCCESS;
            reminderLog.PC_StatusDetails__c = PC_Constants.SUCCESS;
            PC_Database.ins(reminderLog);
            PC_ReminderLog__c insertedLog = new PC_ReminderLog__c();
            insertedLog = [SELECT Id,PC_Status__c,PC_StatusDetails__c FROM PC_ReminderLog__c LIMIT 1];
            insertedLog.PC_StatusDetails__c +=  PC_Constants.SUCCESS;
            PC_Database.upd(insertedLog,false);
            Test.StopTest();
        }
    }
}