objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>The date of birth of the patient</description>
        <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>The status allows records to be classified as inactive and filters out of lookups and reports. The status is used to support validation rules for related records.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>HCO</fullName>
        <active>true</active>
        <description>Hospital, Clinic, Long Term Care Facility or Private Practice</description>
        <label>HCO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Care_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated support coordinator</description>
        <label>Care Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Reimbursment_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reimbursement Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Association__c.object
<CustomObject>
    <description>PatientConnect custom object to manage the patient program&apos;s care team (including physician)</description>
    <fields>
        <fullName>PC_Associated_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect Internal User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the Account is associated as part of the patient&apos;s circle of care.</description>
        <label>Patient Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Care Team</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Interaction__c.object
<CustomObject>
    <description>Patient Connect custom object used to manage information and activities for interactions with / for patients such as infusion appointments, training sessions or another types of patient appointments typically delivered by 3rd parties.</description>
    <fields>
        <fullName>PC_Participants__c</fullName>
        <description>Roles of the participants in the Interaction</description>
        <label>Participants</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCO</fullName>
                </value>
                <value>
                    <fullName>Treating Physician</fullName>
                </value>
                <value>
                    <fullName>Care Coordinator</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Specialist</fullName>
                </value>
                <value>
                    <fullName>Field Reimbursement Manager</fullName>
                </value>
                <value>
                    <fullName>Caregiver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Patient_Program__c</fullName>
        <description>The Program case to which the interaction is related.</description>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>The status of the Interaction such as Requested or Confirmed.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_InteractionParticipant__c.object
<CustomObject>
    <fields>
        <fullName>PC_Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Association</label>
        <referenceTo>PC_Association__c</referenceTo>
        <relationshipLabel>Interaction Participants</relationshipLabel>
        <relationshipName>PC_AssociationInteractionParticipants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Interaction__c</fullName>
        <description>Interaction to which Participant is attending</description>
        <label>Interaction</label>
        <referenceTo>PC_Interaction__c</referenceTo>
        <relationshipLabel>Interaction Participants</relationshipLabel>
        <relationshipName>PC_InteractionParticipant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Interaction Participant</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Interaction Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Test_UpsertIntParticipantsHandler.cls
/*********************************************************************************************************
Class Name      : PC_Test_UpsertIntParticipantsHandler
Description     : Test class for PC_UpsertInteractionParticipantsHandler
Created Date    : Nov 18, 2021
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer            Date                Description
--------------------------------------------------------------------------------------------------------------
Haritha Reddy        Nov 18, 2021        [PC-8339] Initial Version
***************************************************************************************************************/
@isTest
public class PC_Test_UpsertIntParticipantsHandler {
    private static User adminUser,careCoordinator,reimbursementSpecialist;
    private static Account patient;
    private static Case programCase;
    private static PC_Interaction__c interactonRecord;

    @testSetup static void setup() {
        // Create Admin User
        adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'testAdminUser1@test.com', 'test1');
        PC_Database.ins(adminUser);

        //Create Care Coordinator
        careCoordinator = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'testCCUser2@test.com', 'test2');
        careCoordinator = (User) PC_Database.ins(careCoordinator);

        //Create Care Coordinator
        reimbursementSpecialist = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'testRSUser3@test.com', 'test3');
        reimbursementSpecialist = (User) PC_Database.ins(reimbursementSpecialist);

        patient = PC_Test_Setup.createSampleAccount('', PC_Constants.PATIENT_RECORD_TYPE);
        patient.PC_Date_of_Birth__c = date.today().addDays(-100);
        patient = (Account)PC_Database.ins(patient, false);
        system.assertNotEquals(patient.Id, null);

        programCase = PC_Test_Setup.createCase(adminUser, patient);
        programCase.PC_Care_Coordinator__c = careCoordinator.Id;
        programCase.PC_Reimbursment_Specialist__c = reimbursementSpecialist.Id;
        programCase = (Case)PC_Database.ins(programCase, false);
        system.assertNotEquals(programCase.Id, null);

        interactonRecord = new PC_Interaction__c();
        interactonRecord.PC_Patient_Program__c = programCase.Id;
        interactonRecord.PC_Participants__c = 'HCO; Care Coordinator';
        interactonRecord.PC_Status__c = 'Requested';
        PC_Database.ins(interactonRecord, false);

    }

    @isTest static void testParticipantCreation() {
        User adminUser1 = [Select Id from User WHERE username = 'testAdminUser1@test.com'];
        User ccUser = [Select Id from User WHERE username = 'testCCUser2@test.com'];
        Case caseRecord = [Select Id from Case  LIMIT 1];
        PC_Association__c association = [Select Id from PC_Association__c
        where PC_Program__c =: caseRecord.id  AND PC_Associated_User__c =: ccUser.id LIMIT 1];

        System.runAs(adminUser1) {
            Test.StartTest();

            PC_Interaction__c interaction = new PC_Interaction__c();
            interaction.PC_Patient_Program__c = caseRecord.Id;
            interaction.PC_Participants__c = 'HCO; Care Coordinator';
            interaction.PC_Status__c = 'Requested';
            interaction = (PC_Interaction__c)PC_Database.ins(interaction, false);

            Test.stopTest();

            List<PC_InteractionParticipant__c> interactionParticipants = new List<PC_InteractionParticipant__c>();
            interactionParticipants = [Select Id,PC_Association__c FROM PC_InteractionParticipant__c WHERE PC_Interaction__c =: interaction.Id];
            System.assertEquals(interactionParticipants.size(), 1);
            System.assertEquals(interactionParticipants[0].PC_Association__c, association.Id);

        }
    }


    @isTest static void testParticipantUpdate() {
        User adminUser1 = [Select Id from User WHERE username = 'testAdminUser1@test.com'];
        User rsUser = [Select Id from User WHERE username = 'testRSUser3@test.com'];
        PC_Interaction__c interaction = [Select Id,PC_Participants__c from PC_Interaction__c  LIMIT 1];
        Case caseRecord = [Select Id from Case  LIMIT 1];
        PC_Association__c association = [Select Id from PC_Association__c
        where PC_Program__c =: caseRecord.id AND PC_Associated_User__c =: rsUser.Id LIMIT 1];

        System.runAs(adminUser1) {
            Test.StartTest();

            interaction.PC_Participants__c = 'HCO; Reimbursement Specialist';
            PC_Database.upd(interaction, false);

            Test.stopTest();

            List<PC_InteractionParticipant__c> interactionParticipants = new List<PC_InteractionParticipant__c>();
            interactionParticipants = [Select Id,PC_Association__c FROM PC_InteractionParticipant__c
            WHERE PC_Interaction__c =: interaction.Id AND PC_Association__r.PC_Associated_User__c =: rsUser.Id];
            System.assertEquals(interactionParticipants.size(), 1);
            System.assertEquals(interactionParticipants[0].PC_Association__c, association.Id);
        }
    }
}