objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>The date of birth of the patient</description>
        <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Gender__c</fullName>
        <description>The gender of the patient.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Address__c.object
<CustomObject>
    <description>PatientConnect custom object used to track addresses of all types of participants (accounts), including the patient</description>
    <fields>
        <fullName>PC_City__c</fullName>
        <description>The city address.</description>
        <label>City</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_State__c</fullName>
        <description>The state associated with the address. The state is controlled by the country.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PC_Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Zip_Code__c</fullName>
        <description>The zip code associated with the address.</description>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Health_Plan__c.object
<CustomObject>
    <description>Patient Connect custom object: Used to capture a patient&apos;s various health plans (private insurance companies, public payer plans) as part of Patient Connect&apos;s access functionality</description>
    <fields>
        <fullName>Group_No__c</fullName>
        <description>Group number of the private insurance</description>
        <label>Group No.</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Policy_No__c</fullName>
        <description>Identification number / policy number of private insurance</description>
        <label>ID / Policy No.</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Cardholder_Relationship_to_Patient__c</fullName>
        <description>Relationship of cardholder to patient</description>
        <label>Cardholder Relationship to Patient</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Relationship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Group_name__c</fullName>
        <description>Group name of the health plan</description>
        <label>Group name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Has_LTC_Coverage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this flag is checked, it means the coverage is by long term care pharmacy</description>
        <label>Longterm Coverage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Has_Mail_Coverage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if Health Plan has mail coverage benefit</description>
        <label>Mail Coverage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Has_Retail_Coverage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if Health Plan has retail coverage benefit</description>
        <label>Retail Coverage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Has_Specialty_Coverage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this flag is checked, it means the coverage is by specialty pharmacy</description>
        <label>Specialty Coverage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Rx_Bin__c</fullName>
        <description>Six-digit number that health plans can use to process electronic pharmacy claims</description>
        <label>Rx Bin</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Rx_PCN__c</fullName>
        <description>Used to story PCN for Pharmacy Benefits Claims</description>
        <label>Rx PCN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Health Plan</label>
    <nameField>
        <displayFormat>HP-{000000000}</displayFormat>
        <label>Health Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/PC_Relationship.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Self</fullName>
    </customValue>
    <customValue>
        <fullName>Spouse</fullName>
    </customValue>
    <customValue>
        <fullName>Child</fullName>
    </customValue>
    <customValue>
        <fullName>Father</fullName>
    </customValue>
    <customValue>
        <fullName>Mother</fullName>
    </customValue>
    <customValue>
        <fullName>Domestic Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Guardian</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Relationship</masterLabel>
</GlobalValueSet>

classes/PC_PharmacyCardLookup_Example.cls
/*********************************************************************************************************
Class Name      : PC_PharmacyCardLookup_Example
Description     : Implementor class for PC_PharmaCardLookup
Created By      : Vijay Kashikar
Created Date    : Mar 19, 2018
Modification Log:
-----------------------------------------------------------------------------------------------------
Developer                   Date                           Description
-----------------------------------------------------------------------------------------------------
Vijay Kashikar               Mar 19, 2018              Initial Version
Vijay Kashikar         		 May 29, 2018              Added FLS checks
*********************************************************************************************************/
public with sharing class PC_PharmacyCardLookup_Example implements PC_eBenefits.PharmacyCard {
    private String accessToken = null;
    private static final String PHARMACY_DETAILS_API_URL = 'https://api-tr-connectedhealth.dev.ubcpsc.com/plans/PBMs/?AbbreviatedName={1}';

    public PC_eBenefits.PharmacyCardResponse lookupPharmacyCard(PC_eBenefits.PharmacyCardRequest request) {

        try {

            PC_PharmacyCardLookup_Example client = new PC_PharmacyCardLookup_Example();
            PC_eBenefits.PharmacyCardResponse cResponse = new PC_eBenefits.PharmacyCardResponse();
            cResponse.bin = '003858';
            cResponse.insuranceGroupId = '3320057AAA8008N';
            cResponse.insuranceGroupName = 'MO BLUE ACCESS CH E+';
            cResponse.isSuccess = true;
            cResponse.mailCoverage = true;
            cResponse.pcn = 'A4';
            cResponse.planName = 'PN';
            cResponse.policyID = 'QTUAN2210932';
            cResponse.retailCoverage = false;
            cResponse.longTermCareCoverage = true;
            cResponse.specialtyCoverage = false;

            PC_eBenefits.Patient subscriber = new PC_eBenefits.Patient();
            subscriber.gender = 'Male';
            //subscriber.birthdate = '01/01/1990';
            subscriber.birthdate = PC_eBenefits_Utility.parseDateToJSONDate(Date.today());
            subscriber.dob = Date.today();
            subscriber.firstName = 'Test';
            subscriber.lastName = 'Man';
            cResponse.subscriber = subscriber;

            PC_eBenefits.Address subscriberAddress = new PC_eBenefits.Address();
            subscriberAddress.city = 'Boston';
            subscriberAddress.state = 'MA';
            subscriberAddress.postalCode = '0172';
            subscriber.address = subscriberAddress;

            cResponse = client.setResponseLabels(cResponse);

            return cResponse;
        }
        catch (exception ex){
            system.debug('message '+ex.getMessage()+' line '+ex.getStackTraceString());
            PC_Utility.logAndThrowException(ex);
        }
        return null;
    }
    public PC_eBenefits.PharmacyCardResponse setResponseLabels(PC_eBenefits.PharmacyCardResponse response) {
        if(response != null) {
            response.planNameLabel = 'PN';
            response.pcnLabel = PC_Health_Plan__c.PC_Rx_PCN__c.getDescribe().getLabel();
            response.insuranceGroupNameLabel = PC_Health_Plan__c.PC_Group_name__c.getDescribe().getLabel();
            response.insuranceGroupIdLabel = PC_Health_Plan__c.Group_No__c.getDescribe().getLabel();
            response.binLabel = PC_Health_Plan__c.PC_Rx_Bin__c.getDescribe().getLabel();
            response.policyIDLabel = PC_Health_Plan__c.ID_Policy_No__c.getDescribe().getLabel();
            response.mailCoverageLabel = PC_Health_Plan__c.PC_Has_Mail_Coverage__c.getDescribe().getLabel();
            response.retailCoverageLabel = PC_Health_Plan__c.PC_Has_Retail_Coverage__c.getDescribe().getLabel();
            response.longTermCareCoverageLabel = PC_Health_Plan__c.PC_Has_LTC_Coverage__c.getDescribe().getLabel();
            response.specialtyCoverageLabel = PC_Health_Plan__c.PC_Has_Specialty_Coverage__c.getDescribe().getLabel();


            response.subscriber.nameLabel = Account.Name.getDescribe().getLabel();
            response.subscriber.birthdateLabel = Account.PC_Date_of_Birth__c.getDescribe().getLabel();
            response.subscriber.genderLabel = Account.PC_Gender__c.getDescribe().getLabel();
            response.subscriber.cardHolderRelationshipLabel =PC_Health_Plan__c.PC_Cardholder_Relationship_to_Patient__c.getDescribe().getLabel();


            response.subscriber.address.postalCodeLabel = PC_Address__c.PC_Zip_Code__c.getDescribe().getLabel();
            response.subscriber.address.cityLabel = PC_Address__c.PC_City__c.getDescribe().getLabel();
            response.subscriber.address.stateLabel = PC_Address__c.PC_State__c.getDescribe().getLabel();
            return response;
        }
        else {
            return null;
        }


    }
    public PC_eBenefits.PharmacyCardRequest createPharmacyCardRequest() {

        //return PC_eBenefits_Utility.createPharmacyCardRequest(caseId);
        return new PC_eBenefits.PharmacyCardRequest();
    }
    public void updateHealthPlan(PC_eBenefits.PharmacyCardResponse response, PC_Health_Plan__c healthPlan) {
        PC_eBenefits_Utility.updatePharmacyHealthPlan(healthPlan, response);
    }
}