objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_First_Name__c</fullName>
        <description>The first name of the account holder.</description>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Last_Name__c</fullName>
        <description>The last name of the account holder.</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_NPI__c</fullName>
        <description>National Provider Identifier number</description>
        <label>NPI</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Health plan using which the PA case was created</description>
        <inlineHelpText>Health plan using which the PA case was created</inlineHelpText>
        <label>Health Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Health_Plan__c.Patient__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated physician account</description>
        <label>Physician</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PC_Physician</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Physician</relationshipLabel>
        <relationshipName>Physician</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect custom look up field to associate program coverage record to capture outcome of BI/BV case, PAP case or Copay case</description>
        <label>Program Coverage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>You can see only program coverage associated with the current program case.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PC_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Address__c.object
<CustomObject>
    <description>PatientConnect custom object used to track addresses of all types of participants (accounts), including the patient</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <description>The account to which the address is associated with.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Health_Plan__c.object
<CustomObject>
    <description>Patient Connect custom object: Used to capture a patient&apos;s various health plans (private insurance companies, public payer plans) as part of Patient Connect&apos;s access functionality</description>
    <label>Health Plan</label>
    <nameField>
        <displayFormat>HP-{000000000}</displayFormat>
        <label>Health Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Prescription__c.object
<CustomObject>
    <description>This Object captures prescription information for the prescribed drug for a patient when enrolled in an engagement program.</description>
    <fields>
        <fullName>PC_Physician_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The treating physician account associated with a specific prescription.</description>
        <label>Physician</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Physician does not exist or is not a physician account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PC_Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prescriptions (Physician)</relationshipLabel>
        <relationshipName>Physician_Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Program_Coverage__c.object
<CustomObject>
    <description>This is a custom object in Patient Connect that represents patient&apos;s coverage information that satisfies the coverage for the treatment/program that the patient is enrolled into.</description>
    <fields>
        <fullName>PC_Days_Priced__c</fullName>
        <description>Describes the number of days supply for medication that the pricing is returned for by third party service</description>
        <label>Days Priced</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient&apos;s health plan that provides the coverage.</description>
        <label>Health Plan</label>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Program Coverages</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Pharmacy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The health plan payer’s phone number.</description>
        <label>Pharmacy</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Coverage (Pharmacy)</relationshipLabel>
        <relationshipName>Selected_for_Program_Coverage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The prescription associated with the program coverage record</description>
        <label>Prescription</label>
        <referenceTo>PC_Prescription__c</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <description>The outcome status of the coverage.</description>
        <label>Program Coverage Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Pending</fullName>
                </value>
                <value>
                    <fullName>Investigation In Progress</fullName>
                </value>
                <value>
                    <fullName>Eligibility Pending</fullName>
                </value>
                <value>
                    <fullName>Pending PA</fullName>
                </value>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Appeal</fullName>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Sources Not Found</fullName>
                </value>
                <value>
                    <fullName>Covered with Restrictions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the patient is enrolled into and requires coverage for.</description>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Quantity_Priced__c</fullName>
        <description>Describes the quantity of medication that the pricing is returned for by third party service</description>
        <label>Quantity Priced</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Rx_Applied_Deductible__c</fullName>
        <description>Pharmacy Deductable applied amount</description>
        <label>Deductible Applied Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PC_Rx_Applied_Out_Of_Pocket__c</fullName>
        <description>Pharmacy Out Of Pocket Applied Amount</description>
        <label>Out Of Pocket Applied Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PC_Rx_Pay_Amt__c</fullName>
        <description>Pharmacy pay amount</description>
        <label>Patient Pay Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PC_Rx_Remaining_Deductible__c</fullName>
        <description>Pharmacy Deductible Remaining amount</description>
        <label>Deductible Remaining Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PC_Rx_Remaining_Out_Of_Pocket__c</fullName>
        <description>Pharmacy Out Of Pocket Remaining amount</description>
        <label>Out Of Pocket Remaining Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Program Coverage</label>
    <nameField>
        <displayFormat>COV-{000000000}</displayFormat>
        <label>Coverage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_PharmacyEbenefitsLookupController.cls
/*********************************************************************************************************
Class Name      : PC_PharmacyEbenefitsLookupController
Description     : Controller class for PC_PharmacyEbenefitsLookup
Created By      : Vijay Kashikar
Created Date    : Mar 19, 2018
Modification Log:
-----------------------------------------------------------------------------------------------------
Developer                   Date                           Description
-----------------------------------------------------------------------------------------------------
Vijay Kashikar               Mar 19, 2018              Initial Version
Vijay Kashikar         		 May 29, 2018              Added FLS checks
Shishir Bansal              June 22, 2018             added new fields to capture pharmacy details PC-3180
Shishir Bansal              June 26, 2018              added days suppy and quantity values to Program coverage
Vijay Kashikar              Sep  20, 2018              [PC-3777] Made changes so that duplicate pharmacies are not created while saving ebenefit investigation record.
Vijay Kashikar              21-Jan-21                 [PC-7102] Added FLS Checks
*********************************************************************************************************/
public with sharing class PC_PharmacyEbenefitsLookupController {



    @AuraEnabled
    public static PC_eBenefits.PharmacyBenefitsOptions getEBenefitsInfo(String caseId) {
        try {
            PC_eBenefits.PharmacyBenefits2 handler = (PC_eBenefits.PharmacyBenefits2) PC_eBenefits.getPharmacyBenefitsService();
            PC_eBenefits.PharmacyBenefitsOptions request = PC_eBenefits_Utility.getPharmacyBenefitsOptions(caseId);
            system.debug('patient Info - ' + JSON.serialize(request));
            return request;
        }
        catch(Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return null;
    }

    @AuraEnabled
    public static PC_eBenefits.PharmacyBenefitsResponse getPharmacyBenefitInfo(String caseId,
            String healthPlanId, String prescriptionId, String pharmacyId, Boolean isExternalPharmacy,
            Decimal daysSupply, Decimal requestedQuantity, Integer index, String eBenefitsPharmacyJson)
    {
        system.debug('in getPharmacyBenefitInfo');
        system.debug('pharmacyBaseObjectJson -> ' + eBenefitsPharmacyJson);
        PC_eBenefits.PharmacyBenefitsResponse response = new PC_eBenefits.PharmacyBenefitsResponse();
        try {
            PC_eBenefits.PharmacyBenefits2 handler = (PC_eBenefits.PharmacyBenefits2) PC_eBenefits.getPharmacyBenefitsService();


            PC_eBenefits.PharmacyBenefitsRequest pharmacyRequest = handler.createPharmacyBenefitsRequest(); // Blank constructor of Request Body

            PC_eBenefits_Utility.updatePharmacyRequest(caseId, healthPlanId, prescriptionId, pharmacyId,isExternalPharmacy,
                    daysSupply, requestedQuantity, index, pharmacyRequest);

            pharmacyRequest.caseId = caseId;                   //Added new attribute - ACLS
            pharmacyRequest.healthPlanId = healthPlanId;       //Added new attribute - ACLS
            pharmacyRequest.prescriptionId = prescriptionId;   //Added new attribute - ACLS

            response = handler.lookupPharmacyBenefits(pharmacyRequest);
            response.pharmacyId = pharmacyId;
            response.healthPlanId = healthPlanId;
            response.caseId = caseId;
            response.prescriptionId = prescriptionId;
            response.index = index;
            response.pharmacy = (PC_eBenefits.Pharmacy) JSON.deserialize(eBenefitsPharmacyJson, PC_eBenefits.Pharmacy.class);
            system.debug('patient Info - ' + JSON.serialize(response));
            //throw new PC_eLetter.SenderException('Please update the HealthPlan with BIN, PCN, Group, and MemberID. ');
            return response;
        }
        catch(Exception ex) {
            PC_Utility.publishErrorLog(ex, '');
            response.errorMessage = ex.getMessage();
        }
        response.pharmacyId = pharmacyId;
        response.healthPlanId = healthPlanId;
        response.caseId = caseId;
        response.prescriptionId = prescriptionId;
        response.index = index;
        response.isSuccess = false;
        return response;


    }

    @AuraEnabled
    public static PC_Program_Coverage__c createProgramCoverage(String pharmacyBenefitsDetails_JSON) {
        try {
            PC_eBenefits.PharmacyBenefits2 handler = (PC_eBenefits.PharmacyBenefits2) PC_eBenefits.getPharmacyBenefitsService();
            system.debug('createProgramCoverage. pharmacyBenefitsDetails_JSON -> '+pharmacyBenefitsDetails_JSON);
            PC_eBenefits.PharmacyBenefitsResponse coverageDetails = (PC_eBenefits.PharmacyBenefitsResponse) JSON.deserialize(pharmacyBenefitsDetails_JSON, PC_eBenefits.PharmacyBenefitsResponse.class);
            system.debug('coverageDetails -> '+coverageDetails);
            PC_Program_Coverage__c newProgCoverage = new PC_Program_Coverage__c();
            newProgCoverage.PC_Program__c = coverageDetails.caseId;
            newProgCoverage.PC_Health_Plan__c = coverageDetails.healthPlanId;
            //Boolean isExtenalPharmacy = PC_eBenefits_Utility.isExternalPharmacy(coverageDetails.pharmacyId);
            Boolean isExtenalPharmacy =coverageDetails.pharmacy.isExternalPharmacy;
            
            

            if(isExtenalPharmacy) {
                List<Account> pharmacies = PC_eBenefits_Utility.getPharmaciesBy_NPI_OR_NCPDP(coverageDetails.pharmacy.npi, coverageDetails.pharmacy.ncpdp);
                Account existingPharmacy;
                if (pharmacies == null || pharmacies.isEmpty()) {
                    existingPharmacy = null;
                } else if (pharmacies.size() == 1) {
                    existingPharmacy = pharmacies[0];
                } else {
                    PC_eBenefits_Utility.eBenefitsException ex = new PC_eBenefits_Utility.eBenefitsException();
                    ex.setMessage(String.format(Label.PC_Ebenefits_Duplicate_Pharmacy, new List<String>{
                            coverageDetails.pharmacy.npi, coverageDetails.pharmacy.ncpdp
                    }));
                    throw ex;
                }
                if(existingPharmacy == null || String.isBlank(existingPharmacy.Id)) {
                    Account newPharmacy = new Account();
                    PC_Address__c newPharmacyAddress = new PC_Address__c();
                    newPharmacy.RecordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.PC_ACCOUNT, PC_Constants.PHARMACY_RECORD_TYPE);
                    handler.updatePharmacy(coverageDetails, newPharmacy, newPharmacyAddress);
                    system.debug('record to insert-->' + newPharmacy);
                    Account newPharmacyAccount = (Account) PC_Database.ins(newPharmacy);
                    newPharmacyAddress.PC_Account__c = newPharmacyAccount.Id;
                    PC_Address__c newPharmacyAccAddress = (PC_Address__c) PC_Database.ins(newPharmacyAddress);
                    newProgCoverage.PC_Pharmacy__c = newPharmacyAccount.Id;
                }
                else {
                    newProgCoverage.PC_Pharmacy__c = existingPharmacy.Id;
                }

            }
            else {
                //newProgCoverage.PC_Pharmacy__c = PC_eBenefits_Utility.getPharmacyIdBy_Id_Or_ExtId(coverageDetails.pharmacyId);
                newProgCoverage.PC_Pharmacy__c = coverageDetails.pharmacyId;

            }

            newProgCoverage.PC_Prescription__c = coverageDetails.prescriptionId;
            if(coverageDetails.eBenefitsServiceResponse.pricing.patient!= null)
                newProgCoverage.PC_Rx_Pay_Amt__c = coverageDetails.eBenefitsServiceResponse.pricing.patient;
            if(coverageDetails.eBenefitsServiceResponse.accumulators.deductible.individual.applied!= null )
                newProgCoverage.PC_Rx_Applied_Deductible__c  = coverageDetails.eBenefitsServiceResponse.accumulators.deductible.individual.applied;
            if(coverageDetails.eBenefitsServiceResponse.accumulators.deductible.individual.remaining!= null)
                newProgCoverage.PC_Rx_Remaining_Deductible__c     = coverageDetails.eBenefitsServiceResponse.accumulators.deductible.individual.remaining;
            if(coverageDetails.eBenefitsServiceResponse.accumulators.outOfPocket.individual.applied!= null)
                newProgCoverage.PC_Rx_Applied_Out_Of_Pocket__c =   coverageDetails.eBenefitsServiceResponse.accumulators.outOfPocket.individual.applied;
            if(coverageDetails.eBenefitsServiceResponse.accumulators.outOfPocket.individual.remaining!= null)
                newProgCoverage.PC_Rx_Remaining_Out_Of_Pocket__c =coverageDetails.eBenefitsServiceResponse.accumulators.outOfPocket.individual.remaining;


            newProgCoverage.PC_Days_Priced__c = coverageDetails.eBenefitsServiceResponse.daysSupplyPriced;
            newProgCoverage.PC_Quantity_Priced__c =  coverageDetails.eBenefitsServiceResponse.metricQuantityPriced;

            handler.updateProgramCoverage(coverageDetails, newProgCoverage);

            PC_Program_Coverage__c insertedProgCoverage = (PC_Program_Coverage__c) PC_Database.ins(newProgCoverage, true);
            String pcId = insertedProgCoverage.Id;

            List<String> fields = new List<String>();
            fields.add('Id');
            fields.add('NAME');
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Program_Coverage__c'), PC_Database.Operation.Reading, fields);

            PC_Program_Coverage__c pc = [SELECT ID, NAME FROM PC_Program_Coverage__c where id = :pcId];
            return pc;
        }
        catch (exception ex){
            system.debug('message '+ex.getMessage()+' line '+ex.getStackTraceString());
            PC_Utility.logAndThrowException(ex);
        }

        return null;
    }


    @AuraEnabled
    public static PC_eBenefits.Patient getCardHolderInfo(Id healthPlanId) {
        return PC_eBenefits_Utility.getCardHolderInfo_helper(healthPlanId);
    }

    @AuraEnabled
    public static PC_eBenefits.Physician getPhysicianForPrescription(Id prescriptionId ) {
        try {
            system.debug('prescriptionId'+prescriptionId);
            PC_Prescription__c prescription;
            PC_eBenefits.Physician physician;

            //PC_eBenefits.PharmacyCardResponse eligResponse;
            List<String> fields = new List<String>{PC_Constants.getQualifiedAPIName('PC_Physician_Account__c')};
            
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Prescription__c'),PC_Database.Operation.Reading, fields);

            List<String> accountFields = new List<String>();
            accountFields.add(PC_Constants.getQualifiedAPIName('PC_First_Name__c'));
            accountFields.add(PC_Constants.getQualifiedAPIName('PC_Last_Name__c'));
            accountFields.add(PC_Constants.getQualifiedAPIName('PC_NPI__c'));
            PC_Database.assertAccess(PC_Constants.PC_ACCOUNT, PC_Database.Operation.Reading, accountFields);

            if(prescriptionId!=null) {
                prescription =  [Select Id, PC_Physician_Account__c, PC_Physician_Account__r.PC_First_Name__c,PC_Physician_Account__r.PC_Last_Name__c,PC_Physician_Account__r.PC_NPI__c FROM  PC_Prescription__c where Id = :prescriptionId];
            }
             physician = new PC_eBenefits.Physician();


            physician.nameLabel = Case.PC_Physician__c.getDescribe().getLabel();
            physician.npiLabel = Case.PC_Physician__c.getDescribe().getLabel() +' '+ Account.PC_NPI__c.getDescribe().getLabel();
            if(String.isNotBlank(prescription.PC_Physician_Account__c)) {

                physician.npi = prescription.PC_Physician_Account__r.PC_NPI__c;
                physician.firstName =  prescription.PC_Physician_Account__r.PC_First_Name__c;
                physician.lastName =  prescription.PC_Physician_Account__r.PC_Last_Name__c;
                physician.id =  prescription.PC_Physician_Account__c;
            }
            return physician;

        }
        catch(Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return null;
    }

}