objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>The date of birth of the patient</description>
        <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Gender__c</fullName>
        <description>The gender of the patient.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_NPI__c</fullName>
        <description>National Provider Identifier number</description>
        <label>NPI</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Primary_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup to the account’s primary address.</description>
        <label>Address</label>
        <referenceTo>PC_Address__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Address_1__c</fullName>
        <description>The Primary Address 1 of the patient.</description>
        <formula>Account.PC_Primary_Address__r.PC_Address_1__c</formula>
        <label>Address 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address_2__c</fullName>
        <description>The Primary Address 2 of the patient.</description>
        <formula>Account.PC_Primary_Address__r.PC_Address_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_City__c</fullName>
        <description>The primary city of the patient.</description>
        <formula>Account.PC_Primary_Address__r.PC_City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Gender__c</fullName>
        <description>The gender of the patient</description>
        <formula>TEXT ( Account.PC_Gender__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Health plan using which the PA case was created</description>
        <inlineHelpText>Health plan using which the PA case was created</inlineHelpText>
        <label>Health Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Health_Plan__c.Patient__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Phone__c</fullName>
        <description>The patient’s phone number</description>
        <formula>Account.Phone</formula>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated physician account</description>
        <label>Physician</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PC_Physician</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Physician</relationshipLabel>
        <relationshipName>Physician</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_State__c</fullName>
        <description>The State associated with the primary address of the patient</description>
        <formula>TEXT(Account.PC_Primary_Address__r.PC_State__c)</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Zip_Code__c</fullName>
        <description>The zip/postal code associated with the primary address of the patient</description>
        <formula>Account.PC_Primary_Address__r.PC_Zip_Code__c</formula>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Address__c.object
<CustomObject>
    <description>PatientConnect custom object used to track addresses of all types of participants (accounts), including the patient</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <description>The account to which the address is associated with.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Address_1__c</fullName>
        <description>Line 1 of the address.</description>
        <label>Address 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address_2__c</fullName>
        <description>Line 2 of the address.</description>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_City__c</fullName>
        <description>The city address.</description>
        <label>City</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Primary_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Primary Address related to the account. This address reflects on the Account and cases.</description>
        <inlineHelpText>Defines the primary address of the associated account</inlineHelpText>
        <label>Primary Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_State__c</fullName>
        <description>The state associated with the address. The state is controlled by the country.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PC_Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Zip_Code__c</fullName>
        <description>The zip code associated with the address.</description>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Program_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Program Code provides a unique mnemonic or code value that can be used to reference engagement programs. It is expected that a program code would not change during the life of a program, whereas, the name may be modified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Provide a short unique code that will not need to be changed.</inlineHelpText>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Health_Plan__c.object
<CustomObject>
    <description>Patient Connect custom object: Used to capture a patient&apos;s various health plans (private insurance companies, public payer plans) as part of Patient Connect&apos;s access functionality</description>
    <fields>
        <fullName>Patient__c</fullName>
        <description>Person receiving PSP services to and whom this health plan related.</description>
        <label>Patient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Plans</relationshipLabel>
        <relationshipName>Health_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Health Plan</label>
    <nameField>
        <displayFormat>HP-{000000000}</displayFormat>
        <label>Health Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Test_PharmacyCardLookup_UBC.cls
/**
 * Created by vkashikar on 3/22/2018.
 */
@isTest
public class PC_Test_PharmacyCardLookup_UBC {
    private static User adminUser;
    private static final String engagementProgramName = 'engPgm';
    @isTest static void run() {
        adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@test100.com', 'test100');
        PC_Database.ins(adminUser);
        System.runAs(adminUser) {


            List<Account> manufacturers = PC_Test_Setup.createAccounts('testManufacturer', 1, 'Manufacturer');
            manufacturers = (List<Account>) PC_Database.ups(manufacturers);
            Account manufacturer = manufacturers[0];

            Account  patient = PC_Test_Setup.createPatient('testpatient');
            patient.PC_Date_of_Birth__c=Date.today();
            patient.PC_Gender__c='Male';

            patient = (Account)PC_Database.ins(patient, false);
            createAddress(patient.Id);
            system.assertNotEquals(patient.Id, null);

            List<Account> physicians = PC_Test_Setup.createAccounts('PHY',1,PC_Constants.PHYSICIAN_RECORD_TYPE);
            physicians[0].PC_NPI__c='1306200621';

            physicians = PC_Database.ins(physicians);
            createAddress(physicians[0].Id);

            PC_Engagement_Program__c engagementProgram = PC_Test_Setup.createEngagementProgram(engagementProgramName, manufacturer.Id);
            engagementProgram.PC_Program_Code__c = engagementProgramName;
            engagementProgram = (PC_Engagement_Program__c) PC_Database.ups(engagementProgram);
            // check if engagement program is created
            system.assertNotEquals(engagementProgram.Id, Null);

            //Case enrollmentCase = PC_Test_Setup.createEnrollment(engagementProgram.Id);
            Case programCase = PC_Test_Setup.createProgram(patient);
            programCase.PC_Engagement_Program__c = engagementProgram.Id;
            programCase.PC_Physician__c = physicians[0].Id;
            //enrollmentCase.AccountId = patient.Id;
            programCase = (Case) PC_Database.ups(programCase);


            // check if enrollment Case is created
            system.assertNotEquals(programCase.Id, Null);

            List<Account> patients = new List<Account>();
            patients.add(patient);

            List<PC_Health_Plan__c> healthPlans = PC_Test_Setup.createHealthPlans(patients, 1);
            healthPlans[0].Patient__c = patient.Id;
            healthPlans[0].RecordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.PC_HEALTH_PLAN, PC_Constants.HEALTH_PLAN_PHARMACY_PLAN_RECORD_TYPE);
            // insert all health plans
            PC_Database.ins(healthPlans);

            Test.StartTest();

            Test.setMock(HttpCalloutMock.class, new PC_UBC_MockHttpResponseGenerator());
            PC_PharmacyCardLookup_UBC client = new PC_PharmacyCardLookup_UBC();
            PC_UBC_Utility utility = new PC_UBC_Utility();
            boolean token = utility.authenticateViaNamedCreds();
            system.debug(token);
            system.assert(token);

            PC_eBenefits.PharmacyCardRequest cardRequest = client.createPharmacyCardRequest();
            PC_eBenefits_Utility.updatePharmacyCardRequest(programCase.Id, cardRequest);

            PC_eBenefits.PharmacyCardResponse cardResponse = client.lookupPharmacyCard(cardRequest);

            client.updateHealthPlan(cardResponse, healthPlans[0]);
            Test.stopTest();
        }
    }

    public static void createAddress(Id accounId){

        PC_Address__c address = new PC_Address__c();
        address.PC_Account__c = accounId;
        address.PC_Address_1__c = 'test address line 1';
        address.PC_Address_2__c = 'test address line 2';
        address.PC_City__c = 'EDWARDSVILLE';
        address.PC_State__c = 'MA';
        address.PC_Zip_Code__c = '62025';
        //@@RemoveAddressPhone: address.PC_Phone__c = '0727555957';
        address.PC_Primary_Address__c = true;

        address = (PC_Address__c)PC_Database.ins(address, false);
            }

}