objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Country__c</fullName>
        <description>The country name associated with account’s primary address.</description>
        <formula>TEXT(PC_Primary_Address__r.PC_Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Primary_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup to the account’s primary address.</description>
        <label>Address</label>
        <referenceTo>PC_Address__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Address__c.object
<CustomObject>
    <description>PatientConnect custom object used to track addresses of all types of participants (accounts), including the patient</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <description>The account to which the address is associated with.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Address_1__c</fullName>
        <description>Line 1 of the address.</description>
        <label>Address 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_City__c</fullName>
        <description>The city address.</description>
        <label>City</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Country__c</fullName>
        <description>The country associated with the address.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                    <default>true</default>
                    <label>United States</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Primary_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Primary Address related to the account. This address reflects on the Account and cases.</description>
        <inlineHelpText>Defines the primary address of the associated account</inlineHelpText>
        <label>Primary Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_State__c</fullName>
        <description>The state associated with the address. The state is controlled by the country.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PC_Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Zip_Code__c</fullName>
        <description>The zip code associated with the address.</description>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_ProtectedApiSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Protected Api Settings</label>
</CustomObject>

classes/PC_UpdateAccBillingAddr_PriAddrHandler.cls
/*********************************************************************************************************
Trigger Name    : PC_UpdateAccBillingAddr_PrimaryAddr
Description     : trigger on PC_Address__c object.
Created By      : Tetiana Danylyshyn
Created Date    : May 17, 2016
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer          Log#         Date                   	Description
--------------------------------------------------------------------------------------------------------------
Tetiana Danylyshyn             	May 17, 2016          	Initial Version
Alina Balan                    	July 11, 2016         	Added "updatePrimaryAddressOnAccount" method
Shabda Bhujad					Dec 05, 2016			Added FLS check to updatePrimaryAddressOnAccount,updatePrimaryAddress methods
Ajinkya Deshmukh				June 07, 2017			FLS Check Added
Mayuresh Patil                  July 26, 2017           Updated comments for FLS/CRUD checks
Mayuresh Patil                  Nov 1, 2017             Removed google map API to be replaced by salesforce geocoding
Shabda Bhujad                   Nov 14, 2017            PC-2485 Removing the reference to trigger state
Shabda Bhujad                   Dec 18, 2017            PC-1884 Logical breakdown of the trigger handlers
Xiukai Ning                     Feb 28, 2019            PC-3775 - Code review. FLS is NOT needed in Triggers, as they always run in System Mode.
                                                        Trigger delegate class (handler) that has with Sharing keyword however, will apply user sharing.
                                                        We are removing all FLS and With Sharing keywords in the handlers.
Kishore Kanteti                 June 28,2019            [PC-4926]Added Google Map Api for geocoding Line-57
Kishore Kanteti                 August 23,2019          [PC-5331] Added condition to check whether person account enabled/disabled line 56
Satheesh Kumar                  Nov 16, 2021            [PC-8213] Excluded FLS Check and added inherited sharing
Vijay Kashikar                  Jun 16, 2022            [PC-8918] Ensured that the Geolocation fields are updated only for Person Accounts
****************************************************************************************************************/

public inherited sharing class PC_UpdateAccBillingAddr_PriAddrHandler extends PC_TriggerHandler{
    override public void afterInsertUpdate() {
        updatePrimaryAddress(newList);
    }
    /*********************************************************************************
      Method Name    : updatePrimaryAddress
      Author         : Alina BAlan
      Description    : This method will update the billing address on account if its marked
						as primary on address record.
      Return Type    : void
      Parameter      : List of incoming account address records - Trigger.new
     *********************************************************************************/
    private void updatePrimaryAddress(List<PC_Address__c> lstAddresses) {
        Map<Id, Account> accountsToUpdate = new Map<Id, Account>();

        for (PC_Address__c address : lstAddresses) {
            if (address.PC_Primary_Address__c) {
                Account account = new Account();
                account.Id = address.PC_Account__c;
                account.BillingStreet = address.PC_Address_1__c;
                account.BillingCity = address.PC_City__c;
                account.BillingState = address.PC_State__c;
                account.BillingPostalCode = address.PC_Zip_Code__c;
                account.BillingCountry = address.PC_Country__c;
                account.PC_Primary_Address__c = address.Id;
                accountsToUpdate.put(account.Id, account);
            }
        }

        try{
            if (accountsToUpdate != null && !accountsToUpdate.isEmpty()) {
                PC_Database.ups(accountsToUpdate.values(), false);
                updateGeoLocations(accountsToUpdate);
            }

        } catch(Exception e) {
            PC_Utility.createExceptionLog(e);
        }
    }

    private static void updateGeoLocations(Map<Id, Account> accounts) {
        if (PC_ProtectedApiSettings__c.getInstance(PC_Constants.PC_GEOCODE_API_NAME) != null && PC_System.isPersonAccountEnabled()) {
            Set<Id> accountIds = accounts.keySet();
            // Need to do dynamic query as the code needs to be lightly coupled with the Person Account related objs n fields
            // FLS not needed as triggers run in system context
            String query = 'SELECT ID, IsPersonAccount FROM Account WHERE ID IN :accountIds AND IsPersonAccount = true';
            List<Account> personAccounts = Database.query(query);

            Set<Id> personAccountIds = new Set<Id>();
            for (Account acc : personAccounts) {
                personAccountIds.add(acc.Id);
            }

            if (!test.isRunningTest()) {
                PC_GoogleMapServiceV2.updateGeoLocations(personAccountIds);
            }
        }
    }
}