objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>The date of birth of the patient</description>
        <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_First_Name__c</fullName>
        <description>The first name of the account holder.</description>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Last_Name__c</fullName>
        <description>The last name of the account holder.</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_ActiveApplicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the active applicant in an enrollment case, if there are multiple applicants.</description>
        <label>ActiveApplicant</label>
        <referenceTo>PC_Applicant__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>CaseApplicant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>The date of birth of the patient.</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The engagement program associated with the specific applicant.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_First_Name__c</fullName>
        <description>The first name of the patient.</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Last_Name__c</fullName>
        <description>The last name of the patient.</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Applicant associated with this document.</description>
        <label>Applicant</label>
        <referenceTo>PC_Applicant__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Engagement Program lookup for documents.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <description>General Document or Attachment</description>
        <label>Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document_Custom_Workflow_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>PC_Action__c</fullName>
        <description>Custom Label for the Button</description>
        <inlineHelpText>Custom Label for the Button</inlineHelpText>
        <label>Button Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Component__c</fullName>
        <description>Lightning component to be displayed when button is clicked</description>
        <inlineHelpText>Lightning component to be displayed when button is clicked. Include namespace if component has a namespace. &lt;namespaceprefix&gt;:&lt;componentApiName&gt;</inlineHelpText>
        <label>Component</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <description>Engagement Program Code for the engagement program the button should be visible</description>
        <inlineHelpText>Engagement Program Code for the engagement program the button should be visible</inlineHelpText>
        <label>Engagement Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Object_type__c</fullName>
        <label>Object type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Document Custom Workflow Setting</label>
    <pluralLabel>Documents Custom Workflow Setting</pluralLabel>
</CustomObject>

objects/PC_Document_Log__c.object
<CustomObject>
    <description>Patient Connect custom object:  used to link the custom Document object records to various objects</description>
    <fields>
        <fullName>PC_Document_Log__c</fullName>
        <description>A description about the log information modification.</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PC_Document__c</fullName>
        <description>Look up to Document that is created.</description>
        <label>Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient program case associated with the document.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Log</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Document Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if the program is active and can be associated with patients.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Program_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Program Code provides a unique mnemonic or code value that can be used to reference engagement programs. It is expected that a program code would not change during the life of a program, whereas, the name may be modified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Provide a short unique code that will not need to be changed.</inlineHelpText>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program_Service__c.object
<CustomObject>
    <description>Custom junction object to facilitate many-to-many relationships between the Engagement Program and the Service object</description>
    <fields>
        <fullName>PC_Active__c</fullName>
        <description>Indicates whether the Engagement Program Service is currently active.</description>
        <formula>IF( (ISBLANK(  PC_End_Date__c ) ||  ISNULL( PC_End_Date__c ) || 
     PC_End_Date__c &gt;= TODAY()) &amp;&amp; NOT(ISBLANK( PC_Start_Date__c )), true, false)</formula>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <description>Holds the Engagement Program details.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Engagement Program Services</relationshipLabel>
        <relationshipName>PC_Engagement_Program</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Engagement Program Service</label>
    <nameField>
        <displayFormat>EPS-{0}</displayFormat>
        <label>Engagement Program Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Program Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Launch_PreEnrollment.cls
/*********************************************************************************
Class Name      : PC_Launch_PreEnrollment
Description     : Checks if the PC_Docmunent Object as an associated enrollemnt case, and returns True or False
Created By      : TEJAS PATEL
Created Date    : 25-Apr-2017

Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   Description
-----------------------------------------------------------------------------------           
TEJAS PATEL		         25-Apr-2017	              Initial Version
TEJAS PATEL				 02-May-2017				  else if condition to handel NULL account and applicant on the doc,i.e no active applicant
Mike Klumpenaar          23-Jun-2017                  PC-1817 Revert to using PC_SYSTEM.recordTypeId to resolve transaction issue
Mayuresh Patil           07-Sep-2017                  PC-2193 FLS Check updated to new PC303 code
Tejas Patel				 08-Nov-2017				  created new custom label PC_Not_Assigned
Roopsai / Ventkat        20-Aug-2018                  PC-2524 Placeholder button to initiate client custom workflow
*********************************************************************************/
public with sharing class PC_Launch_PreEnrollment {
    private static String nameNotAssigned = System.Label.PC_Not_Assigned;

    /*********************************************************
	Method Name          : checkEnrollment
	Description          : Check If the Documnet has an enrollment case assigned
	Input Params         : Documnet Id
	Return Type          : Returns True if No Enrollment Case assigned and False if Enrollment case is assigned. 
	*********************************************************************************/
    @AuraEnabled
    public static CaseDetails checkEnrollment (ID docID){
        List<PC_Document_Log__c> doc = new List<PC_Document_Log__c>();
        Id recordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.PC_CASE, PC_Constants.CASE_ENROLLMENT_RECORD_TYPE);
        Case enrollmentcase = new Case();
        Account acc			= new Account();
        PC_Applicant__c app	= new PC_Applicant__c();
        
        try {
            //Check FLS/Crud before SOQL            
            List<String> fields = new List<String>{PC_Constants.getQualifiedAPIName('PC_Program__c')};
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Document_Log__c'),PC_Database.Operation.Reading, fields);
            List<String> caseFields = new List<String>{'AccountId', PC_Constants.getQualifiedAPIName('PC_ActiveApplicant__c')};
            PC_Database.assertAccess(PC_Constants.PC_CASE,PC_Database.Operation.Reading, caseFields);
            doc	= [SELECT PC_Program__c, PC_Program__r.AccountId, PC_Program__r.PC_ActiveApplicant__c,PC_Program__r.PC_Engagement_Program__c
            		FROM PC_Document_Log__c 
                   	WHERE PC_Document__c =: docID 
                   	AND (PC_Program__r.RecordTypeId =: recordTypeId) 
                   	LIMIT 1];
        }catch(Exception ex) {
            PC_Utility.logAndThrowException(ex);                
        }      
        if(doc.isEmpty()) {
            CaseDetails casedetails = NULL;
            return casedetails;
        }else if (doc[0].PC_Program__r.AccountId == NULL && doc[0].PC_Program__r.PC_ActiveApplicant__c == NULL) {
            Id enrollmentCaseId	= doc[0].PC_Program__c;
            try {
                //Check FLS/Crud before SOQL            
                List<String> fields = new List<String>{'Id', 'CaseNumber', 'Status', 'Owner.Name', 'CreatedDate'};
                    PC_Database.assertAccess(PC_Constants.PC_CASE,PC_Database.Operation.Reading, fields);
                
                enrollmentcase = [SELECT Id, CaseNumber, Status, Owner.Name, CreatedDate 
                					FROM Case 
                					WHERE Id =: enrollmentCaseId 
                					LIMIT 1];
            }catch(Exception ex) {
                PC_Utility.logAndThrowException(ex);                
            }
            
            CaseDetails casedetails = new CaseDetails(enrollmentcase);
            return casedetails;
            
        }else {
            Id enrollmentCaseId	= doc[0].PC_Program__c;
            Id accountId 		= doc[0].PC_Program__r.AccountId;
            Id applicantId		= doc[0].PC_Program__r.PC_ActiveApplicant__c;
            try {
                //Check FLS/Crud before SOQL            
                List<String> fields = new List<String>{'Id', 'CaseNumber', 'Status', 'Owner.Name', 'CreatedDate'};
                PC_Database.assertAccess(PC_Constants.PC_CASE,PC_Database.Operation.Reading, fields);
                
                enrollmentcase = [SELECT Id, CaseNumber, Status, Owner.Name, CreatedDate 
                					FROM Case 
                					WHERE Id =: enrollmentCaseId 
                					LIMIT 1];  
            }catch(Exception ex) {
                PC_Utility.logAndThrowException(ex);                
            }
            
            if(!String.isEmpty(accountId)) {
                try {
                    //Check FLS/Crud before SOQL            
                    List<String> fields = new List<String>{'Id', 'Name', PC_Constants.getQualifiedAPIName('PC_Date_of_Birth__c')};
                    PC_Database.assertAccess(PC_Constants.PC_ACCOUNT,PC_Database.Operation.Reading, fields);
                    
                    acc = [SELECT Id, Name, PC_Date_of_Birth__c 
                    		FROM Account 
                    		WHERE Id =: accountId 
                    		LIMIT 1];
                    		
                }catch(Exception ex) {
                    PC_Utility.logAndThrowException(ex);                
                }
                
                CaseDetails casedetails = new CaseDetails(acc, enrollmentcase);
                return casedetails;
                
            }else {
                try {
                    //Check FLS/Crud before SOQL            
                    List<String> fields = new List<String>{'Id',PC_Constants.getQualifiedAPIName('PC_Last_Name__c'), PC_Constants.getQualifiedAPIName('PC_First_Name__c'),
                        									PC_Constants.getQualifiedAPIName('PC_Date_of_Birth__c')};
                    PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Applicant__c'),PC_Database.Operation.Reading, fields);
                    
                    app = [SELECT Id, PC_Last_Name__c, PC_First_Name__c, PC_Date_of_Birth__c 
                    		FROM PC_Applicant__c 
                    		WHERE Id =: applicantId 
                    		LIMIT 1];   
                }catch(Exception ex) {
                    PC_Utility.logAndThrowException(ex);                
                }
                
                CaseDetails casedetails = new CaseDetails(app, enrollmentcase);
                return casedetails;
            }
        }
    }
    @AuraEnabled
    public static lstDocumentWorkflowSettingWrapper CheckMetadata (ID docID){
         List<PC_Document_Log__c> doc = new List<PC_Document_Log__c>();
        Id recordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.PC_CASE, PC_Constants.CASE_ENROLLMENT_RECORD_TYPE);
        Case enrollmentcase = new Case();
        Account acc			= new Account();
        PC_Applicant__c app	= new PC_Applicant__c();
        
        try {
            //Check FLS/Crud before SOQL            
            List<String> fields = new List<String>{PC_Constants.getQualifiedAPIName('PC_Program__c')};
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Document_Log__c'),PC_Database.Operation.Reading, fields);
            List<String> caseFields = new List<String>{'AccountId', PC_Constants.getQualifiedAPIName('PC_ActiveApplicant__c')};
            PC_Database.assertAccess(PC_Constants.PC_CASE,PC_Database.Operation.Reading, caseFields);
            doc	= [SELECT PC_Program__c, PC_Program__r.AccountId, PC_Program__r.PC_ActiveApplicant__c,PC_Program__r.PC_Engagement_Program__c,PC_Program__r.PC_Engagement_Program__r.PC_Program_Code__c
            		FROM PC_Document_Log__c 
                   	WHERE PC_Document__c =: docID 
                   	AND (PC_Program__r.RecordTypeId =: recordTypeId) 
                   	LIMIT 1];
        }catch(Exception ex) {
            PC_Utility.logAndThrowException(ex);                
        }
        System.debug('Document Id is' + doc);
        if (!doc.isEmpty()){
            List<lstDocumentWorkflowSettingWrapper> lstDocumentWorkflowSetting = new List<lstDocumentWorkflowSettingWrapper>();
                lstDocumentWorkflowSettingWrapper mWrapper;
                for (PC_Document_Custom_Workflow_Setting__mdt metadata : [select Id,PC_Action__c,PC_Active__c,PC_Component__c,PC_Engagement_Program__c from PC_Document_Custom_Workflow_Setting__mdt where PC_Engagement_Program__c=: doc[0].PC_Program__r.PC_Engagement_Program__r.PC_Program_Code__c and PC_Object_type__c=:'Document'and PC_Active__c=: true LIMIT 1]) {
                mWrapper = new lstDocumentWorkflowSettingWrapper(metadata);
                lstDocumentWorkflowSetting.add(mWrapper);
            }
            System.debug('lstDocumentWorkflowSetting  is' + lstDocumentWorkflowSetting);
            if(lstDocumentWorkflowSetting.size()>0){
                return  lstDocumentWorkflowSetting[0];}
        }
        return null;
    }
	
    
    public class lstDocumentWorkflowSettingWrapper {
       @AuraEnabled public String engagementProgram {get;set;}
        @AuraEnabled public String buttonName {get; set;}
        @AuraEnabled public String componentName {get; set;}
        @AuraEnabled public Boolean Active {get; set;}
        @AuraEnabled public Boolean RequiredAll {get; set;} 
        public lstDocumentWorkflowSettingWrapper() {}
        public lstDocumentWorkflowSettingWrapper(PC_Document_Custom_Workflow_Setting__mdt c) {
            this.engagementProgram = c.PC_Engagement_Program__c;
            this.buttonName = c.PC_Action__c; 
            this.componentName = (c.PC_Component__c.contains(':')) ? c.PC_Component__c : 'c:'+c.PC_Component__c;
            this.Active = c.PC_Active__c;
        }
    }
    public class CaseDetails {
        @AuraEnabled public Id caseId { get; set; }
        @AuraEnabled public Id accountId { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public Date dob { get; set; }
        @AuraEnabled public Date createddate { get; set; }
        @AuraEnabled public String caseowner { get; set; }
        @AuraEnabled public String casenumber { get; set; }
        @AuraEnabled public String casestatus { get; set; }
        
        public CaseDetails() {
        }
        
        public CaseDetails(Account a, Case c) {
            caseId 				= c.Id;
            accountId			= a.Id;
            name	 			= a.Name;
            dob 				= a.PC_Date_of_Birth__c;
            caseowner 			= c.Owner.Name ;
            casenumber 			= c.CaseNumber ;
            casestatus 			= c.Status ;
            createddate 		= c.CreatedDate.date();            
        } 
        
        public CaseDetails(PC_Applicant__c a, Case c) {
            caseId 				= c.Id;
            accountId			= a.Id;
            name                = '';
            if(a.PC_First_Name__c != null && a.PC_Last_Name__c != null){
                name = a.PC_Last_Name__c + ', ' + a.PC_First_Name__c;
            }else if(a.PC_Last_Name__c != null){
                name = a.PC_Last_Name__c;
            }else if(a.PC_First_Name__c != null){
                name = a.PC_First_Name__c;
            }
            dob 				= a.PC_Date_of_Birth__c;
            caseowner 			= c.Owner.Name ;
            casenumber 			= c.CaseNumber ;
            casestatus 			= c.Status ;
            createddate 		= c.CreatedDate.date();
        } 
        
        public CaseDetails(Case c) {
            caseId 				= c.Id;
            accountId			= NULL;
            name	 			= nameNotAssigned;
            dob 				= NULL;
            caseowner 			= c.Owner.Name ;
            casenumber 			= c.CaseNumber ;
            casestatus 			= c.Status ;
            createddate 		= c.CreatedDate.date();
        } 
    }
}