objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_First_Name__c</fullName>
        <description>The first name of the account holder.</description>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Last_Name__c</fullName>
        <description>The last name of the account holder.</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_ParentManufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the manufacturer related with the engagement program&apos;s manufacturer. This field should be used in context of Person Account</description>
        <label>Parent Account(Manufacturer)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Man</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Enrollment_Date__c</fullName>
        <description>The date on which the patient was enrolled to the program</description>
        <label>Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the manufacturer with which the engagement program is associated.</description>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Manufacturer does not exist. Please select a valid manufacturer association.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Manufacturer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Franchise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagement Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program_Service__c.object
<CustomObject>
    <description>Custom junction object to facilitate many-to-many relationships between the Engagement Program and the Service object</description>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <description>Holds the Engagement Program details.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Engagement Program Services</relationshipLabel>
        <relationshipName>PC_Engagement_Program</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Engagement Program Service</label>
    <nameField>
        <displayFormat>EPS-{0}</displayFormat>
        <label>Engagement Program Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Program Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_PatientInfoEWP2Processor.cls
/*********************************************************************************
Class Name      : PC_PatientInfoEWP2Processor
Description     : Creates Account, Program Case and Links Manufacturer to Account
Created By      : Kishore Kanteti
Created Date    : 25-Oct-2021
Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   Description
-----------------------------------------------------------------------------------
Kishore Kanteti 	       25-Oct-21              Initial Version
*********************************************************************************/
global virtual with sharing class PC_PatientInfoEWP2Processor implements PC_EnrollmentWizard.PageProcessor {
    private static String masterPatient = PC_SYSTEM.getPatientConnectSetting(PC_Constants.PC_MASTER_PATIENT,'false').toLowerCase();

    global virtual void processEnrollment(Case enrollmentCase, Map<String, Object> pageState){
        createPatientAccount(enrollmentCase, pageState);
        createProgramCase(enrollmentCase);
    }

    public static void createPatientAccount(Case enrollmentCase, Map<String, Object> pageState){
        if (pageState == null) {
            throw new PC_EnrollmentWizard.PageProcessorException('Missing Page State');
        }
        if (pageState.get('persistentAccount') == null) {
            throw new PC_EnrollmentWizard.PageProcessorException('Missing Account Information');
        }
        Object persistentAccount = (Object) pageState.get('persistentAccount');
        Map<String, Object> patientInfoAccount = (Map<String, Object>) persistentAccount;
        Account acc = new Account();

        //Creating Patient Account
        Object castValue;
        if(patientInfoAccount != null) {
            patientInfoAccount.remove('LastModifiedDate');
            for(String fieldName : patientInfoAccount.keySet()){
                castValue = PC_FieldSetController.castFieldValueBasedOnType(fieldName, patientInfoAccount.get(fieldName), acc);
                acc.put(fieldName, castValue);
            }
        }

        if (enrollmentCase.AccountId != null) {
            acc.put('Id', enrollmentCase.AccountId);
        }
        //Update the RecordType to Patient Record Type
        acc.put('RecordTypeId', PC_SYSTEM.recordTypeId(PC_Constants.PATIENT_OBJECT , PC_Constants.PATIENT_RECORD_TYPE));

        if(PC_SYSTEM.isPersonAccountEnabled()) {
            if(masterPatient == 'false'){
                acc.put('PC_ParentManufacturer__c',enrollmentCase.PC_Engagement_Program__r.PC_Manufacturer__c);
            }
        } else {
            acc.put('Name',(String) (patientInfoAccount.get(PC_Constants.getQualifiedAPIName('PC_Last_Name__c'))) + ' , ' + (String) (patientInfoAccount.get(PC_Constants.getQualifiedAPIName('PC_First_Name__c'))));
            if(masterPatient == 'false'){
                acc.put('ParentId', enrollmentCase.PC_Engagement_Program__r.PC_Manufacturer__c);
            }
        }

        if(acc != null){
            PC_Database.ups(acc);//FLS/CRUD Check enforced in the PC_database method
            PC_EnrollmentWizard.addToRecordsCreated(acc);
            enrollmentCase.AccountId = acc.Id;
        }
    }

    public static void createProgramCase(Case enrollmentCase){
        //Create a new Program Case with patient information
        Case prgCase = new Case();
        prgCase.Status = PC_Constants.STATUS_ENROLLED;
        prgCase.AccountId = enrollmentCase.AccountId;
        prgCase.PC_Engagement_Program__c = enrollmentCase.PC_Engagement_Program__c;
        prgCase.Type = PC_Constants.CASE_PROGRAM_TYPE;

        /*Fetch the case record type id using the values for Program Case Record Type Name and Program Case Record Type Namespace fields from Engagement Program record.
        If the engagement program has no values defined for the former fields then we would consider
        Patient Connect's case record type developer name and namespace to fetch the record type id*/
        Id programCaseRecordTypeId = null;
        programCaseRecordTypeId = PC_SYSTEM.getProgramRecordTypeIdBasedOnEngProgramId(prgCase.PC_Engagement_Program__c);

        if(programCaseRecordTypeId!=null){
            prgCase.RecordTypeId=programCaseRecordTypeId;
        }else{
            prgCase.RecordTypeId = PC_SYSTEM.getDefaultProgramCaseRecordTypeId();
        }

        /* PC-6067: End*/
        prgCase.PC_Enrollment_Date__c = date.today();
        //[PC-1544] Rolled back PC-1467 that populated case orgin on program case with case origin field from related enrollment case
        if(prgCase != null){
            PC_EnrollmentWizard.addToRecordsCreated(prgCase);
            PC_Database.ins(prgCase);//FLS/CRUD Check enforced in the PC_database method
            //Link the newly created program to the Enrollment Case
            enrollmentCase.PC_Program__c = prgCase.Id;
        }
        PC_EnrollmentWizard.addToRecordsCreated(enrollmentCase);
    }
}