objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>The date of birth of the patient</description>
        <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_First_Name__c</fullName>
        <description>The first name of the account holder.</description>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Last_Name__c</fullName>
        <description>The last name of the account holder.</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>The status allows records to be classified as inactive and filters out of lookups and reports. The status is used to support validation rules for related records.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>HCO</fullName>
        <active>true</active>
        <description>Hospital, Clinic, Long Term Care Facility or Private Practice</description>
        <label>HCO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Address__c.object
<CustomObject>
    <description>PatientConnect custom object used to track addresses of all types of participants (accounts), including the patient</description>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>Status that indicates if the address is active or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_AdverseEvent__c.object
<CustomObject>
    <description>The Adverse Event is a custom object in Patient Connect that represents the adverse events reported for the patients enrolled into the patient services program.</description>
    <fields>
        <fullName>PC_Adverse_Event_Reporter__c</fullName>
        <description>The Role who reported Adverse Event.</description>
        <label>Reporter Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Nurse Practitioner</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Physician Assistant</fullName>
                </value>
                <value>
                    <fullName>Other Healthcare Professional</fullName>
                </value>
                <value>
                    <fullName>Risk Manager</fullName>
                </value>
                <value>
                    <fullName>Biomedical Engineer</fullName>
                </value>
                <value>
                    <fullName>Administrator/Supervisor</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
                <value>
                    <fullName>Patient</fullName>
                </value>
                <value>
                    <fullName>Non-Healthcare Professional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Care_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program (Case) to which the adverse event is associated with.</description>
        <label>Care Program</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Adverse Events</relationshipLabel>
        <relationshipName>Adverse_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>Patient&apos;s date of birth. Will be populated from Account.</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Ini_Reporter_Also_Sent_Report_to_FDA__c</fullName>
        <description>Indicates whether the initial reporter also notified or submitted a copy of this report to FDA.</description>
        <label>Ini. Reporter Also Sent Report to FDA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Patient__c</fullName>
        <description>Patient account with which the adverse event is associated.</description>
        <label>Patient</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Adverse Events</relationshipLabel>
        <relationshipName>Adverse_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_ReporterAddress__c</fullName>
        <description>The complete address of the person who reports the adverse event.</description>
        <label>Reporter Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PC_Reporter_City__c</fullName>
        <description>Reporter City</description>
        <label>Reporter City</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Reporter_Country__c</fullName>
        <description>Reporter Country</description>
        <label>Reporter Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Reporter_Email__c</fullName>
        <description>Email address of the Reporter</description>
        <label>Reporter&apos;s Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PC_Reporter_First_Name__c</fullName>
        <description>First name of the reporter</description>
        <label>Reporter&apos;s First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Reporter_Last_Name__c</fullName>
        <description>Last name of the Reporter</description>
        <label>Reporter&apos;s Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Reporter_Phone__c</fullName>
        <description>The telephone number of the person who reports the adverse event.</description>
        <label>Reporter&apos;s Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PC_Reporter_State__c</fullName>
        <description>Reporter State</description>
        <label>Reporter State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Reporter_Zip_Code__c</fullName>
        <description>Reporter&apos;s contact Zip Code.</description>
        <inlineHelpText>Reporter Zip Code</inlineHelpText>
        <label>Reporter Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Adverse Event</label>
    <nameField>
        <displayFormat>AE-{00000000}</displayFormat>
        <label>Adverse Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adverse Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Association__c.object
<CustomObject>
    <description>PatientConnect custom object to manage the patient program&apos;s care team (including physician)</description>
    <label>Association</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Test_AE_InitialReporterRenderer.cls
/*********************************************************************************
Class Name      : PC_Test_AE_InitialReporterRenderer
Description     : Test Class for PC_AE_InitialReporterRendererController Class
Created By      : Xiukai Ning
Created Date    : 30-11-2018
Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   Description
-----------------------------------------------------------------------------------
Xiukai Ning          30-11-2018              Initial Version
*********************************************************************************/
@IsTest
public with sharing class PC_Test_AE_InitialReporterRenderer {

    private static Map<Object, Object> initialReporterObj = new Map<Object, Object>{'firstName'=>'','lastName'=>'','address'=>'','city'=>'','state'=>'','zip'=>'','email'=>'','phone'=>'','occupation'=>'', 'IRalsoSentReportToFDA'=>''};



    @isTest
    static void testInitialReporterDataPopulation() {

        User adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@email.com', 'pctest');
        PC_Database.ins(adminUser, false);

        Case caseRecord = [Select Id from Case  LIMIT 1];
        Account patient  = [Select Id from Account Limit 1];
        PC_AdverseEvent__c aeRec = [Select Id from PC_AdverseEvent__c LIMIT 1];
        Test.StartTest();
        system.runAs(adminUser) {
            PC_AE_InitialReporterRendererController objCntrl = new PC_AE_InitialReporterRendererController();
            PC_AE_InitialReporterRendererController.getInitialReporterData(null, null, String.valueOf(patient.Id));
            PC_AE_InitialReporterRendererController.getReporterDataBasedOnRole(String.valueOf(caseRecord.Id),'HCO');
            objCntrl.updateAdverseEvent(aeRec,initialReporterObj);
            PC_AE_InitialReporterRendererController.getDataFromAE(aeRec.Id,initialReporterObj);
        }
        Test.StopTest();
    }



    /*********************************************************************************
    Method Name    : setup
    Author         : Shishir Bansal
    Description    : This method is used for creating test data
    Return Type    : void
    Parameter      :
    *********************************************************************************/
    @testSetup static void setup() {




        Account patient = new Account();
        patient = PC_Test_Setup.createSampleAccount('', PC_Constants.PATIENT_RECORD_TYPE);
        patient.PC_Date_of_Birth__c = date.today().addDays(-100);
        patient.PC_Status__c = PC_Constants.ACTIVE;
        patient = (Account)PC_Database.ins(patient, false);
        // check if patient is created
        system.assertNotEquals(patient.Id, null);

        Case programCase = PC_Test_Setup.createProgram(patient);
        //programCase = (Case)PC_Database.ins(programCase, false);
        // check if program Case is created
        system.assertNotEquals(programCase.Id, null);

        PC_AdverseEvent__c aeRec = new PC_AdverseEvent__c();

        //insert Adverse Event Record

        aeRec.PC_Patient__c = patient.Id;
        aeRec.PC_Care_Program__c = programCase.Id;

        aeRec.PC_Reporter_First_Name__c = 'TestFirst';
        aeRec.PC_Reporter_Last_Name__c = 'TestLast';
        aeRec.PC_ReporterAddress__c = '123 Lake';
        aeRec.PC_Reporter_City__c = 'Test City';
        aeRec.PC_Reporter_State__c = 'FL';
        aeRec.PC_Reporter_Country__c = 'US';
        aeRec.PC_Reporter_Zip_Code__c = '12345';
        aeRec.PC_Reporter_Email__c = 'test@test.com';
        aeRec.PC_Reporter_Phone__c = '1115557890';
        aeRec.PC_Adverse_Event_Reporter__c = 'Nurse';
        aeRec.PC_Ini_Reporter_Also_Sent_Report_to_FDA__c = 'No';

        PC_Database.ins(aeRec, false);

        Id recordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.PATIENT_OBJECT, 'HCO');
        Account hcoAccount = new Account ();

        hcoAccount.PC_First_Name__c = 'firstHCO';
        hcoAccount.PC_Last_Name__c = 'lastHCO';
        hcoAccount.Name = 'firstHCO lastHCO';
        hcoAccount.RecordTypeId = recordTypeId;

        PC_Database.ins(hcoAccount);

        PC_Association__c association = PC_Test_Setup.createAssociations(programCase.Id , hcoAccount.Id , null , 'HCO');
        PC_Database.ins(association);

        PC_Address__c hcoAddress =  PC_Test_Setup.createAddress(hcoAccount.Id);
        PC_Database.ins(hcoAddress);

    }
}