objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Order__c.object
<CustomObject>
    <fields>
        <fullName>PC_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prescription the order is submitted for.</description>
        <inlineHelpText>Prescription the order is submitted for.</inlineHelpText>
        <label>Prescription</label>
        <referenceTo>PC_Prescription__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Ord-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>PC_DaysSupply__c</fullName>
        <description>Number of days the prescribed medication will last if taken as per the recommended dosage.</description>
        <inlineHelpText>Number of days the prescribed medication will last if taken as per the recommended dosage.</inlineHelpText>
        <label>Days Supply</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_NDC__c</fullName>
        <description>National Drug Code associated with the product being order.</description>
        <formula>PC_Product__r.PC_NDC__c</formula>
        <inlineHelpText>National Drug Code associated with the product being order.</inlineHelpText>
        <label>NDC</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Order__c</fullName>
        <description>Order associated with the order item.</description>
        <inlineHelpText>Order associated with the order item.</inlineHelpText>
        <label>Order</label>
        <referenceTo>PC_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product being ordered.</description>
        <inlineHelpText>Product being ordered.</inlineHelpText>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Quantity__c</fullName>
        <description>Quantity of the product being ordered.</description>
        <inlineHelpText>Quantity of the product being ordered.</inlineHelpText>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Strength__c</fullName>
        <description>Strength of the Drug / Product.</description>
        <formula>PC_Product__r.PC_Strength__c</formula>
        <inlineHelpText>Strength of the Drug / Product.</inlineHelpText>
        <label>Strength</label>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>OrderItemNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Prescription__c.object
<CustomObject>
    <description>This Object captures prescription information for the prescribed drug for a patient when enrolled in an engagement program.</description>
    <fields>
        <fullName>PC_Days_Supply__c</fullName>
        <description>Number of days the prescribed medication will last if taken as per the recommended dosage.</description>
        <label>Days Supply</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The drug associated with a specific prescription.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Prescriptions</relationshipLabel>
        <relationshipName>Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Requested_Quantity__c</fullName>
        <description>Quantity of prescribed medication.</description>
        <label>Requested Quantity</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PC_NDC__c</fullName>
        <description>National Drug Code, is a universal product identifier for human drugs in the United States</description>
        <label>NDC</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Strength__c</fullName>
        <description>Strength of the Drug / Product</description>
        <label>Strength</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PC_Test_CreateOrderItem.cls
/**************************************************************************************
Apex Class Name     : PC_Test_CreateOrderItem
Description         : This class is used for testing PC_CreateOrderItem;
CreatedBy           : Tejas Patel
Created Date        : 09 July 2020
Modification Log    :
--------------------------------------------------------------------------------------------------------------
Developer                   Date                   Description
----------------------------------------------------------------------------
Tejas Patel                 09 July 2020           Initial version
*************************************************************************************/
@isTest
public class PC_Test_CreateOrderItem {

    private static User adminUser;
    public static Boolean isTriggerActive = PC_TriggerHandlerHelper.getTriggerState('PC_Order__c', 'PC_CreateOrderItem');
    public static PC_Prescription__c newPrescription;
    public static Product2 product;

    static void createTestData() {
        Account manufacturer = PC_Test_Setup.createTestAccount(PC_Constants.MANUFACTURER_RECORD_TYPE);
        manufacturer = (Account) PC_Database.ins( manufacturer);

        product = PC_Test_Setup.newProduct('TestProduct', 'P1', manufacturer.Id);
        product.PC_NDC__c = '24542131';
        product.PC_Strength__c = '50';
        product = (Product2) PC_Database.ins( product);

        newPrescription = PC_Test_Setup.newPrescription(product.Id);
        newPrescription = (PC_Prescription__c) PC_Database.ins( newPrescription);
    }

    /*********************************************************************************
    Method Name    : testInsertWithProduct
    Author         : Tejas Patel
    Description    : This method is used for testing createOrderItem on PC_CreateOrderItem
    Return Type    : void
    Parameter      :
    *********************************************************************************/
    @isTest
    static void testInsertWithProduct() {
        if (isTriggerActive) {
            adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@test2.com', 'test2');
            PC_Database.ins(adminUser, false);

            createTestData();

            PC_Order__c orderObj = new PC_Order__c();
            orderObj.PC_Prescription__c = newPrescription.Id;

            List<PC_OrderItem__c> orderItem ;

            Test.StartTest();
            system.runAs(adminUser) {
                orderObj = (PC_Order__c) PC_Database.ins(orderObj);
                orderItem = [SELECT ID, PC_Product__c, PC_Order__c, PC_NDC__c, PC_Strength__c, PC_DaysSupply__c, PC_Quantity__c FROM PC_OrderItem__c];
            }
            system.assertEquals(orderObj.PC_Prescription__c, newPrescription.Id);
            system.assertEquals(orderItem.size(), 1);
            system.assertEquals(orderItem[0].PC_Product__c, product.Id);
            system.assertEquals(orderItem[0].PC_Order__c, orderObj.Id);
            system.assertEquals(orderItem[0].PC_NDC__c, product.PC_NDC__c);
            system.assertEquals(orderItem[0].PC_Strength__c, product.PC_Strength__c);
            system.assertEquals(orderItem[0].PC_DaysSupply__c, newPrescription.PC_Days_Supply__c);
            system.assertEquals(orderItem[0].PC_Quantity__c, newPrescription.PC_Requested_Quantity__c);
            Test.StopTest();
        }
    }
}