objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the manufacturer with which the engagement program is associated.</description>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Manufacturer does not exist. Please select a valid manufacturer association.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Manufacturer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Franchise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagement Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Program Code provides a unique mnemonic or code value that can be used to reference engagement programs. It is expected that a program code would not change during the life of a program, whereas, the name may be modified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Provide a short unique code that will not need to be changed.</inlineHelpText>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Error_Log__c.object
<CustomObject>
    <description>Global error logging object to be used by all applications</description>
    <fields>
        <fullName>PC_Class_Name__c</fullName>
        <description>Name of the Apex class where the exception or error is originated.</description>
        <inlineHelpText>Name of the Apex class where the exception or error is originated.</inlineHelpText>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Error_Message__c</fullName>
        <description>Text for the error message.</description>
        <inlineHelpText>The error message produced by this error</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ACLS_UtilityTest.cls
@isTest
public class ACLS_UtilityTest {
    
    @testSetup 
    static void dataSetup() {
        Map<String,Id> mapAccRecordTypes = ACLS_Utility.getMapOfRecordtype(ACLS_Constants.ACCOUNT);
        
        try{
            //Creating Manufacturer
            Account manufacturer = new Account(Name = 'Test Manufacturer' , recordtypeId = mapAccRecordTypes.get(ACLS_Constants.ACCOUNT_MANUFACTURER_RT));
            insert manufacturer;
            
            //Creating Enagagement program            
            PC_Engagement_Program__c testEP = new PC_Engagement_Program__c(Name = 'Test EP', PC_Program_Code__c = 'testep', PC_Manufacturer__c = manufacturer.Id);
            insert testEP;
            
            //Creating User
            User usr = ACLS_Utility.createTestUser('ACLS Base Profile','TestUser');
            insert usr;
        }
        catch(Exception e){
            PC_Utility.createExceptionLog(e);
        }
    }
    
    @isTest
    public static void test_getEpCode() {
        //Retrieve EP
        PC_Engagement_Program__c ep = [SELECT Id, PC_Program_Code__c FROM PC_Engagement_Program__c  WHERE  PC_Program_Code__c = 'testep' LIMIT 1 ];
        Set<Id> setEPIds = new Set<Id>();
        setEPIds.add(ep.Id);
        
        Map<Id,PC_Engagement_Program__c> mapEpCode = ACLS_Utility.getEpCode(setEPIds);
        System.assertEquals(ep.PC_Program_Code__c, mapEpCode.get(ep.Id).PC_Program_Code__c);
    }
    
    @isTest
    public static void test_getRcordtypeIdByDeveloperName() {
        System.assert(ACLS_Utility.getRecordtypeIdByDeveloperName(ACLS_Constants.OBJ_CASE, ACLS_Constants.CASE_PROGRAM_RT) != null); 
    }
    
    @isTest
    public static void test_getMapOfRecordtype() {
        System.assert(ACLS_Utility.getMapOfRecordtype('Account').size() > 0); 
    }
    @isTest
    public static void test_createTestUser() {
        System.assert(ACLS_Utility.createTestUser('System Administrator','TestName')!= null); 
    }
    @isTest
    public static void test_assignPermissions() {
        User usr = [SELECT id FROM User WHERE lastname = 'TestUser' LIMIT 1];
        System.assert(ACLS_Utility.assignPermissions(usr.Id,'ACLS_Base_Permissions')!= null); 
    }
    @isTest
    public static void test_convertGMTtoEST() {
        DateTime inputDate = DateTime.newInstance(2022, 9, 29, 13, 31, 46);
        DateTime resultDate = DateTime.newInstance(2022, 9, 29, 9, 31, 46);
        system.assertEquals(resultDate, ACLS_Utility.convertGMTtoEST(inputDate), 'Assertion failed');
    }
    @isTest
    public static void test_convertDatetoDateTime() {
        Date inputDate = Date.newInstance(2022, 9, 29);
        DateTime resultDate = DateTime.newInstance(2022, 9, 29, 11, 0, 0);
        system.assertEquals(resultDate, ACLS_Utility.convertDatetoDateTime(inputDate), 'Assertion failed');
    }
    @isTest
    public static void test_getMapOfRecordtypeById() {
        System.assert(ACLS_Utility.getMapOfRecordtypeById('Account').size() > 0); 
    }
    @isTest
    public static void test_getPickListValuesIntoList() {
        System.assert(ACLS_Utility.getPickListValuesIntoList('Account','HealthCloudGA__CountryOfBirth__pc').size() > 0); 
    }
    
    @isTest
    public static void test_getFieldLabelFromFieldAPI() {
        System.assertEquals('Program Code',ACLS_Utility.getFieldLabelFromFieldAPI('PC_Engagement_Program__c','PC_Program_Code__c'),'Field Exception occured'); 
    }

    @isTest
    public static void test_createINTErrorLogs() {
        Test.startTest();
        ACLS_Utility.createINTErrorLogs(null, 'Test Class Error Message', 'Test class stack trace', 'Testing additional info error', 'test', 'ACLS_Utility', 'createINTErrorLogs', null);
        
        Test.stopTest();
        List<PC_Error_Log__c> eg = [Select id, PC_Class_Name__c from PC_Error_Log__c where PC_Class_Name__c = 'ACLS_Utility'];
        system.assertEquals(eg.size()>0, true);

    }
	
	@isTest
    public static void test_createTask() {
        User usr = ACLS_Utility.createTestUser('ACLS Base Profile', 'casemanager12345');
        usr.alias = 'uqusr1';
        usr.email = 'test123@testAshfield.com';
        usr.Username = 'test123@testAhsfield1.com';
        insert usr;
        Map<String, Id> mapAccRecordTypes = ACLS_Utility.getMapOfRecordtype(ACLS_Constants.ACCOUNT);
        
        //Creating Manufacturer 
        List<Account> lstAcct = ACLS_TestDataFactory.createAccount(2);
        lstAcct[0].recordtypeId = mapAccRecordTypes.get(ACLS_Constants.ACCOUNT_MANUFACTURER_RT);
        lstAcct[1].recordtypeId = mapAccRecordTypes.get(ACLS_Constants.ACCOUNT_MANUFACTURER_RT);
        insert lstAcct;
        Test.startTest();
        Task tsk = ACLS_Utility.createTask('Inbound Fax : Exception Occurred', 'Integration', 'Fax', System.today(), usr.id, lstAcct[1].id, '<error message>');
        insert tsk;
        Test.stopTest();
        List<Task> error = [Select id, Subject from Task where Subject = 'Inbound Fax : Exception Occurred'];
        system.assertEquals(error.size()>0, true);
    }
    
     @isTest
    public static void test_logErrors() {
        Test.startTest();
        
        PC_Error_Log__c record = ACLS_Utility.logErrors(null, 'ACLS_Utility', 'logErrors');
        insert record;
        Test.stopTest();
        List<PC_Error_Log__c> error = [Select id, PC_Error_Message__c,PC_Class_Name__c from PC_Error_Log__c where PC_Class_Name__c='ACLS_Utility'];
        system.assertEquals(error.size()>0, true);
    }
}