objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_AdverseEvent2__c.object
<CustomObject>
    <description>The Adverse Event2 is a custom object in Patient Connect that represents the adverse events reported for the patients enrolled into the patient services program.</description>
    <fields>
        <fullName>PC_Care_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program (Case) to which the adverse event is associated with.</description>
        <label>Care Program</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Adverse Events 2</relationshipLabel>
        <relationshipName>Adverse_Events2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adverse Event 2</label>
    <nameField>
        <displayFormat>AE-{00000000}</displayFormat>
        <label>Adverse Events 2 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adverse Events 2</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_AdverseEvent__c.object
<CustomObject>
    <description>The Adverse Event is a custom object in Patient Connect that represents the adverse events reported for the patients enrolled into the patient services program.</description>
    <fields>
        <fullName>PC_Care_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program (Case) to which the adverse event is associated with.</description>
        <label>Care Program</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Adverse Events</relationshipLabel>
        <relationshipName>Adverse_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adverse Event</label>
    <nameField>
        <displayFormat>AE-{00000000}</displayFormat>
        <label>Adverse Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adverse Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_eLetter__c.object
<CustomObject>
    <fields>
        <fullName>PC_Source_Object__c</fullName>
        <description>The objects with which the eLetter is associated.</description>
        <label>Source Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Program Coverage</fullName>
                </value>
                <value>
                    <fullName>Interaction</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Adverse Event 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Template_Name__c</fullName>
        <description>API name for email template.</description>
        <inlineHelpText>Email Template Developer Name</inlineHelpText>
        <label>PC Template Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>eLetter</label>
    <nameField>
        <label>eLetter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eLetters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program_Eletter__c.object
<CustomObject>
    <description>Junction table to associate an eLetter template to multiple programs.</description>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <description>Lookup to the engagement program associated with the eLetter.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Engagement Program eLetter</relationshipLabel>
        <relationshipName>Engagement_Program_eLetter</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_eLetter__c</fullName>
        <description>Lookup to the eLetter template associated with the engagement program.</description>
        <label>eLetter</label>
        <referenceTo>PC_eLetter__c</referenceTo>
        <relationshipLabel>Engagement Program eLetter</relationshipLabel>
        <relationshipName>Engagement_Program_eLetter</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Engagement Program eLetter</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Engagement Program Eletter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Program eLetter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_System_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>PC_eLetter_Sender_Class__c</fullName>
        <defaultValue>&apos;PC_eLetterEmailTemplateSender&apos;</defaultValue>
        <description>The class name of the PC_eLetter.Sender implementation that will be used to send eLetters. The .cls should not be included.</description>
        <label>eLetter Sender Class</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>System Settings</label>
</CustomObject>

classes/PC_Test_SendAdverseEventEmailController.cls
/*********************************************************************************************************
Class Name      : PC_Test_SendAdverseEventEmailController
Description     :
Created By      : Deloitte
Created Date    :
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer                  Date                   Description
Kanteti Kishore           May 5,2020             [PC-5940]Test Class for PC_SendAdverseEventEmailController Component
Hitha Avalakki            Feb 26, 2021           [PC-7442] Replaced PC_Test_Setup.createCases() with PC_Test_Setup.createProgramCases() method.
****************************************************************************************************************/

@IsTest(seeAllData=False)
public with sharing class PC_Test_SendAdverseEventEmailController {
    private static User objUser;
    private static String patientName = 'Patient';
    private static String manufacturerName ='Manufacturer';
    private static String engagementProgramName = 'Program';
    private static String userMail = 'user@t1234.com' ;
    private static String userName = 'TestName' ;
    private static String emailTemplateName = 'PC_TestTemplateName' ;
    private static String adverseEventName = 'Adverse Event' ;
    private static String adverseEvent2Name = 'Adverse Event 2' ;
    private static String senderClassName = 'PC_eLetterEmailTemplateSender' ;

    @testSetup static void setup() {
        objUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, userMail, userName);
        PC_Database.ins(objUser);
        system.runAs(objUser) {
            // Create patient account
            List<Account> accounts = new List<Account>();
            accounts = PC_Test_Setup.createAccounts(patientName, 1, PC_Constants.PATIENT_RECORD_TYPE);
            PC_Database.ins(accounts, false);

            //Create Manufacturer
            List<Account> manufacturerAccounts = new List<Account>();
            manufacturerAccounts = PC_Test_Setup.createAccounts(manufacturerName,1,PC_Constants.MANUFACTURER_RECORD_TYPE);
            PC_Database.ins(manufacturerAccounts, false);

            //Create Engagement Program
            PC_Engagement_Program__c engProgram = new PC_Engagement_Program__c();
            engProgram = PC_Test_Setup.createEngagementProgram(engagementProgramName,manufacturerAccounts[0].Id);
            PC_Database.ins(engProgram, false);

            //Create Case
            List<Case> cases = new List<Case>();
            //[PC-7442] Replaced PC_Test_Setup.createCases() with PC_Test_Setup.createProgramCases() method.
            cases = PC_Test_Setup.createProgramCases(accounts, 1);
            cases[0].PC_Engagement_Program__c =  engProgram.Id;
            PC_Database.ins(cases, false);

            //create Adverse event
            PC_AdverseEvent__c adverseEvent = new PC_AdverseEvent__c();
            adverseEvent = PC_Test_Setup.createAdverseEvents(accounts[0].Id);
            adverseEvent.PC_Care_Program__c = cases[0].Id;
            PC_Database.ins(adverseEvent, false);

            //create Adverse event2
            PC_AdverseEvent2__c adverseEvent2 = new PC_AdverseEvent2__c();
            adverseEvent2 = PC_Test_Setup.newAdverseEvent2(accounts[0].Id);
            //adverseEvent2.PC_Care_Program__c = cases[0].Id;
            PC_Database.ins(adverseEvent2, false);

            //Create Email Template
            EmailTemplate newMailTemplate = new EmailTemplate();
            newMailTemplate = PC_Test_Setup.createEmailTemplate(emailTemplateName);
            PC_Database.ins(newMailTemplate, false);

            //Create eLetter
            PC_eLetter__c eLetter = new PC_eLetter__c();
            eLetter = PC_Test_Setup.createEletter();
            eLetter.PC_Source_Object__c = adverseEventName;
            eLetter.PC_Template_Name__c = emailTemplateName;
            PC_Database.ins(eLetter, false);

            //Create eLetter
            PC_eLetter__c eLetter2 = new PC_eLetter__c();
            eLetter2 = PC_Test_Setup.createEletter();
            eLetter2.PC_Source_Object__c = adverseEvent2Name;
            eLetter2.PC_Template_Name__c = emailTemplateName;
            PC_Database.ins(eLetter2, false);

            //Create engagement program eLetter
            PC_Engagement_Program_Eletter__c engagementProgramEletter = new PC_Engagement_Program_Eletter__c();
            engagementProgramEletter = PC_Test_Setup.createEngagementProgramEletter(engProgram.Id,eLetter.Id,userMail);
            PC_Database.ins(engagementProgramEletter, false);

            //Create System Settings
            PC_System_Settings__c cSetting = new PC_System_Settings__c();
            cSetting.PC_eLetter_Sender_Class__c = senderClassName;
            PC_Database.ins(cSetting);
        }
    }
    @isTest static void testGetEmailAddressAndTemplateDetails() {
        Test.StartTest();
        PC_AdverseEvent__c adverseEvent = new PC_AdverseEvent__c();
        adverseEvent = [SELECT Id FROM PC_AdverseEvent__c LIMIT 1];
        PC_SendAdverseEventEmailController.EmailAddressAndTemplatesWrapper emailAddressAndTemplatesWrapper = new PC_SendAdverseEventEmailController.EmailAddressAndTemplatesWrapper();
        emailAddressAndTemplatesWrapper = PC_SendAdverseEventEmailController.getEmailAddressAndTemplateDetails(adverseEvent.Id);
        system.assertNotEquals(emailAddressAndTemplatesWrapper,null);

        PC_AdverseEvent2__c adverseEvent2 = new PC_AdverseEvent2__c();
        adverseEvent2 = [SELECT Id FROM PC_AdverseEvent2__c LIMIT 1];
        PC_SendAdverseEventEmailController.EmailAddressAndTemplatesWrapper emailAddressAndTemplatesWrapper2 = new PC_SendAdverseEventEmailController.EmailAddressAndTemplatesWrapper();
        emailAddressAndTemplatesWrapper2 = PC_SendAdverseEventEmailController.getEmailAddressAndTemplateDetails(adverseEvent2.Id);
        system.assertNotEquals(emailAddressAndTemplatesWrapper2,null);
        Test.StopTest();
    }
    @isTest static void testSendAdverseEventMail() {
        Test.StartTest();
        PC_AdverseEvent__c adverseEvent = new PC_AdverseEvent__c();
        adverseEvent = [SELECT Id FROM PC_AdverseEvent__c LIMIT 1];
        PC_eLetter__c eLetter = new PC_eLetter__c();
        eLetter = [SELECT Id FROM PC_eLetter__c WHERE PC_Source_Object__c =: adverseEventName LIMIT 1];
        List<String> addresses = new List<String>();
        addresses.add(userMail);
        PC_SendAdverseEventEmailController.sendAdverseEventMail(addresses,String.valueOf(eLetter.Id),adverseEvent.Id);
        Test.StopTest();
    }
}