objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Communication_Language__c</fullName>
        <description>The patient’s preferred communication language such as English, French, and Spanish.</description>
        <label>Communication Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Email__c</fullName>
        <description>The email address of the account.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PC_Specialist_Type__c</fullName>
        <description>The type of the physician specialist. It is dependent on the Account.Type choice &quot;Specialist&quot;.</description>
        <label>Specialist Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cardiologist</fullName>
                </value>
                <value>
                    <fullName>Endocrinologist</fullName>
                </value>
                <value>
                    <fullName>Gastroenterologist</fullName>
                </value>
                <value>
                    <fullName>Hepatologist</fullName>
                </value>
                <value>
                    <fullName>Neurologist</fullName>
                </value>
                <value>
                    <fullName>Oncologist</fullName>
                </value>
                <value>
                    <fullName>Orthopod</fullName>
                </value>
                <value>
                    <fullName>Primary Care</fullName>
                </value>
                <value>
                    <fullName>Rheumatologist</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Sub_Type__c</fullName>
        <description>Used to further categorize accounts when the account type is “Business”.</description>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Infusion Clinic</fullName>
                </value>
                <value>
                    <fullName>Diabetes Center</fullName>
                </value>
                <value>
                    <fullName>MS Clinic</fullName>
                </value>
                <value>
                    <fullName>Hospital Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Retail Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Specialty Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Group Plan</fullName>
                </value>
                <value>
                    <fullName>Federal Plan</fullName>
                </value>
                <value>
                    <fullName>State Plan</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>Eye Clinic</fullName>
                </value>
                <value>
                    <fullName>MRI Service</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>HCO</fullName>
        <active>true</active>
        <description>Hospital, Clinic, Long Term Care Facility or Private Practice</description>
        <label>HCO</label>
    </recordTypes>
    <recordTypes>
        <fullName>PC_Physician</fullName>
        <active>true</active>
        <description>Medical doctor</description>
        <label>Physician</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Communication_Language__c</fullName>
        <description>Patient’s choice of communication language.</description>
        <formula>TEXT ( Account.PC_Communication_Language__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Communication Language</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Email__c</fullName>
        <description>The email of the patient account</description>
        <formula>Account.PC_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Association__c.object
<CustomObject>
    <description>PatientConnect custom object to manage the patient program&apos;s care team (including physician)</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the account which is associated with the patient&apos;s program case.</description>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>PC_Patient</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>PC_Pharmacy</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Payer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Association</relationshipLabel>
        <relationshipName>Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the Account is associated as part of the patient&apos;s circle of care.</description>
        <label>Patient Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Care Team</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_eLetter__c.object
<CustomObject>
    <fields>
        <fullName>PC_Communication_Language__c</fullName>
        <description>The eLetter can be produced in these languages.</description>
        <inlineHelpText>Select supported languages for this eLetter</inlineHelpText>
        <label>Communication Language</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Send_to_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this flag is checked, all other flags (Send Fax,Send email) are automatically unchecked and the eLetter is sent to the current User (for editing before sending to the Patients/Recipients)</description>
        <inlineHelpText>If Selected, the eLetter will be sent to current logged in User.</inlineHelpText>
        <label>Send to User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Source_Object__c</fullName>
        <description>The objects with which the eLetter is associated.</description>
        <label>Source Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Program Coverage</fullName>
                </value>
                <value>
                    <fullName>Interaction</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Adverse Event 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Target_Recipients__c</fullName>
        <description>Selects the target recipients for the eLetter.</description>
        <label>Target Recipients</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Association_Role</valueSetName>
        </valueSet>
    </fields>
    <label>eLetter</label>
    <nameField>
        <label>eLetter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eLetters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PC_Engagement_Program_Eletter__c.object
<CustomObject>
    <description>Junction table to associate an eLetter template to multiple programs.</description>
    <fields>
        <fullName>PC_eLetter__c</fullName>
        <description>Lookup to the eLetter template associated with the engagement program.</description>
        <label>eLetter</label>
        <referenceTo>PC_eLetter__c</referenceTo>
        <relationshipLabel>Engagement Program eLetter</relationshipLabel>
        <relationshipName>Engagement_Program_eLetter</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Engagement Program eLetter</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Engagement Program Eletter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Program eLetter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Program_Coverage__c.object
<CustomObject>
    <description>This is a custom object in Patient Connect that represents patient&apos;s coverage information that satisfies the coverage for the treatment/program that the patient is enrolled into.</description>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the patient is enrolled into and requires coverage for.</description>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Coverage</label>
    <nameField>
        <displayFormat>COV-{000000000}</displayFormat>
        <label>Coverage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_System_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>PC_eLetter_Sender_Class__c</fullName>
        <defaultValue>&apos;PC_eLetterEmailTemplateSender&apos;</defaultValue>
        <description>The class name of the PC_eLetter.Sender implementation that will be used to send eLetters. The .cls should not be included.</description>
        <label>eLetter Sender Class</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>System Settings</label>
</CustomObject>

globalValueSets/PC_Association_Role.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HCO</fullName>
    </customValue>
    <customValue>
        <fullName>Treating Physician</fullName>
    </customValue>
    <customValue>
        <fullName>Reimbursement Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Care Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Field Reimbursement Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Case Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Caregiver</fullName>
    </customValue>
    <masterLabel>Association Role</masterLabel>
</GlobalValueSet>

classes/PC_Test_eLetterAuraController.cls
/*********************************************************************************
Test Class Name : PC_Test_eLetterAuraController
Description     : Test class for PC_eLetterAuraController
Created By      : Roxana Ivan 
Created Date    : June 21, 2016
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------            
Roxana Ivan            June 21, 2016          Initial Version
Mayuresh Patil         Oct 18, 2017           [PC-2069] Fixing issues due to association trigger
Hitha Avalakki         Mar 12, 2019           [PC-4487] Test code to fetch eLetters as per engagement program
*********************************************************************************/
@isTest
public class PC_Test_eLetterAuraController { 
    static final String PHYSICIAN_RECORD_TYPE = 'PC_Physician';
    static final String ACCOUNT_OBJ = 'Account';
    static final String MOCK_SENDER = 'PC_Test_MockELetterSender';
    private static User adminUser;
    
    /*********************************************************************************
    Method Name    : Test 
    Description    : Test create new user functionality
    Return Type    : void
    Parameter      : None
    *********************************************************************************/
    @isTest
    static void getLetters() {
        Test.StartTest();
        // create a record for the custom setting
        PC_System_Settings__c cSetting = new PC_System_Settings__c();
        cSetting.PC_eLetter_Sender_Class__c = MOCK_SENDER;
        PC_Database.ins(cSetting);

        //Create eLetter
        PC_eLetter__c eletter = new PC_eLetter__c (
            Name = 'Test 1',
            PC_Target_Recipients__c = 'HCO; Treating Physician', 
            PC_Communication_Language__c = 'English',
            PC_Send_to_User__c= false,
            PC_Source_Object__c = 'Case'
        );
        PC_Database.ins(eletter);

        Id accountRecordTypeId = PC_System.recordTypeId(ACCOUNT_OBJ, PHYSICIAN_RECORD_TYPE);
        Account account = new Account();
        account.Name = 'Physician Name';
        account.RecordTypeId = accountRecordTypeId;
        account.PC_Specialist_Type__c = 'Cardiologist';
        account.Type = 'Specialist';
        account.PC_Sub_Type__c = 'Other';
        account.PC_Email__c = 'test@test.com';
        PC_Database.ins(account);
        Case programCase = PC_Test_Setup.newCase(account.Id, PC_Constants.CASE_PROGRAM_RECORD_TYPE);
        PC_Database.ins(programCase);

        System.assertEquals(1, PC_eLetterAuraController.getLetters(programCase.Id).size());

        PC_Association__c association = PC_Test_eLetterAuraController.createAssociation(account, programCase, 'Treating Physician', Date.today().addDays(1));
        
        List<PC_eLetter_Recipient> getRecipients =  PC_eLetterAuraController.getRecipients(eletter.Id, programCase.Id);
        getRecipients[0].sendEmail = true;
        String recipientJSON = System.JSON.serialize(getRecipients);
        System.debug('@@Tejas r'+getRecipients);
        System.assertEquals(account.PC_Email__c, getRecipients[0].recipient.email);
        String rType = (String) String.valueOf(PC_eLetter.RecipientType.ACCOUNT);
        String recepients = '[{"bDisableEmail":false,"bDisableFax":false,"bDisableSendToMe":true,"communicationLanguage":"English","recipient":{"Id":"'+ account.Id+'","communicationLanguage":"English","type":"'+rType+'","email":"test@test.com","name":"Name."},"recipientType":"Specialist","sendEmail":true,"sendFax":false,"sendToMe":false}]';
        String returnMessage = PC_eLetterAuraController.sendOutboundDocuments(recipientJSON, eletter.Id, programCase.Id);
        System.debug('@@Tejas'+returnMessage);
        System.assertNotEquals(returnMessage, null);
        Test.StopTest();
    }

    public static PC_Association__c createAssociation(Account account, Case caseObj, String roleName, Date endDate) {
        PC_Association__c association = new PC_Association__c (PC_Account__c = account.Id, PC_Program__c = caseObj.Id, PC_Role__c = roleName, PC_EndDate__c = endDate);

        return (PC_Association__c)PC_Database.ins(association);
    }

    /*********************************************************************************
    Method Name    : testSendToMe
    Description    : Test send eLetter to user
    Return Type    : void
    Parameter      : None
    *********************************************************************************/
    @isTest
    static void testSendToMe() {
        Test.StartTest();
        // create a record for the custom setting
        PC_System_Settings__c cSetting = new PC_System_Settings__c();
        cSetting.PC_eLetter_Sender_Class__c = MOCK_SENDER;
        PC_Database.ins(cSetting);

        //Create eLetter
        PC_eLetter__c eletter = new PC_eLetter__c (
            Name = 'Test 1',
            PC_Target_Recipients__c = 'HCO; Treating Physician', 
            PC_Communication_Language__c = 'English',
            PC_Send_to_User__c=  true,
            PC_Source_Object__c = 'Case'
        );
        PC_Database.ins(eletter);

        Id accountRecordTypeId = PC_System.recordTypeId(ACCOUNT_OBJ, PHYSICIAN_RECORD_TYPE);
        Account account = new Account();
        account.Name = 'Physician Name';
        account.RecordTypeId = accountRecordTypeId;
        account.PC_Specialist_Type__c = 'Cardiologist';
        account.Type = 'Specialist';
        account.PC_Sub_Type__c = 'Other';
        account.PC_Email__c = 'test@test.com';
        PC_Database.ins(account);

        Case programCase = PC_Test_Setup.newCase(account.Id, PC_Constants.CASE_PROGRAM_RECORD_TYPE);
        PC_Database.ins(programCase);

        PC_Association__c association = PC_Test_eLetterAuraController.createAssociation(account, programCase, 'Treating Physician', Date.today().addDays(1));

        List<PC_eLetter_Recipient> getRecipients =  PC_eLetterAuraController.getRecipients(eletter.Id, programCase.Id);
        System.debug('@Tejas Recepients :' + getRecipients[0].recipientEmail);
        System.assertEquals(account.PC_Email__c, getRecipients[0].recipient.email);

        String recepients = '[{"bDisableEmail":false,"bDisableFax":false,"bDisableSendToMe":true,"communicationLanguage":"English","recipient":{"Id":"'+ account.Id+'","PC_Communication_Language__c":"English","Type":"Specialist","PC_Email__c":"test@a.com","Name":"Name."},"recipientType":"Specialist","sendEmail":false,"sendFax":false,"sendToMe":true}]';
        String returnMessage = PC_eLetterAuraController.sendOutboundDocuments(recepients, eletter.Id, programCase.Id);

        System.assertNotEquals(returnMessage, null);
        Test.StopTest();
    }


    /*********************************************************************************
    Method Name    : testSendToMe
    Description    : Test send eLetter to user
    Return Type    : void
    Parameter      : None
    *********************************************************************************/
    @isTest
    static void testSendFax() {
        Test.StartTest();
        // create a record for the custom setting
        PC_System_Settings__c cSetting = new PC_System_Settings__c();
        cSetting.PC_eLetter_Sender_Class__c = MOCK_SENDER;
        PC_Database.ins(cSetting);

        //Create eLetter
        PC_eLetter__c eletter = new PC_eLetter__c (
            Name = 'Test 1',
            PC_Target_Recipients__c = 'HCO; Treating Physician', 
            PC_Communication_Language__c = 'English',
            PC_Send_to_User__c= false,
            PC_Source_Object__c = 'Case'
        );
        PC_Database.ins(eletter);

        Id accountRecordTypeId = PC_System.recordTypeId(ACCOUNT_OBJ, PHYSICIAN_RECORD_TYPE);
        Account account = new Account();
        account.Name = 'Physician Name';
        account.RecordTypeId = accountRecordTypeId;
        account.PC_Specialist_Type__c = 'Cardiologist';
        account.Type = 'Specialist';
        account.PC_Sub_Type__c = 'Other';
        account.PC_Email__c = 'test@test.com';
        PC_Database.ins(account);

        Case programCase = PC_Test_Setup.newCase(account.Id, PC_Constants.CASE_PROGRAM_RECORD_TYPE);
        PC_Database.ins(programCase);

        PC_eLetterAuraController.getLetters(programCase.Id);
        PC_Association__c association = PC_Test_eLetterAuraController.createAssociation(account, programCase, 'Treating Physician', Date.today().addDays(1));
        
        List<PC_eLetter_Recipient> getRecipients =  PC_eLetterAuraController.getRecipients(eletter.Id, programCase.Id);
        System.assertEquals(account.PC_Email__c, getRecipients[0].recipient.email);

        String recepients = '[{"bDisableEmail":false,"bDisableFax":false,"bDisableSendToMe":false,"communicationLanguage":"English","recipient":{"Id":"'+ account.Id+'","PC_Communication_Language__c":"English","Type":"Specialist","PC_Email__c":"test@a.com","Name":"Name."},"recipientType":"Specialist","sendEmail":false,"sendFax":true,"sendToMe":false}]';
        String returnMessage = PC_eLetterAuraController.sendOutboundDocuments(recepients, eletter.Id, programCase.Id);

        System.assertNotEquals(returnMessage, null);
        Test.StopTest();
    }
     /*********************************************************************************
    Method Name    : testSendToMe
    Description    : Test send eLetter to user
    Return Type    : void
    Parameter      : None
    *********************************************************************************/
    @isTest
    static void testNoRecepients() {
        Test.StartTest();
        // create a record for the custom setting
        PC_System_Settings__c cSetting = new PC_System_Settings__c();
        cSetting.PC_eLetter_Sender_Class__c = MOCK_SENDER;
        PC_Database.ins(cSetting);

        PC_eLetter__c eletter = new PC_eLetter__c (
            Name = 'Test 1',
            PC_Target_Recipients__c = 'HCO; Treating Physician', 
            PC_Communication_Language__c = 'English',
            PC_Send_to_User__c= false,
            PC_Source_Object__c = 'Case'
        );
        PC_Database.ins(eletter);

        Id accountRecordTypeId = PC_System.recordTypeId(ACCOUNT_OBJ, PHYSICIAN_RECORD_TYPE);
        Account account = new Account();
        account.Name = 'Physician Name';
        account.RecordTypeId = accountRecordTypeId;
        account.PC_Specialist_Type__c = 'Cardiologist';
        account.Type = 'Specialist';
        account.PC_Sub_Type__c = 'Other';
        account.PC_Email__c = 'test@test.com';
        PC_Database.ins(account);

        Case programCase = PC_Test_Setup.newCase(account.Id, PC_Constants.CASE_PROGRAM_RECORD_TYPE);
        PC_Database.ins(programCase);

        String recepients = '[{"bDisableEmail":false,"bDisableFax":false,"bDisableSendToMe":false,"communicationLanguage":"English","recipient":{},"recipientType":"Specialist","sendEmail":false,"sendFax":true,"sendToMe":false}]';
        String returnMessage = PC_eLetterAuraController.sendOutboundDocuments(recepients, eletter.Id, programCase.Id);
        System.assertNotEquals(returnMessage, null);
        Test.StopTest();
    }

    /*********************************************************************************
    Method Name    : getLettersAsPerEngagementProgram
    Description    : est code to fetch eLetters as per engagement program
    Return Type    : void
    Parameter      : None
    *********************************************************************************/
    @isTest
    static void getLettersAsPerEngagementProgram() {

        adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@test2.com', 'test2');
        PC_Database.ins(adminUser);
        system.runAs(adminUser) {

            List<PC_eLetter__c> eLetterList = new List<PC_eLetter__c>();
            //Create eLetter
            PC_eLetter__c caseEletter = new PC_eLetter__c(
                    Name = 'Patient Welcome Letter',
                    PC_Object_Record_Types__c = 'Program',
                    PC_Source_Object__c = 'Case'
            );
            eLetterList.add(caseEletter);
            PC_eLetter__c interactionEletter = new PC_eLetter__c(
                    Name = 'ELetter for Interaction',
                    PC_Source_Object__c = 'Interaction'
            );
            eLetterList.add(interactionEletter);
            PC_eLetter__c programCovEletter = new PC_eLetter__c(
                    Name = 'ELetter for Program Coverage',
                    PC_Object_Record_Types__c = 'Private Coverage',
                    PC_Source_Object__c = 'Program Coverage'
            );
            eLetterList.add(programCovEletter);
            PC_Database.ins(eLetterList);

            Account manufacturerAcc = PC_Test_Setup.createTestAccount(PC_Constants.MANUFACTURER_RECORD_TYPE);
            PC_Database.ins(manufacturerAcc, false);
            PC_Engagement_Program__c engagementProgram = PC_Test_Setup.createEngagementProgram('ProgramA', manufacturerAcc.Id);
            PC_Database.ins(engagementProgram, false);

            Account patientAccount = PC_Test_Setup.createSampleAccount('Test Patient', PC_Constants.PATIENT_RECORD_TYPE);
            PC_Database.ins(patientAccount);

            Case programCaseRecord = PC_Test_Setup.createProgram(patientAccount);
            programCaseRecord.PC_Engagement_Program__c = engagementProgram.Id;
            PC_Database.upd(programCaseRecord);

            PC_Interaction__c interactionRecord = PC_Test_Setup.newInteraction(programCaseRecord.Id);
            PC_Database.ins(interactionRecord);

            PC_Program_Coverage__c progCoverageRecord = PC_Test_Setup.createProgramCoverage(programCaseRecord.Id);
            PC_Database.ins(progCoverageRecord);

            PC_Engagement_Program_Eletter__c caseEngagementProgEletter = new PC_Engagement_Program_Eletter__c();
            caseEngagementProgEletter.PC_eLetter__c = caseEletter.Id;
            caseEngagementProgEletter.PC_Engagement_Program__c = engagementProgram.Id;
            PC_Database.ins(caseEngagementProgEletter);

            PC_Engagement_Program_Eletter__c interactionEngagementProgEletter = new PC_Engagement_Program_Eletter__c();
            interactionEngagementProgEletter.PC_eLetter__c = interactionEletter.Id;
            interactionEngagementProgEletter.PC_Engagement_Program__c = engagementProgram.Id;
            PC_Database.ins(interactionEngagementProgEletter);

            PC_Engagement_Program_Eletter__c progCovEngagementProgEletter = new PC_Engagement_Program_Eletter__c();
            progCovEngagementProgEletter.PC_eLetter__c = programCovEletter.Id;
            progCovEngagementProgEletter.PC_Engagement_Program__c = engagementProgram.Id;
            PC_Database.ins(progCovEngagementProgEletter);

            Test.StartTest();

            List<PC_LightningMap> caseELettersList = PC_eLetterAuraController.getLetters(programCaseRecord.Id);
            System.assert(caseELettersList.size() > 1);

            List<PC_LightningMap> interactionELettersList = PC_eLetterAuraController.getLetters(interactionRecord.Id);
            System.assert(interactionELettersList.size() > 1);

            List<PC_LightningMap> progCovELettersList = PC_eLetterAuraController.getLetters(progCoverageRecord.Id);

            Test.StopTest();
        }
    }
}