objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>The date of birth of the patient</description>
        <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect custom look up field to associate program coverage record to capture outcome of BI/BV case, PAP case or Copay case</description>
        <label>Program Coverage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>You can see only program coverage associated with the current program case.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PC_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CoverageBenefit.object
<CustomObject>
    <fields>
        <fullName>PC_CoverageLevel__c</fullName>
        <description>Indicates the type of the health plan associated with the patient. The types of health plan are:
        • Primary: If it is a primary health plan.
            • Secondary: If it is a secondary health plan.</description>
        <label>Coverage Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_ProgramCoverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the program coverage associated with the patient.</description>
        <label>Program Coverage</label>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Coverage Benefits</relationshipLabel>
        <relationshipName>PC_Coverage_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Program_Coverage__c.object
<CustomObject>
    <description>This is a custom object in Patient Connect that represents patient&apos;s coverage information that satisfies the coverage for the treatment/program that the patient is enrolled into.</description>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <description>The outcome status of the coverage.</description>
        <label>Program Coverage Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Pending</fullName>
                </value>
                <value>
                    <fullName>Investigation In Progress</fullName>
                </value>
                <value>
                    <fullName>Eligibility Pending</fullName>
                </value>
                <value>
                    <fullName>Pending PA</fullName>
                </value>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Appeal</fullName>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Sources Not Found</fullName>
                </value>
                <value>
                    <fullName>Covered with Restrictions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the patient is enrolled into and requires coverage for.</description>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Coverage</label>
    <nameField>
        <displayFormat>COV-{000000000}</displayFormat>
        <label>Coverage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Test_MedicalBenefitsListController.cls
/*********************************************************************************
Class Name        : PC_Test_MedicalBenefitsListController
Description       : Test Class for PC_MedicalBenefitsListController Class
Created By        : Haritha Reddy
Created Date      : 13-12-2018
Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   Description
-----------------------------------------------------------------------------------
Haritha Reddy          08-04-2018              Initial Version
Shishir Bansal        10-Dec-2019              [PC-5792] Avoid hardcoding of string variable
*********************************************************************************/
@isTest
public with sharing class PC_Test_MedicalBenefitsListController {
    private static User adminUser;
    private static Case programCase;
    private static List<Id> caseList = new List<Id>();
    private static PC_Program_Coverage__c programCoverage;
    private static memberPlan memberPlan;
    private static coverageBenefit coverageBenefit;
    private static coverageBenefitItem coverageBenefitItem;
    @testSetup static void setUp() {
        adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@email.com', 'pctest');
        PC_Database.ins(adminUser, false);
        PC_Test_Setup.assignHealthCloudPermissionSet(adminUser.Id);
    }
    private static void createTestData() {
        adminUser = [SELECT ID FROM User LIMIT 1];
        Account patient = PC_Test_Setup.createSampleAccount(PC_Constants.EMPTY_STRING, PC_Constants.PATIENT_RECORD_TYPE);
        patient.PC_Date_of_Birth__c = date.today().addDays(-100);
        patient = (Account)PC_Database.ins(patient, false);
        // check if patient is created
        system.assertNotEquals(patient.Id, null);

        programCase = PC_Test_Setup.createCase(adminUser, patient);
        programCase = (Case)PC_Database.ins(programCase, false);
        // check if program Case is created
        system.assertNotEquals(programCase.Id, null);
        caseList.add(programCase.Id);

        //insert Program Coverage Record
        Id medicalCoverageRecordTypeId = PC_System.recordTypeId(PC_Constants.PC_PROGRAM_COVERAGE, PC_Constants.PROGRAM_COVERAGE_MEDICAL_RECORD_TYPE);
        programCoverage = new PC_Program_Coverage__c();
        programCoverage.PC_Program__c = programCase.Id;
        programCoverage.recordTypeId = medicalCoverageRecordTypeId;
        PC_Database.ins(programCoverage, false);

        memberPlan = new memberPlan();
        memberPlan.Name = 'TestPlan';
        memberPlan.MemberId = patient.Id;
        PC_Database.ins(memberPlan, false);

        //insert Coverage Benefit Record
        coverageBenefit =  new coverageBenefit();
        coverageBenefit.Name = 'Test Coverage Benefit';
        coverageBenefit.MemberPlanId = memberPlan.Id;
        coverageBenefit.PC_ProgramCoverage__c = programCoverage.Id;
        coverageBenefit.PC_CoverageLevel__c = PC_Constants.HEALTH_PLAN_TYPE_PRIMARY;
        PC_Database.ins(coverageBenefit, false);

        //insert Coverage Benefit Item Record
        coverageBenefitItem =  new coverageBenefitItem();
        coverageBenefitItem.Name = 'Test Coverage Benefit Item';
        coverageBenefitItem.CoverageBenefitId = coverageBenefit.Id;
        coverageBenefitItem.BenefitCategory = PC_Constants.PC_BENEFITCATEGORY_PRODUCT;
        PC_Database.ins(coverageBenefitItem, false);
    }

    @isTest
    static void testInitialDataLoad() {
        createTestData();
        Test.StartTest();
        system.runAs(adminUser) {
            PC_MedicalBenefitsListController.getRelProgramCoverages(caseList);
        }
        Test.StopTest();
    }
}