objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>The status allows records to be classified as inactive and filters out of lookups and reports. The status is used to support validation rules for related records.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_ActiveApplicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the active applicant in an enrollment case, if there are multiple applicants.</description>
        <label>ActiveApplicant</label>
        <referenceTo>PC_Applicant__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>CaseApplicant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The engagement program associated with the specific applicant.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Applicant associated with this document.</description>
        <label>Applicant</label>
        <referenceTo>PC_Applicant__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Document_Name__c</fullName>
        <description>Name of the Document</description>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Document_Status__c</fullName>
        <description>The status of the document.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review Needed</fullName>
                    <default>true</default>
                    <label>Review Needed</label>
                </value>
                <value>
                    <fullName>Categorized</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Spam</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Illegible</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
                <value>
                    <fullName>Split Failure</fullName>
                </value>
                <value>
                    <fullName>Awaiting Attachment</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Ready for Split</fullName>
                </value>
                <value>
                    <fullName>Split in Progress</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Preview Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Engagement Program lookup for documents.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Page_Count__c</fullName>
        <description>To hold total number of pages of parent document. Added in v3.0.1.</description>
        <label>Page Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <description>General Document or Attachment</description>
        <label>Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document_Log__c.object
<CustomObject>
    <description>Patient Connect custom object:  used to link the custom Document object records to various objects</description>
    <fields>
        <fullName>PC_Document_Log__c</fullName>
        <description>A description about the log information modification.</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PC_Document__c</fullName>
        <description>Look up to Document that is created.</description>
        <label>Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient program case associated with the document.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Log</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Document Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_OcrQueue__c.object
<CustomObject>
    <description>Stores information regarding document queued for the OCR service</description>
    <fields>
        <fullName>PC_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether the document is ready for OCR.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_OcrTemplateType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Template type of the queued up source document</description>
        <label>OCR Template Type</label>
        <referenceTo>PC_OcrTemplateType__c</referenceTo>
        <relationshipLabel>OCR Queue</relationshipLabel>
        <relationshipName>OCR_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_SourceContentId__c</fullName>
        <description>Id of the Document Content Version or Attachment</description>
        <label>Source Content Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_SourceDocument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of the PC Document which queued for OCR.</description>
        <label>Source Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>OCR Queue</relationshipLabel>
        <relationshipName>OCR_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>Current state of the extraction process.</description>
        <inlineHelpText>Current state of the extraction process.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OCR Queue</label>
    <nameField>
        <displayFormat>OCRQ-{00000000}</displayFormat>
        <label>OCR Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCR Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_OcrResult__c.object
<CustomObject>
    <description>Stores information regarding the resulting record created for a document after optical character recognition (OCR) has been performed</description>
    <fields>
        <fullName>PC_OcrQueue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCR Queue</label>
        <referenceTo>PC_OcrQueue__c</referenceTo>
        <relationshipLabel>OCR Results</relationshipLabel>
        <relationshipName>OCR_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_ResultStatus__c</fullName>
        <description>Status of the resulting record</description>
        <label>Result Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_ResultingRecordId__c</fullName>
        <description>Id of the resulting record created</description>
        <label>Resulting Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OCR Result</label>
    <nameField>
        <displayFormat>OR-{00000000}</displayFormat>
        <label>OCR Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCR Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_OcrTemplateType__c.object
<CustomObject>
    <description>It holds different types of Templates of a document supported for OCR</description>
    <fields>
        <fullName>PC_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this record is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>OCR Template Type</label>
    <nameField>
        <label>OCR Template Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Template Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_Prescription__c.object
<CustomObject>
    <description>This Object captures prescription information for the prescribed drug for a patient when enrolled in an engagement program.</description>
    <fields>
        <fullName>PC_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The documents associated with the prescription.</description>
        <label>Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>Prescriptions</relationshipLabel>
        <relationshipName>Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PC_Test_OcrResult_Trigger.cls
/**
 * Created by sathekumar on 11/18/2021.
 */

@IsTest
private class PC_Test_OcrResult_Trigger {
    private static User adminUser;
    private static Case reqEnrollCase;
    private static PC_Document__c oDoc;
    private static PC_Document__c oDoc2;
    private static PC_OcrTemplateType__c ocrTemplateTypeObj;
    private static PC_OcrQueue__c ocrQueueObj;
    private static PC_OcrQueue__c ocrQueueObj2;
    private static PC_OcrResult__c ocrResultObj;
    private static PC_Applicant__c onlineApplicant1;
    private static PC_Prescription__c prescription;
    private static String OCR_TEMPLATE_TYPE_NAME = 'test_OcrResult_Trigger_OcrTemplateType2';
    private static String DOCUMENT_NAME = 'ocrResultTestDocument1';
    private static final String ENG_PROGRAM_NAME = 'OCREng1';

    @isTest static void testOcrResultTrigger() {
        adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@test2.com', 'test2');
        PC_Database.ins(adminUser, false);
        system.runAs(adminUser) {
            Test.StartTest();

            //Create the Manufacturer and Engagement Program for Enrollment Case
            Account manuAcc = PC_Test_Setup.createTestAccount(PC_Constants.MANUFACTURER_RECORD_TYPE);
            PC_Database.ins(manuAcc, false);

            PC_Engagement_Program__c engPrgA = PC_Test_Setup.createEngagementProgram(ENG_PROGRAM_NAME, manuAcc.Id);
            PC_Database.ins(engPrgA, false);

            //Create Applicant
            onlineApplicant1 = PC_Test_Setup.createApplicant('Patel');
            PC_Database.ins(onlineApplicant1, false);

            //Create the Enrollment Case with Applicant
            reqEnrollCase = new Case(
                    Status = 'Open',
                    Origin = 'Web',
                    RecordTypeId = PC_SYSTEM.recordTypeId('Case', PC_Constants.CASE_ENROLLMENT_RECORD_TYPE),
                    Type = PC_Constants.CASE_ENROLLMENT_RECORD_TYPE_NAME,
                    PC_Engagement_Program__c = engPrgA.Id,
                    OwnerId = adminUser.Id,
                    PC_ActiveApplicant__c = onlineApplicant1.Id
            );
            PC_Database.ins(reqEnrollCase, false);

            // Create PC Document
            Id recordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.DOCUMENT_OBJECT, PC_Constants.DOCUMENT_FAX_INBOUND_RECORD_TYPE);
            oDoc = new PC_Document__c();
            oDoc.PC_Document_Status__c = PC_Constants.DOCUMENT_STATUS_REVIEW_NEEDED;
            oDoc.PC_Page_Count__c = 5;
            oDoc.PC_Engagement_Program__c = engPrgA.Id;
            oDoc.RecordTypeId = recordTypeId;
            oDoc.PC_Document_Name__c = DOCUMENT_NAME;
            PC_Database.ins(oDoc, false);

            // Create PC Document2
            oDoc2 = new PC_Document__c();
            oDoc2.RecordTypeId = recordTypeId;
            oDoc2.PC_Document_Status__c = PC_Constants.DOCUMENT_STATUS_REVIEW_NEEDED;
            oDoc2.PC_Page_Count__c = 5;
            oDoc2.PC_Engagement_Program__c = engPrgA.Id;
            oDoc2.PC_Applicant__c = onlineApplicant1.Id;
            oDoc2.PC_Document_Name__c = DOCUMENT_NAME + '2';
            PC_Database.ins(oDoc2, false);

            //Attach file to PC Document
            ContentDocument conDocObj = PC_Test_Setup.createFile(oDoc.Id);
            String contentVersionId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId = :conDocObj.Id AND IsLatest = true LIMIT 1] ?.Id;

            //Create a Document Log
            PC_Document_Log__c docObj = new PC_Document_Log__c();
            docObj.PC_Document__c = oDoc.Id;
            docObj.PC_Program__c = reqEnrollCase.Id;
            PC_Database.ins(docObj, false);

            // Create OCR Queue
            ocrQueueObj = new PC_OcrQueue__c();
            ocrQueueObj.PC_Status__c = 'Queued';
            ocrQueueObj.PC_IsActive__c = PC_Constants.TRUE_BOOLEAN;
            ocrQueueObj.PC_SourceDocument__c = oDoc.Id;
            ocrQueueObj.PC_SourceContentId__c = contentVersionId;
            PC_Database.ins(ocrQueueObj, false);

            // Create OCR Queue2
            ocrQueueObj2 = new PC_OcrQueue__c();
            ocrQueueObj2.PC_Status__c = 'Queued';
            ocrQueueObj2.PC_IsActive__c = PC_Constants.TRUE_BOOLEAN;
            ocrQueueObj2.PC_SourceDocument__c = oDoc2.Id;
            ocrQueueObj2.PC_SourceContentId__c = contentVersionId;
            PC_Database.ins(ocrQueueObj2, false);

            //Create prescription
            prescription = new PC_Prescription__c();
            PC_Database.ins(prescription, false);

            // Create OCR Results
            ocrResultObj = new PC_OcrResult__c();
            ocrResultObj.PC_OcrQueue__c = ocrQueueObj.Id;
            ocrResultObj.PC_ResultingRecordId__c = onlineApplicant1.Id;
            ocrResultObj.PC_ResultStatus__c = 'Success';
            PC_Database.ins(ocrResultObj, false);

            // Create OCR Results2
            PC_OcrResult__c ocrResultObj2 = new PC_OcrResult__c();
            ocrResultObj2.PC_OcrQueue__c = ocrQueueObj2.Id;
            ocrResultObj2.PC_ResultingRecordId__c = onlineApplicant1.Id;
            ocrResultObj2.PC_ResultStatus__c = 'Success';
            PC_Database.ins(ocrResultObj2, false);

            // Create OCR Results3
            PC_OcrResult__c ocrResultObj3 = new PC_OcrResult__c();
            ocrResultObj3.PC_OcrQueue__c = ocrQueueObj.Id;
            ocrResultObj3.PC_ResultingRecordId__c = prescription.Id;
            ocrResultObj3.PC_ResultStatus__c = 'Success';
            PC_Database.ins(ocrResultObj3, false);

            Test.stopTest();
        }
    }
}