objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Caregiver_First_Name__c</fullName>
        <description>The first name of the patient’s caregiver.</description>
        <label>Caregiver First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_First_Name__c</fullName>
        <description>The first name of the account holder.</description>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Last_Name__c</fullName>
        <description>The last name of the account holder.</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Caregiver_First_Name__c</fullName>
        <description>The first name of patient’s caregiver.</description>
        <formula>PC_Program__r.Account.PC_Caregiver_First_Name__c</formula>
        <label>Caregiver First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Program_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Program Code provides a unique mnemonic or code value that can be used to reference engagement programs. It is expected that a program code would not change during the life of a program, whereas, the name may be modified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Provide a short unique code that will not need to be changed.</inlineHelpText>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PC_Test_PatientInfoEWP2Processor.cls
/**
 * Class Name      : PC_Test_PatientInfoEWP2Processor
 * Created By      : Kishore Kanteti
 * @Created Date   : 28-Oct-2021
 * Modification Log:
 * ----------------------------------------------------------------------------------
 * Developer              Date                      Description
 * -----------------------------------------------------------------------------------
 * Kishore Kanteti      28-Oct-2021               Initial Version
 */
@isTest
public class PC_Test_PatientInfoEWP2Processor {
    private static final String engagementProgramName = 'PCPCP';

    @isTest static void runPatientInfoEWP2Processor() {
        User adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@testpc.com','UserName');
        PC_Database.ins(adminUser);

        System.runAs(adminUser) {
            Test.StartTest();
            List<Account> manufacturers = PC_Test_Setup.createAccounts('testManufacturer', 1, 'Manufacturer');
            manufacturers = (List<Account>) PC_Database.ups(manufacturers);
            Account manufacturer = manufacturers[0];

            PC_Engagement_Program__c engagementProgram = PC_Test_Setup.createEngagementProgram(engagementProgramName, manufacturer.Id);
            engagementProgram.PC_Program_Code__c = engagementProgramName;
            engagementProgram = (PC_Engagement_Program__c) PC_Database.ups(engagementProgram);

            Case enrollmentCase = PC_Test_Setup.createEnrollment(engagementProgram.Id);
            enrollmentCase = (Case) PC_Database.ups(enrollmentCase);

            //List<Account> caseAccounts = PC_Test_Setup.createAccounts('caseAcc', 1, 'caseAcc');

            //caseAccounts = (List<Account>) PC_Database.ups(caseAccounts);
            Account caseAcc = PC_Test_Setup.createPatient('sName');
            caseAcc = (Account)  PC_Database.ups(caseAcc);

            enrollmentCase.AccountId = caseAcc.Id;
            enrollmentCase = (Case) PC_Database.ups(enrollmentCase);

            //creating pageState as desired by the processor
            Map<String, Object> pageState = new Map<String, Object>();
            Map<String, Object> patientInfo = new Map<String, Object>();
            patientInfo.put(PC_Constants.getQualifiedAPIName('PC_First_Name__c'),'TestProcessorFirstName');
            patientInfo.put(PC_Constants.getQualifiedAPIName('PC_Last_Name__c'),'TestProcessorLastName');
            patientInfo.put(PC_Constants.getQualifiedAPIName('PC_Caregiver_First_Name__c'), 'TestProcessorCGFirstName');
            pageState.put('persistentAccount',patientInfo);
            PC_PatientInfoEWP2Processor patientInfoEWP2Processor = new PC_PatientInfoEWP2Processor();
            patientInfoEWP2Processor.processEnrollment(enrollmentCase, pageState);

            Id x = enrollmentCase.Id;
            Case updatedCase = [Select Id, AccountId, PC_Program__c from Case where Id = :x];
            Id accId = updatedCase.AccountId;
            Account testAcc = [Select Id,PC_First_Name__c,PC_Last_Name__c From Account where Id = :accId];
            system.assertEquals(testAcc.PC_First_Name__c, 'TestProcessorFirstName', 'Success');
            Test.stopTest();
        }
    }
}