objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_NPI__c</fullName>
        <description>National Provider Identifier number</description>
        <label>NPI</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Address_1__c</fullName>
        <description>The Primary Address 1 of the patient.</description>
        <formula>Account.PC_Primary_Address__r.PC_Address_1__c</formula>
        <label>Address 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address_2__c</fullName>
        <description>The Primary Address 2 of the patient.</description>
        <formula>Account.PC_Primary_Address__r.PC_Address_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_City__c</fullName>
        <description>The primary city of the patient.</description>
        <formula>Account.PC_Primary_Address__r.PC_City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Health plan using which the PA case was created</description>
        <inlineHelpText>Health plan using which the PA case was created</inlineHelpText>
        <label>Health Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Health_Plan__c.Patient__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program’s product</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.PC_Engagement_Program__c</field>
                <operation>equals</operation>
                <valueField>PC_Engagement_Program_Product__c.PC_Engagement_Program__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Engagement_Program_Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Address__c.object
<CustomObject>
    <description>PatientConnect custom object used to track addresses of all types of participants (accounts), including the patient</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <description>The account to which the address is associated with.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Address_1__c</fullName>
        <description>Line 1 of the address.</description>
        <label>Address 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address_2__c</fullName>
        <description>Line 2 of the address.</description>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the manufacturer with which the engagement program is associated.</description>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Manufacturer does not exist. Please select a valid manufacturer association.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Manufacturer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Franchise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagement Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Program Code provides a unique mnemonic or code value that can be used to reference engagement programs. It is expected that a program code would not change during the life of a program, whereas, the name may be modified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Provide a short unique code that will not need to be changed.</inlineHelpText>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program_Product__c.object
<CustomObject>
    <description>Junction object for the many to many association of the program to the product. Single program can be assigned to multiple products under same brand or vise versa - A single product can have multiple programs associated to it.</description>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <description>Lookup to the engagement program associated with the product.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Engagement Program Product</relationshipLabel>
        <relationshipName>Engagement_Program_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Manufacturer__c</fullName>
        <description>The name of the manufacturer with which the product and program are associated.</description>
        <formula>PC_Engagement_Program__r.PC_Manufacturer__r.Name</formula>
        <label>Manufacturer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The product associated with the engagement program.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Engagement Program Product</relationshipLabel>
        <relationshipName>Engagement_Program_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Engagement Program Product</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Program Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Health_Plan__c.object
<CustomObject>
    <description>Patient Connect custom object: Used to capture a patient&apos;s various health plans (private insurance companies, public payer plans) as part of Patient Connect&apos;s access functionality</description>
    <fields>
        <fullName>PC_Card_Holder_First_Name__c</fullName>
        <description>The first name of cardholder</description>
        <label>Cardholder First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Card_Holder_Gender__c</fullName>
        <description>Cardholder&apos;s gender information</description>
        <label>Cardholder Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Card_Holder_Last_Name__c</fullName>
        <description>Cardholder&apos;s last name</description>
        <label>Cardholder Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Cardholder_s_Date_of_Birth__c</fullName>
        <description>Cardholder&apos;s date of birth</description>
        <label>Cardholder&apos;s Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <description>Person receiving PSP services to and whom this health plan related.</description>
        <label>Patient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Plans</relationshipLabel>
        <relationshipName>Health_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Health Plan</label>
    <nameField>
        <displayFormat>HP-{000000000}</displayFormat>
        <label>Health Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Prescription__c.object
<CustomObject>
    <description>This Object captures prescription information for the prescribed drug for a patient when enrolled in an engagement program.</description>
    <fields>
        <fullName>PC_Patient_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient account associated with a specific prescription.</description>
        <label>Patient</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PC_Patient</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prescriptions (Patient)</relationshipLabel>
        <relationshipName>Patient_Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Physician_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The treating physician account associated with a specific prescription.</description>
        <label>Physician</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Physician does not exist or is not a physician account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PC_Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prescriptions (Physician)</relationshipLabel>
        <relationshipName>Physician_Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The drug associated with a specific prescription.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Prescriptions</relationshipLabel>
        <relationshipName>Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program case associated with a specific prescription.</description>
        <label>Program Case</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <errorMessage>Program does not exist or is not a program case.</errorMessage>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Prescriptions</relationshipLabel>
        <relationshipName>Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PC_Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>lookup to the manufacturer account the product is associated to</description>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Manufacturer does not exist. Please select a valid Manufacturer account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Manufacturer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Franchise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_NDC__c</fullName>
        <description>National Drug Code, is a universal product identifier for human drugs in the United States</description>
        <label>NDC</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PC_Test_PharmacyEbenefitsLookup_UBC.cls
/*********************************************************************************************************
Class Name      : PC_Test_PharmacyEbenefitsLookup_UBC
Description     : Test class for PC_PharmacyEbenefitsLookup_UBC
Created By      : Vijay Kashikar
Created Date    : March 26, 2018
Modification Log:
-----------------------------------------------------------------------------------------------------
Developer                   Date                           Description
-----------------------------------------------------------------------------------------------------
Vijay Kashikar               March 26, 2018              Initial Version
*********************************************************************************************************/

@isTest
public with sharing class PC_Test_PharmacyEbenefitsLookup_UBC {
    private static User adminUser;
    private static final String engagementProgramName = 'engPgm';
    @isTest static void run() {
        adminUser = PC_Test_Setup.createUser('System Administrator', 'user@test100.com', 'test100');
        PC_Database.ins(adminUser);
        System.runAs(adminUser) {


            List<Account> manufacturers = PC_Test_Setup.createAccounts('testManufacturer', 1, 'Manufacturer');
            manufacturers = (List<Account>) PC_Database.ups(manufacturers);
            Account manufacturer = manufacturers[0];

            Account  patient = PC_Test_Setup.createPatient('testpatient');
            patient = (Account)PC_Database.ins(patient, false);
            createAddress(patient.Id);
            system.assertNotEquals(patient.Id, null);

            List<Account> physicians = PC_Test_Setup.createAccounts('PHY',1,PC_Constants.PHYSICIAN_RECORD_TYPE);
            physicians[0].PC_NPI__c='1306200621';

            physicians = PC_Database.ins(physicians);
            createAddress(physicians[0].Id);

            List<Account> pharmacies = PC_Test_Setup.createAccounts('testPharmacy',1,PC_Constants.PHARMACY_RECORD_TYPE);
            pharmacies = (List<Account>) PC_Database.ups(pharmacies);
            Account pharmacy = pharmacies[0];

            PC_Engagement_Program__c engagementProgram = PC_Test_Setup.createEngagementProgram(engagementProgramName, manufacturer.Id);
            engagementProgram.PC_Program_Code__c = engagementProgramName;
            engagementProgram = (PC_Engagement_Program__c) PC_Database.ups(engagementProgram);
            // check if engagement program is created
            system.assertNotEquals(engagementProgram.Id, Null);

            Product2 product = new Product2();
            //product.PC_NDC__c = '1234';
            product.PC_Manufacturer__c = manufacturer.Id;
            product.Name = 'testProduct';
            product = (Product2) PC_Database.ins(product);

            PC_Engagement_Program_Product__c programProduct = new PC_Engagement_Program_Product__c();
            programProduct.PC_Engagement_Program__c = engagementProgram.Id;
            programProduct.PC_Product__c = product.Id;
            programProduct = (PC_Engagement_Program_Product__c) PC_Database.ins(programProduct);

            //Case enrollmentCase = PC_Test_Setup.createEnrollment(engagementProgram.Id);
            Case programCase = PC_Test_Setup.createProgram(patient);
            programCase.PC_Engagement_Program__c = engagementProgram.Id;
            programCase.PC_Program_Product__c = programProduct.Id;
            //enrollmentCase.AccountId = patient.Id;
            programCase = (Case) PC_Database.ups(programCase);


            // check if enrollment Case is created
            system.assertNotEquals(programCase.Id, Null);

            List<Account> patients = new List<Account>();
            patients.add(patient);

            List<PC_Health_Plan__c> healthPlans = PC_Test_Setup.createHealthPlans(patients, 1);
            healthPlans[0].Patient__c = patient.Id;
            healthPlans[0].PC_Card_Holder_First_Name__c = '1';
            healthPlans[0].PC_Card_Holder_Last_Name__c = '2';
            healthPlans[0].PC_Cardholder_s_Date_of_Birth__c = Date.today();
            healthPlans[0].PC_Card_Holder_Gender__c = 'Male';
            healthPlans[0].RecordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.PC_HEALTH_PLAN, PC_Constants.HEALTH_PLAN_PHARMACY_PLAN_RECORD_TYPE);
            // insert all health plans
            PC_Database.ins(healthPlans);

            PC_Prescription__c prescription = new PC_Prescription__c();
            prescription.PC_Patient_Account__c = patient.Id;
            prescription.PC_Program_Case__c = programCase.Id;
            prescription.PC_Physician_Account__c = physicians[0].id;
            prescription.PC_Product__c = product.Id;
            PC_Database.ins(prescription);

            Test.StartTest();

            Test.setMock(HttpCalloutMock.class, new PC_UBC_MockHttpResponseGenerator());

            PC_PharmacyEbenefitsLookup_UBC client = new PC_PharmacyEbenefitsLookup_UBC();
            PC_eBenefits.PharmacyBenefitsOptions pharmacyEbenefitsOptions = PC_eBenefits_Utility.getPharmacyBenefitsOptions(programCase.Id);
            PC_eBenefits.PharmacyCardRequest pharmacyCardRequest = PC_eBenefits_Utility.getPharmacyCardholderInfo(programCase.Id);
            PC_eBenefits.PharmacyBenefitsRequest pharmacyEbenefitsRequest = client.createPharmacyBenefitsRequest();

            PC_UBC_Utility ubcUtility = new PC_UBC_Utility();
            PC_UBC.PharmacyCoverageServiceInput pharmacyCoverageServiceInput = ubcUtility.getServiceInput(pharmacyEbenefitsRequest);
            PC_eBenefits_Utility.updatePharmacyRequest(programCase.Id, healthPlans[0].Id, prescription.Id, pharmacy.Id,false, 30, 1, 1, pharmacyEbenefitsRequest);

            //PC_eBenefits.PharmacyBenefitsRequest pharmacyEbenefitsRequest = PC_PharmacyEbenefitsLookupController.getPharmacyBenefitInfo(programCase.Id, healthPlans[0].Id, prescription.Id, pharmacy.Id, 30, 1, 1);

            PC_eBenefits.PharmacyBenefitsResponse pharmacyEbenefitsResponse =
                    client.lookupPharmacyBenefits(pharmacyEbenefitsRequest);

            system.assertEquals(true, pharmacyEbenefitsResponse!=null);

            PC_UBC_Utility  eBenefitsServiceClient = new PC_UBC_Utility();
            PC_UBC.PharmacyCoverageServiceInput eBenefitsServiceInput =
                    eBenefitsServiceClient.getServiceInput(programCase.Id, healthPlans[0].Id, pharmacy.Id, prescription.Id, '30', '1');
            PC_UBC.PharmacyCoverageServiceResponse eBenefitsServiceResponse = eBenefitsServiceClient.checkPharmacyCoverageBenefits(eBenefitsServiceInput);
            system.assertEquals(true, eBenefitsServiceResponse!=null);

            Boolean isExtPharmacy = PC_eBenefits_Utility.isExternalPharmacy(pharmacy.id);
            system.assert(!isExtPharmacy);
            Boolean isExtPharmacy2 = PC_eBenefits_Utility.isExternalPharmacy('11');
            system.assert(isExtPharmacy2);

            String id = PC_eBenefits_Utility.getPharmacyIdBy_Id_Or_ExtId(pharmacy.id);

            PC_UBC_Utility.getUnitOfMeasureCode('entyvio', null);
            PC_UBC_Utility.getUnitOfMeasureCode('CLOMIPRAMINE', null);
            PC_UBC_Utility.getUnitOfMeasureCode('', null);

            Test.stopTest();
        }
    }
    public static void createAddress(Id accounId){

        PC_Address__c address = new PC_Address__c();
        address.PC_Account__c = accounId;
        address.PC_Address_1__c = 'test address line 1';
        address.PC_Address_2__c = 'test address line 2';
        address.PC_City__c = 'EDWARDSVILLE';
        address.PC_State__c = 'MA';
        address.PC_Zip_Code__c = '62025';
        //@@RemoveAddressPhone: address.PC_Phone__c = '0727555957';
        address.PC_Primary_Address__c = true;

        address = (PC_Address__c)PC_Database.ins(address, false);
    }
}