objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>The date of birth of the patient</description>
        <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Gender__c</fullName>
        <description>The gender of the patient.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Gender__c</fullName>
        <description>The gender of the patient</description>
        <formula>TEXT ( Account.PC_Gender__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gender</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_AdverseEvent__c.object
<CustomObject>
    <description>The Adverse Event is a custom object in Patient Connect that represents the adverse events reported for the patients enrolled into the patient services program.</description>
    <fields>
        <fullName>PC_Care_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program (Case) to which the adverse event is associated with.</description>
        <label>Care Program</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Adverse Events</relationshipLabel>
        <relationshipName>Adverse_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Date_of_Birth__c</fullName>
        <description>Patient&apos;s date of birth. Will be populated from Account.</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Gender__c</fullName>
        <description>Gender of the Patient</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Patient_Identifier__c</fullName>
        <description>Manufacturer specific identifier for a patient.</description>
        <label>Patient Identifier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Patient__c</fullName>
        <description>Patient account with which the adverse event is associated.</description>
        <label>Patient</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Adverse Events</relationshipLabel>
        <relationshipName>Adverse_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Race__c</fullName>
        <description>Indicates the race of the patient as reported by the patient. For example, Asian, American Indian or Alaskan Native, Black or African American, and so on.</description>
        <label>Race</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>American Indian or Alaskan Native</fullName>
                </value>
                <value>
                    <fullName>Black or African American</fullName>
                </value>
                <value>
                    <fullName>White</fullName>
                </value>
                <value>
                    <fullName>Native Hawaiian or Other Pacific Islander</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Adverse Event</label>
    <nameField>
        <displayFormat>AE-{00000000}</displayFormat>
        <label>Adverse Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adverse Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Test_AE_PatientInfoRendererController.cls
/*********************************************************************************
Class Name      :   PC_Test_AE_PatientInfoRendererController
Description        : Test Class for PC_AE_PatientInfoRendererController Class
Created By        : Haritha Reddy
Created Date     : 28-11-2018
Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   Description
-----------------------------------------------------------------------------------
Haritha Reddy          28-11-2018              Initial Version
*********************************************************************************/
@isTest
public class PC_Test_AE_PatientInfoRendererController {
    private static User adminUser;
    private static Case programCase;
    private static PC_AdverseEvent__c aeRec;
    private static Map<Object, Object> patientInfoObj = new Map<Object, Object>{'patId'=>'','age'=>null,'ageType'=>'Year(s)','dob'=>'1992-04-08','gender'=>'','weight'=>null,'weightType'=>'','ethnicity'=>'','race'=>'White'};

    /*********************************************************************************
Method Name    : createTestData
Author         : Haritha Reddy
Description    : This method is used for creating test data
Return Type    : void
Parameter      :
*********************************************************************************/

    private static void createTestData() {
        adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@email.com', 'pctest');
        PC_Database.ins(adminUser, false);

        Account patient = PC_Test_Setup.createSampleAccount('', PC_Constants.PATIENT_RECORD_TYPE);
        patient.PC_Date_of_Birth__c = date.today().addDays(-100);
        patient = (Account)PC_Database.ins(patient, false);
        // check if patient is created
        system.assertNotEquals(patient.Id, null);

        programCase = PC_Test_Setup.createCase(adminUser, patient);
        programCase = (Case)PC_Database.ins(programCase, false);
        // check if program Case is created
        system.assertNotEquals(programCase.Id, null);

        //insert Adverse Event Record
        aeRec = new PC_AdverseEvent__c();
        aeRec.PC_Patient__c = patient.Id;
        aeRec.PC_Care_Program__c = programCase.Id;
        aeRec.PC_Patient_Identifier__c = '1234';
        aeRec.PC_Race__c = 'White';
        aeRec.PC_Gender__c= 'Male';

        PC_Database.ins(aeRec, false);
    }

    @isTest
    static void testPatientInfoRetrieval() {
        createTestData();
        Test.StartTest();
        system.runAs(adminUser) {
            PC_AE_PatientInfoRendererController objCntrl = new PC_AE_PatientInfoRendererController();
            PC_AE_PatientInfoRendererController.getPatientInfoData();
            objCntrl.updateAdverseEvent(aeRec,patientInfoObj);
            PC_AE_PatientInfoRendererController.fetchDataFromAE(aeRec.Id,patientInfoObj);
            PC_AE_PatientInfoRendererController.fetchDataFromPatient(programCase.Id,patientInfoObj);
        }
        Test.StopTest();
    }
}