objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Manufacturer</fullName>
        <active>true</active>
        <description>Details about the drug manufacturer</description>
        <label>Manufacturer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Engagement Program lookup for documents.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The document request form.</description>
        <label>Request Form</label>
        <referenceTo>PC_Request_Form__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>PC_Document_Request_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <description>General Document or Attachment</description>
        <label>Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program_Service__c.object
<CustomObject>
    <description>Custom junction object to facilitate many-to-many relationships between the Engagement Program and the Service object</description>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <description>Holds the Engagement Program details.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Engagement Program Services</relationshipLabel>
        <relationshipName>PC_Engagement_Program</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Service__c</fullName>
        <description>Holds the Service details.</description>
        <label>Service</label>
        <referenceTo>PC_Service__c</referenceTo>
        <relationshipLabel>Engagement Program Services</relationshipLabel>
        <relationshipName>PC_Engagement_Program_Services</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Start_Date__c</fullName>
        <description>Date on which the Service starts for a given Engagement Program.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Engagement Program Service</label>
    <nameField>
        <displayFormat>EPS-{0}</displayFormat>
        <label>Engagement Program Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Program Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Program_Service_Permission__c.object
<CustomObject>
    <description>Holds patient&apos;s (program&apos;s) consent for a Service.</description>
    <fields>
        <fullName>PC_ProgramCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Holds the Case(of type Program) detail.</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Program Service Permissions</relationshipLabel>
        <relationshipName>PC_Program_Service_Permission</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Service_Permission_Name__c</fullName>
        <description>Generates a unique name from the Service Name and Program Case Number.</description>
        <formula>PC_Service__r.Name &amp; &apos;-&apos; &amp; PC_ProgramCase__r.CaseNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Service Permission Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contains the service details.</description>
        <label>Service</label>
        <referenceTo>PC_Service__c</referenceTo>
        <relationshipLabel>Program Service Permissions</relationshipLabel>
        <relationshipName>PC_Program_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Signed_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the patient&apos;s signed Request Form.</description>
        <label>Signed Request Form</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>Program Service Permissions</relationshipLabel>
        <relationshipName>PC_Signed_Request_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Start_Date__c</fullName>
        <description>Program Service Permission start date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Service Permission</label>
    <nameField>
        <displayFormat>SP-{0}</displayFormat>
        <label>Program Service Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Service Permissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Request_Form__c.object
<CustomObject>
    <description>To track the consent templates that exist for different programs, their versions, and so on.</description>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contains the engagement program detail.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Request Forms</relationshipLabel>
        <relationshipName>PC_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Release_Date__c</fullName>
        <description>The date on which the current version of request form/consent form was released.</description>
        <label>Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Retirement_Date__c</fullName>
        <description>The date on which the current version of request form/consent form was retired.</description>
        <label>Retirement Date</label>
        <type>Date</type>
    </fields>
    <label>Request Form</label>
    <nameField>
        <label>Request Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_Request_Form_Service__c.object
<CustomObject>
    <description>Helps associate many to many relationship between Request Form object and Service object</description>
    <fields>
        <fullName>PC_Request_Form__c</fullName>
        <description>Contains the Request Form details.</description>
        <label>Request Form</label>
        <referenceTo>PC_Request_Form__c</referenceTo>
        <relationshipLabel>Request Form Services</relationshipLabel>
        <relationshipName>PC_Request_Form</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Service__c</fullName>
        <description>Contains the service details</description>
        <label>Service</label>
        <referenceTo>PC_Service__c</referenceTo>
        <relationshipLabel>Request Form Services</relationshipLabel>
        <relationshipName>PC_Service</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Request Form Service</label>
    <nameField>
        <displayFormat>RFS-{0}</displayFormat>
        <label>Request Form Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Form Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Service__c.object
<CustomObject>
    <description>Object to hold different consent categories (each of which can consist of different consent options), so that consent can be captured at a more granular level.</description>
    <fields>
        <fullName>PC_Default_Expiration_Days__c</fullName>
        <description>The number of days after which the service expires.</description>
        <label>Default Expiration Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PC_Test_Consent_DataModel.cls
/*********************************************************************************
Class Name      : PC_Test_Consent_DataModel
Description     : Test the Consent Data Model
Created By      : TEJAS PATEL
Created Date    : 15-May-2017

Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   Description
-----------------------------------------------------------------------------------           
TEJAS PATEL		         15-May-2017	              Initial Version
TEJAS PATEL				 05-June-2017				  Modified the Assert Statements
Vijay Kashikar           07-Marc-2019                 [PC-4556] Changed reference from PC_Program_Service_Permission__c.PC_Program__c to PC_Program_Service_Permission__c.PC_ProgramCase__c
*********************************************************************************/
@isTest
public class PC_Test_Consent_DataModel {
    private static User adminUser;
	public static final String SERVICE_NAME = 'TestService';
    public static final String REQUEST_FORM_NAME = 'TestService';
    private static final Integer SERVICE_NUMBER = 3;
    
    
    /*********************************************************************************
    Method Name    : createRequestForm
    Author         : Tejas Patel
    Description    : This method creates PC_Request_Form__c records
    Return Type    : List<PC_Request_Form>
    Parameter      : Service Name and Number of Records
    *********************************************************************************/
    public static List<PC_Request_Form__c> createRequestForm(String requestFormName, Integer pNoRecs, PC_Engagement_Program__c engagmentProgram){
        List<PC_Request_Form__c> newRequestForm = new List<PC_Request_Form__c>(); 
        for(integer i = 0; i < pNoRecs; i ++){
            PC_Request_Form__c requestForm 			= new PC_Request_Form__c();
            requestForm.Name						= requestFormName + '_' + i;
            requestForm.PC_Release_Date__c			= (DATE) date.today();
            requestForm.PC_Retirement_Date__c		= (DATE) date.today() + 10;
            requestForm.PC_Engagement_Program__c	= engagmentProgram.Id;
            newRequestForm.add(requestForm);
        }
        return newRequestForm;
    }
    
    /*********************************************************************************
    Method Name    : createRequestFormService
    Author         : Tejas Patel
    Description    : This method creates PC_Request_Form_Service__c records
    Return Type    : List<PC_Request_Form_Service__c>
    Parameter      : Service Name and Number of Records
    *********************************************************************************/
    public static List<PC_Request_Form_Service__c> createRequestFormService(List<PC_Request_Form__c> requestForm, Integer pNoRecs, List<PC_Service__c> services){
        List<PC_Request_Form_Service__c> newRequestFormService = new List<PC_Request_Form_Service__c>(); 
        for(integer i = 0; i < pNoRecs; i ++){
            PC_Request_Form_Service__c requestFormService 			= new PC_Request_Form_Service__c();
            requestFormService.PC_Request_Form__c	= requestForm[i].Id;
            requestFormService.PC_Service__c		= services[i].Id;
            newRequestFormService.add(requestFormService);
        }
        return newRequestFormService;
    }
    
    /*********************************************************************************
    Method Name    : createEngagementProgramService
    Author         : Tejas Patel
    Description    : This method creates PC_Engagement_Program_Service__c records
    Return Type    : List<PC_Engagement_Program_Service__c>
    Parameter      : Service Name and Number of Records
    *********************************************************************************/
    public static List<PC_Engagement_Program_Service__c> createEngagementProgramService(PC_Engagement_Program__c engagement, Integer pNoRecs, List<PC_Service__c> services){
        List<PC_Engagement_Program_Service__c> newEngagementProgramService = new List<PC_Engagement_Program_Service__c>(); 
        for(integer i = 0; i < pNoRecs; i ++){
            PC_Engagement_Program_Service__c engagementProgramService 			= new PC_Engagement_Program_Service__c();
            engagementProgramService.PC_Engagement_Program__c	= engagement.Id;
            engagementProgramService.PC_Service__c		= services[i].Id;
            newEngagementProgramService.add(engagementProgramService);
        }
        return newEngagementProgramService;
    }
    
    /*********************************************************************************
    Method Name    : createProgramServicePermissions
    Author         : Tejas Patel
    Description    : This method creates PC_Program_Service_Permission__c records
    Return Type    : List<PC_Program_Service_Permission__c>
    Parameter      : Service Name and Number of Records
    *********************************************************************************/
    public static List<PC_Program_Service_Permission__c> createProgramServicePermissions(List<PC_Service__c> services, Integer pNoRecs, Case programCase, PC_Document__c signedDocument){
        List<PC_Program_Service_Permission__c> newProgramServicePermissions = new List<PC_Program_Service_Permission__c>(); 
        for(integer i = 0; i < pNoRecs; i ++){
            PC_Program_Service_Permission__c programServicePermission = new PC_Program_Service_Permission__c();
            programServicePermission.PC_Start_Date__c  = (Date) date.today();
            programServicePermission.PC_Service__c	   = services[i].Id;
            programServicePermission.PC_ProgramCase__c	   = programCase.Id;
            programServicePermission.PC_Signed_Request_Form__c = signedDocument.Id;
            newProgramServicePermissions.add(programServicePermission);
        }
        return newProgramServicePermissions;
    }
    
    /*********************************************************************************
    Method Name    : createServices
    Author         : Tejas Patel
    Description    : This method creates PC_Service__c records
    Return Type    : List<PC_Service__c>
    Parameter      : Service Name and Number of Records
    *********************************************************************************/
    public static List<PC_Service__c> createServices(String serviceName, Integer pNoRecs){
        List<PC_Service__c> newServices = new List<PC_Service__c>(); 
        for(integer i = 0; i < pNoRecs; i ++){
            PC_Service__c services = new PC_Service__c();
            services.Name = serviceName +'_'+i;
            services.PC_Default_Expiration_Days__c  = i;
            newServices.add(services);
        }
        return newServices;
    }
    
    /*********************************************************************************
	Method Name    : testConsentModel
	Author         : Tejas Patel
	Description    : This method is used for testing the Consent Model
	Return Type    : void 
	Parameter      : 
   *********************************************************************************/
    @isTest 
    static void testConsentModel() {
        adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@test2.com', 'test2');
        PC_Database.ins(adminUser);
        system.runAs(adminUser) {
            Test.StartTest();
            //Bulk Creation of Services
            List<PC_Service__c> services                    = createServices(SERVICE_NAME, SERVICE_NUMBER);
            PC_Database.ins(services,false);
            // check if Services are created for bulk testing
            system.assertEquals(services.size(), SERVICE_NUMBER);
            
            
            // create manufacturer account
        	Account manufacturerAcc = PC_Test_Setup.createTestAccount(PC_Constants.MANUFACTURER_RECORD_TYPE);
        	PC_Database.ins(manufacturerAcc, false);
            
            // create patient account
        	Account patientAcc = PC_Test_Setup.createTestAccount(PC_Constants.PATIENT_RECORD_TYPE);
        	PC_Database.ins(patientAcc, false);
            
            // create program case
        	Case programCase = PC_Test_Setup.newCase(patientAcc.Id , PC_Constants.CASE_PROGRAM_RECORD_TYPE);
        	PC_Database.ins(programCase, false);
            
            // create document
        	PC_Document__c onlineDocument = PC_Test_Setup.createDocument(PC_Constants.DOCUMENT_SMARTFORM_RECORD_TYPE, PC_Constants.DOCUMENT_STATUS_REVIEW_NEEDED);
        	PC_Database.ins(onlineDocument, false);
            
            PC_Engagement_Program__c engagmentProgram = PC_Test_Setup.createEngagementProgram ('TstCMD', manufacturerAcc.Id);
            PC_Database.ins(engagmentProgram, false);
            
            List<PC_Request_Form__c> requestForm = createRequestForm('TestRequestForm' , SERVICE_NUMBER, engagmentProgram);
            PC_Database.ins(requestForm, false);
            // check if RequestForms are created for bulk testing
            system.assertEquals(requestForm.size(), SERVICE_NUMBER);
            
            List<PC_Request_Form_Service__c> requestFormService = createRequestFormService(requestForm, SERVICE_NUMBER, services);
            PC_Database.ins(requestFormService, false);
            // check if RequestFormServices are created for bulk testing
            system.assertEquals(requestFormService.size(), SERVICE_NUMBER);
            
            List<PC_Engagement_Program_Service__c> engagementProgramService = createEngagementProgramService(engagmentProgram, SERVICE_NUMBER, services);
            PC_Database.ins(engagementProgramService, false);
            // check if RequestFormServices are created for bulk testing
            system.assertEquals(engagementProgramService.size(), SERVICE_NUMBER);
            
            //Bulk Creation of Program Service Permission
            List<PC_Program_Service_Permission__c> programServicePermissions   = createProgramServicePermissions(services, SERVICE_NUMBER, programCase, onlineDocument);
            PC_Database.ins(programServicePermissions,false);
            // check if Program Service Permission are created for bulk testing
            system.assertEquals(programServicePermissions.size(), SERVICE_NUMBER);
            
            List<PC_Program_Service_Permission__c> testProgramServicePermission = [SELECT Id, PC_ProgramCase__c, PC_ProgramCase__r.PC_Engagement_Program__c,
                PC_Service__c, PC_Program_Service_Permission_Name__c, 
                PC_Signed_Request_Form__c FROM PC_Program_Service_Permission__c 
                where PC_ProgramCase__c in (SELECT Id from Case where Account.ID = :patientAcc.Id)];
            
            for (PC_Program_Service_Permission__c a : testProgramServicePermission){
                system.assertEquals(a.PC_ProgramCase__c, programCase.Id);
                system.assertEquals(a.PC_Signed_Request_Form__c, onlineDocument.Id);
            }
            
            List<PC_Request_Form_Service__c> testRequestFormService = [SELECT ID, PC_Request_Form__c, PC_Request_Form__r.Name 
                                                                                    FROM PC_Request_Form_Service__c 
                WHERE PC_Service__c IN 
                (SELECT PC_Service__c FROM PC_Program_Service_Permission__c 
                 WHERE PC_Signed_Request_Form__c= :onlineDocument.Id)];
            
            system.assertEquals(testRequestFormService.size(), SERVICE_NUMBER);
            
            Test.StopTest();
        }
    }       
}