objects/Account.object
<CustomObject>
    <fields>
        <fullName>PC_Country__c</fullName>
        <description>The country name associated with account’s primary address.</description>
        <formula>TEXT(PC_Primary_Address__r.PC_Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Primary_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup to the account’s primary address.</description>
        <label>Address</label>
        <referenceTo>PC_Address__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>The status allows records to be classified as inactive and filters out of lookups and reports. The status is used to support validation rules for related records.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Address__c.object
<CustomObject>
    <description>PatientConnect custom object used to track addresses of all types of participants (accounts), including the patient</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <description>The account to which the address is associated with.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Address_1__c</fullName>
        <description>Line 1 of the address.</description>
        <label>Address 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address_2__c</fullName>
        <description>Line 2 of the address.</description>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address_3__c</fullName>
        <description>Line 3 of the address.</description>
        <label>Address 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address_Description__c</fullName>
        <description>The address type such as Business or Home.</description>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Home</fullName>
                    <default>true</default>
                    <label>Home</label>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_City__c</fullName>
        <description>The city address.</description>
        <label>City</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Country__c</fullName>
        <description>The country associated with the address.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                    <default>true</default>
                    <label>United States</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Primary_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Primary Address related to the account. This address reflects on the Account and cases.</description>
        <inlineHelpText>Defines the primary address of the associated account</inlineHelpText>
        <label>Primary Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_State__c</fullName>
        <description>The state associated with the address. The state is controlled by the country.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PC_Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>Status that indicates if the address is active or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Zip_Code__c</fullName>
        <description>The zip code associated with the address.</description>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>PC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient account created to represent the applicant.</description>
        <label>Patient Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PatientRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Address1_1__c</fullName>
        <description>The line one in patient’s second address.</description>
        <label>Address1 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address1_2__c</fullName>
        <description>The line two in patient’s second address.</description>
        <label>Address1 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address1_Description__c</fullName>
        <description>The address type of patient’s second address, such as Business or Home.</description>
        <label>Address1 Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Address_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Address_1__c</fullName>
        <description>The line one in patient’s first address.</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address_2__c</fullName>
        <description>The line two in patient’s first address.</description>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Address_Description__c</fullName>
        <description>The address type of patient’s first address, such as Business or Home.</description>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_City1__c</fullName>
        <description>The city associated with patient’s second address.</description>
        <label>City1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_City__c</fullName>
        <description>The city associated with the patient’s address.</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Country1__c</fullName>
        <description>The country associated with the patient’s second address.</description>
        <label>Country1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Country__c</fullName>
        <description>The country associated with the patient’s address.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Primary_Address1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if second address is primary or not</description>
        <label>Primary Address1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Primary_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Selected or checked when the address is the primary address.</description>
        <label>Primary Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_State1__c</fullName>
        <description>The state associated with the patient&apos;s second address.</description>
        <label>State1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_State__c</fullName>
        <description>The state associated with the patient&apos;s address.</description>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Zip_Code1__c</fullName>
        <description>The zip code associated with the patient&apos;s second address.</description>
        <label>Zip Code1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Zip_Code__c</fullName>
        <description>The zip code associated with the patient&apos;s address.</description>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/PC_Address_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Home</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <masterLabel>Address Type</masterLabel>
</GlobalValueSet>

globalValueSets/PC_Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

classes/PC_AddressInfoEWP.cls
/*********************************************************************************
Class Name      : PC_AddressInfoEWP
Description     : Gets Address records and Fields to Populate Address Info Page
Created By      : Kishore Kanteti
Created Date    : 22-Nov-21
Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   Description
-----------------------------------------------------------------------------------
Kishore Kanteti 	       22-Nov-21              Initial Version
*********************************************************************************/
public with sharing class PC_AddressInfoEWP {

    @AuraEnabled
    public static AddressDetails getAddressFieldsAndRecords(Map<String,String> enrollDetails){
        AddressDetails addressDetails = new AddressDetails();
        try{
            //validating fieldset on address object
            String displayFieldSetName = '';
            displayFieldSetName = enrollDetails.get('displayFieldSetName');
            Boolean validFieldSet = PC_Utility.isValidFieldSet(PC_Constants.ADDRESS_OBJ_API, displayFieldSetName);
            if(!validFieldSet){
                throw new AuraHandledException(System.Label.PC_Enrollment_Fieldset_Error);
            }

            //Getting address fields from fieldset
            List<Map<String,Object>> patientAddresses = new List<Map<String,Object>>();
            List<AddressFieldDetail> addressFields = new List<AddressFieldDetail>();
            addressFields = getAddressFieldsByFieldSet(displayFieldSetName);
            if(addressFields == null){
                List<Object> formattingArguments = new List<Object>{
                        displayFieldSetName, PC_Constants.ADDRESS_OBJ_API
                };
                throw new AuraHandledException(String.format(System.Label.PC_NoFieldsInFieldsetError, formattingArguments));
            }
            addressDetails.addressFields = addressFields;

            //Getting saved/existing addresses
            String patientId = enrollDetails.get('patientId');
            if(String.isBlank(patientId)){
                String activeApplicantId = enrollDetails.get('activeApplicantId');
                patientAddresses = getApplicantAddresses(activeApplicantId,addressFields);
            }else{
                patientAddresses = getAccountAddresses(patientId,addressFields);
            }
            addressDetails.patientAddresses = patientAddresses;

        }catch(Exception ex){
            PC_Utility.logAndThrowException(ex);
        }
        return addressDetails;
    }

    private static Map<String,List<String>> getAddressApplicantFieldsMap(){
        String mappingJSON = PC_SYSTEM.getPatientConnectSetting(PC_Constants.PC_ADDRESS_APPLICANT_MAPPING,'');
        Map<String, List<String>> applicantFieldsByAddressField = new Map<String, List<String>>();
        if(String.isNotBlank(mappingJSON)){
            applicantFieldsByAddressField = (Map<String, List<String>>) JSON.deserialize(mappingJSON, Map<String, List<String>>.class);
        }
        Map<String, List<String>> defaultApplicantFieldsByAddressField = new Map<String, List<String>>();
        defaultApplicantFieldsByAddressField = getDefaultApplicantAddressFieldsMapping();
        for(String addressField : defaultApplicantFieldsByAddressField.keySet()){
            if(!applicantFieldsByAddressField.containsKey(addressField)){
                applicantFieldsByAddressField.put(addressField,defaultApplicantFieldsByAddressField.get(addressField));
            }
        }
        return applicantFieldsByAddressField;
    }
    private static Map<String, List<String>> getDefaultApplicantAddressFieldsMapping(){
        Map<String, List<String>> defaultMapping = new Map<String, List<String>>();
        defaultMapping.put(PC_Constants.getQualifiedAPIName('PC_Address_1__c'), new List<String>{PC_Constants.getQualifiedAPIName('PC_Address_1__c'),PC_Constants.getQualifiedAPIName('PC_Address1_1__c')});
        defaultMapping.put(PC_Constants.getQualifiedAPIName('PC_Address_2__c'), new List<String>{PC_Constants.getQualifiedAPIName('PC_Address_2__c'),PC_Constants.getQualifiedAPIName('PC_Address1_2__c')});
        defaultMapping.put(PC_Constants.getQualifiedAPIName('PC_Address_Description__c'), new List<String>{PC_Constants.getQualifiedAPIName('PC_Address_Description__c'),PC_Constants.getQualifiedAPIName('PC_Address1_Description__c')});
        defaultMapping.put(PC_Constants.getQualifiedAPIName('PC_City__c'), new List<String>{PC_Constants.getQualifiedAPIName('PC_City__c'),PC_Constants.getQualifiedAPIName('PC_City1__c')});
        defaultMapping.put(PC_Constants.getQualifiedAPIName('PC_Country__c'), new List<String>{PC_Constants.getQualifiedAPIName('PC_Country__c'),PC_Constants.getQualifiedAPIName('PC_Country1__c')});
        defaultMapping.put(PC_Constants.getQualifiedAPIName('PC_State__c'), new List<String>{PC_Constants.getQualifiedAPIName('PC_State__c'),PC_Constants.getQualifiedAPIName('PC_State1__c')});
        defaultMapping.put(PC_Constants.getQualifiedAPIName('PC_Zip_Code__c'), new List<String>{PC_Constants.getQualifiedAPIName('PC_Zip_Code__c'),PC_Constants.getQualifiedAPIName('PC_Zip_Code1__c')});
        defaultMapping.put(PC_Constants.getQualifiedAPIName('PC_Primary_Address__c'), new List<String>{PC_Constants.getQualifiedAPIName('PC_Primary_Address__c'),PC_Constants.getQualifiedAPIName('PC_Primary_Address1__c')});
        return defaultMapping;
    }
    private static List<AddressFieldDetail> getAddressFieldsByFieldSet(String fieldSetName){
        List<AddressFieldDetail> addressFields = new List<AddressFieldDetail>();
        for(PC_FieldSetController.FieldSetMember fieldSetMember : PC_FieldSetController.getFields(PC_Constants.ADDRESS_OBJ_API,fieldSetName)){
            AddressFieldDetail eachField = new AddressFieldDetail(fieldSetMember);
            addressFields.add(eachField);
        }
        return addressFields;
    }
    private static List<Map<String,Object>> getApplicantAddresses(String activeApplicantId,List<AddressFieldDetail> addressFieldsByFieldSet){
        List<Map<String,Object>> savedAddresses = new List<Map<String,Object>>();
        if(addressFieldsByFieldSet != null && !addressFieldsByFieldSet.isEmpty()){

            //get address applicant fields map
            Map<String,List<String>> addressApplicantFieldsMap = getAddressApplicantFieldsMap();
            //prepare SOQL query based on fieldAPIs
            String query = 'SELECT ';

            for(AddressFieldDetail addressField : addressFieldsByFieldSet){
                if(addressApplicantFieldsMap.get(addressField.fieldName) != null){
                    for(String applicantAddressField : addressApplicantFieldsMap.get(addressField.fieldName)){
                        query += applicantAddressField + ', ';
                    }
                }else{
                    List<Object> formattingArguments = new List<Object>{
                            addressField.fieldName
                    };
                    throw new AuraHandledException(String.format(System.Label.PC_IncorrectAddressApplicantMapping,formattingArguments));
                }
            }
            query += 'Id, RecordType.Name, LastModifiedDate FROM ' + PC_Constants.getQualifiedAPIName('PC_Applicant__c') +
                    ' WHERE Id' + '=' + '\'' + activeApplicantId + '\'' + ' Limit 1';

            PC_Applicant__c applicant = new PC_Applicant__c();
            //execute query and get applicant
            applicant = Database.query(query);
            //Forming address records based on applicant info and address applicant mapping
            Integer i = 0;
            while(i < addressApplicantFieldsMap.get(addressFieldsByFieldSet[0].fieldName).size()){
                Map<String,Object> address = new Map<String,Object>();
                for(AddressFieldDetail addressField : addressFieldsByFieldSet){
                    if(addressApplicantFieldsMap.get(addressField.fieldName) != null){
                        if(applicant.get(addressApplicantFieldsMap.get(addressField.fieldName)[i]) != null){
                            address.put(addressField.fieldName, applicant.get(addressApplicantFieldsMap.get(addressField.fieldName)[i]));
                        }
                    }else{
                        List<Object> formattingArguments = new List<Object>{
                                addressField.fieldName
                        };
                        throw new AuraHandledException(String.format(System.Label.PC_IncorrectAddressApplicantMapping,formattingArguments));
                    }
                }
                if(address.get(PC_Constants.getQualifiedAPIName('PC_Address_1__c')) != null){
                    address.put('LastModifiedDate', String.valueOf(applicant.LastModifiedDate));
                    address.put('Source', applicant.RecordType.Name);
                    address.put('Name', PC_Constants.NA);
                    address.put('AddressId', applicant.Id + String.valueOf(i));
                    savedAddresses.add(address);
                }
                i++;
            }
        }
        return savedAddresses;
    }
    private static List<Map<String,Object>> getAccountAddresses(String patientId,List<AddressFieldDetail> addressFieldsByFieldSet){
        List<Map<String,Object>> existingAddresses = new List<Map<String,Object>>();

        //FLS Check on Address Object
        List<String> fields = new List<String>();
        for(AddressFieldDetail addressField : addressFieldsByFieldSet){
            fields.add(addressField.fieldName);
        }
        PC_Database.assertAccess(PC_Constants.ADDRESS_OBJ_API,PC_Database.Operation.Reading, fields);

        //Get multiple addresses from existing account
        List<PC_Address__c> accountAddresses = new List<PC_Address__c>();
        accountAddresses = [SELECT Id,PC_Account__c,Name,PC_Address_1__c,PC_Address_2__c,PC_Address_3__c,PC_Address_Description__c,
                PC_City__c, PC_Country__c,PC_State__c, PC_Status__c,PC_Zip_Code__c,PC_Primary_Address__c,LastModifiedDate
                FROM PC_Address__c WHERE PC_Account__c =: patientId];
        for(PC_Address__c address : accountAddresses){
            Map<String, Object> addressFieldsToValue = new Map<String, Object>();
            addressFieldsToValue = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(address));
            addressFieldsToValue.remove('attributes');
            addressFieldsToValue.put('LastModifiedDate', String.valueOf(address.LastModifiedDate));
            addressFieldsToValue.put('AddressId', address.Id);
            existingAddresses.add(addressFieldsToValue);
        }
        return existingAddresses;
    }

    public inherited sharing class AddressDetails{
        @AuraEnabled public List<AddressFieldDetail> addressFields{get;set;}
        @AuraEnabled public List<Map<String,Object>> patientAddresses{get;set;}
        @AuraEnabled public String objectName{get;set;}
        public AddressDetails(){
            objectName = PC_Constants.ADDRESS_OBJ_API;
        }
    }
    public inherited sharing class AddressFieldDetail{
        @AuraEnabled public String label{get;set;}
        @AuraEnabled public String fieldName{get;set;}
        @AuraEnabled public String type{get;set;}
        public AddressFieldDetail(PC_FieldSetController.FieldSetMember fieldDetail){
            label = fieldDetail.label;
            fieldName = fieldDetail.fieldPath;
            type = fieldDetail.type;
        }
    }
}