objects/ACLS_Missing_Information__c.object
<CustomObject>
    <fields>
        <fullName>ACLS_Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consent</fullName>
                </value>
                <value>
                    <fullName>Patient Information</fullName>
                </value>
                <value>
                    <fullName>HCP/HCO Information</fullName>
                </value>
                <value>
                    <fullName>Prescription</fullName>
                </value>
                <value>
                    <fullName>Payer Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACLS_Missing_Information_Fields__c</fullName>
        <description>Capture Missing information related to HCP, Payers, Patient, Caregiver.</description>
        <label>Missing Information</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ACLS_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Provider Consent</fullName>
                </value>
                <value>
                    <fullName>Patient Consent</fullName>
                </value>
                <value>
                    <fullName>Patient Phone Number</fullName>
                </value>
                <value>
                    <fullName>Patient Email Address</fullName>
                </value>
                <value>
                    <fullName>Patient Address</fullName>
                </value>
                <value>
                    <fullName>Date of Birth</fullName>
                </value>
                <value>
                    <fullName>Caregiver Phone Number</fullName>
                </value>
                <value>
                    <fullName>Primary Diagnosis</fullName>
                </value>
                <value>
                    <fullName>Secondary Diagnosis</fullName>
                </value>
                <value>
                    <fullName>NPI</fullName>
                </value>
                <value>
                    <fullName>Tax ID Number</fullName>
                </value>
                <value>
                    <fullName>State License Number</fullName>
                </value>
                <value>
                    <fullName>Site of Care</fullName>
                </value>
                <value>
                    <fullName>Provider Address</fullName>
                </value>
                <value>
                    <fullName>Provider Phone</fullName>
                </value>
                <value>
                    <fullName>Provider Fax</fullName>
                </value>
                <value>
                    <fullName>Provider Email</fullName>
                </value>
                <value>
                    <fullName>Dosage</fullName>
                </value>
                <value>
                    <fullName>Day Supply</fullName>
                </value>
                <value>
                    <fullName>Quantity</fullName>
                </value>
                <value>
                    <fullName>Frequency</fullName>
                </value>
                <value>
                    <fullName>Prescription Date</fullName>
                </value>
                <value>
                    <fullName>Prescription Signature</fullName>
                </value>
                <value>
                    <fullName>Product Name</fullName>
                </value>
                <value>
                    <fullName>Payer Policy Number</fullName>
                </value>
                <value>
                    <fullName>Policy Holder Date of Birth</fullName>
                </value>
                <value>
                    <fullName>CPT Code(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACLS_Object_Name__c</fullName>
        <description>Object API Name on which the missing information is present</description>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACLS_Object_Record_Type_Name__c</fullName>
        <description>Record Type API Name</description>
        <label>Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACLS_Status__c</fullName>
        <description>This field captures the status of the Missing Information record.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Missing Information</label>
    <nameField>
        <displayFormat>MI-{00000}</displayFormat>
        <label>Missing Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missing Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_Program_Service_Permission__c.object
<CustomObject>
    <description>Holds patient&apos;s (program&apos;s) consent for a Service.</description>
    <fields>
        <fullName>PC_Patient_Response__c</fullName>
        <description>Holds the patient&apos;s responses such as Granted, Declined, or Revoked.</description>
        <label>Patient Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Granted</fullName>
                    <isActive>false</isActive>
                    <label>Granted</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                    <isActive>false</isActive>
                    <label>Revoked</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Service Permission</label>
    <nameField>
        <displayFormat>SP-{0}</displayFormat>
        <label>Program Service Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Service Permissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ACLS_Test_MissingInfoTriggerHandler.cls
/*********************************************************************************
Class Name      : ACLS_Test_OverlapServiceDatePSPHandler
Description     : The test class for PC_Program_Service_Permission trigger
Created By      : Deloitte
Created Date    : Jan 10, 2023
*********************************************************************************
Version History :
Date			  Developer 			  User Story					     Changes
Jan 10, 2023	Vartika Goyal				US-120				Added checkOverlapServicesDatesTest
*****************************************************************************************************************/

@isTest(seeAllData=false)
public class ACLS_Test_MissingInfoTriggerHandler {

    @testsetup
	private static void setup(){
        User baseProfUser = ACLS_TestDataFactory.createUser('ACLS Base Profile', 'userpctest@test2.com', 'test2');
        PC_Database.ins(baseProfUser);
        system.runAs(baseProfUser) {
            ACLS_TestDataFactory.assignUserPermissionSet(baseProfUser.Id, 'ACLS_Base_RW_Permissions');

            String sObjectName = 'PC_Program_Service_Permission__c';
            String recordTypeName = null;
                
            //Creating Missing Information
            List<ACLS_Missing_Information__c> missingInformationRecord = ACLS_TestDataFactory.ACLS_Missing_InformationcTestDataMethod(1, sObjectName, recordTypeName);
             missingInformationRecord[0].ACLS_Status__c = ACLS_Constants.INACTIVE_STATUS;
            missingInformationRecord[0].ACLS_Category__c = ACLS_Constants.CONSENT_CATEGORY;
            missingInformationRecord[0].ACLS_Missing_Information_Fields__c = ACLS_Constants.PROVIDER_CONSENT;
            insert missingInformationRecord;

        }
	}

	@isTest 
	public static void ACLS_Test_MissingInfoRecordCreation() {  
        User baseProfUser = [select id from User where Alias = 'test2'];         
        system.runAs(baseProfUser) {
            try{
                String sObjectName = 'PC_Program_Service_Permission__c';
                Map<Id, String>  mapOfRecIdAndFields = new Map<Id, String>();
                Map<Id, Id>  mapOfRecIdAndProgCaseId = new Map<Id, Id>();
                String recordTypeName = null;
                Test.startTest();
                
                //Creating Missing Information
                List<ACLS_Missing_Information__c> missingInformationRecord = [Select id, Name, ACLS_Object_Name__c,ACLS_Status__c, ACLS_Object_Record_Type_Name__c from ACLS_Missing_Information__c where ACLS_Object_Name__c = 'PC_Program_Service_Permission__c'];
                                
               String lstMissingFields = 'PC_Patient_Response__c';
 

                mapOfRecIdAndFields.put(missingInformationRecord[0].Id, lstMissingFields);
                mapOfRecIdAndProgCaseId.put(missingInformationRecord[0].Id, null);

                system.assertEquals(missingInformationRecord[0].ACLS_Object_Record_Type_Name__c, null);
                system.assertEquals(missingInformationRecord[0].ACLS_Object_Name__c, sObjectName);

                ACLS_MissingInfoTriggerHandler.ACLS_MissingInfoRecordCreation(missingInformationRecord[0].ACLS_Object_Name__c,mapOfRecIdAndFields,mapOfRecIdAndProgCaseId,recordTypeName);
                
                Test.stopTest();
                
            }
            catch(Exception ex){
                System.debug('VG'+ex.getMessage());
            }
        }
    }
}