objects/Activity.object
<CustomObject>
    <fields>
        <fullName>PC_Channel__c</fullName>
        <description>Custom copy of managed field &apos;Task Subtype&apos; for use in Activity timeline via custom metadata</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>eLetter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Direction__c</fullName>
        <description>Indicates if the activity such as fax,sms, email or call is inbound or outbound</description>
        <inlineHelpText>Indicate if the task/activity such as fax,sms, email or call is inbound or outbound</inlineHelpText>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the program case with which the task is associated.</description>
        <inlineHelpText>Reference to the program case with which the task is associated.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Child Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Care_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated support coordinator</description>
        <label>Care Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Health plan using which the PA case was created</description>
        <inlineHelpText>Health plan using which the PA case was created</inlineHelpText>
        <label>Health Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Health_Plan__c.Patient__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect custom look up field to associate program coverage record to capture outcome of BI/BV case, PAP case or Copay case</description>
        <label>Program Coverage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>You can see only program coverage associated with the current program case.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PC_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_CaseProduct__c.object
<CustomObject>
    <description>Holds the products associated to a specific case.</description>
    <fields>
        <fullName>PC_Case__c</fullName>
        <description>Lookup to cases</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>ProductCases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to products</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Health_Plan__c.object
<CustomObject>
    <description>Patient Connect custom object: Used to capture a patient&apos;s various health plans (private insurance companies, public payer plans) as part of Patient Connect&apos;s access functionality</description>
    <fields>
        <fullName>PC_Payer_Name__c</fullName>
        <formula>PC_Payer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Plan_Name__c</fullName>
        <description>This field will consist of functional names that will help Support Coordinators to identify Health Plan records.</description>
        <label>Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Plan_Status__c</fullName>
        <description>Status of the health plan</description>
        <label>Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Public_Or_Private__c</fullName>
        <description>This field indicates if the health plan is a public or private plan</description>
        <label>Public or Private</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <description>Person receiving PSP services to and whom this health plan related.</description>
        <label>Patient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Plans</relationshipLabel>
        <relationshipName>Health_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Health Plan</label>
    <nameField>
        <displayFormat>HP-{000000000}</displayFormat>
        <label>Health Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Program_Coverage__c.object
<CustomObject>
    <description>This is a custom object in Patient Connect that represents patient&apos;s coverage information that satisfies the coverage for the treatment/program that the patient is enrolled into.</description>
    <fields>
        <fullName>PC_Comments__c</fullName>
        <description>The comments about the coverage.</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PC_Coverage_Status__c</fullName>
        <description>The status of the coverage.</description>
        <label>Coverage Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient&apos;s health plan that provides the coverage.</description>
        <label>Health Plan</label>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Program Coverages</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Payer_Name__c</fullName>
        <description>The name of the health plan payer.</description>
        <formula>PC_Health_Plan__r.PC_Payer__r.Name</formula>
        <label>Payer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <description>The outcome status of the coverage.</description>
        <label>Program Coverage Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Pending</fullName>
                </value>
                <value>
                    <fullName>Investigation In Progress</fullName>
                </value>
                <value>
                    <fullName>Eligibility Pending</fullName>
                </value>
                <value>
                    <fullName>Pending PA</fullName>
                </value>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Appeal</fullName>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Sources Not Found</fullName>
                </value>
                <value>
                    <fullName>Covered with Restrictions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the patient is enrolled into and requires coverage for.</description>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Coverage</label>
    <nameField>
        <displayFormat>COV-{000000000}</displayFormat>
        <label>Coverage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_RecordIdentifier__c.object
<CustomObject>
    <description>This object will consist of fields that would help to uniquely identify any record other than Account. For Accounts, use Account Identifier object</description>
    <label>Record Identifier</label>
    <nameField>
        <displayFormat>RIA-{0000}</displayFormat>
        <label>Record Identifier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Identifiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_Remote_Service_Log__c.object
<CustomObject>
    <description>This object is used to store information received from the web services</description>
    <label>Remote Service Log</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Remote Service Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remote Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PC_CPT_Codes__c</fullName>
        <label>CPT Codes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>96372</fullName>
                    <label>96372: therapeutic, prophylactic, or diagnostic injection</label>
                </value>
                <value>
                    <fullName>J3490</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PC_BREPharmacyBI_Example.cls
/***************************************************************************************************************
Class Name      : PC_BREPharmacyBI_Example
Description     : This is an example class when initiating the Pharmacy eBenefits via BRE.
Created By      : Chetna Mohapatra
Created Date    :  27-Apr-2022
Modification Log:
------------------------------------------------------------------------------------------------------------------
Developer                   Date                  Description
-------------------------------------------------------------------------------------------------------------------
Chetna Mohapatra         27-Apr-2022             Initial Version
Satheesh Kumar           12-Oct-2022             [PC-9262] Added condition to avoid removing namespace prefix from sObject when sobject contains no namespace.
*******************************************************************************************************************/
 public with sharing class PC_BREPharmacyBI_Example implements PC_eBenefits2.PharmacyBenefits {

   public List<PC_eBenefits2.PharmacyBenefitsResponse> lookupPharmacyBenefits(PC_eBenefits2.PharmacyBenefitsRequest pharmacyBenefitsRequest) {
    /**PharmacyBenefitsRequest contains the sourceId(Trigger object Id) that can be used to create the Request Payload to be sent to the third-party vendor.*/
     List<PC_eBenefits2.PharmacyBenefitsResponse> pharmacyBenefitsResponseList = new List<PC_eBenefits2.PharmacyBenefitsResponse> ();

     /**Service callouts to third party vendors can be done as per the following example:-
     *String payload = JSON.serialize(request);//Create request and covert it into JSON format
     * String endpoint='www.example.com/endpointurl';//To access this external website, create a Remote Site Setting for the same.
     *HttpRequest request = new HttpRequest();//Initialize the external webservice callout request
     *request.setMethod(POST);//Using Http POST Method
     *request.setEndpoint(endpoint);
     *request.setBody(payload);

     //Response received
     *HttpResponse response = sendRequest(request);
     *Integer statusCode = response.getStatusCode();
     *String responseBody = response.getBody();
     *
     *Once the request is initiated, we can get the immediate API response for our request from the Third-party vendor and based on the success or failure of the request
     * use a logging mechanism such as our Remote Service Logs(PC_Remote_Service_Log__c) to log the request and response details.
     * We can also use our Record Identifier Object(PC_RecordIdentifier__c) to log the related Salesforce Ids that were a part of that request,
     * and later use those ids to update the related records based on the response.
     * */

     /**Create the PharmacyBenefitsResponse using the Http Response received from the vendor :-
     PC_eBenefits2.PharmacyBenefitsResponse eachPharmacyBenefitsResponse = new PC_eBenefits2.PharmacyBenefitsResponse();
       eachPharmacyBenefitsResponse.isSuccess=true;
       eachPharmacyBenefitsResponse.errorMessage=null;
       eachPharmacyBenefitsResponse.relatedRecordId='';//Health Plan Id
       eachPharmacyBenefitsResponse.remoteServiceLogId='';//Remote Service Log Id
       eachPharmacyBenefitsResponse.externalId='';//Third-party vendor related Id/External Id
       */
     /**Calling this method to mock the process post successful vendor integration.*/
     processPharmacyCoverage(pharmacyBenefitsRequest);
     return pharmacyBenefitsResponseList;
   }
   private void processPharmacyCoverage(PC_eBenefits2.PharmacyBenefitsRequest pharmacyBenefitsRequest){
       String sourceRecordId= pharmacyBenefitsRequest.sourceRecordId;
       Case programCase= new Case();
       Account patient= new Account();
       List<PC_CaseProduct__c> caseProducts= new List<PC_CaseProduct__c>();
       List<PC_Health_Plan__c> healthPlans= new List<PC_Health_Plan__c>();
       Id pharmacyHealthPlanRecord = PC_SYSTEM.recordTypeId(PC_Constants.PC_HEALTH_PLAN, PC_Constants.HEALTH_PLAN_PHARMACY_PLAN_RECORD_TYPE);
       String objType = String.valueOf(Id.valueOf(sourceRecordId).getSobjectType());
       //remove namespace prefix from objType when objType contains namespace
       objType = objType.contains('__') ? (objType.countMatches('__') == 2 ? objType.substringAfter('__') : objType): objType;
       if(objType== PC_Constants.PC_CASE) {
           programCase = [
                   SELECT Id, AccountId,PC_Care_Coordinator__c, OwnerId
                   FROM Case
                   WHERE Id = :sourceRecordId AND Type = :PC_Constants.CASE_PROGRAM_TYPE
                   WITH SECURITY_ENFORCED
                   LIMIT 1
           ];
           patient = [SELECT (SELECT Id, Name, PC_Plan_Name__c, PC_Payer_Name__c, Patient__c,RecordType.DeveloperName,PC_Public_Or_Private__c
                           FROM Health_Plans__r
                           WHERE RecordTypeId = :pharmacyHealthPlanRecord
                           AND PC_Plan_Status__c = :PC_Constants.ACTIVE)
                   FROM Account
                   WHERE Id = :programCase.AccountId
                   WITH SECURITY_ENFORCED
           ];
           healthPlans=patient.Health_Plans__r;
           caseProducts= [SELECT Id, PC_Product__c, PC_Product__r.Name,PC_Product__r.ProductCode, PC_Product__r.PC_CPT_Codes__c,PC_Case__c
                           FROM PC_CaseProduct__c
                           WHERE PC_Case__c = :programCase.Id
                           WITH SECURITY_ENFORCED
           ];
       }else if(objType== PC_Constants.PC_ACCOUNT){
           patient= [
                   SELECT (SELECT Id FROM Account.Cases WHERE Type =: PC_Constants.CASE_PROGRAM_TYPE LIMIT 1)
                   FROM Account
                   WHERE Id=:sourceRecordId WITH SECURITY_ENFORCED
           ];
           programCase=[SELECT Id,PC_Care_Coordinator__c,OwnerId FROM Case WHERE Id
                   =: patient.Cases[0].Id];
           healthPlans=[ SELECT Id, Name, PC_Plan_Name__c, PC_Payer_Name__c, Patient__c,RecordType.DeveloperName,PC_Public_Or_Private__c
                       FROM PC_Health_Plan__c
                       WHERE Patient__c=:patient.Id
                       AND RecordTypeId = :pharmacyHealthPlanRecord
                       AND PC_Plan_Status__c = :PC_Constants.ACTIVE
                       WITH SECURITY_ENFORCED
           ];
           caseProducts= [SELECT Id, PC_Product__c, PC_Product__r.Name,PC_Product__r.ProductCode, PC_Product__r.PC_CPT_Codes__c,PC_Case__c
                           FROM PC_CaseProduct__c
                           WHERE PC_Case__c = :programCase.Id
                           WITH SECURITY_ENFORCED
           ];

       }else if(objType==PC_Constants.PC_CASEPRODUCT){
           caseProducts=[SELECT Id, PC_Product__c, PC_Product__r.Name,PC_Product__r.ProductCode, PC_Product__r.PC_CPT_Codes__c,PC_Case__c
                                           FROM PC_CaseProduct__c
                                           WHERE Id = :sourceRecordId
                                           WITH SECURITY_ENFORCED
           ];
           programCase= [SELECT Id, AccountId,PC_Care_Coordinator__c,OwnerId FROM Case WHERE Id=:caseProducts[0].PC_Case__c WITH SECURITY_ENFORCED];
           healthPlans=[ SELECT Id, Name, PC_Plan_Name__c, PC_Payer_Name__c, Patient__c,RecordType.DeveloperName,PC_Public_Or_Private__c
                           FROM PC_Health_Plan__c
                           WHERE Patient__c=:programCase.AccountId
                           AND RecordTypeId = :pharmacyHealthPlanRecord
                           AND PC_Plan_Status__c = :PC_Constants.ACTIVE
                          WITH SECURITY_ENFORCED
           ];
       }
       /**Program Coverage Record & Task Creation*/
       List<sObject> coverageRelatedRecords= new List<sObject> ();
       for(PC_Health_Plan__c healthPlan :healthPlans) {
           System.debug('All Details--'+programCase+'--'+caseProducts+'--'+healthPlan);
           coverageRelatedRecords.addAll(createPharmacyCoverageRecordsAndTasks(programCase,caseProducts, healthPlan));
       }
       if(coverageRelatedRecords!=null && !coverageRelatedRecords.isEmpty()){
           PC_Database.ins(coverageRelatedRecords,false);//Insertion of all the coverage records and tasks
           System.debug('Coverage Related Records--' +coverageRelatedRecords);
       }
       /**Calling the updatePharmacyCoverages() with the list of coverageRelatedRecords and null value for PbmTaskOutput since we do not have that value.*/
       updatePharmacyCoverages(coverageRelatedRecords,null);
   }
   private List<sObject> createPharmacyCoverageRecordsAndTasks(Case programCase,List<PC_CaseProduct__c> caseProducts, PC_Health_Plan__c healthPlan){
       List<sObject> pharmacyCoverageAndTask= new List<sObject>();
       /**Coverage Record Creation- Program Coverage Records are created post successful BI/BV for the Patient's health plan.
       * One Program Coverage record is created for each product w.r.t each pharmacy health plan associated with the Patient/Member*/
       for(PC_CaseProduct__c caseProduct:caseProducts) {
           PC_Program_Coverage__c pharmacyCoverage = new PC_Program_Coverage__c();
           pharmacyCoverage.PC_Health_Plan__c = healthPlan.Id;
           pharmacyCoverage.PC_Program__c = programCase.Id;
           //Method for Program Coverage RecordType & Coverage Type selection
           PC_eBenefits2.setCoverageRecordTypeAndType(healthPlan,pharmacyCoverage);
           pharmacyCoverage.PC_Coverage_Status__c = PC_Constants.ACTIVE;
           pharmacyCoverage.PC_Comments__c=caseProduct.PC_Product__r.ProductCode;
           pharmacyCoverageAndTask.add(pharmacyCoverage);
       }
       /**Final Status Related Task(Successful BI/BV)- The task related to the status of the BI/BV process reflects
       * on the activity timeline of the Patient's associated Program Case */
       Task task= new Task();
       if(programCase.PC_Care_Coordinator__c !=null){
           task.OwnerId= programCase.PC_Care_Coordinator__c;
       }else if(programCase.PC_Care_Coordinator__c == null && programCase.OwnerId !=null){
           task.OwnerId= programCase.OwnerId;
       }
       task.WhatId= programCase.Id;
       task.Subject= System.Label.PC_PharmacyBICompletionMessage;
       task.Status=PC_Constants.PC_TASK_STATUS_COMPLETED;
       task.PC_Direction__c= PC_Constants.INBOUND;
       task.PC_Channel__c = PC_Constants.PC_TASK;
       task.Priority = PC_Constants.PC_PRIORITY_NORMAL;
       task.ActivityDate = System.today();
       pharmacyCoverageAndTask.add(task);
       return  pharmacyCoverageAndTask;
   }
   /**Update the Program coverage records with additional coverage details obtained from the vendor as part of pbmTaskOutput*/
   public static void updatePharmacyCoverages(List<sObject> coverageObjects, Object pbmTaskOutput){
     System.debug('Coverage Objects--'+coverageObjects);
   }
 }