objects/Activity.object
<CustomObject>
    <fields>
        <fullName>PC_Category__c</fullName>
        <description>The primary category of the activity.</description>
        <inlineHelpText>The primary category of the activity.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>Alt. Funding</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>Copay</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Support Check-In</fullName>
                </value>
                <value>
                    <fullName>Field Activity</fullName>
                </value>
                <value>
                    <fullName>Patient Enrollment</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>Pharmacy Referral</fullName>
                </value>
                <value>
                    <fullName>Treatment Reminder</fullName>
                </value>
                <value>
                    <fullName>Welcome Gesture</fullName>
                </value>
                <value>
                    <fullName>Training Reminder</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Channel__c</fullName>
        <description>Custom copy of managed field &apos;Task Subtype&apos; for use in Activity timeline via custom metadata</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>eLetter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Close_Date__c</fullName>
        <description>The date and time on which the task was closed.</description>
        <inlineHelpText>The date and time on which the task was closed.</inlineHelpText>
        <label>Close Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the program case with which the task is associated.</description>
        <inlineHelpText>Reference to the program case with which the task is associated.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Child Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Sub_Category__c</fullName>
        <description>The Sub-category of activity.</description>
        <inlineHelpText>The Sub-category of activity.</inlineHelpText>
        <label>Sub-Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PC_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Follow up</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
                <value>
                    <fullName>Confirmation</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Approval request</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
                <value>
                    <fullName>Call pharmacy</fullName>
                </value>
                <value>
                    <fullName>Change of address</fullName>
                </value>
                <value>
                    <fullName>Change of treatment</fullName>
                </value>
                <value>
                    <fullName>Delivery confirmation</fullName>
                </value>
                <value>
                    <fullName>Outcome</fullName>
                </value>
                <value>
                    <fullName>Discontinuation</fullName>
                </value>
                <value>
                    <fullName>HCP</fullName>
                </value>
                <value>
                    <fullName>HCP notification</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Response</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Patient</fullName>
                </value>
                <value>
                    <fullName>Reminder</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>eBV</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PC_Trigger_Task.cls
/*********************************************************************************************************
Class Name      : PC_Trigger_Task 
Description     : trigger on Case object. 
Created By      : Deloitte
Created Date    : May 20, 2016
Modification Log:
-------------------------------------------------------------------------------------------------------------- 
Developer          Log#         Date                   Description
--------------------------------------------------------------------------------------------------------------            
Roxana Ivan                    May 20, 2016          Initial Version
Ajinkya Deshmukh               June 24, 2016         Added calculateTaskAcitivies method to update Task count on Cases
Vijay Kashikar                 June 29, 2016         Added methods to assign and set task subtype values based on custom metadata
Shabda Bhujad,                 Nov 1, 2016			 Removed Support Model references annotated by @@RemoveSupportModel  
Prachi Nandgaonkar
Shabda Bhujad,                 Nov 3, 2016			 Removed General StartDate, Overdue Activities, Pending Activities, Support Model - Generate All, Parent Task  references annotated by @@RemoveGeneralStartDate, @@RemoveOverduePendingActivity, @@RemoveRecType, @@RemoveSupportModel, @@RemoveParentTask
Prachi Nandgaonkar
Prachi Nandgaonkar,       	   Nov 10, 2016          Renamed PC_Task_Subtype__c to PC_Channel__c
Shabda Bhujad
Prachi Nandgaonkar             Feb 20, 2017          Added system debug statements for checking governor limits
Prachi Nandgaonkar             March 2, 2017         Added updateIconsforTimeline() method to updated Task-SubType field used in activity timeline
Mayuresh Patil                 Apr 07, 2017          [PC-1369] Resolved blocker issue raised by force reviewer scanner tool. 
Shabda Bhujad				   June 02, 2017		 [PC-1645] Added the null check for subcategory when Channel is null
Ajinkya Deshmukh			   June 23, 2017		 FLS Check Added (Code Merge), Removed unwarranted fields from soql
Mayuresh Patil                 Jul 26, 2017          Updated CRUD/FLS checks
Mayuresh Patil                 Aug 30, 2017          PC-2128 Resolved Merge issues FLS/CRUD
Shabda Bhujad                  Nov 14, 2017          PC-2485 Removing the reference to trigger state
Mike Klumpenaar                Nov 27, 2017          PC-2537 Fix null reference during insertion of completed task
Tejas Patel                    Dec 12, 2017          PC-2617 Check for Subject to be NULL before updating
Xiukai Ning                    Feb 28, 2019          PC-3775 - Code review. FLS is NOT needed in Triggers, as they always run in System Mode.
                                                     Trigger delegate class (handler) that has with Sharing keyword however, will apply user sharing.
                                                     We are removing all FLS and With Sharing keywords in the handlers.
Tushar Arora                   Jun 26, 2019          [PC-4894] Stop referencing Case.PC_Is_Program_Case__c and Account.PC_IsIndividual__c from code
Hitha Avalakki                 Mar 19, 2021          [PC-7533] Replaced constant CASE_PROGRAM_RECORD_TYPE_NAME to CASE_PROGRAM_TYPE
Satheesh Kumar                 Nov 16, 2021          [PC-8213] Excluded FLS Check and added inherited sharing
****************************************************************************************************************/
public inherited sharing class PC_Trigger_Task extends PC_TriggerHandler {

    override public void beforeInsert() {
        processTaskChanges((List< Task>) newList, (Map<Id, Task>) oldMap);
    }
    
    override public void beforeUpdate() {
        processTaskChanges((List< Task>) newList, (Map<Id, Task>) oldMap);
    }
    

	/************************************************************************************** 
	*   @Description : Process Task changes and update Program case
	*   @Param       : newTaskList. Trigger new task list 
	*   @Param       : oldCaseMap. Trigger old task map
	*   @Return      : Void 
	***************************************************************************************/
    private void processTaskChanges(List<Task> newTaskList, Map<Id, Task> oldTaskMap ) {
        Set<Id> lstRelatedObjects = new Set<Id>();
        try {
            for(Task task : newTaskList) {
                if (!lstRelatedObjects.contains(task.WhatId)) {
                    lstRelatedObjects.add(task.WhatId);
                }

                if (task.Status == PC_CONSTANTS.COMPLETED && oldTaskMap != null && oldTaskMap.get(task.Id).Status != PC_CONSTANTS.COMPLETED) {
                    task.PC_Close_Date__c = Datetime.now();
                }
                //generate the task subject by concatenating the category and 
                //if we have a taks category and if the old subject is null(insert) or the old category or subcategory differ from the new(update)
                //we can not have a subcategory without a category so the subject is either the concatenation of both of the category by itself
                if (task.PC_Category__c != null && task.Subject == null && (oldTaskMap == null || oldTaskMap.get(task.Id).PC_Category__c != task.PC_Category__c || oldTaskMap.get(task.Id).PC_Sub_Category__c != task.PC_Sub_Category__c)) {
                    if (task.PC_Category__c != null && task.PC_Sub_Category__c != null && task.PC_Channel__c != null) {
                        task.Subject = task.PC_Category__c + ' ' + task.PC_Sub_Category__c + ' ' + task.PC_Channel__c;
                    } else if (task.PC_Channel__c == null && task.PC_Sub_Category__c != null) { //[PC-1645] 
                        task.Subject = task.PC_Category__c + ' ' + task.PC_Sub_Category__c;
                    } else {
                        task.Subject = task.PC_Category__c;
                    }
                }
            } 

            Map<Id, Case> mapCases = new Map<Id, Case>([Select Id, PC_Program__c
                                      FROM Case WHERE Id in: lstRelatedObjects]);
            for(Task task : newTaskList) {
                if(mapCases.containsKey(task.WhatId)) {
                    Case relatedCase = mapCases.get(task.WhatId);
                    task.PC_Program__c = (relatedCase.Type == PC_Constants.CASE_PROGRAM_TYPE ? relatedCase.Id : relatedCase.PC_Program__c) ;
                }
            }
        } 
        catch (Exception e) {
            PC_Utility.createExceptionLog(e);
        }
    }
}