objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_PA_Expiration_Date__c</fullName>
        <description>Date when the prior authorization expires</description>
        <label>Expires On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_PA_Outcome__c</fullName>
        <label>PA Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PC_PA_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Unsent</fullName>
                    <isActive>false</isActive>
                    <label>Unsent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_PA_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prescription for which PA is requested</description>
        <label>Prescription</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Prescription__c.PC_Program_Case__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Prescription__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Prescription__c</referenceTo>
        <relationshipLabel>Prescriptions</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_PA_Status__c</fullName>
        <description>The prior authorization status</description>
        <label>PA Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted to Provider</fullName>
                </value>
                <value>
                    <fullName>Submitted to Payer</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Appeal Request</fullName>
                </value>
                <value>
                    <fullName>PA shared with Provider</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Appeal Response</fullName>
                    <isActive>false</isActive>
                    <label>Appeal Response</label>
                </value>
                <value>
                    <fullName>Appealed</fullName>
                    <isActive>false</isActive>
                    <label>Appealed</label>
                </value>
                <value>
                    <fullName>Archived</fullName>
                    <isActive>false</isActive>
                    <label>Archived</label>
                </value>
                <value>
                    <fullName>Cancel Request Sent</fullName>
                    <isActive>false</isActive>
                    <label>Cancel Request Sent</label>
                </value>
                <value>
                    <fullName>Failure</fullName>
                    <isActive>false</isActive>
                    <label>Failure</label>
                </value>
                <value>
                    <fullName>PA Request Submitted to Plan</fullName>
                    <isActive>false</isActive>
                    <label>PA Request Submitted to Plan</label>
                </value>
                <value>
                    <fullName>PA accessed by Provider</fullName>
                    <isActive>false</isActive>
                    <label>PA accessed by Provider</label>
                </value>
                <value>
                    <fullName>Plan PA Response</fullName>
                    <isActive>false</isActive>
                    <label>Plan PA Response</label>
                </value>
                <value>
                    <fullName>Plan Question Response</fullName>
                    <isActive>false</isActive>
                    <label>Plan Question Response</label>
                </value>
                <value>
                    <fullName>Plan Question Set Ready for Provider</fullName>
                    <isActive>false</isActive>
                    <label>Plan Question Set Ready for Provider</label>
                </value>
                <value>
                    <fullName>Question Request Submitted to Plan</fullName>
                    <isActive>false</isActive>
                    <label>Question Request Submitted to Plan</label>
                </value>
                <value>
                    <fullName>Sent to Plan</fullName>
                    <isActive>false</isActive>
                    <label>Sent to Plan</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_PA_Submitted_On__c</fullName>
        <description>Date when the prior authorization is submitted</description>
        <label>Submitted On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_ePA_URL__c</fullName>
        <description>URL of the submitted ePA</description>
        <label>ePA URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Prescription__c.object
<CustomObject>
    <description>This Object captures prescription information for the prescribed drug for a patient when enrolled in an engagement program.</description>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PC_PriorAuthorizationListView.cls
/**
* ----------------------------------------------------------------------------------
* Developer              Date                   	Description
* -----------------------------------------------------------------------------------
* Tejas Patel            Aug 14, 2017			    Initial Version
* Prachi Nandgaonkar     Aug 22, 2017               [PC-1998] Updated class to use Case object instead of custom object for Prior Authorization
* Shabda Bhujad          Aug 22, 2017               [PC-1720][PC-2098] Added the getPARecordTypeId method to initiation form for case logic to list component
* Shabda Bhujad			 Aug 23, 2017				[PC-2017] Added method isPACaseActive to check if an ative PA already exists on case
* Shabda Bhujad	      	 Sep 05, 2017				[PC-2177] Change the query to pull prescription number instead of id
* Tejas Patel            Oct 11,2017                [PC-2398] Translation
*/
public with sharing class PC_PriorAuthorizationListView {
	@AuraEnabled
    public static FieldLabels getFieldLabels(){
        FieldLabels fieldlabels 	= new FieldLabels();
        fieldlabels.paID			= System.Label.PC_PA_Number;
        fieldlabels.prescription	= Case.PC_PA_Prescription__c.getDescribe().getLabel();
        fieldlabels.status			= Case.PC_PA_Status__c.getDescribe().getLabel();
        fieldlabels.submittedon		= Case.PC_PA_Submitted_On__c.getDescribe().getLabel();
        fieldlabels.lastupdatedon	= Case.LastModifiedDate.getDescribe().getLabel(); 
        fieldlabels.expireson		= Case.PC_PA_Expiration_Date__c.getDescribe().getLabel();
        fieldlabels.paOutcome		= Case.PC_PA_Outcome__c.getDescribe().getLabel();
        fieldlabels.paExtURL       = Case.PC_ePA_URL__c.getDescribe().getLabel();
        
        return fieldlabels;
    }
 
    @AuraEnabled
    public static Id getPARecordTypeId (String objName) {
        Id paRecType = PC_SYSTEM.recordTypeId(objName, PC_Constants.CASE_PA_RECORD_TYPE); 
        return paRecType;
    }
    
    @AuraEnabled 
    public static boolean isPACaseActive(ID programId){
        List<String> fields = new List<String>{PC_Constants.getQualifiedAPIName('PC_PA_Status__c')};
        Id PARecordTypeId = PC_System.recordTypeId(PC_Constants.PC_CASE, PC_Constants.CASE_PA_RECORD_TYPE);
        String PARecordTypeName =PC_System.recordTypeName(PC_Constants.PC_CASE,PC_Constants.CASE_PA_RECORD_TYPE) ;
            PC_Database.assertAccess(PC_Constants.PC_CASE,PC_Database.Operation.Reading, fields);
        	String[] nonActiveStatus  = new String[]{PC_Constants.PA_CASE_STATUS_Denied, PC_Constants.PA_CASE_STATUS_Canceled,PC_Constants.PA_CASE_STATUS_Expired};

            integer activePACount = [SELECT Count() FROM Case
                                         WHERE PC_Program__c =: programId 
                                         AND (RecordType.Name =: PARecordTypeName OR Type = : PARecordTypeName)
                                         AND (PC_PA_Status__c NOT IN :nonActiveStatus)
                                        ];            
        if (activePACount>0) {
            return true;
        }
        else {
            return false;	
        }
          
    }
    
    @AuraEnabled
    public static LIST<PAWrapper> getPARecords(ID programId){
        LIST<PAWrapper> painfo 	= new LIST <PAWrapper>();
        String PARecordTypeName = PC_System.recordTypeName(PC_Constants.PC_CASE,PC_Constants.CASE_PA_RECORD_TYPE) ;
        //FLS check
        try{
            List<String> fields = new List<String>{ PC_Constants.getQualifiedAPIName('PC_PA_Prescription__c'), 'LastModifiedDate', 
                    PC_Constants.getQualifiedAPIName('PC_PA_Status__c'),
                    PC_Constants.getQualifiedAPIName('PC_Submitted_On__c'),
                    PC_Constants.getQualifiedAPIName('PC_PA_Expiration_Date__c'),
                    PC_Constants.getQualifiedAPIName('PC_PA_Outcome__c'),
                    PC_Constants.getQualifiedAPIName('PC_ePA_URL__c')};
                                                        
            PC_Database.assertAccess(PC_Constants.PC_CASE,PC_Database.Operation.Reading, fields);

            LIST<Case> pa = [
                    SELECT CaseNumber, PC_PA_Prescription__r.Name,
                            toLabel(PC_PA_Status__c), PC_PA_Submitted_On__c, LastModifiedDate,
                            PC_PA_Expiration_Date__c, toLabel(PC_PA_Outcome__c), PC_ePA_URL__c
                    FROM Case
                    WHERE PC_Program__c = :programId AND (Case.RecordType.Name = :PARecordTypeName OR Case.Type = :PARecordTypeName) ORDER BY LastModifiedDate DESC

            ];
            
            for(Case p : pa){
                painfo.add(new PAWrapper(p));
            }
            
        }catch(Exception ex) {
            PC_Utility.logAndThrowException(ex);                
        }
        return painfo;
    }
    
    public class FieldLabels{
        @AuraEnabled public String paID { get; set; }
        @AuraEnabled public String prescription { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public String submittedon { get; set; }
        @AuraEnabled public String lastupdatedon { get; set; }
        @AuraEnabled public String expireson { get; set; }
        @AuraEnabled public String paOutcome { get; set; }
        @AuraEnabled public String paExtURL { get; set; }
        
        public FieldLabels() {
        }
    }
    
    public class PAWrapper{
        @AuraEnabled public String paID { get; set; }
        @AuraEnabled public String prescription { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public Date submittedon { get; set; }
        @AuraEnabled public Date lastupdatedon { get; set; }
        @AuraEnabled public Date expireson { get; set; }
        @AuraEnabled public String paUrl { get; set; }
        @AuraEnabled public String paOutcome { get; set; }
        @AuraEnabled public String paExtURL { get; set; }
        
        public PAWrapper(Case pa) {
            paID = pa.CaseNumber;
            prescription = pa.PC_PA_Prescription__r.Name;
            status = pa.PC_PA_Status__c;
            submittedon = pa.PC_PA_Submitted_On__c;
            lastupdatedon = date.ValueOf(pa.LastModifiedDate);
            expireson = pa.PC_PA_Expiration_Date__c;
            paUrl = '/'+ pa.Id;
            paOutcome = pa.PC_PA_Outcome__c;
            if(String.isBlank(pa.PC_ePA_URL__c)) {
                paExtURL = PC_Constants.EMPTY_STRING;
            }
            else {
                paExtURL = pa.PC_ePA_url__c;
            }
        }
        
        public PAWrapper() {}
    }
}