objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Communication_Language__c</fullName>
        <description>Patient’s choice of communication language.</description>
        <formula>TEXT ( Account.PC_Communication_Language__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Communication Language</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_eLetter__c.object
<CustomObject>
    <fields>
        <fullName>PC_Allow_Send_to_Patient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Selecting this field allows the eLetter to be sent to the patients.</description>
        <label>Allow Send to Patient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Category__c</fullName>
        <description>Defines the category of the eLetter. i.e whether the eLetter is used for Email, Fax or Automated Email.</description>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Automated Email</fullName>
                </value>
                <value>
                    <fullName>Automated Fax</fullName>
                </value>
                <value>
                    <fullName>Automated SMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Communication_Language__c</fullName>
        <description>The eLetter can be produced in these languages.</description>
        <inlineHelpText>Select supported languages for this eLetter</inlineHelpText>
        <label>Communication Language</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Hide_From_eLetter_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Selecting this will hide this eLetter on eLetter management page.</description>
        <inlineHelpText>Selecting this will hide this eLetter on eLetter management page.</inlineHelpText>
        <label>Hide From eLetter Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Object_Record_Types__c</fullName>
        <description>Case types with which the eLetter is associated.</description>
        <label>Object Record Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>PC_Source_Object__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BI / BV</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Private Coverage</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>Prior Authorization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Send_to_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this flag is checked, all other flags (Send Fax,Send email) are automatically unchecked and the eLetter is sent to the current User (for editing before sending to the Patients/Recipients)</description>
        <inlineHelpText>If Selected, the eLetter will be sent to current logged in User.</inlineHelpText>
        <label>Send to User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Source_Object__c</fullName>
        <description>The objects with which the eLetter is associated.</description>
        <label>Source Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Program Coverage</fullName>
                </value>
                <value>
                    <fullName>Interaction</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Adverse Event 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Target_Recipients__c</fullName>
        <description>Selects the target recipients for the eLetter.</description>
        <label>Target Recipients</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Association_Role</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Template_Name__c</fullName>
        <description>API name for email template.</description>
        <inlineHelpText>Email Template Developer Name</inlineHelpText>
        <label>PC Template Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>eLetter</label>
    <nameField>
        <label>eLetter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eLetters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/PC_Association_Role.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HCO</fullName>
    </customValue>
    <customValue>
        <fullName>Treating Physician</fullName>
    </customValue>
    <customValue>
        <fullName>Reimbursement Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Care Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Field Reimbursement Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Case Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Caregiver</fullName>
    </customValue>
    <masterLabel>Association Role</masterLabel>
</GlobalValueSet>

classes/PC_SupportPlan_eLetterController.cls
/**
 * Created by tejapatel on 11/14/2018.
 *
 * --------------------------------------------------------------------------------------------------------------
    Developer                   Date                   	Description
    --------------------------------------------------------------------------------------------------------------
    Hitha Avalakki              Mar 19, 2021            PC-7533: Replaced constant CASE_PROGRAM_RECORD_TYPE_NAME to CASE_PROGRAM_TYPE
    Satheesh Kumar              Apr 14, 2021            PC-6528: Added eletter category check in geteLetterObject where condition
    Hitha Avalakki              Apr 15, 2021            PC-7538: Removed the condition of 'PC_Object_Record_Types__c' for fetching eletters configured for a case.
 */

public with sharing class PC_SupportPlan_eLetterController {
    @AuraEnabled
    public static eLetterObject geteLetterObject(){
        eLetterObject eLetterObjects            =   new eLetterObject();
        LIST<eLettres> eLetters                 =   new LIST<eLettres>();
        STRING caseObject                       =   PC_Constants.PC_CASE;
        List<PC_PicklistFieldManager.PicklistEntryWrapper> targetRecepientList = PC_PicklistFieldManager.getPicklistEntryWrappers(PC_eLetter__c.PC_Target_Recipients__c);
        PC_PicklistFieldManager.PicklistEntryWrapper patientRecepient = new PC_PicklistFieldManager.PicklistEntryWrapper(PC_Constants.PATIENT_ACCOUNT_TYPE_VALUE,System.label.PC_Patient);
        targetRecepientList.add(patientRecepient);
        List<PC_eLetter__c> eLetterObj =  new List<PC_eLetter__c>();

        try {
            List<String> eLetterFields = new List<String>();
            eLetterFields = new List<String>{
                    'Id', 'Name', PC_Constants.getQualifiedAPIName('PC_Communication_Language__c'), PC_Constants.getQualifiedAPIName('PC_Hide_From_eLetter_Page__c'),
                    PC_Constants.getQualifiedAPIName('PC_Target_Recipients__c'), PC_Constants.getQualifiedAPIName('PC_Template_Name__c'),
                    PC_Constants.getQualifiedAPIName('PC_Allow_Send_to_Patient__c'), PC_Constants.getQualifiedAPIName('PC_Source_Object__c'),
                    PC_Constants.getQualifiedAPIName('PC_Send_to_User__c'), PC_Constants.getQualifiedAPIName('PC_Category__c')
            };
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_eLetter__c'), PC_Database.Operation.Reading, eLetterFields);

            //PC-7538: Removed the condition of 'PC_Object_Record_Types__c' for fetching eletters configured for a case
            //Only eLetters with PC_Send_to_User__c set to false and Category set to either Automated Email or/and Automated Fax
            eLetterObj = [
                    SELECT ID, Name, toLabel(PC_Communication_Language__c), PC_Target_Recipients__c, PC_Template_Name__c,
                            PC_Allow_Send_to_Patient__c,PC_Send_to_User__c
                    FROM PC_eLetter__c
                    WHERE PC_Source_Object__c = :caseObject AND PC_Send_to_User__c = false
                    AND PC_Category__c INCLUDES (:PC_Constants.PC_ELETTER_CATEGORY_AUTOMATED_EMAIL, :PC_Constants.PC_ELETTER_CATEGORY_AUTOMATED_FAX)
            ];

            for (PC_eLetter__c e : eLetterObj) {
                eLettres eLetter = new eLettres();
                LIST<targetRecepient> targetRecepients  =   new LIST<targetRecepient>();
                eLetter.eLetterID               = e.Id;
                eLetter.eLetterName             = e.Name;
                eLetter.targetRecepientMapping  = targetRecepientList;
                if(String.isNotBlank(e.PC_Target_Recipients__c)){
                    for (STRING t : e.PC_Target_Recipients__c.split(';')) {
                        targetRecepient targetRecepient = new targetRecepient();
                        targetRecepient.recepient = t;
                        targetRecepient.communicationLanguage = e.PC_Communication_Language__c;
                        targetRecepient.selected = true;
                        targetRecepients.add(targetRecepient);
                    }
                }
                if(e.PC_Allow_Send_to_Patient__c == true){
                    targetRecepient targetRecepient1         =   new targetRecepient();
                    targetRecepient1.recepient               =   PC_Constants.PATIENT_ACCOUNT_TYPE_VALUE;
                    targetRecepient1.communicationLanguage   =   e.PC_Communication_Language__c;
                    targetRecepient1.selected                =   true;
                    targetRecepients.add(targetRecepient1);
                }
                if(targetRecepients != null && !targetRecepients.isEmpty()){
                    eLetter.targetRecepient = targetRecepients;
                    eLetters.add(eLetter);
                }
            }
            eLetterObjects.eLettres = eLetters;

        } catch (Exception ex){
            PC_Utility.createExceptionLog(ex);
        }
        return eLetterObjects;
    }

    @AuraEnabled
    public static FieldLabels getFieldLabels(){
        FieldLabels fieldlabels 			= new FieldLabels();

        fieldlabels.eLetterName		        = PC_eLetter__c.Name.getDescribe().getLabel();
        fieldlabels.targetRecepient			= PC_eLetter__c.PC_Target_Recipients__c.getDescribe().getLabel();
        fieldlabels.communicationLanguage	= PC_eLetter__c.PC_Communication_Language__c.getDescribe().getLabel();

        return fieldlabels;
    }

    public class FieldLabels {
        //eLetter Fields
        @AuraEnabled public String eLetterName { get; set; }
        @AuraEnabled public String targetRecepient { get; set; }
        @AuraEnabled public String communicationLanguage { get; set; }

        public FieldLabels() {
        }
    }

    public class eLetterObject {
        //eLetter JSON Wrapper
        @AuraEnabled public LIST <eLettres> eLettres{ get; set; }

        public eLetterObject() {
            eLettres e              =   new eLettres();
            LIST<eLettres> eList    =   new LIST<eLettres>();
            eList.add(e);
            eLettres                =   eList;
        }
    }

    public class eLettres {
        //All eLetters
        @AuraEnabled public STRING eLetterID { get; set; }
        @AuraEnabled public STRING eLetterName { get; set; }
        @AuraEnabled public LIST <targetRecepient> targetRecepient{ get; set; }
        @AuraEnabled public List<PC_PicklistFieldManager.PicklistEntryWrapper> targetRecepientMapping{ get; set; }
        public eLettres() {
            eLetterID                       =   PC_Constants.EMPTY_STRING;
            eLetterName                     =   PC_Constants.EMPTY_STRING;
            targetRecepient tr              =   new targetRecepient();
            LIST<targetRecepient> trList    =   new LIST<targetRecepient>();
            trList.add(tr);
            targetRecepient                 =   trList;
        }
    }

    public class targetRecepient {
        //All eLetters
        @AuraEnabled public STRING recepient { get; set; }
        @AuraEnabled public STRING communicationLanguage { get; set; }
        @AuraEnabled public Boolean selected { get; set; }

        public targetRecepient() {
            recepient               =   PC_Constants.EMPTY_STRING;
            communicationLanguage   =   PC_Constants.EMPTY_STRING;
            selected                =   false;
        }
    }
}