objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Association__c.object
<CustomObject>
    <description>PatientConnect custom object to manage the patient program&apos;s care team (including physician)</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the account which is associated with the patient&apos;s program case.</description>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>PC_Patient</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>PC_Pharmacy</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Payer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Association</relationshipLabel>
        <relationshipName>Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Associated_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect Internal User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_AssociationStatus__c</fullName>
        <description>Indicates Active or Inactive status of the association.</description>
        <label>Association Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the Account is associated as part of the patient&apos;s circle of care.</description>
        <label>Patient Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Care Team</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Role__c</fullName>
        <description>The Role that the Account plays as part of the patient&apos;s circle of care.</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCO</fullName>
                </value>
                <value>
                    <fullName>Treating Physician</fullName>
                </value>
                <value>
                    <fullName>Field Reimbursement Manager</fullName>
                </value>
                <value>
                    <fullName>Caregiver</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Clinical Educator</fullName>
                </value>
                <value>
                    <fullName>Care Coordinator</fullName>
                    <isActive>false</isActive>
                    <label>Care Coordinator</label>
                </value>
                <value>
                    <fullName>Reimbursement Specialist</fullName>
                    <isActive>false</isActive>
                    <label>Reimbursement Specialist</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_ProcessNewAssociationHandler.cls
/*********************************************************************************************************
Class Name      : PC_ProcessNewAssociationHandler
Description     : Trigger on Association object to Manage Case Team Member and Update the Program Case
Created By      : Tejas Patel
Created Date    : Jan 4, 2018
Modification Log:
-------------------------------------------------------------------------------------------------------------- 
Developer                   Date                   	Description
--------------------------------------------------------------------------------------------------------------            
Tejas Patel            		Jan 4, 2018        		Initial Version
Mayuresh Patil              Feb 7,2019              PC-4341 - Ability to add non contact accounts as associations
Xiukai Ning                 Feb 28, 2019            PC-3775 - Code review. FLS is NOT needed in Triggers, as they always run in System Mode.
                                                    Trigger delegate class (handler) that has with Sharing keyword however, will apply user sharing.
                                                    We are removing all FLS and With Sharing keywords in the handlers.
Xiukai Ning                 Mar 8, 2019             PC-3404 - Provide readable error message if user is creating an Association whose role is not configured in CaseTeamRole
Mayruesh Patil              Apr 22, 2019            PC-4751 - Fixing condition flow for case team member roles.
Tejas Patel            		Aug 5, 2019             PC-5251 - Stopping recursive case update
Tejas Patel            		Aug 22, 2019            PC-5071 - If CaseTeamRole is not defined, only an association record is created, the error displayed has been removed
Kishore Kanteti             Aug 27,2021             PC-8068 - Removed FLS Check on DML Operation
Satheesh Kumar              Nov 16, 2021            [PC-8213] Excluded FLS Check and added inherited sharing
Hitha Avalakki              Dec 02, 2021            [PC-8372] Removed the multiple flag checks
****************************************************************************************************************/
public inherited sharing class PC_ProcessNewAssociationHandler extends PC_TriggerHandler{
 	public static boolean isExecuting = false;

    override public void afterInsert() {
        system.debug('Trigger Handler ::: PC_ProcessNewAssociationHandler');
        PC_ProcessNewAssociationHandler.isExecuting = false;
        processNewAssociation((List<PC_Association__c>) newList);
    }
    
    /*
    * Method Name    : processNewAssociation
    * Author         : Ajinkya Deshmukh
    * Description    : Helper method to handle after insert
    * Return Type    : void
    * Parameter      : Map<Id, PC_Association__c>
    */
    private void processNewAssociation (List<PC_Association__c> newAssociations) {
        Set<Id> casesToUpdate = new Set<Id>();
        List<CaseTeamMember> caseTeamMembersToInsert = new List<CaseTeamMember>();
        Map<String, CaseTeamRole> caseTeamRolesMap = PC_AssociationTriggerHelper.getCaseTeamRoles();
        Map<Id, String> mapAccountIdToContactId = new Map<Id, Id>();
        mapAccountIdToContactId = PC_AssociationTriggerHelper.formulateMapAccountToContact(newAssociations);
        for (PC_Association__c eachAssociation : newAssociations) {
            if (eachAssociation.PC_AssociationStatus__c == PC_Constants.ACTIVE ) {
                if(eachAssociation.PC_Role__c == PC_Constants.PC_ROLE_CARE_COORDINATOR || eachAssociation.PC_Role__c == PC_Constants.PC_ROLE_REIMBURSEMENT_SPECIALIST
                        || eachAssociation.PC_Role__c == PC_Constants.ROLE_TREATING_PHYSICIAN ){
                    casesToUpdate.add(eachAssociation.PC_Program__c);
                }
                    if ((mapAccountIdToContactId.get(eachAssociation.PC_Account__c) != null && eachAssociation.PC_Account__c != null) || eachAssociation.PC_Associated_User__c != null) {
                        if (caseTeamRolesMap.containsKey(eachAssociation.PC_Role__c)){
                        caseTeamMembersToInsert.add(
                                new CaseTeamMember(
                                        ParentId = eachAssociation.PC_Program__c,
                                        MemberId = eachAssociation.PC_Account__c != null ? mapAccountIdToContactId.get(eachAssociation.PC_Account__c) : eachAssociation.PC_Associated_User__c,
                                        TeamRoleId = caseTeamRolesMap.get(eachAssociation.PC_Role__c).Id
                                )
                        );
                        }
                    }
            }
        }

        if (!caseTeamMembersToInsert.isEmpty()) {
            PC_Database.ins(caseTeamMembersToInsert,false);
        }
        /*
        * Manage case updates
        */

        if(!casesToUpdate.isEmpty()){
            PC_ProcessNewAssociationHandler.isExecuting = true;
            PC_AssociationTriggerHelper.manageCaseUpdates(new List<Id>(casesToUpdate));
        }
    }
}