objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_PA_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prescription for which PA is requested</description>
        <label>Prescription</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Prescription__c.PC_Program_Case__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Prescription__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Prescription__c</referenceTo>
        <relationshipLabel>Prescriptions</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_PA_Status__c</fullName>
        <description>The prior authorization status</description>
        <label>PA Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted to Provider</fullName>
                </value>
                <value>
                    <fullName>Submitted to Payer</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Appeal Request</fullName>
                </value>
                <value>
                    <fullName>PA shared with Provider</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Appeal Response</fullName>
                    <isActive>false</isActive>
                    <label>Appeal Response</label>
                </value>
                <value>
                    <fullName>Appealed</fullName>
                    <isActive>false</isActive>
                    <label>Appealed</label>
                </value>
                <value>
                    <fullName>Archived</fullName>
                    <isActive>false</isActive>
                    <label>Archived</label>
                </value>
                <value>
                    <fullName>Cancel Request Sent</fullName>
                    <isActive>false</isActive>
                    <label>Cancel Request Sent</label>
                </value>
                <value>
                    <fullName>Failure</fullName>
                    <isActive>false</isActive>
                    <label>Failure</label>
                </value>
                <value>
                    <fullName>PA Request Submitted to Plan</fullName>
                    <isActive>false</isActive>
                    <label>PA Request Submitted to Plan</label>
                </value>
                <value>
                    <fullName>PA accessed by Provider</fullName>
                    <isActive>false</isActive>
                    <label>PA accessed by Provider</label>
                </value>
                <value>
                    <fullName>Plan PA Response</fullName>
                    <isActive>false</isActive>
                    <label>Plan PA Response</label>
                </value>
                <value>
                    <fullName>Plan Question Response</fullName>
                    <isActive>false</isActive>
                    <label>Plan Question Response</label>
                </value>
                <value>
                    <fullName>Plan Question Set Ready for Provider</fullName>
                    <isActive>false</isActive>
                    <label>Plan Question Set Ready for Provider</label>
                </value>
                <value>
                    <fullName>Question Request Submitted to Plan</fullName>
                    <isActive>false</isActive>
                    <label>Question Request Submitted to Plan</label>
                </value>
                <value>
                    <fullName>Sent to Plan</fullName>
                    <isActive>false</isActive>
                    <label>Sent to Plan</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect custom look up field to associate program coverage record to capture outcome of BI/BV case, PAP case or Copay case</description>
        <label>Program Coverage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>You can see only program coverage associated with the current program case.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PC_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Prescription__c.object
<CustomObject>
    <description>This Object captures prescription information for the prescribed drug for a patient when enrolled in an engagement program.</description>
    <fields>
        <fullName>PC_hasActivePA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when the prescription has an associated prior authorization.</description>
        <label>hasActivePA</label>
        <type>Checkbox</type>
    </fields>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Program_Coverage__c.object
<CustomObject>
    <description>This is a custom object in Patient Connect that represents patient&apos;s coverage information that satisfies the coverage for the treatment/program that the patient is enrolled into.</description>
    <fields>
        <fullName>PC_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The prescription associated with the program coverage record</description>
        <label>Prescription</label>
        <referenceTo>PC_Prescription__c</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <description>The outcome status of the coverage.</description>
        <label>Program Coverage Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Pending</fullName>
                </value>
                <value>
                    <fullName>Investigation In Progress</fullName>
                </value>
                <value>
                    <fullName>Eligibility Pending</fullName>
                </value>
                <value>
                    <fullName>Pending PA</fullName>
                </value>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Appeal</fullName>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Sources Not Found</fullName>
                </value>
                <value>
                    <fullName>Covered with Restrictions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_hasActivePA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Selected or checked when the program coverage has an active prior authorization.</description>
        <label>Has Active PA</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Coverage</label>
    <nameField>
        <displayFormat>COV-{000000000}</displayFormat>
        <label>Coverage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Trigger_PA_Case.cls
/*********************************************************************************************************
Class Name      : PC_Trigger_PA_Case 
Description     : Sets Active PA on Coverage and Prescription
Created By      : Shabda Bhujad
Created Date    : Sept 06, 2017
Modification Log:
-------------------------------------------------------------------------------------------------------------- 
Developer                   Date                   	Description
--------------------------------------------------------------------------------------------------------------            
Shabda Bhujad				Sep 24, 2017			Initial version
Shabda Bhujad				Oct 03, 2017 			PC-2335 Updated code to use record type developer name instead of name
Shabda Bhujad               Nov 14, 2017            PC-2485 Removing the reference to trigger state
Xiukai Ning                 Feb 28, 2019            PC-3775 - Code review. FLS is NOT needed in Triggers, as they always run in System Mode.
                                                    Trigger delegate class (handler) that has with Sharing keyword however, will apply user sharing.
                                                    We are removing all FLS and With Sharing keywords in the handlers.
Hitha Avalakki              Jan 29, 2020            [PC-5945] Modified the code to use PC_Constants.CASE_PA_RECORD_TYPE_NAME instead of fetching the record type id for PA case.
                                                    This was required in order to prevent the SOQL query required to fetch the PA case record type id.
Satheesh Kumar              Nov 16, 2021            [PC-8213] Excluded FLS Check and added inherited sharing
****************************************************************************************************************/
public inherited sharing class PC_Trigger_PA_Case extends PC_TriggerHandler {

    override public void beforeUpdate() {
        resetActivePA((List< Case>) newList);
    }
    
    override public void afterInsertUpdate() {
        setActivePA((List< Case>) newList);
    }
    
    
    private void setActivePA(List<Case> newCaseList) {
        Set<Id> programCoverageIds = new Set<Id>();
        Set<Id> prescriptionIds = new Set<Id>();

        /* 
         * Check for active PA on Program Coverage and Prescription
		 */
        for(Case caseObj : newCaseList) {
            if((caseObj.Type == PC_Constants.CASE_PA_RECORD_TYPE_NAME)
               && caseObj.PC_PA_Status__c != PC_Constants.PA_CASE_STATUS_Denied && caseObj.PC_PA_Status__c != PC_Constants.PA_CASE_STATUS_Canceled 
               && caseObj.PC_PA_Status__c != PC_Constants.PA_CASE_STATUS_Expired && caseObj.PC_PA_Status__c != null) {
                   if (caseObj.PC_Program_Coverage__c!=null) {
                       programCoverageIds.add(caseObj.PC_Program_Coverage__c);
                   }
                   if (caseObj.PC_PA_Prescription__c!=null) {
                       prescriptionIds.add(caseObj.PC_PA_Prescription__c);
                   }
               } 
        }        
        
        if(!programCoverageIds.isEmpty()) {
            List<PC_Program_Coverage__c> programCoverageforPA = [SELECT Id, PC_hasActivePA__c
                                                                 FROM PC_Program_Coverage__c 
                                                                 where id IN : programCoverageIds];
            
            if (!programCoverageforPA.isEmpty()) {
                List<PC_Program_Coverage__c> toUpdatePrgCoverages = new List<PC_Program_Coverage__c>();
                for (PC_Program_Coverage__c eachPrgCov : programCoverageforPA) {
                    if(!eachPrgCov.PC_hasActivePA__c) {
                        eachPrgCov.PC_hasActivePA__c= TRUE;
                        toUpdatePrgCoverages.add(eachPrgCov);
                    }            
                }        
                PC_Database.upd(toUpdatePrgCoverages, FALSE);
            }
        }
        
        if(!prescriptionIds.isEmpty()) {
            List<PC_Prescription__c> prescriptionforPA = [SELECT Id, PC_hasActivePA__c
                                                          FROM PC_Prescription__c 
                                                          where id IN : prescriptionIds];
            
            if (!prescriptionforPA.isEmpty()) {
                List<PC_Prescription__c> toUpdatePrescription = new List<PC_Prescription__c>();
                for (PC_Prescription__c eachPrescription : prescriptionforPA) {
                    if(!eachPrescription.PC_hasActivePA__c) {
                        eachPrescription.PC_hasActivePA__c= TRUE;
                        toUpdatePrescription.add(eachPrescription);
                    }
                }        
                PC_Database.upd(toUpdatePrescription, FALSE);
            }  
        }
    }
    
    private void resetActivePA(List<Case> newCaseList) {
        Set<Id> programCoverageIds = new Set<Id>();
        Set<Id> prescriptionIds = new Set<Id>();
        String[] nonActiveStatus  = new String[]{PC_Constants.PA_CASE_STATUS_Denied, PC_Constants.PA_CASE_STATUS_Canceled,PC_Constants.PA_CASE_STATUS_Expired};

        /* 
         * Check for PA on Program Coverage and Prescription 
		 */
        for(Case caseObj : newCaseList) {
                if((caseObj.Type == PC_Constants.CASE_PA_RECORD_TYPE_NAME)) {
                       if (caseObj.PC_Program_Coverage__c!=null) {
                           programCoverageIds.add(caseObj.PC_Program_Coverage__c);
                       }
                       if (caseObj.PC_PA_Prescription__c!=null) {
                           prescriptionIds.add(caseObj.PC_PA_Prescription__c);
                       }
                   } 
            }        

        if(!programCoverageIds.isEmpty()) {
            List<PC_Program_Coverage__c> programCoverageforPA = [SELECT Id, PC_hasActivePA__c
                                                                 FROM PC_Program_Coverage__c 
                                                                 where id IN : programCoverageIds];
            
            List<Case> casesforPrgCoverage = [SELECT Id, PC_Program_Coverage__c
                                              FROM Case 
                                              WHERE PC_Program_Coverage__c IN : programCoverageIds 
                                              AND Type =:PC_Constants.CASE_PA_RECORD_TYPE_NAME
                                              AND PC_PA_Status__c NOT IN :nonActiveStatus
                                              AND Id NOT IN: newCaseList];
            
            if (!programCoverageforPA.isEmpty()) {
                List<PC_Program_Coverage__c> toUpdatePrgCoverages = new List<PC_Program_Coverage__c>();
                for (PC_Program_Coverage__c eachPrgCov : programCoverageforPA) {
                    if(eachPrgCov.PC_hasActivePA__c && casesforPrgCoverage.isEmpty()) {
                        eachPrgCov.PC_hasActivePA__c= FALSE;
                        toUpdatePrgCoverages.add(eachPrgCov);
                    }            
                }        
                PC_Database.upd(toUpdatePrgCoverages, FALSE);
            }    
        }       
        
        if(!prescriptionIds.isEmpty()) {
            List<PC_Prescription__c> prescriptionforPA = [SELECT Id, PC_hasActivePA__c
                                                          FROM PC_Prescription__c 
                                                          where id IN : prescriptionIds];
            
            List<Case> casesforPrescription = [SELECT Id, PC_PA_Prescription__c
                                               FROM Case 
                                               WHERE PC_PA_Prescription__c IN : prescriptionIds 
                                               AND Type =: PC_Constants.CASE_PA_RECORD_TYPE_NAME
                                               AND PC_PA_Status__c NOT IN :nonActiveStatus
                                               AND Id NOT IN: newCaseList];
            if (!prescriptionforPA.isEmpty()) {
                List<PC_Prescription__c> toUpdatePrescriptions = new List<PC_Prescription__c>();
                for (PC_Prescription__c eachPrescription : prescriptionforPA) {
                    if(eachPrescription.PC_hasActivePA__c && casesforPrescription.isEmpty()) {
                        eachPrescription.PC_hasActivePA__c= FALSE;
                        toUpdatePrescriptions.add(eachPrescription);
                    }            
                }        
                PC_Database.upd(toUpdatePrescriptions, FALSE);
            }   
        }
    }
}