objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect custom look up field to associate program coverage record to capture outcome of BI/BV case, PAP case or Copay case</description>
        <label>Program Coverage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>You can see only program coverage associated with the current program case.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PC_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Pharmacy_Referral__c.object
<CustomObject>
    <description>The PC_Pharmacy_Referral__c is a custom object in Patient Connect used to store referrals for pharmacy.</description>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program coverage associated with a specific pharmacy referral.</description>
        <label>Program Coverage</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Coverage does not exist or is not active.</errorMessage>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Coverage_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <infoMessage>You can only associate active program coverage to a referral. Search results only display active program coverage.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Pharmacy Referrals</relationshipLabel>
        <relationshipName>Pharmacy_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program case associated with a specific pharmacy referral.</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Program does not exist or is not a program case.</errorMessage>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <infoMessage>You can only associate program case to a referral. Search results only display program cases.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Pharmacy Referrals</relationshipLabel>
        <relationshipName>PC_Pharmacy_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pharmacy Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Pharmacy Referral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pharmacy Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Program_Coverage__c.object
<CustomObject>
    <description>This is a custom object in Patient Connect that represents patient&apos;s coverage information that satisfies the coverage for the treatment/program that the patient is enrolled into.</description>
    <fields>
        <fullName>PC_Coverage_Status__c</fullName>
        <description>The status of the coverage.</description>
        <label>Coverage Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Pharmacy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The health plan payer’s phone number.</description>
        <label>Pharmacy</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Coverage (Pharmacy)</relationshipLabel>
        <relationshipName>Selected_for_Program_Coverage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <description>The outcome status of the coverage.</description>
        <label>Program Coverage Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Pending</fullName>
                </value>
                <value>
                    <fullName>Investigation In Progress</fullName>
                </value>
                <value>
                    <fullName>Eligibility Pending</fullName>
                </value>
                <value>
                    <fullName>Pending PA</fullName>
                </value>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Appeal</fullName>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Sources Not Found</fullName>
                </value>
                <value>
                    <fullName>Covered with Restrictions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the patient is enrolled into and requires coverage for.</description>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Coverage</label>
    <nameField>
        <displayFormat>COV-{000000000}</displayFormat>
        <label>Coverage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Test_NewReferral.cls
/**
 * Created by vkashikar on 8/17/2018.
 * Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   Description
-----------------------------------------------------------------------------------
Shishir Bansal        10-Dec-2019      [PC-5792] Avoid hardcoding of string variable
Hitha Avalakki        26-Feb-2021      [PC-7442] Replaced PC_Test_Setup.createCases() with PC_Test_Setup.createProgramCases() method.
*********************************************************************************/
@isTest
public class PC_Test_NewReferral {
    private static User adminUser;
    private static final Integer OBJECTS_NUMBER = 3;
    private static final String ACTIVE_PICKLISTRING='ACTIVE';

    @isTest static void testMethodReferral() {
        adminUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@test100.com', 'test100');
        //Create multiple patient accounts

        PC_Database.ins(adminUser);

        System.runAs(adminUser) {
            Test.StartTest();

            List<Account> patientAccounts = PC_Test_Setup.createAccounts('Patient', OBJECTS_NUMBER, PC_Constants.PATIENT_RECORD_TYPE);
            PC_Database.ins(patientAccounts);
            // Check if 3 patients are created for bulk testing
            System.assertEquals(3, patientAccounts.size());

            //Create multiple program cases
            //[PC-7442] Replaced PC_Test_Setup.createCases() with PC_Test_Setup.createProgramCases() method.
            List<Case> programCases = PC_Test_Setup.createProgramCases(patientAccounts, OBJECTS_NUMBER);
            PC_Database.ins(programCases);
            // Check if 3 cases are created for bulk testing
            system.assertEquals(3, programCases.size());

            //Create multiple pharmacy referrals
            List<PC_Pharmacy_Referral__c> referrals = PC_Test_Setup.createReferrals(programCases, OBJECTS_NUMBER);
            PC_Database.ins(referrals);
            // Check if 3 referrals are created for bulk testing
            system.assertEquals(3, referrals.size());
            //Check if referral 1 was created on program case 1
            system.assertEquals(programCases[0].Id, referrals[0].PC_Program__c);



            PC_Program_Coverage__c programCoverage = PC_Test_Setup.createProgramCoverage(programCases[0].Id);
            programCoverage.PC_Coverage_Status__c = ACTIVE_PICKLISTRING;
            PC_Database.ins(programCoverage);

            PC_NewReferral.InitData initData = PC_NewReferral.getData(programCases[0].id); // without pharmacy
            system.assert(initData.programCoverages.isEmpty());

            List<Account> pharmacies = PC_Test_Setup.createAccounts('pharmacy',1,PC_Constants.PHARMACY_RECORD_TYPE);
            PC_Database.ins(pharmacies);

            programCoverage.PC_Pharmacy__c = pharmacies[0].Id;
            PC_Database.upd(programCoverage);

            PC_NewReferral.InitData initData2 = PC_NewReferral.getData(programCases[0].id); // with pharmacy
            system.assert(!initData2.programCoverages.isEmpty());

            Case paCase = PC_Test_Setup.createCase(adminUser, patientAccounts[0]);
            paCase.RecordTypeId = PC_System.recordTypeId('Case',PC_Constants.CASE_PA_RECORD_TYPE);
            paCase.PC_Program__c = programCases[0].Id;
            PC_Database.ins(paCase);

            paCase.PC_Program_Coverage__c = programCoverage.Id;
            PC_Database.upd(paCase);

            PC_NewReferral.InitData initData3 = PC_NewReferral.getData(programCases[0].id); // with pharmacy
            system.assert(!initData3.programCoverages.isEmpty());

            try {
                PC_NewReferral.InitData initData4 = PC_NewReferral.getData(null); // with pharmacy
            }
            catch(Exception ex) {
                system.assert(true);
            }

            Test.StopTest();
        }
    }
}