objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect custom look up field to associate program coverage record to capture outcome of BI/BV case, PAP case or Copay case</description>
        <label>Program Coverage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>You can see only program coverage associated with the current program case.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PC_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_Document_Category__c</fullName>
        <description>The Category that the document may fall into.
Note: A document can be associated with multiple categories.</description>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>PC_EngagementProgramCode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Enrollment Form</fullName>
                </value>
                <value>
                    <fullName>Patient Consent</fullName>
                </value>
                <value>
                    <fullName>Patient Information Update</fullName>
                </value>
                <value>
                    <fullName>Insurance Information</fullName>
                </value>
                <value>
                    <fullName>Prescription</fullName>
                </value>
                <value>
                    <fullName>Copay Information</fullName>
                </value>
                <value>
                    <fullName>PA Documentation</fullName>
                </value>
                <value>
                    <fullName>Appeals Documentation</fullName>
                </value>
                <value>
                    <fullName>Post Infusion Report</fullName>
                </value>
                <value>
                    <fullName>Post Training Report</fullName>
                </value>
                <value>
                    <fullName>Test Results</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Illegible Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <description>General Document or Attachment</description>
        <label>Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document_Log__c.object
<CustomObject>
    <description>Patient Connect custom object:  used to link the custom Document object records to various objects</description>
    <fields>
        <fullName>PC_Association_Record_Id__c</fullName>
        <description>The record ID for the corresponding association.</description>
        <label>Association Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Document_Category__c</fullName>
        <description>Document sent or received can be categorized as Enrollment Form, Payer Forms, Coverage Denial Documentation, Adverse Event, and Product Complaint.</description>
        <label>Document Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Welcome Gesture</fullName>
                </value>
                <value>
                    <fullName>Copay Card</fullName>
                </value>
                <value>
                    <fullName>Copay Program Cover Letter</fullName>
                </value>
                <value>
                    <fullName>Enrollment Form</fullName>
                </value>
                <value>
                    <fullName>Payer Forms</fullName>
                </value>
                <value>
                    <fullName>Coverage Denial Documentation</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Product Complaint</fullName>
                </value>
                <value>
                    <fullName>Adverse Event and Product Complaint</fullName>
                </value>
                <value>
                    <fullName>Program Feedback</fullName>
                </value>
                <value>
                    <fullName>Patient Authorization</fullName>
                </value>
                <value>
                    <fullName>Patient Consent</fullName>
                </value>
                <value>
                    <fullName>Patient Opt Out</fullName>
                </value>
                <value>
                    <fullName>Patient HIPAA Revocation</fullName>
                </value>
                <value>
                    <fullName>Verbal Authorization Transcript Representation</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Enrollment Follow Up</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Illegible</fullName>
                </value>
                <value>
                    <fullName>Injection Training</fullName>
                </value>
                <value>
                    <fullName>Patient Un-enrollment</fullName>
                </value>
                <value>
                    <fullName>AE/PC</fullName>
                </value>
                <value>
                    <fullName>Medical Notes</fullName>
                </value>
                <value>
                    <fullName>Prescription</fullName>
                </value>
                <value>
                    <fullName>Insurance Information</fullName>
                </value>
                <value>
                    <fullName>Physician Authorization</fullName>
                </value>
                <value>
                    <fullName>Lab Results</fullName>
                </value>
                <value>
                    <fullName>Post Injection Training Report</fullName>
                </value>
                <value>
                    <fullName>SA Documentation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Document_Log__c</fullName>
        <description>A description about the log information modification.</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PC_Document__c</fullName>
        <description>Look up to Document that is created.</description>
        <label>Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Document Log</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Document Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Program_Coverage__c.object
<CustomObject>
    <description>This is a custom object in Patient Connect that represents patient&apos;s coverage information that satisfies the coverage for the treatment/program that the patient is enrolled into.</description>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <description>The outcome status of the coverage.</description>
        <label>Program Coverage Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Pending</fullName>
                </value>
                <value>
                    <fullName>Investigation In Progress</fullName>
                </value>
                <value>
                    <fullName>Eligibility Pending</fullName>
                </value>
                <value>
                    <fullName>Pending PA</fullName>
                </value>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Appeal</fullName>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Sources Not Found</fullName>
                </value>
                <value>
                    <fullName>Covered with Restrictions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Coverage</label>
    <nameField>
        <displayFormat>COV-{000000000}</displayFormat>
        <label>Coverage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Test_DocumentModificationLog.cls
/**************************************************************************************
Apex Class Name     : PC_Test_DocumentModificationLog
Description         : This class is used for testing PC_DocumentModificationLog;
CreatedBy           : Deloitte
Created Date        : 11 October 2019
Modification Log    :
--------------------------------------------------------------------------------------------------------------
Developer                   Date                   Description
----------------------------------------------------------------------------
Kanteti Kishore        11 October 2019           Initial version
*************************************************************************************/
@isTest(seeAllData=False)
public class PC_Test_DocumentModificationLog {
    private static User objUser2;
    private static PC_Document__c oDoc;
    private static final String DOC_CATEGORY = 'Enrollment Form';
    private static final String ACC_NAME = 'Account Name';
    private static final String ENG_PROGRAM_NAME = 'Program';
    private static final String ASSOCIATION_TYPE = 'Program Case';
    private static final String ASSOCIATION_NAME = 'Case';


    /*********************************************************************************
Method Name    : createTestData
Author         : Kishore Kanteti
Description    : This method is used for creating test data
Return Type    : void
Parameter      :
*********************************************************************************/
    private static void createTestData() {

        objUser2 = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@test95.com', 'test95');
        PC_Database.ins(objUser2, false);
        system.assertNotEquals(objUser2.Id, Null);

        createObjects();
    }

    /*********************************************************************************
Method Name    : createObjects
Author         : Kishore Kanteti
Description    : This method is used for creating a document
Return Type    : void
Parameter      :
*********************************************************************************/
    private static void createObjects() {
        system.runAs(objUser2) {
            Id accRecordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.PATIENT_OBJECT, PC_Constants.PC_BUSINESSACCOUNT_PATIENT_RECORD_TYPE);
            Account acc = PC_Test_Setup.createAccount(ACC_NAME,accRecordTypeId);
            PC_Database.ins(acc, false);
            Case program  = PC_Test_Setup.createProgram(acc);
            PC_Program_Coverage__c programCoverage = PC_Test_Setup.createProgramCoverage(program.Id);
            PC_Database.ins(programCoverage, false);
            oDoc = PC_Test_Setup.createDocument(PC_Constants.DOCUMENT_FAX_INBOUND_RECORD_TYPE, PC_Constants.DOCUMENT_STATUS_REVIEW_NEEDED, ENG_PROGRAM_NAME + 'A');
            Id recordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.DOCUMENT_OBJECT, PC_Constants.DOCUMENT_FAX_INBOUND_RECORD_TYPE);
            oDoc.PC_Document_Category__c = DOC_CATEGORY;
            oDoc.RecordTypeId = recordTypeId;
            PC_Database.ins(oDoc, false);
            PC_Document_Log__c docLog = PC_Test_Setup.createDocumentLog( oDoc.Id,programCoverage.Id,ASSOCIATION_TYPE,ASSOCIATION_NAME);
            docLog.PC_Association_Record_Id__c = acc.Id;
            PC_Database.ins(docLog, false);

        }
    }
    /*********************************************************************************
Method Name    : testgetModificationLogs
Author         : Alina Balan
Description    : This method is used for testing "getModificationLogs"
Return Type    : void
Parameter      :
*********************************************************************************/
    @isTest static void testgetModificationLogs(){
        createTestData();
        system.runAs(objUser2) {
            Test.StartTest();

            PC_DocumentModificationLog.DocLogAndDescWrapper docLogAndDescWrapper = PC_DocumentModificationLog.getModificationLogs(oDoc.Id);
            system.assertnotEquals(0,docLogAndDescWrapper.documentLogWrapperList.size());
            system.assertnotEquals(null,docLogAndDescWrapper.showDocumentLogFieldVal);

            Test.StopTest();
        }
    }
}