objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Communication_Language__c</fullName>
        <description>Patient’s choice of communication language.</description>
        <formula>TEXT ( Account.PC_Communication_Language__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Communication Language</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_eLetter__c.object
<CustomObject>
    <fields>
        <fullName>PC_Allow_Send_to_Patient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Selecting this field allows the eLetter to be sent to the patients.</description>
        <label>Allow Send to Patient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Communication_Language__c</fullName>
        <description>The eLetter can be produced in these languages.</description>
        <inlineHelpText>Select supported languages for this eLetter</inlineHelpText>
        <label>Communication Language</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Object_Record_Types__c</fullName>
        <description>Case types with which the eLetter is associated.</description>
        <label>Object Record Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>PC_Source_Object__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BI / BV</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Private Coverage</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>Prior Authorization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Send_to_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this flag is checked, all other flags (Send Fax,Send email) are automatically unchecked and the eLetter is sent to the current User (for editing before sending to the Patients/Recipients)</description>
        <inlineHelpText>If Selected, the eLetter will be sent to current logged in User.</inlineHelpText>
        <label>Send to User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Source_Object__c</fullName>
        <description>The objects with which the eLetter is associated.</description>
        <label>Source Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Program Coverage</fullName>
                </value>
                <value>
                    <fullName>Interaction</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Adverse Event 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Target_Recipients__c</fullName>
        <description>Selects the target recipients for the eLetter.</description>
        <label>Target Recipients</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PC_Association_Role</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Template_Name__c</fullName>
        <description>API name for email template.</description>
        <inlineHelpText>Email Template Developer Name</inlineHelpText>
        <label>PC Template Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>eLetter</label>
    <nameField>
        <label>eLetter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eLetters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/PC_Association_Role.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HCO</fullName>
    </customValue>
    <customValue>
        <fullName>Treating Physician</fullName>
    </customValue>
    <customValue>
        <fullName>Reimbursement Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Care Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Field Reimbursement Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Case Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Caregiver</fullName>
    </customValue>
    <masterLabel>Association Role</masterLabel>
</GlobalValueSet>

classes/PC_Test_SupportPlan_eLetterController.cls
/**
 * Created by shisbansal on 11/20/2018.
 */

@IsTest
private class PC_Test_SupportPlan_eLetterController {

    @isTest static void testMethod1() {

            Test.startTest();
            PC_SupportPlan_eLetterController.eLetterObject eLetterObject =   PC_SupportPlan_eLetterController.geteLetterObject();
            PC_SupportPlan_eLetterController.FieldLabels fieldLabelsObj = PC_SupportPlan_eLetterController.getFieldLabels();
            //Hitha Avalakki: [PC-5757] : Added a LIMIT to query
            List<PC_eLetter__c> eLetterList = [Select Id,name, PC_Source_Object__c from PC_eLetter__c LIMIT 3];
            system.assert(eLetterList.size() == 3);
            Test.stopTest();
    }

    @testSetup static void setup() {

        List<PC_eLetter__c> testEletters = new List<PC_eLetter__c>();
        for(Integer i=0;i<2;i++) {
            testEletters.add(new PC_eLetter__c(Name = 'TestEletter'+i, PC_Source_Object__c ='Case',PC_Communication_Language__c = 'English;French',PC_Target_Recipients__c ='HCO;Treating Physician', PC_Template_Name__c = 'PC_Referral_Notification',PC_Allow_Send_to_Patient__c = true,PC_Send_to_User__c = true, PC_Object_Record_Types__c='Program' ));
        }
        PC_eLetter__c eLetter = new PC_eLetter__c(Name = 'TestEletter2', PC_Source_Object__c ='Case',PC_Communication_Language__c = 'English;French',PC_Target_Recipients__c ='HCO;Treating Physician', PC_Template_Name__c = 'PC_Referral_Notification', PC_Send_to_User__c = false, PC_Object_Record_Types__c='Program', PC_Allow_Send_to_Patient__c = true);
        testEletters.add(eLetter);
        Database.insert(testEletters,false);
    }
}