objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Association__c.object
<CustomObject>
    <description>PatientConnect custom object to manage the patient program&apos;s care team (including physician)</description>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the Account is associated as part of the patient&apos;s circle of care.</description>
        <label>Patient Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Care Team</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Role__c</fullName>
        <description>The Role that the Account plays as part of the patient&apos;s circle of care.</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCO</fullName>
                </value>
                <value>
                    <fullName>Treating Physician</fullName>
                </value>
                <value>
                    <fullName>Field Reimbursement Manager</fullName>
                </value>
                <value>
                    <fullName>Caregiver</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Clinical Educator</fullName>
                </value>
                <value>
                    <fullName>Care Coordinator</fullName>
                    <isActive>false</isActive>
                    <label>Care Coordinator</label>
                </value>
                <value>
                    <fullName>Reimbursement Specialist</fullName>
                    <isActive>false</isActive>
                    <label>Reimbursement Specialist</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Interaction__c.object
<CustomObject>
    <description>Patient Connect custom object used to manage information and activities for interactions with / for patients such as infusion appointments, training sessions or another types of patient appointments typically delivered by 3rd parties.</description>
    <fields>
        <fullName>PC_Participants__c</fullName>
        <description>Roles of the participants in the Interaction</description>
        <label>Participants</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCO</fullName>
                </value>
                <value>
                    <fullName>Treating Physician</fullName>
                </value>
                <value>
                    <fullName>Care Coordinator</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Specialist</fullName>
                </value>
                <value>
                    <fullName>Field Reimbursement Manager</fullName>
                </value>
                <value>
                    <fullName>Caregiver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Patient_Program__c</fullName>
        <description>The Program case to which the interaction is related.</description>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>The status of the Interaction such as Requested or Confirmed.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_InteractionParticipant__c.object
<CustomObject>
    <fields>
        <fullName>PC_Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Association</label>
        <referenceTo>PC_Association__c</referenceTo>
        <relationshipLabel>Interaction Participants</relationshipLabel>
        <relationshipName>PC_AssociationInteractionParticipants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Interaction__c</fullName>
        <description>Interaction to which Participant is attending</description>
        <label>Interaction</label>
        <referenceTo>PC_Interaction__c</referenceTo>
        <relationshipLabel>Interaction Participants</relationshipLabel>
        <relationshipName>PC_InteractionParticipant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Role__c</fullName>
        <description>The Role that the Participant plays as part of the patient&apos;s circle of care.</description>
        <formula>IF(NOT(ISBLANK(PC_Association__c)) ,   TEXT(PC_Association__r.PC_Role__c)  , IF(NOT(ISBLANK( PC_Practitioner__c  )) , $Label.PC_Practitioner  , &apos;&apos;))</formula>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <label>Interaction Participant</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Interaction Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_CreateParticipantForNewCareTeamMember.cls
/*********************************************************************************************************
Class Name      : PC_CreateParticipantForNewCareTeamMember
Description     : Trigger handler on Association object to create Interaction participant when new care team member is added for related case.
Created By      : Haritha Reddy
Created Date    : Nov 20, 2021
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer                   Date                   Description
--------------------------------------------------------------------------------------------------------------
Haritha Reddy           Nov 20, 2021            [PC-8312]Initial Version
************************************************************************************************************/
public inherited sharing class PC_CreateParticipantForNewCareTeamMember extends PC_TriggerHandler {
    override public void afterInsert(){
        createInteractionParticipants((List<PC_Association__c>)newList);
    }

    /*********************************************************************************
    Method Name    : createInteractionParticipants
    Description    : This method creates new interaction participant for new care team member added in related case.
    Return Type    : void
    Parameter      : List of incoming association records - Trigger.new
    *********************************************************************************/
    private void createInteractionParticipants(List<PC_Association__c> newAssociations) {
        Set<Id> caseIds = new Set<Id>();
        for(PC_Association__c association : newAssociations){
            caseIds.add(association.PC_Program__c);
        }
        List<PC_Interaction__c> interactionList = new List<PC_Interaction__c>();
        interactionList = [Select Id,PC_Participants__c,PC_Patient_Program__c FROM PC_Interaction__c WHERE PC_Participants__c != null
        AND PC_Patient_Program__c IN: caseIds AND (PC_Status__c = 'Confirmed' OR PC_Status__c = 'Requested')];

        if(interactionList != null && !interactionList.isEmpty()){
            //Create new Interaction Participant for new care team member added if corresponding role is selected in Interaction record
            List<PC_InteractionParticipant__c> interactionParticipantsToBeCreated = new List<PC_InteractionParticipant__c>();
            for(PC_Association__c association : newAssociations){
                for(PC_Interaction__c interaction : interactionList){
                    if(interaction.PC_Patient_Program__c == association.PC_Program__c && interaction.PC_Participants__c.containsIgnoreCase(association.PC_Role__c)){
                        PC_InteractionParticipant__c newInteractionParticipant =  new PC_InteractionParticipant__c();
                        newInteractionParticipant.PC_Interaction__c = interaction.Id;
                        newInteractionParticipant.PC_Association__c = association.Id;
                        interactionParticipantsToBeCreated.add(newInteractionParticipant);
                    }
                }
            }
            if(interactionParticipantsToBeCreated != null && !interactionParticipantsToBeCreated.isEmpty()){
                PC_Database.ins(interactionParticipantsToBeCreated, false);
            }
        }
    }
}