objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_EngagementProgramCode__c</fullName>
        <description>Internal field to associate Engagement Program Code with Document Tags/Category. Not to be used on layout.</description>
        <label>Engagement Program Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>ASHF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Engagement Program lookup for documents.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <description>General Document or Attachment</description>
        <label>Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Program_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Program Code provides a unique mnemonic or code value that can be used to reference engagement programs. It is expected that a program code would not change during the life of a program, whereas, the name may be modified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Provide a short unique code that will not need to be changed.</inlineHelpText>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PC_UpdateEngagementProgramCodeHandler.cls
/*********************************************************************************************************
Trigger Name    : PC_UpdateEngagementProgramCodeHandler
Description     : trigger on PC_Document__c object.
Created By      : Vivek Kumar Mishra
Created Date    : May 24, 2018
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer          Log#      	Date                   	Description
--------------------------------------------------------------------------------------------------------------
Xiukai Ning                     Feb 28, 2019            PC-3775 - Code review. FLS is NOT needed in Triggers, as they always run in System Mode.
                                                        Trigger delegate class (handler) that has with Sharing keyword however, will apply user sharing.
                                                        We are removing all FLS and With Sharing keywords in the handlers.
Satheesh Kumar                  Nov 16, 2021            [PC-8213] Excluded FLS Check and added inherited sharing
****************************************************************************************************************/

public inherited sharing class PC_UpdateEngagementProgramCodeHandler extends PC_TriggerHandler{
    override public void beforeInsertUpdate(){
        updateEngagementProgramCode((List<PC_Document__c>)newList, (Map<Id, PC_Document__c>)oldMap);
    }
    /*********************************************************************************
      Method Name    : updateEngagementProgramCode
      Author         : Vivek Kumar Mishra
      Description    : This method will update the engagement program code based on
                       the engagement program associated with the new/update document
                       record
      Return Type    : void
      Parameter      : List of incoming document records - Trigger.new
     *********************************************************************************/
    private void updateEngagementProgramCode(List<PC_Document__c> newDocuments, Map<Id, PC_Document__c> oldDocuments){
        Set<Id> engProgramIds = new Set<Id>();

        //Collect associated engagement program ids out of new records
        for(PC_Document__c document : newDocuments){
            //In case of update event Engagement program ids should only be added to the set
            // if there is a change in  associated Engagement program between old and new records.
            if (oldMap == null || (oldMap.containsKey(document.Id)
                    && !(((PC_Document__c)oldMap.get(document.Id)).PC_Engagement_Program__c
                    == document.PC_Engagement_Program__c)))
            engProgramIds.add(document.PC_Engagement_Program__c);
        }

        if(!engProgramIds.isEmpty()){
            //Get an id->Object__c map of PC_Engagement_Program__c
            Map<Id, PC_Engagement_Program__c> engPrograms = new Map<Id, PC_Engagement_Program__c>([SELECT Id, PC_Program_Code__c
            FROM PC_Engagement_Program__c WHERE Id IN: engProgramIds]);

            //Fetching out the list of existing values for Engagement Program Picklist
            List<String> myPicklist = new List<String>();
            Schema.DescribeFieldResult field = PC_Document__c.PC_EngagementProgramCode__c.getDescribe();

            for (Schema.PicklistEntry f : field.getPicklistValues()){
                myPicklist.add(f.getLabel());

            }

            //Attach engagement program id with new record
            for(PC_Document__c document : newDocuments){
                if(document.PC_Engagement_Program__c != null){
                    ID engProgramId = document.PC_Engagement_Program__c;
                    String pcProgramCode = (engPrograms.get(engProgramId)).PC_Program_Code__c;
                    if(myPicklist.contains(pcProgramCode)){
                        (document.PC_EngagementProgramCode__c) = pcProgramCode;
                    } else if(myPicklist.contains(PC_Constants.PC_NONE)){
                        //Setting up the Engagement Program Code as 'None' in no such
                        // Picklist Value Scenario
                        (document.PC_EngagementProgramCode__c) = PC_Constants.PC_NONE;
                    } else{
                        document.PC_EngagementProgramCode__c = null;
                    }

                } else{
                    //Setting up engagement program code as 'None' in case of
                    //no engagement program associated
                    if(myPicklist.contains(PC_Constants.PC_NONE)){
                        (document.PC_EngagementProgramCode__c) = PC_Constants.PC_NONE;
                    } else{
                        document.PC_EngagementProgramCode__c = null;
                    }

                }
            }
        }
    }
}