objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Association__c.object
<CustomObject>
    <description>PatientConnect custom object to manage the patient program&apos;s care team (including physician)</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the account which is associated with the patient&apos;s program case.</description>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>PC_Patient</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>PC_Pharmacy</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Payer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Association</relationshipLabel>
        <relationshipName>Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the Account is associated as part of the patient&apos;s circle of care.</description>
        <label>Patient Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Care Team</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Role__c</fullName>
        <description>The Role that the Account plays as part of the patient&apos;s circle of care.</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCO</fullName>
                </value>
                <value>
                    <fullName>Treating Physician</fullName>
                </value>
                <value>
                    <fullName>Field Reimbursement Manager</fullName>
                </value>
                <value>
                    <fullName>Caregiver</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Clinical Educator</fullName>
                </value>
                <value>
                    <fullName>Care Coordinator</fullName>
                    <isActive>false</isActive>
                    <label>Care Coordinator</label>
                </value>
                <value>
                    <fullName>Reimbursement Specialist</fullName>
                    <isActive>false</isActive>
                    <label>Reimbursement Specialist</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_HCOEWPProcessor.cls
/*********************************************************************************
Class Name      : PC_HCOEWPProcessor
Description     : Associates physian with enrollment case
Created By      : Vijay Kashikar
Created Date    : 4-Jan-2017
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
-----------------------------------------------------------------------------------            
Vijay Kashikar		        4-Jan-17              Initial Version
Vijay Kashikar		        12 Apr 17             [PC-1436] Added condition to avoid calling PC_Database.ups() when the object is null/empty.
Ajinkya Deshmukh			21 Jun 17			  FLS Check Added (Code Merge)
Tejas Patel                 06 Jul 17             Removing the SOQL sattemenst from the for loop
Mayuresh Patil              07 Sep 17             PC-2193 FLS Check updated to new PC303 code
Vijay Kashikar              26 Jun 20             [PC-6398] Stored the records created in the global queue.
Haritha Reddy           21-Jan-2021             [PC-7102] Added FLS Check
*********************************************************************************/
public with sharing class PC_HCOEWPProcessor implements PC_EnrollmentWizard.PageProcessor{
    public static void processEnrollment(Case enrollmentCase, Map<String, Object> pageState) {
        if (pageState != null ) {
            ID programId = enrollmentCase.PC_Program__c;

            String role = PC_Constants.ACCOUNT_ROLE;

            List<PC_Association__c> existingHCOs;

            List<String> fields = new List<String>{
                    PC_Constants.getQualifiedAPIName('PC_Program__c'),
                    PC_Constants.getQualifiedAPIName('PC_Role__c')};
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Association__c'), PC_Database.Operation.Reading, fields);

            existingHCOs = [SELECT Id FROM PC_Association__c
            WHERE PC_Program__c = :programId
            AND PC_Role__c = :role];

            for (String key : pageState.keySet()) {
                if(key == 'selectedHCOIds') {
                    if(programId != null) {
                        
                        List<Object> selectedHCOs = (List<Object>) pageState.get(key);                         
                        
                        List<PC_Association__c> associations = new List<PC_Association__c>();
                        PC_Association__c hco;

                        Set<String> existingHCOsAsStrSet = new Set<String>();
                        for(PC_Association__c pac : existingHCOs){
                            existingHCOsAsStrSet.add(pac.Id);
                        }
                        for (Object hcoId : selectedHCOs) {
                            
                            if(!existingHCOsAsStrSet.contains((String) hcoId)) {
                                hco = new PC_Association__c();
                                hco.PC_Program__c = programId; 
                                hco.PC_Account__c = (String) hcoId;                             
                                hco.PC_Role__c = role;
                                associations.add(hco);                            }
                            else {
                                System.debug('\t' +'association not created for hcoId since it already exists: ' + (String) hcoId);
                            }
                            
                            
                        }
                        if(!associations.isEmpty()) {
                        	PC_Database.ups(associations);//FLS/CRUD Check enforced in the PC_database method
                            PC_EnrollmentWizard.addToRecordsCreated((List<SObject>) associations);
                        }
                    }
                    else {
                        throw new PC_EnrollmentWizard.PageProcessorException('HCO Processor: Program ID not found');
                    }
                    
                }
            }
        } else {
            throw new PC_EnrollmentWizard.PageProcessorException('Missing page state');
        }
    }
}