objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_ActiveApplicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the active applicant in an enrollment case, if there are multiple applicants.</description>
        <label>ActiveApplicant</label>
        <referenceTo>PC_Applicant__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>CaseApplicant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>PC_IsCreatedUsingOCR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether the applicant created using OCR or not.</description>
        <inlineHelpText>Specifies whether the applicant created using OCR or not.</inlineHelpText>
        <label>Is Created Using OCR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_IsReviewed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether the record is reviewed or not.</description>
        <inlineHelpText>Specifies whether the record is reviewed or not.</inlineHelpText>
        <label>Is Reviewed</label>
        <type>Checkbox</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Applicant associated with this document.</description>
        <label>Applicant</label>
        <referenceTo>PC_Applicant__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document_Log__c.object
<CustomObject>
    <description>Patient Connect custom object:  used to link the custom Document object records to various objects</description>
    <fields>
        <fullName>PC_Document_Log__c</fullName>
        <description>A description about the log information modification.</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PC_Document__c</fullName>
        <description>Look up to Document that is created.</description>
        <label>Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient program case associated with the document.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Log</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Document Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_OcrQueue__c.object
<CustomObject>
    <description>Stores information regarding document queued for the OCR service</description>
    <fields>
        <fullName>PC_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether the document is ready for OCR.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_SourceDocument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of the PC Document which queued for OCR.</description>
        <label>Source Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>OCR Queue</relationshipLabel>
        <relationshipName>OCR_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>Current state of the extraction process.</description>
        <inlineHelpText>Current state of the extraction process.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OCR Queue</label>
    <nameField>
        <displayFormat>OCRQ-{00000000}</displayFormat>
        <label>OCR Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCR Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PC_DocumentEnrollmentWithOCR.cls
/**
 * Created by sathekumar on 6/24/2021.
 */

public with sharing class PC_DocumentEnrollmentWithOCR {

    @AuraEnabled
    public static DocumentStatus checkDocumentOcrStatus(String documentId) {
        DocumentStatus documentStatus = new DocumentStatus();
        try {
            documentStatus.ocrServiceEnabled = isOcrServiceEnabled();
            documentStatus.previousOcrQueueStatus = previousOcrQueueStatus(documentId);
            documentStatus.applicantExistOnDocument = isApplicantExistOnDocument(documentId);
            documentStatus.enrollmentCaseExistOnDocument = isEnrollmentCaseExistOnDocument(documentId);
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return documentStatus;
    }

    @AuraEnabled
    public static String cancelOCR(String documentId) {
        String message;
        try {
            List<String> ocrQueueFields = new List<String>{PC_Constants.getQualifiedAPIName('PC_SourceDocument__c'), PC_Constants.getQualifiedAPIName('PC_Status__c'), PC_Constants.getQualifiedAPIName('PC_IsActive__c')};
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_OcrQueue__c'), PC_Database.Operation.Reading, ocrQueueFields);
            List<PC_OcrQueue__c> ocrQueueList = [SELECT Id, PC_SourceDocument__c, PC_Status__c, PC_IsActive__c FROM PC_OcrQueue__c WHERE PC_SourceDocument__c = :documentId AND PC_Status__c IN ('Queued', 'In Progress') LIMIT 1];
            if (ocrQueueList.size() > 0) {
                PC_OcrQueue__c ocrQueue = ocrQueueList[0];
                ocrQueue.PC_Status__c = PC_Constants.PC_OCR_QUEUE_STATUS_CANCELED;
                ocrQueue.PC_IsActive__c = PC_Constants.FALSE_BOOLEAN;
                PC_Database.upd(ocrQueue);
            } else {
                message = System.Label.PC_NotAbleToCancelOcrMessage;
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return message;
    }

    @AuraEnabled
    public static ApplicantOcrDetails getApplicantOcrDetails(String enrollmentCaseId) {
        ApplicantOcrDetails applicantOcrDetails = new ApplicantOcrDetails();
        try {
            applicantOcrDetails.isOcrEnabled = isOcrServiceEnabled();
            if(applicantOcrDetails.isOcrEnabled) {
                // FLS Check for PC_Document__c
                List<String> fields = new List<String>{ PC_Constants.getQualifiedAPIName('PC_ActiveApplicant__c') };
                PC_Database.assertAccess(PC_Constants.PC_CASE, PC_Database.Operation.Reading, fields);
                String activeApplicantId = [SELECT Id, PC_ActiveApplicant__c FROM Case WHERE Id = :enrollmentCaseId LIMIT 1] ?.PC_ActiveApplicant__c;
                if (String.isNotBlank(activeApplicantId)) {
                    PC_Applicant__c applicantObj = [SELECT Id, PC_IsCreatedUsingOCR__c, PC_IsReviewed__c FROM PC_Applicant__c WHERE Id =: activeApplicantId];
                    applicantOcrDetails.isCreatedUsingOCR = applicantObj.PC_IsCreatedUsingOCR__c;
                    applicantOcrDetails.isReviewed = applicantObj.PC_IsReviewed__c;
                }
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return applicantOcrDetails;
    }


    private static String previousOcrQueueStatus(String documentId) {
        Boolean isValid;
        //FLS Check
        List<String> ocrQueueFields = new List<String>{
                PC_Constants.getQualifiedAPIName('PC_SourceDocument__c'), PC_Constants.getQualifiedAPIName('PC_Status__c'), PC_Constants.getQualifiedAPIName('PC_IsActive__c')
        };
        PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_OcrQueue__c'), PC_Database.Operation.Reading, ocrQueueFields);
        String ocrQueueStatus = [SELECT Id, PC_SourceDocument__c, PC_Status__c, PC_IsActive__c FROM PC_OcrQueue__c WHERE PC_SourceDocument__c = :documentId ORDER BY createdDate DESC LIMIT 1]?.PC_Status__c;
        return ocrQueueStatus;
    }

    private static Boolean isOcrServiceEnabled() {
        String useOCR = PC_SYSTEM.getPatientConnectSetting('PC_UseOCR', PC_Constants.FALSE_STRING);
        return Boolean.valueOf(useOCR);
    }

    private static Boolean isApplicantExistOnDocument(String documentId) {
        // Check FLS for PC_Document__c
        List<String> pcDocumentFields = new List<String>{'Id', PC_Constants.getQualifiedAPIName('PC_Applicant__c')};
        PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Document__c'), PC_Database.Operation.Reading, pcDocumentFields);
        PC_Document__c documentObj = [SELECT Id, PC_Applicant__c FROM PC_Document__c WHERE Id = :documentId];
        if (String.isNotBlank(documentObj.PC_Applicant__c)) {
            return true;
        }
        return false;
    }

    private static Boolean isEnrollmentCaseExistOnDocument(String documentId) {
        Id recordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.PC_CASE, PC_Constants.CASE_ENROLLMENT_RECORD_TYPE);
        List<PC_Document_Log__c> docLog = [ SELECT PC_Program__c, PC_Program__r.RecordTypeId FROM PC_Document_Log__c WHERE PC_Document__c = :documentId AND (PC_Program__r.RecordTypeId = :recordTypeId) LIMIT 1];
        if (docLog.isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    public inherited sharing class DocumentStatus {
        @AuraEnabled public Boolean ocrServiceEnabled { get; set; }
        @AuraEnabled public String previousOcrQueueStatus { get; set; }
        @AuraEnabled public Boolean applicantExistOnDocument { get; set; }
        @AuraEnabled public Boolean enrollmentCaseExistOnDocument { get; set; }

        public DocumentStatus() {
            ocrServiceEnabled = PC_Constants.FALSE_BOOLEAN;
            previousOcrQueueStatus = PC_Constants.EMPTY_STRING;
            applicantExistOnDocument = PC_Constants.FALSE_BOOLEAN;
            enrollmentCaseExistOnDocument = PC_Constants.FALSE_BOOLEAN;
        }
    }

    public inherited sharing class ApplicantOcrDetails {
        @AuraEnabled public Boolean isOcrEnabled { get; set; }
        @AuraEnabled public Boolean isCreatedUsingOCR { get; set; }
        @AuraEnabled public Boolean isReviewed { get; set; }

        public ApplicantOcrDetails() {
            isOcrEnabled = PC_Constants.FALSE_BOOLEAN;
            isCreatedUsingOCR = PC_Constants.FALSE_BOOLEAN;
            isReviewed = PC_Constants.FALSE_BOOLEAN;
        }
    }
}