objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Health plan using which the PA case was created</description>
        <inlineHelpText>Health plan using which the PA case was created</inlineHelpText>
        <label>Health Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Health_Plan__c.Patient__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_PA_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prescription for which PA is requested</description>
        <label>Prescription</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Prescription__c.PC_Program_Case__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Prescription__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Prescription__c</referenceTo>
        <relationshipLabel>Prescriptions</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_PA_Submitted_On__c</fullName>
        <description>Date when the prior authorization is submitted</description>
        <label>Submitted On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated physician account</description>
        <label>Physician</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PC_Physician</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Physician</relationshipLabel>
        <relationshipName>Physician</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect custom look up field to associate program coverage record to capture outcome of BI/BV case, PAP case or Copay case</description>
        <label>Program Coverage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>You can see only program coverage associated with the current program case.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PC_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program’s product</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.PC_Engagement_Program__c</field>
                <operation>equals</operation>
                <valueField>PC_Engagement_Program_Product__c.PC_Engagement_Program__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Engagement_Program_Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Health_Plan__c.object
<CustomObject>
    <description>Patient Connect custom object: Used to capture a patient&apos;s various health plans (private insurance companies, public payer plans) as part of Patient Connect&apos;s access functionality</description>
    <label>Health Plan</label>
    <nameField>
        <displayFormat>HP-{000000000}</displayFormat>
        <label>Health Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Prescription__c.object
<CustomObject>
    <description>This Object captures prescription information for the prescribed drug for a patient when enrolled in an engagement program.</description>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Program_Coverage__c.object
<CustomObject>
    <description>This is a custom object in Patient Connect that represents patient&apos;s coverage information that satisfies the coverage for the treatment/program that the patient is enrolled into.</description>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient&apos;s health plan that provides the coverage.</description>
        <label>Health Plan</label>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Program Coverages</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The prescription associated with the program coverage record</description>
        <label>Prescription</label>
        <referenceTo>PC_Prescription__c</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <description>The outcome status of the coverage.</description>
        <label>Program Coverage Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Pending</fullName>
                </value>
                <value>
                    <fullName>Investigation In Progress</fullName>
                </value>
                <value>
                    <fullName>Eligibility Pending</fullName>
                </value>
                <value>
                    <fullName>Pending PA</fullName>
                </value>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Appeal</fullName>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Sources Not Found</fullName>
                </value>
                <value>
                    <fullName>Covered with Restrictions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the patient is enrolled into and requires coverage for.</description>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Coverage</label>
    <nameField>
        <displayFormat>COV-{000000000}</displayFormat>
        <label>Coverage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_ePriorAuthInitiationFormController.cls
/*********************************************************************************************************
Class Name      : PC_ePriorAuthInitiationFormController
Description     : Controller for PC_ePriorAuthInitiationForm
Created By      : Vijay Kashikar
Created Date    : Jan 01, 2018
Modification Log:
-----------------------------------------------------------------------------------------------------
Developer                   Date                           Description
-----------------------------------------------------------------------------------------------------
Vijay Kashikar              20 June, 2019              Initial Version
Kanteti Kishore             13-Dec-2019                [PC-5795] Reduced parameters for submitPA method
*********************************************************************************************************/
public with sharing class PC_ePriorAuthInitiationFormController {
    @AuraEnabled
    public static PC_ePA.InitiationFormData getData(Id caseId, String overridePrescriptionWithCoverage ) {
        try {
            system.debug('in getData');
            system.debug('overridePrescriptionwithCoverage-->'+overridePrescriptionWithCoverage);
            List<PC_ePA.HealthPlan> healthPlans = PC_ePA.getHealthPlansByCaseId(caseId);
            List<PC_ePA.Prescription> prescriptions = new List<PC_ePA.Prescription>();
            List<PC_ePA.ProgramCoverage> programCoverages = new List<PC_ePA.ProgramCoverage>();

            if(overridePrescriptionWithCoverage == PC_Constants.FALSE_STRING) {
                prescriptions = PC_ePA.getPrescriptionsByCaseId(caseId);
            }

            else if(overridePrescriptionWithCoverage == PC_Constants.TRUE_STRING) {
                programCoverages = PC_ePA.getProgramCoveragesByCaseId(caseId);
            }


            PC_ePA.InitiationFormData formData = new PC_ePA.InitiationFormData();
            formData.healthPlans = healthPlans;
            formData.prescriptions = prescriptions;
            formData.healthPlanLabels = PC_ePA.getHealthPlanLabels();
            formData.prescriptionLabels = PC_ePA.getPrescriptionLabels();
            formData.patient = PC_ePA.getPatientByCaseId(caseId);
            formData.patientLabels = PC_ePA.getPatientLabels();
            formData.searchFormLabels = PC_ePA.getFormLabels();
            formData.programCoverages = programCoverages;
            formData.programCoveragesLabel =PC_ePA.getProgramCoverageLabels();
            system.debug('formData-->'+formData);
            return formData;
        }
        catch(Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return null;
    }
    @AuraEnabled
    public static PC_ePA.FormsResponse searchPAForms(Id caseId, Id pbmId, Id productId) {
        system.debug('in getPharmacyBenefitInfo');
        PC_ePA.FormsResponse response = new PC_ePA.FormsResponse();
        try {
            PC_ePA.Client handler = PC_ePA.getClientService();
            system.debug('handler -> ' + handler);
            PC_ePA.FormsRequest formsRequest = handler.createSearchFormsRequest();
            system.debug('formsRequest -> ' + formsRequest);
            PC_ePA.updateFormsRequest(caseId, pbmId, productId, formsRequest);
            system.debug('updated formsRequest -> ' + formsRequest);
            response = handler.searchForms(formsRequest);
            system.debug('search form response - ' + JSON.serialize(response));
            return response;
        }
        catch(Exception ex) {
            PC_Utility.logAndThrowException(ex);
            //response.errorMessage = ex.getMessage();
        }
        return null;
    }
    @AuraEnabled

    public static PC_ePA.PAResponse submitPA(Map<String,String> ePADetails) {
        try {
            Id caseId = (Id) ePADetails.get('caseId');
            Id pbmId = (Id) ePADetails.get('pbmId');
            Id prescriptionId = (Id) ePADetails.get('prescriptionId');
            Id programCoverageId = (Id) ePADetails.get('programCoverageId');
            String overridePrescriptionWithCoverage = '';
            overridePrescriptionWithCoverage = ePADetails.get('overridePrescriptionWithCoverage');
            String formId = '';
            formId = ePADetails.get('formId');

            PC_ePA.Client handler = PC_ePA.getClientService();
            system.debug('handler -> ' + handler);



            PC_ePA.PARequest request = handler.submitPA();
            PC_ePA.updatePARequest(ePADetails, request);
             system.debug('request -->'+request);
            PC_ePA.PAResponse response = handler.createPA(request);
            system.debug('search form response - ' + response);

            try {
                Case paCase = new Case();
                //paCase.PC_PA_Prescription__c = PC_ePA.getPrescriptionsByCaseId(caseId);
                //Id physicianId = PC_ePA.getPhysicianIdByCaseId(caseId);
                Case programCase = PC_ePA.getCase(caseId);

                //if(!String.isBlank(physicianId)) {
                    paCase.PC_Physician__c = programCase.PC_Physician__c;
                //}
                paCase.PC_Program__c = caseId;
                paCase.PC_PA_Submitted_On__c = Date.today();
                paCase.PC_Health_Plan__c = pbmId;
                paCase.PC_Engagement_Program__c = programCase.PC_Engagement_Program__c;
                paCase.PC_Program_Product__c = programCase.PC_Program_Product__c;

                if( overridePrescriptionWithCoverage ==PC_Constants.TRUE_STRING ) {
                    paCase.PC_Program_Coverage__c = programCoverageId;
                    List<PC_Program_Coverage__c> programCoverages = [Select PC_Prescription__c from PC_Program_Coverage__c where id = :programCoverageId LIMIT 1];
                    if(programCoverages != null && !programCoverages.isEmpty()) {
                        paCase.PC_PA_Prescription__c = programCoverages[0].PC_Prescription__c;
                    }
                }
                else{
                    paCase.PC_PA_Prescription__c = prescriptionId;
                }

                handler.updatePACase(paCase, response);
                PC_Database.ins(paCase);

                response.paCaseId = paCase.Id;
                response.isSuccess = true;
                response.is_ePA_created = true;

                return response;
            }
            catch(Exception ex) {
                response.isSuccess = false;
                String message = 'PA case could not be created. However, the ePA was submitted successfully.';
                if(String.isNotBlank(response.htmlURL)) {
                    response.is_ePA_created = true;
                    message = message;// + ' -> ' + response.htmlURL;
                }
                response.errorMessage = message;
                PC_Utility.publishErrorLog(ex, message + '--> ' + response.htmlURL);
                return response;
            }
        }
        catch(Exception ex) {
            PC_Utility.logAndThrowException(ex);
            //response.errorMessage = ex.getMessage();
        }
        return null;
    }

}