objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated engagement program for which the case has been created</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Action_Center_Setting__mdt.object
<CustomObject>
    <description>Settings to configure Action center on program case page.</description>
    <fields>
        <fullName>PC_Action_Component_Attributes__c</fullName>
        <description>Attributes that will be passed onto the component at the time of dynamic creation.</description>
        <inlineHelpText>This must be in JSON format. 
Example {&quot;componentAttributeName1&quot;:&quot;componentAttributeValue1&quot;,&quot;componentAttributeName2&quot;:&quot;componentAttributeValue2&quot;}</inlineHelpText>
        <label>Action Component Attributes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PC_Action_Component__c</fullName>
        <description>Component Name that should be triggered when clicked on the action</description>
        <inlineHelpText>Input the API name of the component that should be triggered when action icon is clicked.</inlineHelpText>
        <label>Action Component</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Should be checked if the Action needs to be displayed</description>
        <inlineHelpText>Should be checked if the Action needs to be displayed</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Case_Record_Type__c</fullName>
        <description>Record type associated with the case type where the action should be displayed</description>
        <inlineHelpText>Select the record type of the case to which the action should be associated with. If record type is not present add it to the picklist of the metadata before adding the record.</inlineHelpText>
        <label>Case Record Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>PC_Program</fullName>
                    <default>true</default>
                    <label>PC_Program</label>
                </value>
                <value>
                    <fullName>PC_PAP</fullName>
                </value>
                <value>
                    <fullName>PC_BIBV</fullName>
                </value>
                <value>
                    <fullName>PC_Benefits_Investigation_Benefits_Verification</fullName>
                </value>
                <value>
                    <fullName>PC_Copay</fullName>
                </value>
                <value>
                    <fullName>PC_Prior_Authorization</fullName>
                </value>
                <value>
                    <fullName>PC_Alternate_Funding</fullName>
                </value>
                <value>
                    <fullName>PC_Appeal</fullName>
                </value>
                <value>
                    <fullName>PC_Enrollment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Case_Recordtype_Namespaceprefix__c</fullName>
        <description>The field describes the namespace prefix for case record type.</description>
        <inlineHelpText>Namespace of record type</inlineHelpText>
        <label>Case Record Type Namespace Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program_Code__c</fullName>
        <description>Engagement program code that maps to the Engagement program the action is associated to.</description>
        <inlineHelpText>Enter the program code for the Engagement Program</inlineHelpText>
        <label>Engagement Program Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Other_Case_Record_Type__c</fullName>
        <description>Enter Case record type when Other is selected as Case Record Type.</description>
        <inlineHelpText>Enter Case record type when Other is selected as Case Record Type.</inlineHelpText>
        <label>Other Case Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action Center Setting</label>
    <pluralLabel>Action Center Settings</pluralLabel>
</CustomObject>

objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Engagement Program lookup for documents.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program__c.object
<CustomObject>
    <description>Patient services program offered by the manufacturer or franchise.</description>
    <fields>
        <fullName>PC_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if the program is active and can be associated with patients.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Program_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Program Code provides a unique mnemonic or code value that can be used to reference engagement programs. It is expected that a program code would not change during the life of a program, whereas, the name may be modified.</description>
        <externalId>true</externalId>
        <inlineHelpText>Provide a short unique code that will not need to be changed.</inlineHelpText>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engagement Program</label>
    <nameField>
        <label>Engagement Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Engagement_Program_Service__c.object
<CustomObject>
    <description>Custom junction object to facilitate many-to-many relationships between the Engagement Program and the Service object</description>
    <fields>
        <fullName>PC_Active__c</fullName>
        <description>Indicates whether the Engagement Program Service is currently active.</description>
        <formula>IF( (ISBLANK(  PC_End_Date__c ) ||  ISNULL( PC_End_Date__c ) || 
     PC_End_Date__c &gt;= TODAY()) &amp;&amp; NOT(ISBLANK( PC_Start_Date__c )), true, false)</formula>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <description>Holds the Engagement Program details.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Engagement Program Services</relationshipLabel>
        <relationshipName>PC_Engagement_Program</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Engagement Program Service</label>
    <nameField>
        <displayFormat>EPS-{0}</displayFormat>
        <label>Engagement Program Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Program Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_LaunchTaskActionComponent.cls
/*********************************************************************************
Class Name      : PC_LaunchTaskActionComponent
Description     : Methods for Guided Task Management
Created By      : Vijay Kashikar
Created Date    : 09-Jul-20
Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   	Description
-----------------------------------------------------------------------------------
Vijay Kashikar            09-Jul-2020              Initial Version
Satheesh Kumar            11-Nov-2020              [PC-6943] Added documentId property to TaskActionDetails class
Vijay Kashikar            21-Jan-21                [PC-7102] Added FLS Checks
Vijay Kashikar            21-Jan-2021              [PC-7102] Added sharing clause
Haritha Reddy             10-Oct-2022              [PC-9224] Added a condition to handle scenario when org namespace is empty
*********************************************************************************/

public with sharing class PC_LaunchTaskActionComponent {
    public inherited sharing class TaskActionDetails {
        @AuraEnabled public PC_HomeActivitiesController.TaskActionComponent actionComponent {get;set;}
        @AuraEnabled public String relatedToObject {get;set;}
        @AuraEnabled public String relatedToId {get;set;}
        @AuraEnabled public String documentId {get;set;}
        private String relatedToId_RecordTypeDevName {get;set;}
        private String relatedToId_RecordTypeNamespace {get;set;}
        private String relatedToProgramCode {get;set;}
        @AuraEnabled public String actionCenterAttributes {get;set;}

        public TaskActionDetails() {
            actionComponent = new PC_HomeActivitiesController.TaskActionComponent();
        }
    }

    @AuraEnabled
    public static TaskActionDetails getActionComponent(Id taskRecordId) {
        try {
            List<String> fields = new List<String>();
            fields.add(PC_Constants.getQualifiedAPIName('PC_ActionComponent__c'));
            fields.add('WhatId');
            fields.add(PC_Constants.getQualifiedAPIName('PC_Document__c'));
            PC_Database.assertAccess(PC_Constants.PC_TASK,PC_Database.Operation.Reading, fields);

            Task currentTask = [SELECT Id, WhatId, PC_Document__c, PC_ActionComponent__c FROM Task WHERE Id = :taskRecordId];

            if(currentTask != null) {
                List<PC_HomeActivitiesController.PicklistEntry> taskActionComponents =
                        PC_HomeActivitiesController.getActionComponentPicklistValues();
                TaskActionDetails actionDetails = new TaskActionDetails();
                if(String.isNotBlank(currentTask.PC_ActionComponent__c)) {
                    actionDetails.actionComponent = getActionComponentDetails(currentTask.PC_ActionComponent__c, taskActionComponents);
                    setRelatedInfo(actionDetails, currentTask);
                    actionDetails.actionCenterAttributes = getComponentAttributes(actionDetails);
                    return actionDetails;
                }
                else {
                    return null;
                }
            }
            else {
                return null;
            }
        }
        catch(Exception ex) {
            PC_Utility.createExceptionLog(ex);
            throw new AuraHandledException(ex.getMessage());
        }
    }
    private static void setRelatedInfo(TaskActionDetails actionDetails, Task currentTask) {
        if(currentTask.WhatId != null) {
            actionDetails.relatedToId = currentTask.WhatId;
            actionDetails.relatedToObject = currentTask.WhatId.getSObjectType().getDescribe().getName();
            if(actionDetails.relatedToObject.toLowerCase() == 'case') {
                List<String> caseFields = new List<String>();
                caseFields.add(PC_Constants.getQualifiedAPIName('PC_Engagement_Program__r') + '.' +
                    PC_Constants.getQualifiedAPIName('PC_Program_Code__c'));
                PC_Database.assertAccess(PC_Constants.PC_CASE, PC_Database.Operation.Reading, caseFields);
                Case relatedCase = [
                        SELECT ID, PC_Engagement_Program__r.PC_Program_Code__c, RecordType.DeveloperName, RecordType.NamespacePrefix
                        FROM Case
                        WHERE ID = :actionDetails.relatedToId
                ];
                actionDetails.relatedToProgramCode = relatedCase.PC_Engagement_Program__r.PC_Program_Code__c;
                actionDetails.relatedToId_RecordTypeDevName = relatedCase.RecordType.DeveloperName;
                actionDetails.relatedToId_RecordTypeNamespace = relatedCase.RecordType.NamespacePrefix;
            }
        }
        if(currentTask.PC_Document__c != null){
            actionDetails.documentId = currentTask.PC_Document__c;
        }
    }
    private static PC_HomeActivitiesController.TaskActionComponent
        getActionComponentDetails(String actionCmpAPIName, List<PC_HomeActivitiesController.PicklistEntry> taskActionComponents) {
        if(String.isNotBlank(actionCmpAPIName)) {
            actionCmpAPIName = actionCmpAPIName.toLowerCase();
            for (PC_HomeActivitiesController.PicklistEntry picklistEntry : taskActionComponents) {
                if (picklistEntry.value.toLowerCase() == actionCmpAPIName) {
                    PC_HomeActivitiesController.TaskActionComponent actionCmpDetails = new PC_HomeActivitiesController.TaskActionComponent();
                    actionCmpDetails.label = picklistEntry.label;
                    actionCmpDetails.apiName = replaceNamespace(picklistEntry.value);
                    return actionCmpDetails;
                }
            }
        }
        return null;
    }
    private static String replaceNamespace(String apiName) {
        if(String.isNotBlank(apiName)) {
            apiName = apiName.toLowerCase();
            String pcNamespace = PC_Constants.OrgNamespace.toLowerCase();
            if(String.isBlank(pcNamespace) && apiName.startsWithIgnoreCase('patientconnect__')) {
                apiName = apiName.replace('patientconnect__', 'c:');
            }
            else if(String.isNotBlank(pcNamespace) && apiName.startsWithIgnoreCase('patientconnect__')) {
                apiName = apiName.replace('patientconnect__', pcNamespace + ':');
            }
            else if(apiName.startsWithIgnoreCase('c__')) {
                apiName = apiName.replace('c__', 'c:');
            }
            else if(!apiName.contains('__')) {
                apiName = 'c:'+ apiName;
            }
            else {
                apiName = apiName.replace('__', ':');
            }
        }
        return apiName;
    }
    private static String getComponentAttributes(TaskActionDetails actionDetails) {
        String componentAttributes;
        if(String.isNotBlank(actionDetails.actionComponent.apiName) && String.isNotBlank(actionDetails.relatedToProgramCode)) {
            List<PC_Action_Center_Setting__mdt> allActionCenters = [
                    SELECT ID, PC_Action_Component_Attributes__c
                    FROM PC_Action_Center_Setting__mdt
                    WHERE PC_Active__c = true
                    AND PC_Action_Component__c = :actionDetails.actionComponent.apiName
                    AND
                    (PC_Engagement_Program_Code__c = :actionDetails.relatedToProgramCode OR
                    PC_Engagement_Program_Code__c = 'All')
                    AND PC_Case_Record_Type__c = 'All'

            ];
            List<PC_Action_Center_Setting__mdt> pcOtherActionCenters = [
                    SELECT ID, PC_Action_Component_Attributes__c
                    FROM PC_Action_Center_Setting__mdt
                    WHERE PC_Active__c = true
                    AND PC_Action_Component__c = :actionDetails.actionComponent.apiName
                    AND (PC_Engagement_Program_Code__c = :actionDetails.relatedToProgramCode OR
                    PC_Engagement_Program_Code__c = 'All')
                    AND
                    (PC_Case_Record_Type__c != 'Other' AND PC_Case_Record_Type__c != 'All' AND
                    PC_Case_Record_Type__c = :actionDetails.relatedToId_RecordTypeDevName)
            ];
            List<PC_Action_Center_Setting__mdt> nonPCOtherActionCenters = [
                    SELECT ID, PC_Action_Component_Attributes__c
                    FROM PC_Action_Center_Setting__mdt
                    WHERE PC_Active__c = true AND PC_Action_Component__c = :actionDetails.actionComponent.apiName
                    AND (PC_Engagement_Program_Code__c = :actionDetails.relatedToProgramCode OR
                    PC_Engagement_Program_Code__c = 'All')
                    AND
                    (PC_Case_Record_Type__c = 'Other' AND
                    PC_Other_Case_Record_Type__c = :actionDetails.relatedToId_RecordTypeDevName AND
                    PC_Case_Recordtype_Namespaceprefix__c = :actionDetails.relatedToId_RecordTypeNamespace)
            ];
            // Multiple queries written to avoid SOQL error - Disjunction not supported.

            List<PC_Action_Center_Setting__mdt> actionCenters = new List<PC_Action_Center_Setting__mdt>();
            actionCenters.addAll(allActionCenters);
            actionCenters.addAll(pcOtherActionCenters);
            actionCenters.addAll(nonPCOtherActionCenters);

            if(actionCenters != null && actionCenters.size() == 1) {
                componentAttributes = actionCenters[0].PC_Action_Component_Attributes__c;
            }
            else if (actionCenters != null && actionCenters.size() > 1) {
                ActionComponentException ex = new ActionComponentException();
                String exceptionMessage = Label.PC_TaskActionMultipleConfigError;
                List<String> arguments = new List<String>();
                arguments.add(actionDetails.actionComponent.apiName);
                arguments.add(actionDetails.relatedToProgramCode);
                exceptionMessage = String.format(exceptionMessage, arguments);
                ex.setMessage(exceptionMessage);
                throw ex;
            }
        }
        if(String.isBlank(componentAttributes)) {
            componentAttributes = '{}';
        }
        return componentAttributes;
    }
    public inherited sharing class ActionComponentException extends Exception {

    }
}