objects/Case.object
<CustomObject>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Health plan using which the PA case was created</description>
        <inlineHelpText>Health plan using which the PA case was created</inlineHelpText>
        <label>Health Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Health_Plan__c.Patient__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_PA_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prescription for which PA is requested</description>
        <label>Prescription</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Prescription__c.PC_Program_Case__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Prescription__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Prescription__c</referenceTo>
        <relationshipLabel>Prescriptions</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_PA_Status__c</fullName>
        <description>The prior authorization status</description>
        <label>PA Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted to Provider</fullName>
                </value>
                <value>
                    <fullName>Submitted to Payer</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Appeal Request</fullName>
                </value>
                <value>
                    <fullName>PA shared with Provider</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Appeal Response</fullName>
                    <isActive>false</isActive>
                    <label>Appeal Response</label>
                </value>
                <value>
                    <fullName>Appealed</fullName>
                    <isActive>false</isActive>
                    <label>Appealed</label>
                </value>
                <value>
                    <fullName>Archived</fullName>
                    <isActive>false</isActive>
                    <label>Archived</label>
                </value>
                <value>
                    <fullName>Cancel Request Sent</fullName>
                    <isActive>false</isActive>
                    <label>Cancel Request Sent</label>
                </value>
                <value>
                    <fullName>Failure</fullName>
                    <isActive>false</isActive>
                    <label>Failure</label>
                </value>
                <value>
                    <fullName>PA Request Submitted to Plan</fullName>
                    <isActive>false</isActive>
                    <label>PA Request Submitted to Plan</label>
                </value>
                <value>
                    <fullName>PA accessed by Provider</fullName>
                    <isActive>false</isActive>
                    <label>PA accessed by Provider</label>
                </value>
                <value>
                    <fullName>Plan PA Response</fullName>
                    <isActive>false</isActive>
                    <label>Plan PA Response</label>
                </value>
                <value>
                    <fullName>Plan Question Response</fullName>
                    <isActive>false</isActive>
                    <label>Plan Question Response</label>
                </value>
                <value>
                    <fullName>Plan Question Set Ready for Provider</fullName>
                    <isActive>false</isActive>
                    <label>Plan Question Set Ready for Provider</label>
                </value>
                <value>
                    <fullName>Question Request Submitted to Plan</fullName>
                    <isActive>false</isActive>
                    <label>Question Request Submitted to Plan</label>
                </value>
                <value>
                    <fullName>Sent to Plan</fullName>
                    <isActive>false</isActive>
                    <label>Sent to Plan</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect custom look up field to associate program coverage record to capture outcome of BI/BV case, PAP case or Copay case</description>
        <label>Program Coverage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.PC_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>PC_Program_Coverage__c.PC_hasActivePA__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>You can see only program coverage associated with the current program case.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>PC_Program_Coverage__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PC_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the associated parent program case</description>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Health_Plan__c.object
<CustomObject>
    <description>Patient Connect custom object: Used to capture a patient&apos;s various health plans (private insurance companies, public payer plans) as part of Patient Connect&apos;s access functionality</description>
    <fields>
        <fullName>PC_Plan_Status__c</fullName>
        <description>Status of the health plan</description>
        <label>Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Public_Or_Private__c</fullName>
        <description>This field indicates if the health plan is a public or private plan</description>
        <label>Public or Private</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Health Plan</label>
    <nameField>
        <displayFormat>HP-{000000000}</displayFormat>
        <label>Health Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_Prescription__c.object
<CustomObject>
    <description>This Object captures prescription information for the prescribed drug for a patient when enrolled in an engagement program.</description>
    <fields>
        <fullName>PC_Patient_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient account associated with a specific prescription.</description>
        <label>Patient</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PC_Patient</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prescriptions (Patient)</relationshipLabel>
        <relationshipName>Patient_Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program case associated with a specific prescription.</description>
        <label>Program Case</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <errorMessage>Program does not exist or is not a program case.</errorMessage>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Prescriptions</relationshipLabel>
        <relationshipName>Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_hasActivePA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when the prescription has an associated prior authorization.</description>
        <label>hasActivePA</label>
        <type>Checkbox</type>
    </fields>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Program_Coverage__c.object
<CustomObject>
    <description>This is a custom object in Patient Connect that represents patient&apos;s coverage information that satisfies the coverage for the treatment/program that the patient is enrolled into.</description>
    <fields>
        <fullName>PC_Health_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient&apos;s health plan that provides the coverage.</description>
        <label>Health Plan</label>
        <referenceTo>PC_Health_Plan__c</referenceTo>
        <relationshipLabel>Program Coverages</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The prescription associated with the program coverage record</description>
        <label>Prescription</label>
        <referenceTo>PC_Prescription__c</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Program_Coverage__c</fullName>
        <description>The outcome status of the coverage.</description>
        <label>Program Coverage Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Pending</fullName>
                </value>
                <value>
                    <fullName>Investigation In Progress</fullName>
                </value>
                <value>
                    <fullName>Eligibility Pending</fullName>
                </value>
                <value>
                    <fullName>Pending PA</fullName>
                </value>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Appeal</fullName>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>Created in Error</fullName>
                </value>
                <value>
                    <fullName>Sources Not Found</fullName>
                </value>
                <value>
                    <fullName>Covered with Restrictions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the patient is enrolled into and requires coverage for.</description>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Program Coverage</relationshipLabel>
        <relationshipName>Program_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_hasActivePA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Selected or checked when the program coverage has an active prior authorization.</description>
        <label>Has Active PA</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Coverage</label>
    <nameField>
        <displayFormat>COV-{000000000}</displayFormat>
        <label>Coverage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Test_PA_Case_Trigger.cls
/*********************************************************************************
Class Name      : PC_Test_PA_Case_Trigger
Description     : Test methods for PA Case Trigger Handler
Created By      : Shabda Bhujad
Created Date    : 25-Sep-2017
Modification Log:
----------------------------------------------------------------------------------
Developer                   Date                   Description
-----------------------------------------------------------------------------------
Shabda Bhujad			  Sep, 25 2017			 Initial version
Mayuresh Patil            Aug 20, 2018              PC-3241 Adding access to medical health plan recordtype
*********************************************************************************/
@isTest
private class PC_Test_PA_Case_Trigger {
    private static User adminUser1;
    private static final Integer OBJECTS_NUMBER = 3;
    public static Boolean isTriggerActive = PC_TriggerHandlerHelper.getTriggerState('Case', 'PC_Trigger_PA_Case');
    @isTest
    static void testActivePAonProgramCoverage() {
        if(isTriggerActive){
            adminUser1 = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'userpctest@test2.com', 'test2');
            PC_Database.ins(adminUser1, false);
            
            system.runAs(adminUser1) {
                Test.StartTest();
                /* 
                 * Create Patient account
                 */
                Account aAccount = PC_Test_Setup.createPatient('Patient123');
                PC_Database.ins(aAccount);
                /* 
                 * Create health plans
                 */
                List<Account> accounts = [Select Id FROM Account WHERE Id =: aAccount.Id];
                
                List<PC_Health_Plan__c> healthPlans = PC_Test_Setup.createHealthPlans(accounts, OBJECTS_NUMBER);
                healthPlans[0].RecordTypeId = PC_System.recordTypeId(PC_Constants.PC_HEALTH_PLAN, PC_Constants.HEALTH_PLAN_MEDICAL_RECORD_TYPE);
                healthPlans[0].PC_Plan_Status__c = PC_Constants.ACTIVE;
                healthPlans[0].PC_Public_Or_Private__c = PC_Constants.HEALTH_PLAN_TYPE_PRIVATE;
                healthPlans[1].RecordTypeId = PC_System.recordTypeId(PC_Constants.PC_HEALTH_PLAN, PC_Constants.HEALTH_PLAN_MEDICAL_RECORD_TYPE);
                healthPlans[1].PC_Plan_Status__c = PC_Constants.ACTIVE;
                healthPlans[1].PC_Public_Or_Private__c = PC_Constants.HEALTH_PLAN_TYPE_PUBLIC;
                PC_Database.ins(healthPlans);
                System.assertEquals(healthPlans.size(), 3);
                /*
                 * Create a program case
                 */
                Case aCase = PC_Test_Setup.newCase(aAccount.Id, PC_Constants.CASE_PROGRAM_RECORD_TYPE);
                PC_Database.ins(aCase);
                
                List<PC_Program_Coverage__c> programCoverages = [SELECT Id, PC_hasActivePA__c FROM PC_Program_Coverage__c WHERE PC_Program__c =: aCase.Id];
                System.assertEquals(FALSE, programCoverages[0].PC_hasActivePA__c);
                System.assertEquals(FALSE, programCoverages[1].PC_hasActivePA__c);
                /* 
                 * Create Prescription
                 */
                PC_Prescription__c patientPrescription = new PC_Prescription__c();
                patientPrescription.PC_Patient_Account__c = aAccount.Id;
                patientPrescription.PC_Program_Case__c = aCase.Id;                
                PC_Database.ins(patientPrescription);
                
                List<PC_Prescription__c> prescriptions = [Select Id FROM PC_Prescription__c WHERE Id =: patientPrescription.Id];
                /*
                 * Create a PA case with the Program Coverage created for program case and Prescription related to the program case
                 */
                Case paCase = PC_Test_Setup.newCase(aAccount.Id, PC_Constants.CASE_PA_RECORD_TYPE);
                paCase.PC_Program__c = aCase.Id;
                paCase.PC_Program_Coverage__c = programCoverages[0].Id;
                paCase.PC_PA_Prescription__c= prescriptions[0].Id;
                PC_Database.ins(paCase);                
                /*
                 * Check if the hasActivePA is false on Program Coverage and Prescription since the PC_PA_Status__c value on Case is null
                 */
                programCoverages = [SELECT Id, PC_hasActivePA__c FROM PC_Program_Coverage__c WHERE PC_Program__c =: aCase.Id];
                System.assertEquals(FALSE,programCoverages[0].PC_hasActivePA__c);
                System.assertEquals(FALSE, programCoverages[1].PC_hasActivePA__c);
                
                prescriptions = [Select Id,PC_hasActivePA__c FROM PC_Prescription__c WHERE PC_Program_Case__c =: aCase.Id];
                System.assertEquals(FALSE,prescriptions[0].PC_hasActivePA__c);
                /*
                 * Update the PA Case Status to Denied and check if the hasActivePA is false on Program Coverage and Prescription
				 */                
                List<Case> paCases = [Select Id, PC_PA_Status__c FROM Case WHERE PC_Program__c =: aCase.Id];
                paCases[0].PC_PA_Status__c = PC_Constants.PA_CASE_STATUS_Denied;
                PC_Database.upd(paCases);
                
                programCoverages = [SELECT Id, PC_hasActivePA__c FROM PC_Program_Coverage__c WHERE PC_Program__c =: aCase.Id];
                System.assertEquals(FALSE,programCoverages[0].PC_hasActivePA__c);
                
                prescriptions = [Select Id,PC_hasActivePA__c FROM PC_Prescription__c WHERE PC_Program_Case__c =: aCase.Id];
                System.assertEquals(FALSE,prescriptions[0].PC_hasActivePA__c);

                /*
                 * Update the PA Case Status to Approved and check if the hasActivePA is true on Program Coverage and Prescription
				 */
                List<Case> paCasesList = [Select Id, PC_PA_Status__c FROM Case WHERE PC_Program__c =: aCase.Id];
                paCasesList[0].PC_PA_Status__c = PC_Constants.PA_CASE_STATUS_Approved;
                PC_Database.upd(paCasesList);

                programCoverages = [SELECT Id, PC_hasActivePA__c FROM PC_Program_Coverage__c WHERE PC_Program__c =: aCase.Id];
                System.assertEquals(TRUE,programCoverages[0].PC_hasActivePA__c);

                prescriptions = [Select Id,PC_hasActivePA__c FROM PC_Prescription__c WHERE PC_Program_Case__c =: aCase.Id];
                System.assertEquals(TRUE,prescriptions[0].PC_hasActivePA__c);
                Test.stopTest();
            }
        } 
        else {
            System.debug('The Trigger is DeActivated : ' + isTriggerActive);
        }
    }

}