objects/PC_Association__c.object
<CustomObject>
    <description>PatientConnect custom object to manage the patient program&apos;s care team (including physician)</description>
    <fields>
        <fullName>PC_AssociationStatus__c</fullName>
        <description>Indicates Active or Inactive status of the association.</description>
        <label>Association Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_EndDate__c</fullName>
        <description>The date on which the participant ceased to be an association member.
Note: A new record will be created if the participant becomes a member again. This ensures integrity of history.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_IsCreatedViaWCD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This helps to identify whether the association record is created by WCD or not.</description>
        <inlineHelpText>This helps to identify whether the association record is created by WCD or not.</inlineHelpText>
        <label>Is Created via WCD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the Account is associated as part of the patient&apos;s circle of care.</description>
        <label>Patient Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Care Team</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_DeactivateWCDAssociationHandler.cls
/*********************************************************************************************************
Class Name      : PC_DeactivateWCDAssociationHandler
Description     : beforeInsert trigger on PC_Association__c object to Deactivate all existing active association when new associations is created via WCD or WCR
Created By      : Satheesh Kumar
Created Date    : Jul 28, 2022
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer                   Date                   	Description
--------------------------------------------------------------------------------------------------------------
Satheesh Kumar    		Jul 28, 2022        		Initial Version
****************************************************************************************************************/

public inherited sharing class PC_DeactivateWCDAssociationHandler extends PC_TriggerHandler {
    override public void beforeInsert() {
        system.debug('Trigger Handler ::: PC_DeactivateWCDAssociationHandler');
        if (PC_WorkCaseDistributionForCaseHandler.isProcessed == true || PC_WorkCaseDistributionForAssocHandler.isProcessed == true ||
                PC_WorkCaseRedistributionForAccHandler.isProcessed == true || PC_WorkCaseRedistributionForAddrHandler.isProcessed == true ||
                PC_WorkCaseRedistributionForUserHandler.isProcessed == true) {
            deactivateOldWCDAssociations((List<PC_Association__c>) newList);
        }
    }

    /**
     * This method is used to deactivate all active associations created via WCD
     * @param newAssociations
     */
    private void deactivateOldWCDAssociations (List<PC_Association__c> newAssociations) {
        Set<Id> programCaseIds = new Set<Id>();
        List<PC_Association__c> associationsToExpire = new List<PC_Association__c>();

        for(PC_Association__c eachAssociation : newAssociations) {
            if(eachAssociation.PC_AssociationStatus__c == PC_Constants.ACTIVE && eachAssociation.PC_IsCreatedViaWCD__c) {
                programCaseIds.add(eachAssociation.PC_Program__c);
            }
        }
        if(!programCaseIds.isEmpty()){
            associationsToExpire = getAllActiveAssociations(programCaseIds);

            if (!associationsToExpire.isEmpty()) {
                PC_Database.upd(associationsToExpire, false);
            }
        }
    }

    /**
      * This method is used to get all active associations created via WCD
      * @param programCaseIds
      */
    private List<PC_Association__c> getAllActiveAssociations(Set<Id> programCaseIds) {
        List<PC_Association__c> oldAssociations = new List<PC_Association__c>();
        List<PC_Association__c> associationsToExpire = new List<PC_Association__c>();

        //FLS is NOT needed in Triggers, as they always run in System Mode.
        oldAssociations = [
                SELECT Id, PC_Program__c
                FROM PC_Association__c
                WHERE PC_Program__c IN :programCaseIds AND PC_AssociationStatus__c = :PC_Constants.ACTIVE
                AND PC_IsCreatedViaWCD__c = :PC_Constants.TRUE_BOOLEAN
        ];

        for (PC_Association__c oldA : oldAssociations) {
            oldA.PC_AssociationStatus__c = PC_Constants.INACTIVE;
            oldA.PC_EndDate__c = (Date) System.today();
            associationsToExpire.add(oldA);
        }
        return associationsToExpire;
    }
}