objects/PC_Association__c.object
<CustomObject>
    <description>PatientConnect custom object to manage the patient program&apos;s care team (including physician)</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference to the account which is associated with the patient&apos;s program case.</description>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>PC_Patient</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>PC_Pharmacy</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Payer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Association</relationshipLabel>
        <relationshipName>Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Associated_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient Connect Internal User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_AssociationStatus__c</fullName>
        <description>Indicates Active or Inactive status of the association.</description>
        <label>Association Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Program__c</fullName>
        <description>The program to which the Account is associated as part of the patient&apos;s circle of care.</description>
        <label>Patient Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Case.Type</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Care Team</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Role__c</fullName>
        <description>The Role that the Account plays as part of the patient&apos;s circle of care.</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCO</fullName>
                </value>
                <value>
                    <fullName>Treating Physician</fullName>
                </value>
                <value>
                    <fullName>Field Reimbursement Manager</fullName>
                </value>
                <value>
                    <fullName>Caregiver</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Clinical Educator</fullName>
                </value>
                <value>
                    <fullName>Care Coordinator</fullName>
                    <isActive>false</isActive>
                    <label>Care Coordinator</label>
                </value>
                <value>
                    <fullName>Reimbursement Specialist</fullName>
                    <isActive>false</isActive>
                    <label>Reimbursement Specialist</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_CheckExistingAssociationHandler.cls
/*********************************************************************************************************
Class Name      : PC_CheckExistingAssociationHandler
Description     : trigger on PC_Association__c object to check for existing Associations
Created By      : Tejas Patel
Created Date    : Jan 4, 2018
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer                   Date                   	Description
--------------------------------------------------------------------------------------------------------------
Tejas Patel            		July 16, 2019        		Initial Version
Haritha Reddy             21-Jan-2021              [PC-7102] Added FLS Check
Hitha Avalakki            25-May-2021               [PC-7545]: Removed 'with sharing' class level declaration since trigger handler code runs in system context
Kishore Kanteti           27-Aug-2021               [PC-8068] Commented FLS Check
Satheesh Kumar            Nov 16, 2021              [PC-8213] Excluded FLS Check and added inherited sharing
****************************************************************************************************************/

/* PC-7545: 'with sharing' class level declaration is not required since trigger handler code runs in Trigger Context*/
public inherited sharing class PC_CheckExistingAssociationHandler extends PC_TriggerHandler{
    override public void beforeInsertUpdate() {
        system.debug('Trigger Handler ::: PC_CheckExistingAssociationHandler');
        checkExistingAssociations((List<PC_Association__c>) newList);
    }

    /*
    * Method Name    : checkExistingAssociations
    * Author         : Tejas Patel
    * Description    : This is a helper method to check if active
    *                  Association exist for the same lookup
    * Return Type    : void
    * Parameter      : List<Id> newAssociations
    */
    private void checkExistingAssociations (List<PC_Association__c> newAssociations) {
        Set<Id> caseIds = new Set<Id>();
        Set<Id> associationIds = new Set<Id>();
        for (PC_Association__c eachAssociation : newAssociations) {
            caseIds.add(eachAssociation.PC_Program__c);
            associationIds.add(eachAssociation.Id);
        }
        /*
            List<String> fields = new List<String>{PC_Constants.getQualifiedAPIName('PC_Program__c'),
                    PC_Constants.getQualifiedAPIName('PC_Account__c'),
                    PC_Constants.getQualifiedAPIName('PC_Associated_User__c'),
                    PC_Constants.getQualifiedAPIName('PC_Role__c')
            };
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Association__c'), PC_Database.Operation.Reading, fields);
        */
        List<PC_Association__c> oldAssociations =  [SELECT Id, PC_Role__c, PC_Account__c, PC_Associated_User__c, PC_Program__c
        FROM PC_Association__c
        WHERE PC_Program__c
                IN : caseIds
        AND PC_AssociationStatus__c
                =: PC_Constants.ACTIVE
        AND ID NOT IN :associationIds];
        for (PC_Association__c newAssociation : newAssociations) {
            if (newAssociation.PC_AssociationStatus__c == PC_Constants.ACTIVE) {
                for (PC_Association__c oldAssociation : oldAssociations) {
                    if (newAssociation.id != oldAssociation.id) {
                        if (newAssociation.PC_Program__c == oldAssociation.PC_Program__c
                                && (newAssociation.PC_Role__c == oldAssociation.PC_Role__c) &&
                                (
                                    ((newAssociation.PC_Account__c == oldAssociation.PC_Account__c) && newAssociation.PC_Account__c != null)
                                        ||
                                    ((newAssociation.PC_Associated_User__c == oldAssociation.PC_Associated_User__c) && newAssociation.PC_Associated_User__c != null)
                                )
                                ) {
                            newAssociation.addError(Label.PC_ExisitingAssociation);
                        }
                    }
                }
            }
        }
    }
}