objects/PC_Address__c.object
<CustomObject>
    <description>PatientConnect custom object used to track addresses of all types of participants (accounts), including the patient</description>
    <fields>
        <fullName>PC_Account__c</fullName>
        <description>The account to which the address is associated with.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_ClearBillingAddrsOnAccountAfterDelete.cls
/**
 * Created by vkashikar on 8/29/2022.
 */

public with sharing class PC_ClearBillingAddrsOnAccountAfterDelete extends PC_TriggerHandler {
    override public void afterDelete() {
        updatePrimaryAddressOnAccountAfterDelete(oldList);
    }
    private void updatePrimaryAddressOnAccountAfterDelete(List<PC_Address__c> addresses) {
        Set<Id> accountIds = new Set<Id> ();
        List<Account> accountsToBeUpdated = new List<Account>();
        try {
            for (PC_Address__c address : addresses) {
                accountIds.add(address.PC_Account__c);
            }
            for (Account account : [SELECT Id, (SELECT Id FROM Addresses__r) FROM Account WHERE Id IN :accountIds]) {
                if (account.Addresses__r == null || account.Addresses__r.size() == 0) {
                    account.BillingStreet = '';
                    account.BillingCity = '';
                    account.BillingState = '';
                    account.BillingPostalCode = '';
                    account.BillingCountry = '';
                    accountsToBeUpdated.add(account);
                }
            }
            if (accountsToBeUpdated.size() > 0) {
                PC_Database.upd(accountsToBeUpdated, false);
            }
        }catch(Exception e) {
            PC_Utility.createExceptionLog(e);
        }


    }
}