objects/PC_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The engagement program associated with the specific applicant.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_Document_Category__c</fullName>
        <description>The Category that the document may fall into.
Note: A document can be associated with multiple categories.</description>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>PC_EngagementProgramCode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Enrollment Form</fullName>
                </value>
                <value>
                    <fullName>Patient Consent</fullName>
                </value>
                <value>
                    <fullName>Patient Information Update</fullName>
                </value>
                <value>
                    <fullName>Insurance Information</fullName>
                </value>
                <value>
                    <fullName>Prescription</fullName>
                </value>
                <value>
                    <fullName>Copay Information</fullName>
                </value>
                <value>
                    <fullName>PA Documentation</fullName>
                </value>
                <value>
                    <fullName>Appeals Documentation</fullName>
                </value>
                <value>
                    <fullName>Post Infusion Report</fullName>
                </value>
                <value>
                    <fullName>Post Training Report</fullName>
                </value>
                <value>
                    <fullName>Test Results</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Illegible Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Document_Name__c</fullName>
        <description>Name of the Document</description>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_EngagementProgramCode__c</fullName>
        <description>Internal field to associate Engagement Program Code with Document Tags/Category. Not to be used on layout.</description>
        <label>Engagement Program Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>ASHF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Engagement_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Engagement Program lookup for documents.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <description>General Document or Attachment</description>
        <label>Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document_Log__c.object
<CustomObject>
    <description>Patient Connect custom object:  used to link the custom Document object records to various objects</description>
    <fields>
        <fullName>PC_Document_Category__c</fullName>
        <description>Document sent or received can be categorized as Enrollment Form, Payer Forms, Coverage Denial Documentation, Adverse Event, and Product Complaint.</description>
        <label>Document Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Welcome Gesture</fullName>
                </value>
                <value>
                    <fullName>Copay Card</fullName>
                </value>
                <value>
                    <fullName>Copay Program Cover Letter</fullName>
                </value>
                <value>
                    <fullName>Enrollment Form</fullName>
                </value>
                <value>
                    <fullName>Payer Forms</fullName>
                </value>
                <value>
                    <fullName>Coverage Denial Documentation</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Product Complaint</fullName>
                </value>
                <value>
                    <fullName>Adverse Event and Product Complaint</fullName>
                </value>
                <value>
                    <fullName>Program Feedback</fullName>
                </value>
                <value>
                    <fullName>Patient Authorization</fullName>
                </value>
                <value>
                    <fullName>Patient Consent</fullName>
                </value>
                <value>
                    <fullName>Patient Opt Out</fullName>
                </value>
                <value>
                    <fullName>Patient HIPAA Revocation</fullName>
                </value>
                <value>
                    <fullName>Verbal Authorization Transcript Representation</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Enrollment Follow Up</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Illegible</fullName>
                </value>
                <value>
                    <fullName>Injection Training</fullName>
                </value>
                <value>
                    <fullName>Patient Un-enrollment</fullName>
                </value>
                <value>
                    <fullName>AE/PC</fullName>
                </value>
                <value>
                    <fullName>Medical Notes</fullName>
                </value>
                <value>
                    <fullName>Prescription</fullName>
                </value>
                <value>
                    <fullName>Insurance Information</fullName>
                </value>
                <value>
                    <fullName>Physician Authorization</fullName>
                </value>
                <value>
                    <fullName>Lab Results</fullName>
                </value>
                <value>
                    <fullName>Post Injection Training Report</fullName>
                </value>
                <value>
                    <fullName>SA Documentation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Document__c</fullName>
        <description>Look up to Document that is created.</description>
        <label>Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Document Log</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Document Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_OcrQueue__c.object
<CustomObject>
    <description>Stores information regarding document queued for the OCR service</description>
    <fields>
        <fullName>PC_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether the document is ready for OCR.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_OcrTemplateType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Template type of the queued up source document</description>
        <label>OCR Template Type</label>
        <referenceTo>PC_OcrTemplateType__c</referenceTo>
        <relationshipLabel>OCR Queue</relationshipLabel>
        <relationshipName>OCR_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_SourceDocument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of the PC Document which queued for OCR.</description>
        <label>Source Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>OCR Queue</relationshipLabel>
        <relationshipName>OCR_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <description>Current state of the extraction process.</description>
        <inlineHelpText>Current state of the extraction process.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OCR Queue</label>
    <nameField>
        <displayFormat>OCRQ-{00000000}</displayFormat>
        <label>OCR Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCR Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_OcrResponse__c.object
<CustomObject>
    <description>It stores the OCR response of the document after processing.</description>
    <fields>
        <fullName>PC_OcrQueue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCR Queue</label>
        <referenceTo>PC_OcrQueue__c</referenceTo>
        <relationshipLabel>OCR Responses</relationshipLabel>
        <relationshipName>OCR_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OCR Response</label>
    <nameField>
        <displayFormat>OCRR-{00000000}</displayFormat>
        <label>OCR Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCR Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_OcrResult__c.object
<CustomObject>
    <description>Stores information regarding the resulting record created for a document after optical character recognition (OCR) has been performed</description>
    <fields>
        <fullName>PC_OcrQueue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCR Queue</label>
        <referenceTo>PC_OcrQueue__c</referenceTo>
        <relationshipLabel>OCR Results</relationshipLabel>
        <relationshipName>OCR_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_OcrResponse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCR Response</label>
        <referenceTo>PC_OcrResponse__c</referenceTo>
        <relationshipLabel>OCR Results</relationshipLabel>
        <relationshipName>OCR_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OCR Result</label>
    <nameField>
        <displayFormat>OR-{00000000}</displayFormat>
        <label>OCR Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCR Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_OcrTemplateMapping__c.object
<CustomObject>
    <description>Map the fields of the incoming form/attachment to the equivalent fields in the appropriate Salesforce data object</description>
    <fields>
        <fullName>PC_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the mapping is active (true) or not (false)</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_OcrTemplateType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>OCR Template Type</label>
        <referenceTo>PC_OcrTemplateType__c</referenceTo>
        <relationshipLabel>OCR Template Mappings</relationshipLabel>
        <relationshipName>OCR_Template_Mappings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>OCR Template Mapping</label>
    <nameField>
        <label>OCR Template Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Template Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_OcrTemplateType__c.object
<CustomObject>
    <description>It holds different types of Templates of a document supported for OCR</description>
    <fields>
        <fullName>PC_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this record is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>OCR Template Type</label>
    <nameField>
        <label>OCR Template Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Template Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PC_OcrReviewDocumentController.cls
/**
 * Created by sathekumar on 10/10/2021.
 */

public with sharing class PC_OcrReviewDocumentController {
    /**
     * Method helps to check the document extension is valid for OCR
     * @param documentId Id of the document
     */
    @AuraEnabled
    public static void validateDocument(String documentId) {
        String extension;
        Boolean isValid;
        try {
            extension = getDocumentExtension(documentId);
            if (String.isNotBlank(extension)) {
                isValid = isExtensionValidForOCR(extension.toLowerCase());
                if (!isValid) {
                    throw new AuraHandledException(System.label.PC_InvalidDocumentTypeMessage);
                }
            } else {
                throw new AuraHandledException(System.label.PC_NoFilesFoundMessage);
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);

        }
    }

    /*******************************************************************
    Method Name    : validateDocument
    Description    : method used to validate the OCR document
    Return Type    : void
    Parameter      : String (documentId)
    *******************************************************************/
    public static String getDocumentExtension(String documentId) {
        String extension;
        Boolean useSalesforceFiles = PC_SYSTEM.useSalesforceFiles();
        Boolean useFileStrictMode = PC_SYSTEM.useDocumentPreviewInStrictMode();

        //FLS Check Attachment
        List<String> attachmentFields = new List<String>{'Id', 'Name'};
        PC_Database.assertAccess('Attachment', PC_Database.Operation.Reading, attachmentFields);
        List<Attachment> lstAttachment = [SELECT Id, Name FROM Attachment WHERE ParentId = :documentId order by createdDate desc LIMIT 1];

        //FLS Check ContentDocumentLink
        List<String> cdlFields = new List<String>{'ContentDocumentId', 'ContentDocument.ContentModifiedDate', 'LinkedEntityId'};
        PC_Database.assertAccess('ContentDocumentLink', PC_Database.Operation.Reading, cdlFields);
        List<ContentDocumentLink> lstContentDocumentLink = [SELECT ContentDocumentId,ContentDocument.ContentModifiedDate FROM ContentDocumentLink WHERE LinkedEntityId = :documentId order by ContentDocument.ContentModifiedDate desc LIMIT 1];

        if ((useSalesforceFiles && lstContentDocumentLink.size() > 0) || (useSalesforceFiles && useFileStrictMode && lstContentDocumentLink.size() > 0) ||
                ((!useFileStrictMode && !useSalesforceFiles) && (lstContentDocumentLink.size() > 0 && lstAttachment.size() == 0))) {
            String contentDocumentId = lstContentDocumentLink[0].ContentDocumentId;
            if (String.isNotBlank(contentDocumentId)) {
                //FLS Check
                List<String> cvFields = new List<String>{'Id', 'FileExtension', 'FileType', 'ContentDocumentId'};
                PC_Database.assertAccess('ContentVersion', PC_Database.Operation.Reading, cvFields);
                extension = [SELECT Id, FileExtension, FileType, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId = :contentDocumentId AND IsLatest = true LIMIT 1] ?.FileExtension;
            }
        } else {
            if(lstAttachment.size() > 0){
                String attName = lstAttachment[0].Name;
                if (String.isNotBlank(attName)) {
                    List<String> parts = (attName.toLowerCase()).splitByCharacterType();
                    extension = parts[parts.size() - 1];
                }
            }
        }
        return extension;
    }

    /********************************************************************
    Method Name    : isExtensionValidForOCR
    Description    : Return true if the extension is valid for OCR Process
    Return Type    : Boolean
    Parameter      : extension
    *********************************************************************/
    public static Boolean isExtensionValidForOCR(String extension) {
        //set<String> setExtAllowed = new set<String>{'jpg', 'jpeg', 'png', 'pdf'};
        List<String> setExtAllowed = getSupportedFileTypes();
        if (setExtAllowed.contains(extension)) {
            return true;
        }
        return false;
    }

    /**
     * This method returns the Supported File Types for the OCR to Process
     */
    public static List<String> getSupportedFileTypes() {
        List<String> supportedFileTypes = new List<String>();
        String useOCR = PC_Constants.EMPTY_STRING;
        try {
            useOCR = PC_SYSTEM.getPatientConnectSetting('PC_UseOCR', PC_Constants.FALSE_STRING);
            if (Boolean.valueOf(useOCR)) {
                String ocrService = PC_SYSTEM.getPatientConnectSetting(PC_Constants.PC_OCR_SERVICE_PROVIDER, PC_Constants.PC_OCR_SERVICE_AMAZON_TEXTRACT);
                if (Test.isRunningTest()) {
                    ocrService = PC_Constants.PC_OCR_SERVICE_AMAZON_TEXTRACT;
                }
                if (String.isNotBlank(ocrService)) {
                    if (ocrService.equalsIgnoreCase(PC_Constants.PC_OCR_SERVICE_AMAZON_TEXTRACT)) {
                        PC_OCR.ExtractDocument handler = PC_OCR.getExtractService(PC_Constants.PC_DEFAULT_TEXTRACT_OCRSERVICE_CLASSNAME);
                        supportedFileTypes = handler.getSupportedFileTypes();
                    } else {
                        PC_OCR.ExtractDocument handler = PC_OCR.getExtractService(PC_Constants.EMPTY_STRING);
                        supportedFileTypes = handler.getSupportedFileTypes();
                    }
                } else {
                    throw new AuraHandledException(System.label.PC_OcrServiceNotConfigured);
                }
            } else {
                throw new AuraHandledException(System.label.PC_OcrFeatureNotEnabled);
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return supportedFileTypes;
    }

    @AuraEnabled
    public static DocumentInfo getDocumentInfo(String documentId, String templateCategoriesString) {
        DocumentInfo documentInfo = new DocumentInfo();
        List<String> templateCategories = (List<String>) JSON.deserialize(templateCategoriesString, List<String>.class);
        String templateTypeId = PC_Constants.EMPTY_STRING;
        system.debug('templateCategories-->'+templateCategories);
        try {
            //FLS Check Document
            List<String> documentFields = new List<String>{PC_Constants.getQualifiedAPIName('PC_Document_Name__c'), PC_Constants.getQualifiedAPIName('PC_Engagement_Program__c'), PC_Constants.getQualifiedAPIName('PC_EngagementProgramCode__c'), PC_Constants.getQualifiedAPIName('PC_Document_Category__c')};
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Document__c'), PC_Database.Operation.Reading, documentFields);
            // Document
            List<PC_Document__c> documentList = [
                    SELECT Id, Name, PC_Document_Name__c, PC_Engagement_Program__c, PC_EngagementProgramCode__c, PC_Document_Category__c
                    FROM PC_Document__c
                    WHERE Id = :documentId
            ];
            if(documentList.size() > 0){
                documentInfo.documentObj = documentList[0];
            }

            if (String.isNotBlank(documentId)) {
                // FLS Check PC_OcrQueue__c
                List<String> ocrQueueFields = new List<String>{PC_Constants.getQualifiedAPIName('PC_SourceDocument__c'), PC_Constants.getQualifiedAPIName('PC_Status__c'), PC_Constants.getQualifiedAPIName('PC_IsActive__c')};
                PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_OcrQueue__c'), PC_Database.Operation.Reading, ocrQueueFields);
                List<PC_OcrQueue__c> queueList = [
                        SELECT Id, PC_SourceDocument__c, PC_Status__c, PC_IsActive__c, PC_OcrTemplateType__c, PC_OcrTemplateType__r.Name
                        FROM PC_OcrQueue__c
                        WHERE PC_SourceDocument__c = :documentId
                        ORDER BY LastModifiedDate DESC
                        LIMIT 1
                ];
                if (queueList.size() > 0) {
                    documentInfo.ocrQueue = queueList[0];
                    if (String.isNotBlank(queueList[0].PC_OcrTemplateType__c)) {
                        templateTypeId = queueList[0].PC_OcrTemplateType__c;
                        documentInfo.isTemplateTypeIdPreConfigured = PC_Constants.TRUE_BOOLEAN;
                        documentInfo.templateTypeId = templateTypeId;
                        documentInfo.templateTypeName = queueList[0].PC_OcrTemplateType__r.Name;
                    } else {
                        String engagementProgram = documentInfo.documentObj ?.PC_Engagement_Program__c;
                        system.debug('engagementProgram--->' + engagementProgram);
                        if (String.isNotBlank(engagementProgram)) {
                            PC_OcrTemplateSelection.TemplateTypeSetting templateTypeSetting = new PC_OcrTemplateSelection.TemplateTypeSetting();
                            templateTypeSetting = tryAutoPickingTemplateType(engagementProgram, templateCategories); //new List<String>{'Prescription'});
                            if (templateTypeSetting != null) {
                                documentInfo.templateTypeId = templateTypeSetting.value;
                                documentInfo.templateTypeName = templateTypeSetting.label;
                                documentInfo.isTemplateTypeAutoSelected = PC_Constants.TRUE_BOOLEAN;
                                templateTypeId = documentInfo.templateTypeId;
                            }
                        }
                    }

                    // FLS Check PC_OcrResponse__c
                    List<String> ocrResponseFields = new List<String>{PC_Constants.getQualifiedAPIName('PC_OcrQueue__c'), PC_Constants.getQualifiedAPIName('PC_OcrStatus__c'), PC_Constants.getQualifiedAPIName('PC_OcrService__c')};
                    PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_OcrResponse__c'), PC_Database.Operation.Reading, ocrResponseFields);
                    List<PC_OcrResponse__c> ocrResponseList = [
                            SELECT Id, PC_OcrQueue__c, PC_OcrStatus__c, PC_OcrService__c
                            FROM PC_OcrResponse__c
                            WHERE PC_OcrStatus__c = :PC_Constants.PC_OCR_STATUS_SUCCESS and PC_OcrQueue__c = :documentInfo.ocrQueue.Id
                            ORDER BY LastModifiedDate DESC
                            LIMIT 1
                    ];
                    if (ocrResponseList.size() > 0) {
                        documentInfo.ocrResponse = ocrResponseList[0];
                    }

                    // FLS Check PC_OcrResult__c
                    List<String> ocrResultFields = new List<String>{
                            PC_Constants.getQualifiedAPIName('PC_OcrQueue__c'), PC_Constants.getQualifiedAPIName('PC_OcrResponse__c'), PC_Constants.getQualifiedAPIName('PC_ResultingRecordId__c'), PC_Constants.getQualifiedAPIName('PC_ResultStatus__c')
                    };
                    PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_OcrResult__c'), PC_Database.Operation.Reading, ocrResultFields);
                    // PC_OcrResult__c
                    documentInfo.ocrResults = [
                            SELECT Id, PC_OcrQueue__c, PC_OcrResponse__c, PC_ResultingRecordId__c, PC_ResultStatus__c
                            FROM PC_OcrResult__c
                            WHERE PC_ResultStatus__c = :PC_Constants.PC_OCR_STATUS_SUCCESS and PC_OcrQueue__c = :documentInfo.ocrQueue.Id
                    ];

                } else {
                    String engagementProgram = documentInfo.documentObj ?.PC_Engagement_Program__c;
                    system.debug('engagementProgram--->' + engagementProgram);
                    if (String.isNotBlank(engagementProgram)) {
                        PC_OcrTemplateSelection.TemplateTypeSetting templateTypeSetting = new PC_OcrTemplateSelection.TemplateTypeSetting();
                        templateTypeSetting = tryAutoPickingTemplateType(engagementProgram, templateCategories); //new List<String>{'Prescription'});
                        if (templateTypeSetting != null) {
                            documentInfo.templateTypeId = templateTypeSetting.value;
                            documentInfo.templateTypeName = templateTypeSetting.label;
                            documentInfo.isTemplateTypeAutoSelected = PC_Constants.TRUE_BOOLEAN;
                            templateTypeId = documentInfo.templateTypeId;
                        }
                    }
                }

                if (String.isNotBlank(templateTypeId)) {
                    // FLS Check PC_OcrTemplateType__c
                    List<String> ocrTemplateTypeFields = new List<String>{PC_Constants.getQualifiedAPIName('PC_IsActive__c'), PC_Constants.getQualifiedAPIName('PC_Label__c')
                    };
                    PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_OcrTemplateType__c'), PC_Database.Operation.Reading, ocrTemplateTypeFields);
                    // PC_OcrTemplateType__c
                    List<PC_OcrTemplateType__c> templateTypeList = [
                            SELECT Id, Name, PC_IsActive__c, PC_Label__c
                            FROM PC_OcrTemplateType__c
                            WHERE PC_IsActive__c = true and Id = :templateTypeId
                    ];
                    if (templateTypeList.size() > 0) {
                        documentInfo.templateType = templateTypeList[0];
                        // FLS Check PC_OcrTemplateMapping__c
                        List<String> ocrTemplateMappingFields = new List<String>{PC_Constants.getQualifiedAPIName('PC_OcrTemplateType__c'), PC_Constants.getQualifiedAPIName('PC_TargetObject__c'), PC_Constants.getQualifiedAPIName('PC_TargetObjectRecordType__c')};
                        PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_OcrTemplateMapping__c'), PC_Database.Operation.Reading, ocrTemplateMappingFields);
                        documentInfo.ocrTemplateMappings = [SELECT Id, Name, PC_OcrTemplateType__c, PC_TargetObject__c, PC_TargetObjectRecordType__c FROM PC_OcrTemplateMapping__c WHERE PC_IsActive__c = true AND PC_OcrTemplateType__c = :templateTypeId];
                        // Get RecordType Id
                        if ((documentInfo.ocrTemplateMappings).size() > 0 && String.isNotBlank(documentInfo.ocrTemplateMappings[0].PC_TargetObject__c)) {
                            Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(documentInfo.ocrTemplateMappings[0].PC_TargetObject__c);
                            Schema.DescribeSObjectResult describeSObjectResult = sObjectType.getDescribe();
                            if (String.isNotBlank(documentInfo.ocrTemplateMappings[0].PC_TargetObjectRecordType__c)) {
                                Map<String, Id> recordTypeIdMap = PC_OcrResponseHelper.getSObjectRecordTypeMap(documentInfo.ocrTemplateMappings[0].PC_TargetObject__c);
                                documentInfo.targetObjectRecordTypeId = recordTypeIdMap.get(documentInfo.ocrTemplateMappings[0].PC_TargetObjectRecordType__c);
                            } else {
                                List<Schema.RecordTypeInfo> rtInfos = describeSObjectResult.getRecordTypeInfos();
                                for (Schema.RecordTypeInfo rtInfo : rtInfos) {
                                    if (rtInfo.isDefaultRecordTypeMapping()) {
                                        documentInfo.targetObjectRecordTypeId = rtInfo.getRecordTypeId();
                                        break;
                                    }
                                }
                            }
                            documentInfo.targetObjectLabel = describeSObjectResult.getLabel();
                        }
                    }
                }
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return documentInfo;
    }

    @AuraEnabled
    public static OcrDocumentResponse getOcrDocumentFieldsMap(String templateTypeId, String ocrResponseId) {
        OcrDocumentResponse ocrDocumentResponse = new OcrDocumentResponse();
        Map<String, String> fieldValueMap = new Map<String, String> ();
        String extractedValues = PC_Constants.EMPTY_STRING;
        try {
            Map<Id, List<PC_OcrTemplateMapping__c>> ocrTemplateMappingMap = PC_OcrResponseHelper.getOcrTemplateMapping(new Set<Id>{templateTypeId});
            if(String.isNotBlank(ocrResponseId)){
                extractedValues = PC_OcrResponseHelper.parseOcrResponse(ocrResponseId);
            }
            if(ocrTemplateMappingMap.get(templateTypeId) != null && ocrTemplateMappingMap.get(templateTypeId).size() > 0) {
                List<PC_OcrTemplateMapping__c> ocrTemplateMappings = ocrTemplateMappingMap.get(templateTypeId);
                ocrDocumentResponse.ocrTemplateMappings = ocrTemplateMappings;
                // Get RecordType Id
                if (String.isNotBlank(ocrTemplateMappings[0].PC_TargetObject__c)) {
                    Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(ocrTemplateMappings[0].PC_TargetObject__c);
                    Schema.DescribeSObjectResult describeSObjectResult = sObjectType.getDescribe();
                    if (String.isNotBlank(ocrTemplateMappings[0].PC_TargetObjectRecordType__c)) {
                        Map<String, Id> recordTypeIdMap = PC_OcrResponseHelper.getSObjectRecordTypeMap(ocrTemplateMappings[0].PC_TargetObject__c);
                        ocrDocumentResponse.recordTypeId = recordTypeIdMap.get(ocrTemplateMappings[0].PC_TargetObjectRecordType__c);

                        //Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(ocrTemplateMappings[0].PC_TargetObject__c);
                        //Schema.DescribeSObjectResult describeSObjectResult = sObjectType.getDescribe();
                        //ocrDocumentResponse.recordTypeId = describeSObjectResult.getRecordTypeInfosByDeveloperName().get(ocrTemplateMappings[0].PC_TargetObjectRecordType__c).getRecordTypeId();
                    } else {
                        List<Schema.RecordTypeInfo> rtInfos = describeSObjectResult.getRecordTypeInfos();
                        for (Schema.RecordTypeInfo rtInfo : rtInfos) {
                            if (rtInfo.isDefaultRecordTypeMapping()) {
                                ocrDocumentResponse.recordTypeId = rtInfo.getRecordTypeId();
                                break;
                            }
                        }
                    }
                    ocrDocumentResponse.objectLabel = describeSObjectResult.getLabel();
                }
                if(String.isNotBlank(extractedValues)) {
                    fieldValueMap = PC_OcrResponseHelper.createObjectFieldAndResponseMap(extractedValues, ocrTemplateMappings[0].PC_FieldMapping__c);
                    ocrDocumentResponse.fieldValueMap = fieldValueMap;
                }
            } else {
                throw new PC_OcrReviewDocumentException(System.Label.PC_NoActiveTemplateMappingFound);
            }
            return ocrDocumentResponse;
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
            return null;
        }
    }

    public static PC_OcrTemplateSelection.TemplateTypeSetting tryAutoPickingTemplateType(String engProgram, List<String> categoryList){
        List<PC_OcrTemplateSelection.TemplateTypeSetting> templateTypeSettings = new List<PC_OcrTemplateSelection.TemplateTypeSetting>();
        List<String> validCategory = PC_OcrTemplateSelection.checkAndRemoveInvalidCategory(categoryList);
        templateTypeSettings = PC_OcrTemplateSelection.getTemplateTypes(engProgram, validCategory);
        if(templateTypeSettings.size() == 1){
            return templateTypeSettings[0];
        } else {
            return null;
        }
    }

    @AuraEnabled
    public static void createLinkLog(String documentId, String targetRecordId){
        PC_Document_Log__c pcDocumentLog = new PC_Document_Log__c();
        String associationRecordName = PC_Constants.EMPTY_STRING;
        String recordTypeName = PC_Constants.EMPTY_STRING;
        String objectLabel = PC_Constants.EMPTY_STRING;
        String sObjectType = PC_Constants.EMPTY_STRING;
        try {
            Map<String, Schema.SObjectType> sObjectMap = Schema.getGlobalDescribe();
            sObjectType = String.valueOf(Id.valueOf(targetRecordId).getSobjectType());
            objectLabel = sObjectMap.get(sObjectType).getDescribe().getLabel();
            if(sObjectType != PC_Constants.CANDIDATE_PATIENT_OBJECT) {
                if (!isLinkLogExists(documentId, targetRecordId)) {
                    recordTypeName = PC_Utility.getRecordTypeNameByRecordId(targetRecordId);

                    List<sObject> sObj = new List<sObject>();
                    String query = 'Select Id, Name from ' + sObjectType + ' where id = \'' + targetRecordId + '\'';
                    sObj = PC_Database.queryWithAccess(query, false);
                    if (!sObj.isEmpty()) {
                        associationRecordName = (String) sObj[0].get('Name');
                    }
                    pcDocumentLog.PC_Document__c = documentId;
                    pcDocumentLog.PC_Association_Record_ID__c = targetRecordId;
                    pcDocumentLog.PC_Association_Record_Name__c = associationRecordName;
                    pcDocumentLog.PC_Association_Type__c = (String.isNotBlank(recordTypeName)) ? objectLabel + ': ' + recordTypeName : objectLabel;
                    PC_Database.ins(pcDocumentLog);
                }
            } else {
                //FLS Check Document
                List<String> documentFields = new List<String>{PC_Constants.getQualifiedAPIName('PC_Applicant__c')};
                PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Document__c'), PC_Database.Operation.Reading, documentFields);
                // Document
                List<PC_Document__c> documentList = [SELECT Id, PC_Applicant__c FROM PC_Document__c WHERE Id = :documentId AND PC_Applicant__c = null];
                if(documentList.size() > 0){
                    documentList[0].PC_Applicant__c = targetRecordId;
                    PC_Database.upd(documentList[0]);
                }
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
    }

    private static Boolean isLinkLogExists(String documentId, String targetRecordId){
        try {
            //FLS Check PC_Document_Log__c
            List<String> fields = new List<String>{PC_Constants.getQualifiedAPIName('PC_Document_Log__c'), PC_Constants.getQualifiedAPIName('PC_Program__c'), 'LastModifiedBy', 'LastModifiedDate', PC_Constants.getQualifiedAPIName('PC_Association_Record_Id__c'), PC_Constants.getQualifiedAPIName('PC_Association_Type__c'), PC_Constants.getQualifiedAPIName('PC_Association_Record_Name__c'), PC_Constants.getQualifiedAPIName('PC_Document__c')};
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Document_Log__c'), PC_Database.Operation.Reading, fields);

            List<PC_Document_Log__c> lstDocLogs = [
                    SELECT Name, PC_Document_Log__c, PC_Association_Record_Id__c, PC_Association_Type__c, PC_Association_Record_Name__c
                    FROM PC_Document_Log__c
                    WHERE PC_Document__c = :documentId AND PC_Association_Record_Id__c = :targetRecordId
            ];
            if (lstDocLogs.size() > 0) {
                return true;
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return false;
    }

    @AuraEnabled
    public static void completeOcrQueueAndCreateOcrResults(String ocrQueueId, String targetRecordId, String templateTypeId){
        system.debug('Create OCR Results'+templateTypeId);
        try {
            /*FLS Check for OCR Queue fields*/
            List<String> ocrQueueFields = new List<String>{PC_Constants.getQualifiedAPIName('PC_Status__c'), PC_Constants.getQualifiedAPIName('PC_OcrTemplateType__c'), PC_Constants.getQualifiedAPIName('PC_IsActive__c')};
            PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_OcrQueue__c'), PC_Database.Operation.Reading, ocrQueueFields);

            List<PC_OcrQueue__c> ocrQueueList = [Select Id, PC_Status__c, PC_OcrTemplateType__c, PC_IsActive__c FROM PC_OcrQueue__c where Id =:ocrQueueId];
            if (ocrQueueList.size() > 0 && ocrQueueList[0].PC_Status__c != PC_Constants.PC_OCR_QUEUE_STATUS_COMPLETED) {
                createOcrResults(ocrQueueId, targetRecordId);
                ocrQueueList[0].PC_Status__c = PC_Constants.PC_OCR_QUEUE_STATUS_COMPLETED;
                ocrQueueList[0].PC_IsActive__c = PC_Constants.FALSE_BOOLEAN;
                ocrQueueList[0].PC_OcrTemplateType__c = templateTypeId;
                PC_Database.upd(ocrQueueList[0]);
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
    }

    public static List<PC_OcrResult__c> createOcrResults(String ocrQueueId, String targetRecordId) {
        List<PC_OcrResult__c> ocrResults = new List<PC_OcrResult__c>();
        PC_OcrResult__c ocrResult = new PC_OcrResult__c();
        ocrResult.PC_ResultingRecordId__c = targetRecordId;
        ocrResult.PC_ResultStatus__c = 'Success';
        ocrResult.PC_OcrQueue__c = ocrQueueId;
        ocrResults.add(ocrResult);
        PC_Database.ins(ocrResults);
        return ocrResults;
    }

    public inherited sharing class OcrDocumentResponse{
        @AuraEnabled
        public Map<String, String> fieldValueMap;
        @AuraEnabled
        public String recordTypeId;
        @AuraEnabled
        public String objectLabel;
        @AuraEnabled
        public List<PC_OcrTemplateMapping__c> ocrTemplateMappings;

        public OcrDocumentResponse() {
            this.fieldValueMap = new Map<String, String> ();
            this.ocrTemplateMappings = new List<PC_OcrTemplateMapping__c> ();
            this.recordTypeId = PC_Constants.EMPTY_STRING;
            this.objectLabel = PC_Constants.EMPTY_STRING;
        }
    }

    public inherited sharing class DocumentInfo{
        @AuraEnabled
        public PC_Document__c documentObj;
        @AuraEnabled
        public PC_OcrQueue__c ocrQueue;
        @AuraEnabled
        public PC_OcrResponse__c ocrResponse;
        @AuraEnabled
        public PC_OcrTemplateType__c templateType;
        @AuraEnabled
        public String templateTypeId;
        @AuraEnabled
        public String templateTypeName;
        @AuraEnabled
        public Boolean isTemplateTypeIdPreConfigured;
        @AuraEnabled
        public Boolean isTemplateTypeAutoSelected;
        @AuraEnabled
        public String targetObjectRecordTypeId;
        @AuraEnabled
        public String targetObjectLabel;
        @AuraEnabled
        public List<PC_OcrTemplateMapping__c> ocrTemplateMappings;
        @AuraEnabled
        public List<PC_OcrResult__c> ocrResults;

        public DocumentInfo(){
            this.documentObj = new PC_Document__c();
            this.ocrQueue = new PC_OcrQueue__c();
            this.ocrResponse = new PC_OcrResponse__c();
            this.templateType = new PC_OcrTemplateType__c();
            this.templateTypeId = PC_Constants.EMPTY_STRING;
            this.templateTypeName = PC_Constants.EMPTY_STRING;
            this.targetObjectLabel = PC_Constants.EMPTY_STRING;
            this.targetObjectRecordTypeId = PC_Constants.EMPTY_STRING;
            this.isTemplateTypeIdPreConfigured = PC_Constants.FALSE_BOOLEAN;
            this.isTemplateTypeAutoSelected = PC_Constants.FALSE_BOOLEAN;
            this.ocrTemplateMappings = new List<PC_OcrTemplateMapping__c> ();
            this.ocrResults = new List<PC_OcrResult__c> ();
        }
    }

    public inherited sharing class PC_OcrReviewDocumentException extends Exception {}
}