objects/PC_Association__c.object
<CustomObject>
    <description>PatientConnect custom object to manage the patient program&apos;s care team (including physician)</description>
    <label>Association</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_ProgramRegionUserHistory__c.object
<CustomObject>
    <fields>
        <fullName>PC_EngagementProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the Engagement Program of the Program Region User Mapping record for which Associate record is created.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Program Region User Histories</relationshipLabel>
        <relationshipName>PC_ProgramRegionUserHistories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the Region of the Program Region User Mapping record for which Associate record is created.</description>
        <label>Region</label>
        <referenceTo>PC_Region__c</referenceTo>
        <relationshipLabel>Program Region User Histories</relationshipLabel>
        <relationshipName>PC_ProgramRegionUserHistories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Region User History</label>
    <nameField>
        <displayFormat>PRUH{0}</displayFormat>
        <label>Program Region User History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Region User History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PC_ProgramRegionUserMapping__c.object
<CustomObject>
    <description>Program Region User Mapping is a junction object to associate an engagement program to a user and a region.</description>
    <fields>
        <fullName>PC_EngagementProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the engagement program associated to the region.</description>
        <label>Engagement Program</label>
        <referenceTo>PC_Engagement_Program__c</referenceTo>
        <relationshipLabel>Program Region User Mappings</relationshipLabel>
        <relationshipName>ProgRegionUserMapEngagementProg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the region.</description>
        <label>Region</label>
        <referenceTo>PC_Region__c</referenceTo>
        <relationshipLabel>Program Region User Mappings</relationshipLabel>
        <relationshipName>ProgramRegionUserMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Region User Mapping</label>
    <nameField>
        <displayFormat>PTUM{0}</displayFormat>
        <label>Program Region User Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Region User Mappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PC_Region__c.object
<CustomObject>
    <description>Region is a custom object in Patient Connect that represents the details of a region.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PC_WCDDefaultService.cls
/**
 Class Name     : PC_WCDDefaultService
 Author         : Pavankumar
 Description    : This class is used to create Associations for all the 'Program Region Records' received
 User-Story     : PC-8232
 */

public with sharing class PC_WCDDefaultService implements PC_WCD.UserMappingFinder{

/*********************************************************************************************************************************************
Method Name    : createAssociations
Author         : Pavankumar
Description    : This method is used to create Associations for all the 'Program Region Records' received
Return Type    : List<PC_Association__c>
Parameter      : List<PC_ProgramRegionUserMapping__c>, Map<Id, Id>
User-Story     : PC-8232
*********************************************************************************************************************************************/
    public PC_WCD.FindMapperResponse findMapper(PC_WCD.FindMapperRequest request) {
        List<PC_WCD.programRegionUsersMappingByEngagementPrograms> programRegionUsersMappingByEngagementProgramsClass = new List<PC_WCD.programRegionUsersMappingByEngagementPrograms>();
        List<PC_WCD.programRegionUsersHistoryMappingByEngagementPrograms> programRegionUsersHistoryMappingByEngagementProgramsClass = new List<PC_WCD.programRegionUsersHistoryMappingByEngagementPrograms>();
        Map<Id, PC_WCD.caseDetails> caseRecordIdMappingWithCaseDetails = new Map<Id, PC_WCD.caseDetails>();
        Map<Id, List<PC_ProgramRegionUserMapping__c>> ProgramRegionMappingWithEngagement = new Map<Id, List<PC_ProgramRegionUserMapping__c>>();
        Map<Id, List<PC_ProgramRegionUserHistory__c>> programRegionUsersHistoryMappingByEngagement = new Map<Id, List<PC_ProgramRegionUserHistory__c>>();
        Map<Id, List<PC_ProgramRegionUserMapping__c>> caseMappingWithRequiredProgramRegionUserMappingRecords = new Map<Id, List<PC_ProgramRegionUserMapping__c>>();
        Set<Id> regionIdSet = new Set<Id>();
        programRegionUsersMappingByEngagementProgramsClass = request.programRegionUsersMappingByEngPrograms;
        programRegionUsersHistoryMappingByEngagementProgramsClass = request.programRegionUsersHistoryMappingByEngPrograms;
        caseRecordIdMappingWithCaseDetails = request.caseIdMapWithCaseDetails;
        for (PC_WCD.programRegionUsersMappingByEngagementPrograms classRecord : programRegionUsersMappingByEngagementProgramsClass) {
            ProgramRegionMappingWithEngagement.put(classRecord.engagementProgram, classRecord.programRegionUserMappingsByRoles) ;
        }
        for (PC_WCD.programRegionUsersHistoryMappingByEngagementPrograms historyClassRecord : programRegionUsersHistoryMappingByEngagementProgramsClass) {
            programRegionUsersHistoryMappingByEngagement.put(historyClassRecord.engagementProgramId, historyClassRecord.programRegionUserHistoryRecords);
        }

        for(Id caserecordId : caseRecordIdMappingWithCaseDetails.keySet()){
            Set<PC_ProgramRegionUserMapping__c> programRegionUserMappingsSet = new Set<PC_ProgramRegionUserMapping__c>();
            regionIdSet = caseRecordIdMappingWithCaseDetails.get(caserecordId).regionSetId;
            for(Id regionId:regionIdSet){
                List<PC_ProgramRegionUserMapping__c> programRegionsList = new List<PC_ProgramRegionUserMapping__c>();
                for (PC_ProgramRegionUserMapping__c programregionrecord : ProgramRegionMappingWithEngagement.get(caseRecordIdMappingWithCaseDetails.get(caserecordId).engagementProgramId)) {
                    if (programregionrecord.PC_EngagementProgram__c == caseRecordIdMappingWithCaseDetails.get(caserecordId).engagementProgramId && programregionrecord.PC_Region__c == regionId) {
                        programRegionsList.add(programregionrecord);
                    }
                }
                programRegionUserMappingsSet.addAll(programRegionsList);
            }
            system.debug('programRegionUserMappingsSet is '+programRegionUserMappingsSet);
            if(caseMappingWithRequiredProgramRegionUserMappingRecords.keySet().contains(caserecordId)){
                List<PC_ProgramRegionUserMapping__c> programRegionUserMappingsList = caseMappingWithRequiredProgramRegionUserMappingRecords.get(caserecordId);
                programRegionUserMappingsList.addAll(programRegionUserMappingsSet);
                caseMappingWithRequiredProgramRegionUserMappingRecords.put(caserecordId, programRegionUserMappingsList);
            }else{
                List<PC_ProgramRegionUserMapping__c> listOfProgramRegionUserMappings = new List<PC_ProgramRegionUserMapping__c>();
                listOfProgramRegionUserMappings.addAll(programRegionUserMappingsSet);
                caseMappingWithRequiredProgramRegionUserMappingRecords.put(caserecordId, listOfProgramRegionUserMappings);
            }
        }

        system.debug('caseMappingWithRequiredProgramRegionUserMappingRecords is '+caseMappingWithRequiredProgramRegionUserMappingRecords);
        PC_WCD.FindMapperResponse pcd = new PC_WCD.FindMapperResponse();
        pcd.programRegionUserMappingsByCase = caseMappingWithRequiredProgramRegionUserMappingRecords;
        return pcd;
    }

}