objects/PC_AdverseEvent__c.object
<CustomObject>
    <description>The Adverse Event is a custom object in Patient Connect that represents the adverse events reported for the patients enrolled into the patient services program.</description>
    <fields>
        <fullName>PC_Patient__c</fullName>
        <description>Patient account with which the adverse event is associated.</description>
        <label>Patient</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Adverse Events</relationshipLabel>
        <relationshipName>Adverse_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Adverse Event</label>
    <nameField>
        <displayFormat>AE-{00000000}</displayFormat>
        <label>Adverse Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adverse Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PC_Test_Trigger_AdverseEvent.cls
/*********************************************************************************************************
Class Name      : PC_Test_Trigger_AdverseEvent
Description     : Tests PC_Trigger_AdverseEvent.
Created By      : Kanteti Kishore
Created Date    : August 07, 2019
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer                   Date                     Description
--------------------------------------------------------------------------------------------------------------
Kanteti Kishore        August 07, 2019               Initial version
****************************************************************************************************************/
@isTest
public class PC_Test_Trigger_AdverseEvent{


/*********************************************************************************
    Method Name    : testAdvEvtPatient
    Author         : Kishore Kanteti
    Description    : This method populates patient name for person account associated before person account record is created.
    Return Type    : void
    Parameter      :
*********************************************************************************/
    @isTest public static void testAdvEvtPatient() {
        Account testAcc = PC_Test_Setup.createTestAccount(PC_Constants.MANUFACTURER_RECORD_TYPE);
        /* Account testAcc = new Account();
         testAcc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(PC_Constants.PATIENT_RECORD_TYPE).getRecordTypeId();
         testAcc.Name = 'ACCOUNT_NAME';*/
        PC_Database.ins(testAcc);

        Test.startTest();
        PC_AdverseEvent__c advEvt = new PC_AdverseEvent__c(PC_Patient__c = testAcc.Id);
        PC_Database.ins(advEvt);
        Test.stopTest();
    }

}