objects/PC_CaseProduct__c.object
<CustomObject>
    <description>Holds the products associated to a specific case.</description>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_SupportPlan__c.object
<CustomObject>
    <description>Custom object in Patient Connect that helps to create a predefined template of activities (tasks and events) according to the type of case and the brands that are supported.</description>
    <fields>
        <fullName>PC_SupportPlan_Behavior__c</fullName>
        <description>This describes the behavior of the Support Plan. Note - If the value is blank, then the behavior is assumed to be &apos;RunEveryTimeRuleMatches&apos; by default.</description>
        <inlineHelpText>Would you like to run this Support Plan every time the conditions are met for a record?</inlineHelpText>
        <label>Support Plan Runtime Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RunEveryTimeRuleMatches</fullName>
                    <default>true</default>
                    <label>Yes, run this Support Plan every time the conditions are met.</label>
                </value>
                <value>
                    <fullName>RunOncePerRecord</fullName>
                    <label>No, run this Support Plan only once per record.</label>
                </value>
                <value>
                    <fullName>RunEveryTimeIfNoPendingRuntime</fullName>
                    <label>No, run this Support Plan only when there are no pending activities from previous Support Plan Runtime(s).</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_TriggerEventObject__c</fullName>
        <description>API Name of Object on which  Support plan is Run</description>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Support Plan</label>
    <nameField>
        <label>Support Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PC_SPPharmacyBIController.cls
/**************************************************************************************************************************************************************************
Class Name      : PC_SPPharmacyBIController
Description     : This is the SP Automation Task Component Controller For Pharmacy BI.
Created By      : Satheesh Kumar & Chetna Mohapatra
Created Date    : 25-Feb-2022
Modification Log:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Developer                   Date                  Description
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Chetna Mohapatra
& Satheesh Kumar        25-Feb-2022             Initial Version
Satheesh Kumar          12-Oct-2022             [PC-9262] Added condition to avoid removing namespace prefix from sObject when sobject contains no namespace.
 **********************************************************************************************************************************************************************/
public with sharing class PC_SPPharmacyBIController {
    static final List<String> PHARMACY_BI_SUPPORTED_OBJECT = new List<String>{'CASE', 'ACCOUNT','PC_CASEPRODUCT__C'};

    @AuraEnabled
    public static PharmacyBenefitsInfo getPharmacyInfo(String supportPlanId){
        PharmacyBenefitsInfo pharmacyBenefitsInfo = new PharmacyBenefitsInfo();
        try{
            // FLS Check for Support Plan
            List<String> supportPlanFields = new List<String>{ PC_Constants.getQualifiedAPIName('PC_TriggerEventObject__c'), PC_Constants.getQualifiedAPIName('PC_SupportPlan_Behavior__c') };
            PC_Database.assertAccess(PC_Constants.PC_SUPPORT_PLAN, PC_Database.Operation.Reading, supportPlanFields);

            PC_SupportPlan__c supportPlan = [SELECT Id, PC_TriggerEventObject__c, PC_SupportPlan_Behavior__c FROM PC_SupportPlan__c WHERE Id = :supportPlanId][0];
            String triggerEventObjectName = supportPlan.PC_TriggerEventObject__c;
            //remove namespace prefix from triggerEventObjectName when triggerEventObjectName contains namespace
            triggerEventObjectName = triggerEventObjectName.contains('__') ? (triggerEventObjectName.countMatches('__') == 2 ? triggerEventObjectName.substringAfter('__') : triggerEventObjectName): triggerEventObjectName;

            if (String.isNotBlank(triggerEventObjectName) && PHARMACY_BI_SUPPORTED_OBJECT.contains(triggerEventObjectName.toUpperCase())) {
                pharmacyBenefitsInfo.isValidTriggerEventObject = PC_Constants.TRUE_BOOLEAN;
            } else {
                pharmacyBenefitsInfo.isValidTriggerEventObject = PC_Constants.FALSE_BOOLEAN;
                pharmacyBenefitsInfo.notSupportErrorMessage = String.format(System.Label.PC_SPPharmacyeBIUnsupportedErrorMessage, new List<Object>{triggerEventObjectName, String.join( PHARMACY_BI_SUPPORTED_OBJECT, ', ' )});
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
        return pharmacyBenefitsInfo;
    }

    public inherited sharing class PharmacyBenefitsInfo {
        @AuraEnabled
        public Boolean isValidTriggerEventObject { get; set; }
        @AuraEnabled
        public String notSupportErrorMessage { get; set; }
        public PharmacyBenefitsInfo() {
            isValidTriggerEventObject = PC_Constants.FALSE_BOOLEAN;
            notSupportErrorMessage = PC_Constants.EMPTY_STRING;
        }
    }
}