objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document_Action_Setting__mdt.object
<CustomObject>
    <description>Custom metadata to configure actions to be performed on each document</description>
    <fields>
        <fullName>PC_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Custom metadata field to capture if action icon is activated</description>
        <inlineHelpText>Icon will be displayed only if this field is checked</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Component__c</fullName>
        <description>Custom metadata field to store API name of component that needs to be launched for the action</description>
        <inlineHelpText>API name of component that needs to be launched on clicking action icon</inlineHelpText>
        <label>Component</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Document_Record_Type__c</fullName>
        <description>Custom metadata field to capture which document record type (API name of document record type) should the action be applicable for. Leave blank if action applies to all record types.</description>
        <inlineHelpText>API name of document record type to which the action should be associated with. To apply icon for all record types, use keyword &apos;ALL&apos; without single quotes. For example: ALL</inlineHelpText>
        <label>Document Record Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Icon__c</fullName>
        <description>Custom metadata field to capture icon to be displayed on Document Action Ribbon</description>
        <inlineHelpText>Name of the Lightning Icon. Refer Icons section on Salesforce Lightning Design System. 
Sample Input:  standard-account</inlineHelpText>
        <label>Icon</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Label__c</fullName>
        <description>Label of the Document Action Icon that will visible on the document action center. You may also specify the fully qualified custom label path ($Label.namespace.labelName).</description>
        <inlineHelpText>Label of the Document Action Icon that will visible on the document action center. You may also specify the fully qualified custom label path ($Label.namespace.labelName).</inlineHelpText>
        <label>Icon Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Ordinal__c</fullName>
        <description>Custom metadata field to capture order in which action icon should display on Document Action Ribbon</description>
        <inlineHelpText>Numeric order in which icon should be displayed left to right. 1 indicates left most.</inlineHelpText>
        <label>Ordinal</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document Action Setting</label>
    <pluralLabel>Document Action Settings</pluralLabel>
</CustomObject>

classes/PC_ChangeDocOwnerLightningController.cls
public class PC_ChangeDocOwnerLightningController {
    @AuraEnabled
    public static PC_Document__c getDocDetails(Id docId) {
        PC_Document__c selectedDoc = new PC_Document__c();
        //FLS Check on PC_Document__c
        List<String> fields = new List<String>{'Name', 'RecordTypeId'};
        PC_Database.assertAccess(PC_Constants.getQualifiedAPIName('PC_Document__c'), PC_Database.Operation.Reading, fields);
        
        selectedDoc = [SELECT Name, RecordType.DeveloperName FROM PC_Document__c WHERE ID =: docId];
        return selectedDoc;
    }
    
    @AuraEnabled
    public static LIST<ActionIconsWrapper> setupActionIcons(Id docId) {
        PC_Document__c selectedDoc = getDocDetails(docId);
       	LIST<PC_Document_Action_Setting__mdt> actionIconMetaData = [SELECT PC_Active__c, PC_Component__c, PC_Icon__c, PC_Document_Record_Type__c,
                                                                    PC_Label__c, PC_Ordinal__c FROM PC_Document_Action_Setting__mdt
                                                                  	WHERE PC_Active__c =: TRUE AND PC_Document_Record_Type__c =: selectedDoc.RecordType.DeveloperName
                                                                   	ORDER BY PC_Ordinal__c ];
        
        LIST<ActionIconsWrapper> actionIconsWrapper	= 	NEW LIST<ActionIconsWrapper>();
        
        FOR(PC_Document_Action_Setting__mdt a : actionIconMetaData){
            actionIconsWrapper.add(new ActionIconsWrapper(a));
        }
        System.debug('@@actionIconsWrapper :' + actionIconsWrapper);
        RETURN actionIconsWrapper;
    }
    
    /**
	* Wrapper for the action icons setup. Includes all information needed to initialize the
	* action icons.
	*/
    public class ActionIconsWrapper {
        @AuraEnabled public Boolean iconActive {get; set;}
        @AuraEnabled public String 	iconActionComponent {get; set;}
        @AuraEnabled public String 	iconDocRecordType {get; set;}
        @AuraEnabled public String 	iconImage {get; set;}
        @AuraEnabled public String 	iconLabel {get; set;}
        @AuraEnabled public Decimal iconOrdinal {get; set;}
        @AuraEnabled public Boolean iconVisibility {get; set;}
        
        public ActionIconsWrapper() {}
        
        public ActionIconsWrapper(PC_Document_Action_Setting__mdt a) {
        	iconActive 			= a.PC_Active__c;
            iconActionComponent = a.PC_Component__c;
            iconDocRecordType 	= a.PC_Document_Record_Type__c;
            iconImage 			= a.PC_Icon__c;
            iconLabel 			= a.PC_Label__c;  
            iconOrdinal 		= a.PC_Ordinal__c;
            iconVisibility 		= True;
        }
    }
    
}