objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_Document_Category__c</fullName>
        <description>The Category that the document may fall into.
Note: A document can be associated with multiple categories.</description>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>PC_EngagementProgramCode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Enrollment Form</fullName>
                </value>
                <value>
                    <fullName>Patient Consent</fullName>
                </value>
                <value>
                    <fullName>Patient Information Update</fullName>
                </value>
                <value>
                    <fullName>Insurance Information</fullName>
                </value>
                <value>
                    <fullName>Prescription</fullName>
                </value>
                <value>
                    <fullName>Copay Information</fullName>
                </value>
                <value>
                    <fullName>PA Documentation</fullName>
                </value>
                <value>
                    <fullName>Appeals Documentation</fullName>
                </value>
                <value>
                    <fullName>Post Infusion Report</fullName>
                </value>
                <value>
                    <fullName>Post Training Report</fullName>
                </value>
                <value>
                    <fullName>Test Results</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Illegible Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <description>General Document or Attachment</description>
        <label>Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PC_Test_InboundFaxLightningController.cls
/**************************************************************************************
Apex Class Name     : PC_Test_InboundFaxLightningController
Description         : This class is used for testing PC_DocInboundFaxLightningController;
CreatedBy           : Deloitte
Created Date        : 16 June 2016
Modification Log    :
-------------------------------------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------                 
Alina Balan                 16 June 2016           Initial version
*************************************************************************************/
@isTest(seeAllData=False) 
public with sharing class PC_Test_InboundFaxLightningController {
    private static User objUser;
    private static User objUser2;
    private static PC_Document__c oDoc;
    private static Attachment oAttachment;
    private static final String DOC_CATEGORY = 'Enrollment Form';
    //private static final String DOC_CATEGORY_PRESCRIPTION = 'Prescription';
    
    /*********************************************************************************
    Method Name    : createTestData
    Author         : Alina Balan
    Description    : This method is used for creating test data
    Return Type    : void 
    Parameter      : 
    *********************************************************************************/
    private static void createTestData() {
        objUser = PC_Test_Setup.createUser(PC_Test_Setup.CALL_CENTER_AGENT_PROFILE, 'user@test80.com', 'test80');
        PC_Database.ins(objUser);
        objUser2 = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, 'user@test79.com', 'test79');
        PC_Database.ins( objUser2);
        createObjects();
    }
    
    /*********************************************************************************
    Method Name    : createDoc
    Author         : Alina Balan
    Description    : This method is used for creating a document with attachments
    Return Type    : void 
    Parameter      : 
    *********************************************************************************/
    private static void createObjects() {
        system.runAs(objUser2) {
            oDoc = PC_Test_Setup.createDocument(PC_Constants.DOCUMENT_FAX_INBOUND_RECORD_TYPE, PC_Constants.DOCUMENT_STATUS_NEW);
            Id recordTypeId = PC_SYSTEM.recordTypeId(PC_Constants.DOCUMENT_OBJECT, PC_Constants.DOCUMENT_FAX_INBOUND_RECORD_TYPE);
            oDoc.PC_Document_Category__c = DOC_CATEGORY;
            oDoc.RecordTypeId = recordTypeId;
            PC_Database.ins(oDoc);
            oAttachment = PC_Test_Setup.createAttachment(oDoc.Id);
            PC_Database.ins(oAttachment);
        }
    }
    
    /*********************************************************************************
    Method Name    : testgetAttachmentId
    Author         : Alina Balan
    Description    : This method is used for testing "getAttachmentId"
    Return Type    : void 
    Parameter      : 
    *********************************************************************************/
    @isTest static void testgetAttachmentId(){
        createTestData();
        system.runAs(objUser2) {
            Test.StartTest();
            PC_DocumentInboundFaxLightningController.FaxDetailsWrapper faxWrapper = PC_DocumentInboundFaxLightningController.getAttachmentId(oDoc.Id + '');
            system.assertNotEquals(faxWrapper.attachmentId, null);
            Test.StopTest();
         }
     }
}