objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <fields>
        <fullName>PC_Document_Category__c</fullName>
        <description>The Category that the document may fall into.
Note: A document can be associated with multiple categories.</description>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>PC_EngagementProgramCode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Enrollment Form</fullName>
                </value>
                <value>
                    <fullName>Patient Consent</fullName>
                </value>
                <value>
                    <fullName>Patient Information Update</fullName>
                </value>
                <value>
                    <fullName>Insurance Information</fullName>
                </value>
                <value>
                    <fullName>Prescription</fullName>
                </value>
                <value>
                    <fullName>Copay Information</fullName>
                </value>
                <value>
                    <fullName>PA Documentation</fullName>
                </value>
                <value>
                    <fullName>Appeals Documentation</fullName>
                </value>
                <value>
                    <fullName>Post Infusion Report</fullName>
                </value>
                <value>
                    <fullName>Post Training Report</fullName>
                </value>
                <value>
                    <fullName>Test Results</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Illegible Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <description>General Document or Attachment</description>
        <label>Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ACLS_DocumentValidator.cls
/*********************************************************************************************************
Class Name      : ACLS_DocumentValidator
Description     : This class demonstrates how a Document Action’s visibility and 
accessibility can be shown/hidden conditionally depending on the values 
of the Document’s Categories.  
Created By      : Deloitte
Created Date    : Jan 18, 2023
****************************************************************************************************************
Version History :
Date			  Developer 			  User Story					     Changes
Jan 18, 2023	  Deloitte				   US-137				             Initial Version
*****************************************************************************************************************/

global with sharing class ACLS_DocumentValidator implements PC_ActionValidator.Validator { 
    global static Boolean isVisible(PC_ActionValidator.Params validationParams) { 
        PC_Document__c selectedDoc = getDocDetails(validationParams.recordId);  
        Boolean isVisible = false;  
        // In the condition below, it is decided whether to show the document action or not depending on the document tag value
        if ((selectedDoc.PC_Document_Category__c != null) && (selectedDoc.PC_Document_Category__c.contains('Enrollment Form'))) 
            isVisible = true; 
        return isVisible; 
    } 
    global static PC_ActionValidator.AccessibilityResponse isAccessible(PC_ActionValidator.Params validationParams) 
    { 
        PC_ActionValidator.AccessibilityResponse vdw = new PC_ActionValidator.AccessibilityResponse(); 
        PC_Document__c selectedDoc = getDocDetails(validationParams.recordId); 
        vdw.isAccessible = false; 
        // In the condition below, it is decided whether to allow the click action on document action or not depending on the document tag value 
        if((selectedDoc.PC_Document_Category__c != null) && (selectedDoc.PC_Document_Category__c.contains('Enrollment'))) 
        { 
            vdw.isAccessible = true; 
            vdw.message = 'This action is not accessible if document contains Enrollment'; //This message is shown to the end user. 
        } 
        return vdw; 
    } 
    global static PC_Document__c getDocDetails(String docId) { 
        PC_Document__c selectedDoc = new PC_Document__c ();  

        if(Schema.sObjectType.PC_Document__c.isAccessible()){
            selectedDoc = [SELECT Name, RecordType.DeveloperName, RecordType.NamespacePrefix,PC_Document_Category__c FROM 
                       PC_Document__c WHERE ID =: docId]; 
        }

        return selectedDoc; 
    } 
}