objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <description>General Document or Attachment</description>
        <label>Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_OcrTemplateType__c.object
<CustomObject>
    <description>It holds different types of Templates of a document supported for OCR</description>
    <fields>
        <fullName>PC_APIName__c</fullName>
        <description>API Name of the OCR template type</description>
        <externalId>true</externalId>
        <inlineHelpText>The API Name must be unique. The name must begin with a letter, and use only alphanumeric characters and underscores. The name cannot end with an underscore or have two consecutive underscores.</inlineHelpText>
        <label>API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PC_CreateResultsAfterOCRCompletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether to create resultant record post OCR completion or not.</description>
        <inlineHelpText>Specifies whether to create resultant record post OCR completion or not.</inlineHelpText>
        <label>Create results post OCR completion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this record is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Label__c</fullName>
        <description>Label of the template</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OCR Template Type</label>
    <nameField>
        <label>OCR Template Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Template Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_SupportPlan__c.object
<CustomObject>
    <description>Custom object in Patient Connect that helps to create a predefined template of activities (tasks and events) according to the type of case and the brands that are supported.</description>
    <fields>
        <fullName>PC_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Support Plan is active.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_TriggerEventObject__c</fullName>
        <description>API Name of Object on which  Support plan is Run</description>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Support Plan</label>
    <nameField>
        <label>Support Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PC_Test_QueueDocumentForOCRController.cls
/**
 * Created by sathekumar on 10/25/2021.
 */

@IsTest
private class PC_Test_QueueDocumentForOCRController {

    private static User objUser;
    private static PC_SupportPlan__c oSupPlan;
    private static final String USER_ALIAS = 'ocrUser1';
    private static final String USER_EMAIL = 'ocruser1@test.com';
    private static final String OCR_TEMPLATE_TYPE_NAME = 'test_QueueDocumentForOCR_TemplateType1';
    private static final String OCR_TEMPLATE_TYPE2_NAME = 'test_QueueDocumentForOCR_TemplateType2';

    @testSetup static void createTestData(){
        //Insert User
        objUser = PC_Test_Setup.createUser(PC_Test_Setup.SYS_ADMIN_PROFILE, USER_EMAIL, USER_ALIAS);
        objUser = (User) PC_Database.ins(objUser);
        system.runAs(objUser){
            //Create template type
            PC_OcrTemplateType__c ocrTemplateTypeObj = new PC_OcrTemplateType__c();
            ocrTemplateTypeObj.Name = OCR_TEMPLATE_TYPE_NAME;
            ocrTemplateTypeObj.PC_Label__c = OCR_TEMPLATE_TYPE_NAME;
            ocrTemplateTypeObj.PC_APIName__c = OCR_TEMPLATE_TYPE_NAME;
            ocrTemplateTypeObj.PC_IsActive__c = PC_Constants.TRUE_BOOLEAN;
            ocrTemplateTypeObj.PC_CreateResultsAfterOCRCompletion__c = PC_Constants.TRUE_BOOLEAN;
            PC_Database.ins(ocrTemplateTypeObj, false);

            //Create template type 2
            PC_OcrTemplateType__c ocrTemplateTypeObj2 = new PC_OcrTemplateType__c();
            ocrTemplateTypeObj2.Name = OCR_TEMPLATE_TYPE2_NAME;
            ocrTemplateTypeObj2.PC_Label__c = OCR_TEMPLATE_TYPE2_NAME;
            ocrTemplateTypeObj2.PC_APIName__c = OCR_TEMPLATE_TYPE2_NAME;
            ocrTemplateTypeObj2.PC_IsActive__c = PC_Constants.TRUE_BOOLEAN;
            PC_Database.ins(ocrTemplateTypeObj2, false);

            //Create Support Plan for Object Document
            oSupPlan = PC_Test_Setup.createSupportPlan();
            oSupPlan.PC_TriggerEventObject__c = PC_Constants.getQualifiedAPIName('PC_Document__c');
            PC_Database.ins(oSupPlan, false);
        }

    }

    @isTest static void testGetOcrTemplateOptions() {
        objUser = [Select Id from User where Alias =: USER_ALIAS];
        PC_QueueDocumentForOCRController.OcrTemplateOptions templateOptions = new PC_QueueDocumentForOCRController.OcrTemplateOptions();
        system.runAs(objUser){
            Test.startTest();
            PC_SupportPlan__c supportPlan = [SELECT Id, PC_TriggerEventObject__c FROM PC_SupportPlan__c LIMIT 1];
            try {
                System.assertEquals(2, (PC_QueueDocumentForOCRController.getOcrTemplateOptions(supportPlan.Id)).templateTypeSettingList.size());
            } catch (Exception e) {
                System.assertNotEquals(null, e, 'Exception should be thrown');
            }
            Test.stopTest();
        }
    }
}