objects/PC_Document__c.object
<CustomObject>
    <description>PatientConnect custom object to manage documents</description>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{00000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_Document_Log__c.object
<CustomObject>
    <description>Patient Connect custom object:  used to link the custom Document object records to various objects</description>
    <fields>
        <fullName>PC_Association_Record_Id__c</fullName>
        <description>The record ID for the corresponding association.</description>
        <label>Association Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Association_Record_Name__c</fullName>
        <label>Association Record Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Association_Type__c</fullName>
        <description>The type of association (for example, Program, Health Plan, and Coverage).</description>
        <label>Association Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Document_Log__c</fullName>
        <description>A description about the log information modification.</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PC_Document__c</fullName>
        <description>Look up to Document that is created.</description>
        <label>Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Document Log</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Document Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PC_OcrQueue__c.object
<CustomObject>
    <description>Stores information regarding document queued for the OCR service</description>
    <fields>
        <fullName>PC_SourceDocument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of the PC Document which queued for OCR.</description>
        <label>Source Document</label>
        <referenceTo>PC_Document__c</referenceTo>
        <relationshipLabel>OCR Queue</relationshipLabel>
        <relationshipName>OCR_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OCR Queue</label>
    <nameField>
        <displayFormat>OCRQ-{00000000}</displayFormat>
        <label>OCR Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCR Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_OcrResult__c.object
<CustomObject>
    <description>Stores information regarding the resulting record created for a document after optical character recognition (OCR) has been performed</description>
    <fields>
        <fullName>PC_OcrQueue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCR Queue</label>
        <referenceTo>PC_OcrQueue__c</referenceTo>
        <relationshipLabel>OCR Results</relationshipLabel>
        <relationshipName>OCR_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_ResultStatus__c</fullName>
        <description>Status of the resulting record</description>
        <label>Result Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_ResultingRecordId__c</fullName>
        <description>Id of the resulting record created</description>
        <label>Resulting Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OCR Result</label>
    <nameField>
        <displayFormat>OR-{00000000}</displayFormat>
        <label>OCR Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCR Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PC_LinkResultsWithDocumentOcrHandler.cls
/**
 * Created by sathekumar on 11/17/2021.
 */

public inherited sharing class PC_LinkResultsWithDocumentOcrHandler extends PC_TriggerHandler {
    override public void afterInsert() {
        LinkNonApplicantWithDocument((List<PC_OcrResult__c>) newList, (Map<Id, PC_OcrResult__c>) newMap);
    }

    private void LinkNonApplicantWithDocument(List<PC_OcrResult__c> ocrResultList, Map<Id, PC_OcrResult__c> newOcrResultsByIdsMap) {
        String associationRecordName = PC_Constants.EMPTY_STRING;
        String recordTypeName = PC_Constants.EMPTY_STRING;
        String objectLabel = PC_Constants.EMPTY_STRING;
        String sObjectType = PC_Constants.EMPTY_STRING;
        String targetRecordId = PC_Constants.EMPTY_STRING;
        String documentId = PC_Constants.EMPTY_STRING;
        Map<String, Schema.SObjectType> sObjectMap = Schema.getGlobalDescribe();

        PC_Document_Log__c pcDocumentLog = new PC_Document_Log__c();
        List<PC_Document_Log__c> pcDocumentLogList = new List<PC_Document_Log__c>();
        Set<Id> ocrResultIds = new Set<Id>();
        Set<String> targetRecordIds = new Set<String>();
        Set<String> documentIds = new Set<String>();
        Map<String, String> documentAndAssociationRecordIdMap = new Map<String, String>();
        try {
            ocrResultIds = newOcrResultsByIdsMap.keySet();
            Map<Id, PC_OcrResult__c> ocrResultMap = new Map<Id, PC_OcrResult__c>([
                    SELECT Id, Name, PC_OcrQueue__r.PC_SourceDocument__c, PC_ResultingRecordId__c, PC_ResultStatus__c, PC_OcrQueue__r.OwnerId
                    FROM PC_OcrResult__c
                    WHERE PC_OcrQueue__c != null AND PC_ResultingRecordId__c != null AND PC_ResultStatus__c = 'Success' AND Id IN :ocrResultIds
            ]);

            for (PC_OcrResult__c ocrResult : ocrResultMap.values()) {
                if (String.isNotBlank(ocrResult.PC_ResultingRecordId__c)) {
                    targetRecordIds.add(ocrResult ?.PC_ResultingRecordId__c);
                }
                if (String.isNotBlank(ocrResult ?.PC_OcrQueue__r ?.PC_SourceDocument__c)) {
                    documentIds.add(ocrResult ?.PC_OcrQueue__r ?.PC_SourceDocument__c);
                }
            }

            Map<Id, PC_Document_Log__c> documentLogMap = new Map<Id, PC_Document_Log__c>([
                    SELECT Name, PC_Document_Log__c, PC_Document__c, PC_Association_Record_Id__c, PC_Association_Type__c, PC_Association_Record_Name__c
                    FROM PC_Document_Log__c
                    WHERE PC_Document__c IN :documentIds AND PC_Association_Record_Id__c IN :targetRecordIds
            ]);

            for (PC_Document_Log__c documentLog : documentLogMap.values()) {
                documentAndAssociationRecordIdMap.put(documentLog.PC_Document__c, documentLog.PC_Association_Record_Id__c);
            }

            for (PC_OcrResult__c ocrResult : ocrResultMap.values()) {
                targetRecordId = ocrResult ?.PC_ResultingRecordId__c;
                documentId = ocrResult ?.PC_OcrQueue__r ?.PC_SourceDocument__c;
                system.debug('targetRecordId--->' + targetRecordId);
                system.debug('documentId--->' + documentId);
                if (String.isNotBlank(targetRecordId)) {
                    sObjectType = String.valueOf(Id.valueOf(targetRecordId).getSobjectType());
                    objectLabel = sObjectMap.get(sObjectType).getDescribe().getLabel();
                    if (sObjectType != PC_Constants.CANDIDATE_PATIENT_OBJECT) {
                        if (! (documentAndAssociationRecordIdMap.containsKey(documentId) && documentAndAssociationRecordIdMap.get(documentId) == targetRecordId)) {
                            system.debug('isLinkLogExists--->true');
                            recordTypeName = PC_Utility.getRecordTypeNameByRecordId(targetRecordId);

                            List<sObject> sObj = new List<sObject>();
                            String query = 'Select Id, Name from ' + sObjectType + ' where id = \'' + targetRecordId + '\'';
                            sObj = PC_Database.queryWithAccess(query, false);
                            if (!sObj.isEmpty()) {
                                associationRecordName = (String) sObj[0].get('Name');
                            }
                            pcDocumentLog.PC_Document__c = documentId;
                            pcDocumentLog.PC_Association_Record_ID__c = targetRecordId;
                            pcDocumentLog.PC_Association_Record_Name__c = associationRecordName;
                            pcDocumentLog.PC_Association_Type__c = (String.isNotBlank(recordTypeName)) ? objectLabel + ': ' + recordTypeName : objectLabel;
                            pcDocumentLogList.add(pcDocumentLog);
                        }
                    }
                }
            }
            system.debug('pcDocumentLogList--->' + pcDocumentLogList.size());
            if (pcDocumentLogList.size() > 0) {
                system.debug('pcDocumentLogList--->' + pcDocumentLogList);
                PC_Database.ins(pcDocumentLogList, false);
            }
        } catch (Exception ex) {
            PC_Utility.logAndThrowException(ex);
        }
    }
}