objects/PC_Error_Log__c.object
<CustomObject>
    <description>Global error logging object to be used by all applications</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_Message__c.object
<CustomObject>
    <description>The PC_Message__c is a custom object in Patient Connect that logs the SMSs and App messages sent/received.</description>
    <fields>
        <fullName>PC_Message_Status__c</fullName>
        <description>The delivery status of the message sent/received.</description>
        <label>Message Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Undelivered</fullName>
                </value>
                <value>
                    <fullName>Receiving</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Unprocessed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_SMSVendorName__c</fullName>
        <description>The vendor used for facilitating messaging service</description>
        <label>SMS Vendor Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Source_Type__c</fullName>
        <description>The type of message sent - SMS or App Message.</description>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>App Message</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Type__c</fullName>
        <description>The direction of the message sent - Inbound or Outbound.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PC_ReminderQueue__c.object
<CustomObject>
    <description>Reminder queue stores the details of the reminders for configured objects.</description>
    <fields>
        <fullName>PC_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If user wants to manually activate or deactivate reminder queue then this checkbox can be used.</description>
        <inlineHelpText>Reminder queue is not considered for sending reminders if it is false</inlineHelpText>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_AllRemindersSent__c</fullName>
        <formula>PC_RemindersSentSuccessfully__c ==  PC_RemindersToBeSent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>All Reminders Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_SupportPlanActivity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the Support plan activity Id to refer.</description>
        <inlineHelpText>Support Plan Activity Id</inlineHelpText>
        <label>Support Plan Activity</label>
        <referenceTo>PC_SupportPlanActivity__c</referenceTo>
        <relationshipLabel>Reminder Queues</relationshipLabel>
        <relationshipName>Reminder_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reminder Queue</label>
    <nameField>
        <displayFormat>RQ-{0000}</displayFormat>
        <label>Reminder Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reminder Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_Remote_Service_Log__c.object
<CustomObject>
    <description>This object is used to store information received from the web services</description>
    <label>Remote Service Log</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Remote Service Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remote Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_SupportPlan__c.object
<CustomObject>
    <description>Custom object in Patient Connect that helps to create a predefined template of activities (tasks and events) according to the type of case and the brands that are supported.</description>
    <label>Support Plan</label>
    <nameField>
        <label>Support Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_SupportPlanActivity__c.object
<CustomObject>
    <description>Custom object in Patient Connect to store template activities for a Support Plan.</description>
    <fields>
        <fullName>PC_SupportPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Support Plan to which an activity or an activity sequence belongs.</description>
        <label>Support Plan</label>
        <referenceTo>PC_SupportPlan__c</referenceTo>
        <relationshipLabel>Support Plan Activities</relationshipLabel>
        <relationshipName>Support_Plan_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support Plan Activity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Plan Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_SupportPlanActivityLog__c.object
<CustomObject>
    <description>Custom object to store Support Plan Activity Logs</description>
    <fields>
        <fullName>PC_SupportPlanActivity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support Plan Activity using which the new Record is created</description>
        <label>Support Plan Activity</label>
        <referenceTo>PC_SupportPlanActivity__c</referenceTo>
        <relationshipLabel>Support Plan Activity Logs</relationshipLabel>
        <relationshipName>PC_SupportPlanActivityLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PC_SupportPlanRuntime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support Plan Runtime which was used to execute Support Plan Activity</description>
        <label>Support Plan Runtime</label>
        <referenceTo>PC_SupportPlanRuntime__c</referenceTo>
        <relationshipLabel>Support Plan Activity Logs</relationshipLabel>
        <relationshipName>PC_SupportPlanActivityLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support Plan Activity Log</label>
    <nameField>
        <displayFormat>SPAL-{000000}</displayFormat>
        <label>Support Plan Activity Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Plan Activity Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PC_SupportPlanRuntime__c.object
<CustomObject>
    <description>Patient Connect custom object to capture run time instance of a Support Plan</description>
    <fields>
        <fullName>PC_CurrentActivityStatus__c</fullName>
        <description>Status of the current activity. Determines if the activity is in progress or a pending state.</description>
        <label>Current Activity Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Condition</fullName>
                    <default>true</default>
                    <label>Pending Condition</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Current_Group_Status__c</fullName>
        <description>Status of the current group. Determines if the group is in progress or a pending state.</description>
        <label>Current Group Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Condition</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_SupportPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support Plan to which the run time instance belongs.</description>
        <label>Support Plan</label>
        <referenceTo>PC_SupportPlan__c</referenceTo>
        <relationshipLabel>Support Plan Runtime</relationshipLabel>
        <relationshipName>Support_Plan_Runtime</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support Plan Runtime</label>
    <nameField>
        <label>Support Plan Runtime Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Plan Runtime</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PC_PurgeBatchScheduler.cls
/**
 * Created by vkashikar on 6/30/2021.
 */

/**
 * Scheduler batch job to schedule PC_PurgeBatch as per the settings in PC_PurgeBatchScope of Patient Connect Setting.
 */
global with sharing class PC_PurgeBatchScheduler implements Schedulable {
    private final static String SETTING_NAME = 'PC_PurgeBatchSetting';
    private static String CONFIGURED_SETTING_VALUE = PC_System.getPatientConnectSetting(SETTING_NAME, '');
    private static String EXAMPLE_SETTING = '{"scope":[{"context":"SPAL_RO","offset":365},{"context":"SPAL_NRO","offset":365},{"context":"ERR","offset":365},{"context": "MSG_TWL","offset":365},{"context":"RSL","offset":365},{"context":"RQ","offset":365}],"emptyRecycleBin":true}';
    private static Datetime dateTimeNow = datetime.now();

    /**
     * Execute method that is auto-called by SF while scheduling the batch job.
     * This method schedules as per the settings in PC_PurgeBatchSetting & PC_BatchJobProperties of Patient Connect Settings
     * For each context set in PC_PurgeBatchSetting, the PC_PurgeBatch is executed.
     * For any invalid setting, InvalidSettingsException is thrown.
     * @param sc SchedulableContext having trigger id.
     */
    global void execute(SchedulableContext sc) {
        final String BATCH_JOB_NAME = 'PC_PurgeBatch';
        Setting setting = getSetting(CONFIGURED_SETTING_VALUE);
        PC_BatchUtility.BatchJobProperties batchProperties = PC_BatchUtility.getBatchJobSetting(BATCH_JOB_NAME);
        for(ContextSetting contextSetting : setting.scope) {
            String contextName = contextSetting.context;
            Integer offset = contextSetting.offset;
            PC_PurgeBatch.Parameters batchParameters = getBatchParameters(contextSetting, batchProperties.notifyAllAdmins, setting.emptyRecycleBin);
            system.debug(batchParameters);
            PC_PurgeBatch batch = new PC_PurgeBatch(batchParameters);
            Id batchId = Database.executeBatch(batch, batchProperties.size);
        }
    }

    private static PC_PurgeBatch.Parameters getBatchParameters(ContextSetting contextSetting, Boolean notifyAllAdmins, Boolean emptyRecycleBin) {
        PC_PurgeBatch.Parameters parameters = new PC_PurgeBatch.Parameters();
        parameters.emptyRecycleBin = emptyRecycleBin;
        parameters.sendSummaryEmailToAllAdmins = notifyAllAdmins;
        parameters.scopeQuery = getQuery(contextSetting);
        parameters.scopeCountQuery = getCountQuery(contextSetting);
        parameters.logFileName = 'PC_PurgeJob_' + contextSetting.context;
        return parameters;
    }

    public static Setting getSetting(String settingString) {
        Setting setting = new Setting();
        system.debug('***');
        system.debug(settingString);
        if(String.isNotBlank(settingString)) {
            setting = (Setting) JSON.deserialize(settingString, Setting.class);
        }
        if(setting == null || setting.scope == null || setting.scope.isEmpty()) {
            throw new InvalidSettingsException('Invalid Setting - Ensure that the Settings are in the format - ' + EXAMPLE_SETTING);
        }
        return setting;
    }

    private static String getQuery(ContextSetting contextSetting) {
        String c = contextSetting.context;
        Integer modifiedDateOffsetInDays = contextSetting.offset;
        String query = '';
        String limitDatetime = dateTimeNow.addDays(-1*modifiedDateOffsetInDays).format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'');
        if(c == 'SPAL_RO') {
            query =
                    ' SELECT Id ' + ' FROM PC_SupportPlanActivityLog__c ' +
                            ' WHERE ' +
                            ' LastModifiedDate <= ' + limitDatetime + ' ' +
                            ' AND ' +
                            ' isDeleted = false ' +
                            ' AND ' +
                            ' PC_SupportPlanActivity__r.PC_SupportPlan__r.PC_SupportPlan_Behavior__c = \'RunOncePerRecord\' ' +
                            ' AND ' +
                            ' ( ' +
                            ' PC_SupportPlanRuntime__r.PC_CurrentActivityStatus__c = \'Completed\' ' +
                            ' OR ' +
                            ' PC_SupportPlanRuntime__r.PC_Current_Group_Status__c = \'Completed\' ' +
                            ' ) ' +
                            ' ORDER BY LastModifiedDate ASC ';
        }
        else if(c == 'SPAL_NRO') {
            query =
                    ' SELECT Id ' +
                    ' FROM PC_SupportPlanActivityLog__c ' +
                    ' WHERE ' +
                    ' LastModifiedDate <= ' + limitDatetime + ' ' +
                    ' AND ' +
                    ' isDeleted = false ' +
                    ' AND ' +
                    ' PC_SupportPlanActivity__r.PC_SupportPlan__r.PC_SupportPlan_Behavior__c != \'RunOncePerRecord\'' +
                    ' AND ' +
                    ' ( ' +
                            ' PC_SupportPlanRuntime__r.PC_CurrentActivityStatus__c = \'Completed\'' +
                            ' OR ' +
                            ' PC_SupportPlanRuntime__r.PC_Current_Group_Status__c = \'Completed\'' +
                    ' ) ' +
                    ' ORDER BY LastModifiedDate ASC ';
        }
        else if(c == 'ERR') {
            query =
                    ' SELECT Id ' +
                    ' FROM PC_Error_Log__c ' +
                    ' WHERE ' +
                    ' LastModifiedDate <= ' + limitDatetime + ' ' +
                    ' AND ' +
                    ' isDeleted = false ' +
                    ' ORDER BY LastModifiedDate ASC ';
        }
        else if(c == 'MSG_TWL') {
            query =
                    ' SELECT Id ' +
                    ' FROM PC_Message__c ' +
                    ' WHERE ' +
                    ' LastModifiedDate <= ' + limitDatetime + ' ' +
                    ' AND ' +
                    ' isDeleted = false ' +
                    ' AND ' +
                    ' PC_Type__c = \'Outbound\'' +
                    ' AND ' +
                    ' PC_Source_Type__c=\'SMS\'' +
                    ' AND ' +
                    ' (PC_Message_Status__c = \'Delivered\' OR PC_Message_Status__c = \'Undelivered\')' +
                    ' AND ' +
                    ' PC_SMSVendorName__c = \'Twilio\'' +
                    ' ORDER BY LastModifiedDate ASC ';
        }
        else if(c == 'RSL') {
            query =
                    ' SELECT Id ' +
                    ' FROM PC_Remote_Service_Log__c ' +
                    ' WHERE ' +
                    ' LastModifiedDate <= ' + limitDatetime + ' ' +
                    ' AND ' +
                    ' isDeleted = false ' +
                    ' ORDER BY LastModifiedDate ASC ';
        }
        else if(c == 'RQ') {
            query =
                    'SELECT ID ' +
                            ' FROM PC_ReminderQueue__c ' +
                            ' WHERE ' +
                            ' LastModifiedDate <= ' + limitDatetime + ' ' +
                            ' AND ' +
                            ' isDeleted = false ' +
                            ' AND ' +
                            ' (PC_Active__c = FALSE OR PC_AllRemindersSent__c = TRUE) ' +
                            ' ORDER BY LastModifiedDate ASC ';
        }
        return query;
    }
    private static String getCountQuery(ContextSetting contextSetting) {
        String c = contextSetting.context;
        Integer modifiedDateOffsetInDays = contextSetting.offset;
        String query = '';
        String limitDatetime = dateTimeNow.addDays(-1*modifiedDateOffsetInDays).formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'');
        if(c == 'SPAL_RO') {
            query =
                    ' SELECT COUNT() ' + ' FROM PC_SupportPlanActivityLog__c ' +
                            ' WHERE ' +
                            ' LastModifiedDate <= ' + limitDatetime + ' ' +
                            ' AND ' +
                            ' isDeleted = false ' +
                            ' AND ' +
                            ' PC_SupportPlanActivity__r.PC_SupportPlan__r.PC_SupportPlan_Behavior__c = \'RunOncePerRecord\' ' +
                            ' AND ' +
                            ' ( ' +
                            ' PC_SupportPlanRuntime__r.PC_CurrentActivityStatus__c = \'Completed\' ' +
                            ' OR ' +
                            ' PC_SupportPlanRuntime__r.PC_Current_Group_Status__c = \'Completed\' ' +
                            ' ) ';
        }
        else if(c == 'SPAL_NRO') {
            query =
                    ' SELECT COUNT() ' +
                            ' FROM PC_SupportPlanActivityLog__c ' +
                            ' WHERE ' +
                            ' LastModifiedDate <= ' + limitDatetime + ' ' +
                            ' AND ' +
                            ' isDeleted = false ' +
                            ' AND ' +
                            ' PC_SupportPlanActivity__r.PC_SupportPlan__r.PC_SupportPlan_Behavior__c != \'RunOncePerRecord\'' +
                            ' AND ' +
                            ' ( ' +
                            ' PC_SupportPlanRuntime__r.PC_CurrentActivityStatus__c = \'Completed\'' +
                            ' OR ' +
                            ' PC_SupportPlanRuntime__r.PC_Current_Group_Status__c = \'Completed\'' +
                            ' ) ';
        }
        else if(c == 'ERR') {
            query =
                    ' SELECT COUNT() ' +
                            ' FROM PC_Error_Log__c ' +
                            ' WHERE ' +
                            ' LastModifiedDate <= ' + limitDatetime + ' ' +
                            ' AND ' +
                            ' isDeleted = false ';
        }
        else if(c == 'MSG_TWL') {
            query =
                    ' SELECT COUNT() ' +
                            ' FROM PC_Message__c ' +
                            ' WHERE ' +
                            ' LastModifiedDate <= ' + limitDatetime + ' ' +
                            ' AND ' +
                            ' isDeleted = false ' +
                            ' AND ' +
                            ' PC_Type__c = \'Outbound\'' +
                            ' AND ' +
                            ' PC_Source_Type__c=\'SMS\'' +
                            ' AND ' +
                            ' (PC_Message_Status__c = \'Delivered\' OR PC_Message_Status__c = \'Undelivered\')' +
                            ' AND ' +
                            ' PC_SMSVendorName__c = \'Twilio\'';
        }
        else if(c == 'RSL') {
            query =
                    ' SELECT COUNT() ' +
                            ' FROM PC_Remote_Service_Log__c ' +
                            ' WHERE ' +
                            ' LastModifiedDate <= ' + limitDatetime + ' ' +
                            ' AND ' +
                            ' isDeleted = false ';
        }

        else if(c == 'RQ') {
            query =
                    'SELECT COUNT() ' +
                            ' FROM PC_ReminderQueue__c ' +
                            ' WHERE ' +
                            ' LastModifiedDate <= ' + limitDatetime + ' ' +
                            ' AND ' +
                            ' isDeleted = false ' +
                            ' AND ' +
                            ' (PC_Active__c = FALSE OR PC_AllRemindersSent__c = TRUE) ';
        }
        return query;
    }

    public Class ContextSetting {
        public String context;
        public Integer offset;
    }
    public Class Setting {
        public List<ContextSetting> scope;
        public Boolean emptyRecycleBin;
    }
    global Class InvalidSettingsException extends Exception {

    }

}