objects/PC_Message__c.object
<CustomObject>
    <description>The PC_Message__c is a custom object in Patient Connect that logs the SMSs and App messages sent/received.</description>
    <fields>
        <fullName>PC_Message_Read__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The date and time message read by the user.</description>
        <label>Message Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Message_Status__c</fullName>
        <description>The delivery status of the message sent/received.</description>
        <label>Message Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Undelivered</fullName>
                </value>
                <value>
                    <fullName>Receiving</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Unprocessed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PC_Type__c</fullName>
        <description>The direction of the message sent - Inbound or Outbound.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PC_SetMessageReadValueHandler.cls
/**********************************************************************************************************************************************
Class Name      : PC_SetMessageReadValueHandler
Description     : Trigger on Message object that sets Message Read field value for an Outbound message only after its status changes to Delivered.
Created By      : Chetna Mohapatra
Created Date    : Oct 25, 2021
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer                   Date                    Description
--------------------------------------------------------------------------------------------------------------
Chetna Mohapatra          Oct 25, 2021           Initial Version
Satheesh Kumar            Nov 16, 2021           [PC-8213] Excluded FLS Check and added inherited sharing
************************************************************************************************************************************************/
public inherited sharing class PC_SetMessageReadValueHandler extends PC_TriggerHandler {
    //This class runs under Trigger context and hence 'with sharing' is not provided.
    override public void beforeUpdate(){
        setMessageReadValue((List<PC_Message__c >) newList);
    }
    /******************************************************************************************************
    Method Name    : setMessageReadValue
    Author         : Chetna Mohapatra
    Description    : This method is to set the Message Read field value for an Outbound message only after
                     its status changes to Delivered.
    Return Type    : void
    Parameter      : List of new Message records- messages
    *******************************************************************************************************/
    private void setMessageReadValue(List<PC_Message__c> messages) {
        for (PC_Message__c msg : messages) {
            if (msg.PC_Type__c == PC_Constants.OUTBOUND && msg.PC_Message_Status__c== PC_SMS.PC_SMS_DELIVERED) {
                msg.PC_Message_Read__c = true;
            }
        }
    }

}