objects/PC_Prescription__c.object
<CustomObject>
    <description>This Object captures prescription information for the prescribed drug for a patient when enrolled in an engagement program.</description>
    <fields>
        <fullName>PC_Dosage__c</fullName>
        <description>The dosage of each drug in the prescription.</description>
        <label>Dosage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PC_Patient_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The patient account associated with a specific prescription.</description>
        <label>Patient</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PC_Patient</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prescriptions (Patient)</relationshipLabel>
        <relationshipName>Patient_Prescriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PC_Test_ValidatePrescriptionRecType.cls
/*********************************************************************************************************
Class Name      : PC_Test_ValidatePrescriptionRecType
Description     : Tests PC_Trigger_ValidatePatientOnPrescription .
Created By      : Kanteti Kishore
Created Date    : Sep 17, 2019
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer                   Date                     Description
--------------------------------------------------------------------------------------------------------------
Kanteti Kishore        Sep 17, 2019               Initial version
****************************************************************************************************************/
@isTest
public class PC_Test_ValidatePrescriptionRecType{


/*********************************************************************************
    Method Name    : testPrescPatient
    Author         : Kishore Kanteti
    Description    : This method populates patient name for person account associated before person account record is created.
    Return Type    : void
    Parameter      :
*********************************************************************************/
    @isTest public static void testPrescPatient() {
        Account testAcc = PC_Test_Setup.createTestAccount(PC_Constants.PC_PATIENT_PERSONACCOUNT_RECORDTYPE_API);
        PC_Database.ins(testAcc);

        Test.startTest();
        PC_Prescription__c presc = new PC_Prescription__c(PC_Patient_Account__c = testAcc.Id);
        PC_Database.ins(presc);
        presc.PC_Dosage__c = PC_Constants.PC_PATIENT_PERSONACCOUNT_RECORDTYPE_API;
        PC_Database.upd(presc);
        Test.stopTest();
    }

}