objects/PC_ProtectedApiSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PC_ProtectedApiKey__c</fullName>
        <label>Protected Api Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PC_SubscriberEditable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Enable this option to show this setting in the protected api settings and to accept input key from subscriber.</inlineHelpText>
        <label>Subscriber Editable</label>
        <type>Checkbox</type>
    </fields>
    <label>Protected Api Settings</label>
</CustomObject>

classes/PC_Test_ProtectedCustomSettingsCntrl.cls
/*********************************************************************************************************
Class Name      : PC_Test_ProtectedCustomSettingsCntrl
Description     : Test class for PC_Test_ProtectedCustomSettingsCntrl
Created By      : Deloitte
Created Date    :
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer          Log#         Date                   Description
--------------------------------------------------------------------------------------------------------------
Deloitte                                               Initial Version
Shishir Bansal                  Dec 05,2019            [PC-5787] Added null check before DML operation
****************************************************************************************************************/

@isTest(seeAllData=False)
public class PC_Test_ProtectedCustomSettingsCntrl {

    @isTest static void testApiKey(){
        PC_ProtectedApiSettings__c protApi = new PC_ProtectedApiSettings__c();
        protApi.Name = PC_Constants.PC_GEOCODE_API_NAME;
        protApi.PC_ProtectedApiKey__c =PC_Constants.PC_GEOCODE_API_NAME;
        protApi.PC_SubscriberEditable__c = true;
        if(protApi !=null) {
            insert protApi;
        }
        PC_ProtectedCustomSettingsCntrl.getApiLabels();
        PC_ProtectedCustomSettingsCntrl.updateApiKey(PC_Constants.PC_GEOCODE_API_NAME,PC_Constants.PC_GEOCODE_API_NAME);
        PC_ProtectedCustomSettingsCntrl.createApiSetting(PC_Constants.PC_ACCOUNT,PC_Constants.PC_ACCOUNT,PC_Constants.PC_GEOCODE_API_NAME);
    } 
}